Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2019-12, with the labels that each got.

#1090 AP-1096 Add YVETTECLARK1 contact_id
  config/encrypted_private_beta_users.yml
  helm_deploy/apply-for-legal-aid/whitelisted_users.yaml
Labels: ready for review

#1088 AP-1062 Amend default scope for DA003
  db/seeds/legal_framework/proceeding_type_scope_limitations.csv
  lib/tasks/legal_framework.rake
Labels: Approved

#1087 AP-1078 Refactor CCMS ref on means/merits reports
  app/controllers/providers/means_reports_controller.rb
  app/controllers/providers/merits_reports_controller.rb
  app/services/reports/base_report_creator.rb
  app/services/reports/means_report_creator.rb
  app/services/reports/merits_report_creator.rb
  spec/requests/providers/means_reports_spec.rb
  spec/requests/providers/merits_reports_spec.rb
  spec/services/reports/means_report_creator_spec.rb
  spec/services/reports/merits_report_creator_spec.rb
Labels: Approved, UAT

#1092 AP1107 Tranche 2 Authorised Beta Users
  helm_deploy/apply-for-legal-aid/whitelisted_users.yaml
Labels: Approved

#1102 Add dummy user to whitelisted_users.yaml
  helm_deploy/apply-for-legal-aid/whitelisted_users.yaml
Labels: ready for review

#1103 Enable CCMS submissions
  helm_deploy/apply-for-legal-aid/values-production.yaml
Labels: ready for review

#1091 AP1093 Create a report of submitted applications on the admin page
  app/controllers/admin/submitted_applications_reports_controller.rb
  app/models/legal_aid_application.rb
  app/views/admin/submitted_applications_reports/_submitted_applications.html.erb
  app/views/admin/submitted_applications_reports/show.html.erb
  app/views/layouts/admin.html.erb
  config/locales/en/admin.yml
  config/locales/en/layouts.yml
  config/routes.rb
  spec/requests/admin/submitted_applications_reports_spec.rb
Labels: UAT

#1105 AP1123 Remove Benefit Types from the application
  app/controllers/admin/benefit_types_controller.rb
  app/views/admin/benefit_types/_form.html.erb
  app/views/admin/benefit_types/edit.html.erb
  app/views/admin/benefit_types/index.html.erb
  app/views/admin/benefit_types/new.html.erb
  app/views/admin/benefit_types/show.html.erb
  app/views/layouts/admin.html.erb
  config/locales/en/admin.yml
  config/locales/en/layouts.yml
  config/routes.rb
  db/migrate/20191206104140_drop_benefit_types.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/data/benefit_types.yml
  spec/requests/admin/benefit_types_spec.rb
Labels: UAT

#1106 Ap 1121 event driven widgets
  app/models/ccms/submission.rb
  app/models/dashboard/widget_data_providers/daily_new_providers.rb
  app/models/dashboard/widget_data_providers/failed_ccms_submissions.rb
  app/models/dashboard/widget_data_providers/number_provider_firms.rb
  app/models/dashboard/widget_data_providers/pending_ccms_submissions.rb
  app/models/dashboard_widget.rb
  app/models/feedback.rb
  app/models/firm.rb
  app/models/legal_aid_application.rb
  app/models/merits_assessment.rb
  app/models/provider.rb
  app/services/dashboard_event_handler.rb
  config/initializers/active_support_notification_events.rb
  config/initializers/sidekiq.rb
  config/initializers/whitelisted_users.rb
  helm_deploy/apply-for-legal-aid/templates/dashboard_daily_new_providers_cron.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_failed_ccms_submissions_cron.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_number_provider_firms_cron.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_past_three_weeks_average_feedback_score.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_past_weeks_average_feedback_score.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_pending_ccms_submissions_cron.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_started_applications_cron.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_submitted_applications_cron.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_total_submitted_applications_cron.yml
  lib/tasks/jobs/dashboard_updater.rake
  spec/events_spec.rb
  spec/models/dashboard/widget_data_providers/failed_ccms_submissions_spec.rb
  spec/models/dashboard/widget_data_providers/pending_ccms_submissions_spec.rb
  spec/requests/citizens/resend_link_requests_spec.rb
  spec/requests/feedbacks_spec.rb
  spec/services/citizen_email_service_spec.rb
  spec/services/smoke_test/test_emails_spec.rb
Labels: Approved

#1108 AP-1131 - Only count submitted MeritsApplications
  app/models/dashboard/widget_data_providers/total_submitted_applications.rb
  spec/models/dashboard/widget_data_providers/total_submitted_applications_spec.rb
Labels: Approved

#1109 AP-1132 : Dashboard errors in sidekiq/prometheus
  app/models/dashboard/widget_data_providers/past_three_weeks_average_feedback_score.rb
  app/models/dashboard/widget_data_providers/past_weeks_average_feedback_score.rb
  spec/models/dashboard/widget_data_providers/past_three_weeks_average_feedback_score_spec.rb
  spec/models/dashboard/widget_data_providers/past_weeks_average_feedback_score_spec.rb
Labels: Approved

#1107 Ap 1094 journey specific errors
  app/controllers/citizens/own_homes_controller.rb
  app/controllers/citizens/shared_ownerships_controller.rb
  app/controllers/providers/own_homes_controller.rb
  app/controllers/providers/shared_ownerships_controller.rb
  app/forms/legal_aid_applications/own_home_form.rb
  app/forms/legal_aid_applications/shared_ownership_form.rb
  config/locales/en/activemodel.yml
  spec/requests/citizens/own_home_spec.rb
  spec/requests/providers/shared_ownerships_spec.rb
Labels: UAT

#1119 BugFix - Make whitelisted users check case insensitive
  app/models/provider.rb
  spec/models/provider_spec.rb
Labels: ready for review

#1120 Bug Fix - Update Provider retreiver to use URI.escape instead of CGI.escape
  .rubocop.yml
  app/services/provider_details_retriever.rb
Labels: ready for review

#1118 remove applicant name from page title
  app/views/providers/check_benefits/_check_benefits_result.html.erb
  config/locales/en/providers.yml
Labels: UAT

#1129 AP-1105: admin feedback review
  app/controllers/admin/feedback_controller.rb
  app/views/admin/feedback/_feedbacks.erb
  app/views/admin/feedback/show.html.erb
  app/views/feedback/new.html.erb
  app/views/layouts/admin.html.erb
  config/locales/en/admin.yml
  config/locales/en/generic.yml
  config/locales/en/helpers.yml
  config/locales/en/layouts.yml
  config/routes.rb
  spec/requests/admin/feedback_spec.rb
Labels: Approved

#1131 AP-1129: Update statement of case
  app/assets/stylesheets/govuk-mods.scss
  app/views/providers/statement_of_cases/show.html.erb
  config/locales/en/providers.yml
Labels: ready for review

#1130 AP1133 police notified
  app/forms/respondents/respondent_form.rb
  app/javascript/src/respondent_detail.js
  app/views/providers/respondents/_respondent_detail.html.erb
  app/views/providers/respondents/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  features/providers/civil_application_journey.feature
  spec/factories/respondents.rb
  spec/forms/respondents/respondent_form_spec.rb
Labels: ready for review

#1135 CircleCI: Update the gemfile cache
  .circleci/config.yml
Labels: ready for review
