Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2019-08, with the labels that each got.

#680 AP568 and AP535 Restrictions page for passported and non-passported flow
  .rubocop.yml
  app/controllers/citizens/restrictions_controller.rb
  app/controllers/providers/restrictions_controller.rb
  app/forms/legal_aid_applications/restrictions_form.rb
  app/helpers/application_helper.rb
  app/helpers/check_answers_helper.rb
  app/helpers/gov_uk_form_helper.rb
  app/models/legal_aid_application.rb
  app/models/legal_aid_application_restriction.rb
  app/models/restriction.rb
  app/services/save_applicant_means_answers.rb
  app/views/citizens/legal_aid_applications/index.html.erb
  app/views/citizens/restrictions/_form.html.erb
  app/views/citizens/restrictions/show.html.erb
  app/views/providers/about_the_financial_assessments/show.html.erb
  app/views/providers/capital_introductions/show.html.erb
  app/views/providers/merits_declarations/show.html.erb
  app/views/providers/restrictions/show.html.erb
  app/views/providers/start/index.html.erb
  app/views/providers/start_merits_assessments/show.html.erb
  app/views/shared/_check_answers_assets.html.erb
  app/views/shared/_check_answers_restrictions.html.erb
  app/views/shared/check_answers/_item.html.erb
  app/views/shared/check_answers/_no_link_items.html.erb
  app/views/shared/forms/_fieldset_header.html.erb
  app/views/shared/forms/conditional_checkbox_with_numeric_input
  config/locales/en/activemodel.yml
  config/locales/en/citizens.yml
  config/locales/en/providers.yml
  config/locales/en/restrictions.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/migrate/20190723142529_drop_laa_restrictions_table.rb
  db/migrate/20190723142558_drop_restrictions_table.rb
  db/migrate/20190723142637_add_restrictions_to_legal_aid_applications.rb
  db/schema.rb
  db/seeds/restrictions.rb
  features/citizens/citizens.feature
  features/providers/check_your_answers.feature
  features/providers/civil_application_journey.feature
  features/step_definitions/citizens_steps.rb
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_application_restrictions.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/restrictions.rb
  spec/forms/legal_aid_applications/restrictions_form_spec.rb
  spec/models/admin_user_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/restriction_spec.rb
  spec/requests/citizens/check_answers_spec.rb
  spec/requests/citizens/restrictions_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
  spec/requests/providers/restrictions_spec.rb
  spec/services/save_applicant_means_answers_spec.rb
Labels: UAT

#683 AP-759 & AP-779 Create Scope Limitation(s) for an application
  app/controllers/providers/check_passported_answers_controller.rb
  app/controllers/providers/check_provider_answers_controller.rb
  app/controllers/providers/proceedings_types_controller.rb
  app/controllers/providers/used_delegated_functions_controller.rb
  app/models/application_scope_limitation.rb
  app/models/legal_aid_application.rb
  app/models/proceeding_type.rb
  app/models/proceeding_type_scope_limitation.rb
  app/views/providers/check_provider_answers/index.html.erb
  app/views/providers/limitations/show.html.erb
  config/locales/en/providers.yml
  db/migrate/20190723083236_create_application_scope_limitations.rb
  db/migrate/20190724135655_add_enum_column_to_application_scope_limitations.rb
  db/schema.rb
  features/providers/civil_application_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/proceeding_type_scope_limitations.rb
  spec/factories/proceeding_types.rb
  spec/factories/scope_limitations.rb
  spec/factory_specs/legal_aid_application_factory_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/proceeding_type_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/limitations_spec.rb
  spec/requests/providers/proceedings_types_spec.rb
  spec/requests/providers/used_delegated_functions_spec.rb
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: ready for review

#702 Ap835 hard coded ccms true results and 839 APP_AMEND_TYPE
  app/models/ccms/submission.rb
  app/services/ccms/attribute_value_generator.rb
  config/ccms/ccms_keys.yml
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
  spec/support/xml_extractor.rb
Labels: ready for review

#717 Fix bundle error
  .circleci/config.yml
  Gemfile.lock
Labels: ready for review

#718 Bundle updates
  Gemfile.lock
Labels: ready for review

#708 AP-858 Avoid webhint false positives
  .hintrc
  app/services/html_page_saver.rb
  features/support/env.rb
  spec/services/html_page_saver_spec.rb
Labels: ready for review

#719 Update faker
  Gemfile.lock
  spec/factories/bank_accounts.rb
  spec/factories/bank_transactions.rb
  spec/factories/dependants.rb
  spec/factories/incidents.rb
  spec/factories/offices.rb
  spec/factories/providers.rb
  spec/factories/service_levels.rb
  spec/factories/vehicles.rb
  spec/requests/citizens/dependants/relationships_spec.rb
  spec/requests/citizens/vehicles/estimated_values_spec.rb
  spec/requests/citizens/vehicles/remaining_payments_spec.rb
  spec/requests/providers/statement_of_case_spec.rb
  spec/requests/providers/vehicles/estimated_values_spec.rb
  spec/requests/providers/vehicles/remaining_payments_spec.rb
  spec/services/ccms/applicant_add_response_parser_spec.rb
  spec/services/ccms/applicant_add_status_response_parser_spec.rb
  spec/services/ccms/applicant_search_response_parser_spec.rb
  spec/services/ccms/case_add_requestor_spec.rb
  spec/services/ccms/case_add_response_parser_spec.rb
  spec/services/ccms/case_add_status_response_parser_spec.rb
  spec/services/ccms/check_applicant_status_service_spec.rb
  spec/services/ccms/obtain_applicant_reference_service_spec.rb
  spec/services/ccms/obtain_case_reference_service_spec.rb
  spec/services/ccms/obtain_document_id_service_spec.rb
  spec/services/ccms/reference_data_response_parser_spec.rb
  spec/services/ccms/upload_documents_service_spec.rb
  spec/services/malware_scanner_spec.rb
  spec/support/true_layer_mock_data.rb
  spec/validators/currency_validator_spec.rb
Labels: ready for review

#720 Amend location of div to fix spacing issue
  app/views/providers/limitations/show.html.erb
Labels: ready for review

#706 Ap 834 ccms false
  config/ccms/ccms_keys.yml
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: ready for review

#733 AP-638 categorise benefits as included or excluded
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/admin.scss
  app/controllers/admin/benefit_types_controller.rb
  app/controllers/admin/legal_aid_applications_controller.rb
  app/controllers/admin/settings_controller.rb
  app/helpers/admin_helper.rb
  app/helpers/layouts_helper.rb
  app/models/benefit_type.rb
  app/views/admin/benefit_types/_form.html.erb
  app/views/admin/benefit_types/edit.html.erb
  app/views/admin/benefit_types/index.html.erb
  app/views/admin/benefit_types/new.html.erb
  app/views/admin/benefit_types/show.html.erb
  app/views/admin/legal_aid_applications/index.html.erb
  app/views/admin/settings/show.html.erb
  app/views/layouts/admin.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/admin.yml
  config/locales/en/generic.yml
  config/locales/en/layouts.yml
  config/routes.rb
  db/migrate/20190808094323_create_benefit_types.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/data/benefit_types.yml
  db/seeds/legal_framework.rb
  spec/factories/benefit_types.rb
  spec/requests/admin/benefit_types_spec.rb
Labels: ready for review

#739 AP-707 HTML errors fixing
  .hintrc
  app/views/providers/submitted_applications/show.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_client_details.html.erb
  app/views/shared/check_answers/_item.html.erb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/check_answers/_one_link_section.html.erb
  app/views/shared/check_answers/_proceedings_details.html.erb
  app/views/shared/check_answers/_restrictions.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  app/views/shared/forms/shared_ownership_form/_shared_ownership_item.html.erb
  bin/generate_webhint_reports.sh
Labels: WIP

#736 AP-795 Generate unique Proceeding Case ID
  app/models/application_proceeding_type.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/case_add_requestor.rb
  ccms_integration/ccms_spec.rb
  config/ccms/ccms_keys.yml
  db/migrate/20190812135413_add_proceeding_case_id_to_application_proceeding_types.rb
  db/schema.rb
  db/seeds/proceeding_case_id.rb
  spec/factories/submissions.rb
  spec/models/application_proceeding_type_spec.rb
  spec/rails_helper.rb
  spec/services/ccms/case_add_requestor_spec.rb
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
  spec/support/xml_extractor.rb
Labels: ready for review

#725 AP828 Unit Testing ProceedingTypes JavaScript
  app/javascript/src/modules/proceedings.js
  app/javascript/src/proceeding_types.js
  db/schema.rb
  package.json
  spec/javascript/modules/proceedings.spec.js
  spec/javascript/proceeding_types.spec.js
Labels: ready for review

#734 AP-804 Print application
  app/assets/stylesheets/helpers.scss
  app/helpers/application_helper.rb
  app/views/citizens/declarations/show.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/providers/submitted_applications/show.html.erb
  app/views/shared/_applicant_declaration.html.erb
  config/locales/en/citizens.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  spec/requests/providers/submitted_applications_spec.rb
Labels: ready for review

#750 AP-868 Add remaining family statement attribute and test
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: ready for review

#742 Ap 840 client assets
  app/services/ccms/attribute_value_generator.rb
  config/ccms/ccms_keys.yml
  db/schema.rb
  spec/services/ccms/case_add_requestor_spec.rb
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: ready for review

#753 Ap 799 domain name
  .circleci/config.yml
  helm_deploy/apply-for-legal-aid/templates/NOTES.txt
  helm_deploy/apply-for-legal-aid/templates/ingress.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: ready for review

#744 AP867 Update Submitted Application for passported
  app/assets/stylesheets/check-your-answers.scss
  app/views/providers/submitted_applications/show.html.erb
  config/locales/en/providers.yml
  features/providers/civil_application_journey.feature
Labels: UAT

#740 AP-842 Respondent Details
  app/forms/respondents/respondent_form.rb
  app/helpers/check_answers_helper.rb
  app/javascript/src/respondent_detail.js
  app/models/legal_aid_application.rb
  app/views/providers/respondents/_respondent_detail.html.erb
  app/views/providers/respondents/show.html.erb
  app/views/shared/check_answers/_item.html.erb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/check_answers/_no_link_item.html.erb
  app/views/shared/check_answers/_section_break.html.erb
  config/locales/en/providers.yml
  db/schema.rb
  spec/factories/respondents.rb
  spec/forms/respondents/respondent_form_spec.rb
Labels: UAT

#763 Update README to Include Create Test Applications as Admin
  README.md
Labels: ready for review

#765 Include Webhint into tests
  Rakefile
Labels: ready for review

#749 AP872 CCMS Harcoded False Attributes
  config/ccms/ccms_keys.yml
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: ready for review

#752 Ap 870 other assets
  app/services/ccms/attribute_value_generator.rb
  config/ccms/ccms_keys.yml
  spec/services/ccms/case_add_requestor_spec.rb
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: ready for review

#754 Add attribute to omit list
  app/services/ccms/attribute_value_generator.rb
  config/ccms/ccms_keys.yml
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: ready for review

#748 AP-829 - update GOVUK styles
  app/assets/fonts/bold-a2452cb66f-v1.woff2
  app/assets/fonts/bold-affa96571d-v2.woff
  app/assets/fonts/bold-b542beb274-v2.woff2
  app/assets/fonts/bold-f38c792ac2-v1.woff
  app/assets/fonts/bold-fb2676462a-v1.eot
  app/assets/fonts/bold-tabular-357fdfbcc3-v1.eot
  app/assets/fonts/bold-tabular-784c21afb8-v1.woff
  app/assets/fonts/bold-tabular-b89238d840-v1.woff2
  app/assets/fonts/light-2c037cf7e1-v1.eot
  app/assets/fonts/light-458f8ea81c-v1.woff
  app/assets/fonts/light-94a07e06a1-v2.woff2
  app/assets/fonts/light-f38ad40456-v1.woff2
  app/assets/fonts/light-f591b13f7d-v2.woff
  app/assets/fonts/light-tabular-498ea8ffe2-v1.eot
  app/assets/fonts/light-tabular-62cc6f0a28-v1.woff
  app/assets/fonts/light-tabular-851b10ccdd-v1.woff2
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/check-your-answers.scss
  app/assets/stylesheets/govuk-mods.scss
  app/assets/stylesheets/govuk_secondary_button.scss
  app/assets/stylesheets/interruption-panel.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/narrow-table-display.scss
  app/assets/stylesheets/providers/legal_aid_applications.scss
  app/assets/stylesheets/providers/proceeding_types.scss
  app/assets/stylesheets/table-category-column.scss
  app/assets/stylesheets/table-sort.scss
  app/assets/stylesheets/task-list.scss
  app/helpers/application_helper.rb
  app/views/admin/legal_aid_applications/index.html.erb
  app/views/citizens/legal_aid_applications/index.html.erb
  app/views/citizens/restrictions/_form.html.erb
  app/views/layouts/_govuk_base64_fonts.html.erb
  app/views/layouts/_header.html.erb
  app/views/providers/client_received_legal_helps/show.html.erb
  app/views/providers/legal_aid_applications/index.html.erb
  app/views/providers/proceedings_before_the_courts/show.html.erb
  app/views/providers/respondents/_respondent_detail.html.erb
  app/views/providers/start/index.html.erb
  app/views/providers/substantive_applications/show.html.erb
  app/views/providers/used_delegated_functions/show.html.erb
  app/views/shared/forms/_savings_and_investments_form.html.erb
  app/views/shared/forms/_success_prospect_form.html.erb
  app/views/shared/forms/dependants/_assets_value.html.erb
  app/views/shared/forms/dependants/_monthly_incomes.html.erb
  app/views/shared/forms/other_assets/_form.html.erb
  app/views/shared/forms/vehicles/_remaining_payment.html.erb
  features/providers/civil_application_journey.feature
  features/step_definitions/civil_journey_steps.rb
  package.json
  yarn.lock
Labels: UAT

#766 AP-746 Generate means report PDF
  app/controllers/providers/means_reports_controller.rb
  app/controllers/providers/merits_declarations_controller.rb
  app/models/concerns/legal_aid_application_state_machine.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_capital.rb
  app/services/flow/flows/provider_merits.rb
  app/services/merits_report_creator.rb
  app/services/reports/means_report_creator.rb
  app/services/reports/merits_report_creator.rb
  app/services/reports/reports_creator.rb
  app/views/providers/check_provider_answers/index.html.erb
  app/views/providers/means_reports/show.html.erb
  app/views/providers/means_summaries/show.html.erb
  app/views/providers/merits_reports/_client_details.html.erb
  app/views/providers/merits_reports/show.html.erb
  app/views/providers/submitted_applications/show.html.erb
  app/views/shared/_application_ref.html.erb
  app/views/shared/check_answers/_client_details.html.erb
  app/workers/reports_creator_worker.rb
  config/locales/en/model_enum_translations.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  spec/requests/providers/means_reports_spec.rb
  spec/requests/providers/merits_declarations_spec.rb
  spec/services/reports/means_report_creator_spec.rb
  spec/services/reports/merits_report_creator_spec.rb
  spec/services/reports/reports_creator_spec.rb
Labels: UAT

#778 AP841 Update content on capital introduction page
  config/locales/en/providers.yml
Labels: ready for review

#775 AP-846 Access to non-passported route
  app/assets/stylesheets/interruption-panel.scss
  app/controllers/admin/settings_controller.rb
  app/controllers/providers/check_benefits_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  app/views/providers/check_benefits/_check_benefits_result.html.erb
  app/views/providers/check_benefits/_use_ccms.html.erb
  app/views/providers/check_benefits/index.html.erb
  config/application.rb
  config/locales/en/activemodel.yml
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  db/migrate/20190823093923_add_allow_non_passported_route.rb
  db/schema.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/factories/benefit_check_results.rb
  spec/requests/admin/settings_spec.rb
  spec/requests/providers/check_benefits_spec.rb
Labels: ready for review

#777 AP-714 fix hint text
  config/locales/en/helpers.yml
Labels: UAT

#783 AP-824 persist none_selected checkboxes
  app/controllers/citizens/identify_types_of_incomes_controller.rb
  app/controllers/citizens/identify_types_of_outgoings_controller.rb
  app/controllers/providers/identify_types_of_incomes_controller.rb
  app/controllers/providers/identify_types_of_outgoings_controller.rb
  app/forms/citizens/other_assets_form.rb
  app/forms/savings_amounts/savings_amounts_form.rb
  app/javascript/src/checkbox_control.js
  app/models/concerns/capital.rb
  app/views/shared/forms/_identify_types_of_outgoings_form.html.erb
  app/views/shared/forms/_savings_and_investments_form.html.erb
  app/views/shared/forms/_types_of_income_form.html.erb
  app/views/shared/forms/other_assets/_form.html.erb
  db/migrate/20190827122038_add_none_selected.rb
  db/schema.rb
  spec/forms/citizens/other_assets_form_spec.rb
  spec/forms/savings_amounts/savings_amounts_form_spec.rb
  spec/requests/citizens/identify_types_of_incomes_spec.rb
  spec/requests/citizens/identify_types_of_outgoings_spec.rb
  spec/requests/citizens/other_assets_spec.rb
  spec/requests/citizens/savings_and_investments_spec.rb
  spec/requests/providers/identify_types_of_incomes_spec.rb
  spec/requests/providers/identify_types_of_outgoings_spec.rb
  spec/requests/providers/other_assets_spec.rb
  spec/requests/providers/savings_and_investments_spec.rb
Labels: ready for review

#773 Simplify CircleCI process by using a separate job and workflow rather than parallelism. And some other improvements
  .circleci/config.yml
Labels: UAT

#776 AP869 global means and merits values generated from application
  app/services/ccms/attribute_value_generator.rb
  app/views/providers/submitted_applications/show.html.erb
  config/ccms/ccms_keys.yml
  spec/services/ccms/case_add_requestor_spec.rb
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: ready for review

#788 AP-917 Remove mode as alias for journey
  app/controllers/citizens/other_assets_controller.rb
  app/controllers/citizens/restrictions_controller.rb
  app/controllers/citizens/vehicles/purchase_dates_controller.rb
  app/controllers/citizens/vehicles_controller.rb
  app/controllers/providers/other_assets_controller.rb
  app/controllers/providers/property_values_controller.rb
  app/controllers/providers/restrictions_controller.rb
  app/controllers/providers/vehicles/purchase_dates_controller.rb
  app/controllers/providers/vehicles_controller.rb
  app/forms/citizens/other_assets_form.rb
  app/forms/legal_aid_applications/own_vehicle_form.rb
  app/forms/legal_aid_applications/property_value_form.rb
  app/forms/legal_aid_applications/restrictions_form.rb
  config/locales/en/activemodel.yml
  spec/forms/legal_aid_applications/restrictions_form_spec.rb
  spec/requests/citizens/other_assets_spec.rb
  spec/requests/citizens/restrictions_spec.rb
  spec/requests/providers/other_assets_spec.rb
  spec/requests/providers/restrictions_spec.rb
Labels: ready for review

#782 Ap 810 fix ccms document upload
  app/models/ccms/submission.rb
  app/models/concerns/ccms_submission_state_machine.rb
  app/models/provider.rb
  app/services/ccms/add_case_service.rb
  app/services/ccms/case_add_requestor.rb
  app/services/ccms/obtain_document_id_service.rb
  app/services/ccms/upload_documents_service.rb
  ccms_integration/ccms_spec.rb
  spec/factories/submissions.rb
  spec/models/ccms/submission_spec.rb
  spec/services/ccms/add_case_service_spec.rb
  spec/services/ccms/case_add_requestor_spec.rb
  spec/services/ccms/obtain_document_id_service_spec.rb
  spec/services/ccms/upload_documents_service_spec.rb
Labels: ready for review

#784 AP-877 generate CCM payload attributes from legal aid application
  app/forms/citizens/other_assets_form.rb
  app/models/legal_aid_application.rb
  app/services/ccms/attribute_value_generator.rb
  config/ccms/ccms_keys.yml
  config/locales/en/activemodel.yml
  config/locales/en/shared.yml
  db/migrate/20190827131229_rename_money_assets_value.rb
  db/schema.rb
  spec/factories/other_assets_declarations.rb
  spec/forms/citizens/other_assets_form_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/citizens/other_assets_spec.rb
  spec/requests/providers/other_assets_spec.rb
  spec/services/ccms/case_add_requestor_spec.rb
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: ready for review

#785 AP-538 Add "Error: " prefix to page head title if error present
  app/helpers/application_helper.rb
  app/helpers/page_template_helper.rb
  config/locales/en/errors.yml
  spec/requests/providers/applicants_spec.rb
Labels: ready for review
