Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2019-11, with the labels that each got.

#968 ap-1024 Content edit confirm office
  config/locales/en/providers.yml
  spec/requests/providers/confirm_offices_spec.rb
Labels: UAT

#972 AP-1026 start page content edit
  config/locales/en/providers.yml
Labels: Approved

#991 AP-1039 Remove remaining hardcoded attributes
  config/ccms/ccms_keys.yml
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: Approved

#990 AP-1027 Remove hardcoded housing attributes
  config/ccms/ccms_keys.yml
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: Approved

#986 ap-976 Update readme on admin settings
  README.md
  config/locales/en/providers.yml
Labels: Approved

#985 AP-914 - Add details to means report
  app/controllers/providers/means_reports_controller.rb
  app/views/providers/means_reports/show.html.erb
  app/views/shared/check_answers/_capital_result.html.erb
  ccms_integration/ccms_spec.rb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  spec/factories/cfe_results/mock_results.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/means_reports_spec.rb
  spec/services/ccms/add_case_service_spec.rb
  spec/services/ccms/obtain_document_id_service_spec.rb
  spec/services/reports/means_report_creator_spec.rb
Labels: Approved

#995 Add CCMS reference to submitted application page
  app/views/providers/submitted_applications/show.html.erb
  config/locales/en/providers.yml
Labels: Approved

#998 AP-1042 Remove hardcoded provider reference
  app/services/ccms/case_add_requestor.rb
Labels: Approved

#1001 Avoid Prometheus duplicated targets in UAT
  helm_deploy/apply-for-legal-aid/templates/service-monitor.yaml
Labels: Approved

#1014 Delete .orig file
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb.orig
Labels: Approved

#997 AP-989 Add Sentry alerting for postcode lookup
  app/services/address_lookup_service.rb
  spec/services/address_lookup_service_spec.rb
Labels: Approved

#1000 AP-1044 Correct benefit check result
  app/services/ccms/attribute_value_generator.rb
  config/ccms/ccms_keys.yml
  spec/services/ccms/add_case_service_spec.rb
  spec/services/ccms/case_add_requestor_spec.rb
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: Approved

#1004 AP-1047 content edits to provider dashboard
  app/helpers/application_helper.rb
  config/locales/en/providers.yml
  features/providers/check_your_answers.feature
  features/providers/civil_application_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  features/step_definitions/civil_journey_steps.rb
Labels: Ready to merge

#999 AP-1040 content and style changes
  app/views/providers/end_of_applications/show.html.erb
  config/locales/en/providers.yml
Labels: Approved

#1019 AP 1019 et al - document uploads to CCMS
  app/models/concerns/ccms_submission_state_machine.rb
  app/services/ccms/add_applicant_service.rb
  app/services/ccms/add_case_service.rb
  app/services/ccms/check_applicant_status_service.rb
  app/services/ccms/check_case_status_service.rb
  app/services/ccms/obtain_applicant_reference_service.rb
  app/services/ccms/obtain_case_reference_service.rb
  app/services/ccms/obtain_document_id_service.rb
  spec/models/ccms/submission_spec.rb
  spec/services/ccms/add_case_service_spec.rb
  spec/services/ccms/obtain_document_id_service_spec.rb
Labels: Approved

#1018 AP-931 new contact us layout
  app/views/contacts/show.html.erb
  config/locales/en/contacts.yml
  spec/requests/contact_spec.rb
Labels: Approved

#1024 AP-1059 CCMS warning letter and savings attributes
  app/services/ccms/attribute_value_generator.rb
  config/ccms/ccms_keys.yml
  spec/services/ccms/case_add_requestor_spec.rb
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: Approved

#1029 AP-1016 Fix CCMS delegated functions flag
  app/services/ccms/case_add_requestor.rb
  spec/services/ccms/case_add_requestor_spec.rb
Labels: Approved

#1026 AP-1064 CCMS valuable possessions
  app/services/ccms/attribute_value_generator.rb
  config/ccms/ccms_keys.yml
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: Approved

#1028 AP-1057 Amend hard coded text in CCMS payloads
  config/ccms/ccms_keys.yml
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: Approved

#1003 AP-1045 CYA content edits
  config/locales/en/shared.yml
  spec/requests/citizens/check_answers_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
Labels: Approved, UAT

#1015 AP-1050 content edits to other assets page
  app/views/shared/forms/other_assets/_form.html.erb
  config/locales/en/shared.yml
Labels: Approved, UAT, UAT Success

#1021 AP-1054 Fix bug where currency values no being correctly stored
  app/forms/vehicle_form/estimated_value_form.rb
  app/forms/vehicle_form/remaining_payment_form.rb
  spec/requests/providers/vehicles/estimated_values_spec.rb
  spec/requests/providers/vehicles/remaining_payments_spec.rb
Labels: Approved, UAT, UAT Success

#1027 AP-1055 Error if date fields contain non-numeric characters
  app/forms/concerns/date_field_builder.rb
  spec/requests/citizens/dependants_spec.rb
  spec/requests/citizens/vehicles/purchase_dates_spec.rb
  spec/requests/providers/applicant_details_spec.rb
  spec/requests/providers/date_client_told_incidents_spec.rb
  spec/requests/providers/used_delegated_functions_spec.rb
  spec/requests/providers/vehicles/purchase_dates_spec.rb
Labels: Approved, UAT, UAT Success

#996 AP-948 Improve means result page
  app/models/cfe/result.rb
  app/services/cfe/create_capitals_service.rb
  app/services/mock_benefit_check_service.rb
  app/views/providers/capital_assessment_results/_other_assets.html.erb
  app/views/providers/capital_assessment_results/_property_results.html.erb
  app/views/providers/capital_assessment_results/_total_capital.html.erb
  app/views/providers/capital_assessment_results/show.html.erb
  config/locales/en/providers.yml
  spec/factories/cfe_results.rb
  spec/factories/cfe_results/mock_results.rb
  spec/models/cfe/result_spec.rb
  spec/requests/citizens/legal_aid_applications_spec.rb
  spec/requests/providers/capital_assessment_results_spec.rb
  spec/services/cfe/create_capitals_service_spec.rb
Labels: Approved, UAT

#1034 AP-1072 CYA screen HTML and Styling
  app/assets/stylesheets/check-your-answers.scss
  app/views/shared/check_answers/_item.html.erb
  app/views/shared/check_answers/_no_link_item.html.erb
Labels: Approved

#1033 Ap 1065 content edits limitations
  config/locales/en/providers.yml
  db/seeds/legal_framework/levels_of_service.csv
  features/providers/civil_application_journey.feature
Labels: Approved

#1017 AP-1021 Add a boolean check to see if case has been submitted
  app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
  spec/requests/providers/legal_aid_applications_spec.rb
Labels: Approved

#1023 AP-1061 minor content edits
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/check_your_answers.feature
Labels: Approved

#953 AP-979 Export stats to Geckoboard
  Gemfile
  Gemfile.lock
  README.md
  app/jobs/dashboard/updater_job.rb
  app/models/dashboard/widget.rb
  app/models/dashboard/widget_data_providers/daily_new_providers.rb
  app/models/dashboard/widget_data_providers/number_provider_firms.rb
  app/models/dashboard/widget_data_providers/past_three_weeks_average_feedback_score.rb
  app/models/dashboard/widget_data_providers/past_weeks_average_feedback_score.rb
  app/models/dashboard/widget_data_providers/started_applications.rb
  app/models/dashboard/widget_data_providers/submitted_applications.rb
  app/models/dashboard/widget_data_providers/total_submitted_applications.rb
  app/models/dashboard_widget.rb
  app/models/host_env.rb
  config/application.rb
  config/initializers/dashboard.rb
  features/support/env.rb
  helm_deploy/apply-for-legal-aid/templates/.dashboard_template_cron.yaml.sample
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/dashboard_daily_new_providers_cron.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_number_provider_firms_cron.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_past_three_weeks_average_feedback_score.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_past_weeks_average_feedback_score.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_started_applications_cron.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_submitted_applications_cron.yaml
  helm_deploy/apply-for-legal-aid/templates/dashboard_total_submitted_applications_cron.yml
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  lib/tasks/jobs/dashboard_updater.rake
  spec/jobs/dashboard/updater_job_spec.rb
  spec/models/dashboard/widget_data_providers/daily_new_providers_spec.rb
  spec/models/dashboard/widget_data_providers/number_provider_firms_spec.rb
  spec/models/dashboard/widget_data_providers/past_three_weeks_average_feedback_score_spec.rb
  spec/models/dashboard/widget_data_providers/past_weeks_average_feedback_score_spec.rb
  spec/models/dashboard/widget_data_providers/started_applications_spec.rb
  spec/models/dashboard/widget_data_providers/submitted_applications_spec.rb
  spec/models/dashboard/widget_data_providers/total_submitted_applications_spec.rb
  spec/models/dashboard/widget_spec.rb
  spec/models/host_env_spec.rb
Labels: Approved, UAT

#1032 AP-1066 content edits savings and investments
  app/views/shared/forms/_savings_and_investments_form.html.erb
  config/locales/en/providers.yml
  features/providers/check_your_answers.feature
  features/providers/civil_application_journey.feature
Labels: WIP

#1049 Upgrade Git Crypt guide link in Readme
  README.md
Labels: Approved

#1031 AP-1068 content edits - property % share
  app/views/citizens/percentage_homes/show.html.erb
  app/views/providers/percentage_homes/show.html.erb
  app/views/shared/forms/_percentage_home_form.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/shared.yml
Labels: Approved, UAT

#1048 Fix issue with overlong cronjob name
  helm_deploy/apply-for-legal-aid/templates/.dashboard_template_cron.yaml.sample
  helm_deploy/apply-for-legal-aid/templates/dashboard_total_submitted_applications_cron.yml
Labels: Approved

#1051 Ap 1069 content edit delegated function
  app/views/providers/delegated_confirmation/index.html.erb
  config/locales/en/providers.yml
  features/providers/pathways_from_check_your_answers.feature
  spec/requests/providers/delegated_confirmation_spec.rb
Labels: Approved, UAT

#1052 Ap 1080 layout
  app/views/citizens/property_values/_form.html.erb
  app/views/citizens/property_values/show.html.erb
  app/views/providers/property_values/show.html.erb
  app/views/shared/forms/_outstanding_mortgage_form.html.erb
Labels: Approved, UAT

#1050 AP-1032 Make admin delete all work
  app/models/ccms/submission.rb
  db/migrate/20191114151820_add_on_delete_to_merits_assessment_fk.rb
  db/migrate/20191114152212_add_on_delete_to_statement_of_case_fk.rb
  db/migrate/20191114193807_add_on_delete_to_ccms_submissions_fk.rb
  db/schema.rb
  spec/factories/ccms_submission_documents.rb
  spec/factories/ccms_submission_histories.rb
  spec/factories/ccms_submissions.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/admin/legal_aid_applications_spec.rb
Labels: Approved, UAT

#1055 Ap 1053 error message styling in form
  app/views/providers/used_delegated_functions/show.html.erb
  app/views/shared/_show_errors.html.erb
  app/views/shared/forms/_savings_and_investments_form.html.erb
  app/views/shared/forms/_shared_ownership_form.html.erb
  app/views/shared/forms/_success_prospect_form.html.erb
  app/views/shared/forms/other_assets/_form.html.erb
  app/views/shared/forms/vehicles/_remaining_payment.html.erb
Labels: Approved, UAT

#1056 Refresh True Layer testing account client secret
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: Approved

#1059 AP-944 DoB error message wording
  config/locales/en/activemodel.yml
Labels: ready for review

#1043 AP-923 Add /.well-known/security.txt
  config/routes.rb
  spec/requests/security_text_spec.rb
Labels: Approved, UAT

#1061 FIX matching error in XML blocks for decimals ending in 0
  spec/support/xml_attribute_block_matcher.rb
Labels: Approved

#1022 AP-1035 fix bug where saved applications showing as submitted
  app/controllers/providers/merits_declarations_controller.rb
  app/models/merits_assessment.rb
  spec/requests/providers/merits_declarations_spec.rb
Labels: UAT Success

#1042 AP-1037 Fix various CCMS attributes
  app/models/legal_aid_application.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/case_add_requestor.rb
  ccms_integration/ccms_spec.rb
  config/ccms/ccms_keys.yml
  spec/services/ccms/add_case_service_spec.rb
  spec/services/ccms/case_add_requestor_spec.rb
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
  spec/support/xml_extractor.rb
Labels: Approved, UAT

#1053 AP-1056 content edits to property value page
  config/locales/en/activemodel.yml
  config/locales/en/citizens.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
Labels: Approved

#1063 AP-1081 delegated function cost limitation
  app/models/legal_aid_application.rb
  app/services/ccms/case_add_requestor.rb
  spec/models/legal_aid_application_spec.rb
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
  spec/support/xml_extractor.rb
Labels: Approved

#1062 Fix issues with feature tests
  features/providers/check_your_answers.feature
  features/step_definitions/civil_journey_steps.rb
Labels: Approved

#1058 ap-857 update merits declaration content
  app/views/providers/merits_declarations/show.html.erb
  config/locales/en/providers.yml
Labels: Approved, UAT

#1067 AP-1084 minor ccms payload fixes
  app/services/ccms/case_add_requestor.rb
  config/ccms/ccms_keys.yml
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: ready for review

#1064 AP-1048 making substantive application edits
  config/locales/en/providers.yml
Labels: Approved

#1073 AP-1025 Update Google OAuth2 secrets
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: Approved

#1074 AP-1025 Update Google OAuth2 secrets
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: ready for review

#1076 Update packages before install Python dependencies
  .circleci/config.yml
Labels: ready for review

#1041 AP-959 Use new Provider Details API
  README.md
  app/services/mock_provider_details_retriever.rb
  app/services/provider_details_creator.rb
  app/services/provider_details_retriever.rb
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/cassettes/provider_details_api.yml
  spec/services/mock_provider_details_retriever_spec.rb
  spec/services/provider_details_creator_spec.rb
  spec/services/provider_details_retriever_spec.rb
Labels: Approved

#1066 Ap 985 restrict logins
  .circleci/config.yml
  .gitattributes
  app/controllers/concerns/providers/authorizable.rb
  app/models/provider.rb
  config/initializers/whitelisted_users.rb
  helm_deploy/apply-for-legal-aid/whitelisted_users.yaml
  spec/models/provider_spec.rb
  spec/requests/providers/legal_aid_applications_spec.rb
Labels: Approved

#1005 Mitigate Omniauth CSRF vulnerability
  Gemfile
  Gemfile.lock
  app/views/admin_users/sessions/new.html.erb
  config/initializers/omniauth.rb
  spec/requests/omniauth_csrf_vulnerability_spec.rb
Labels: Approved, security

#1075 AP-1089 Hard code contact ids for private beta users
  .circleci/config.yml
  .gitattributes
  app/services/ccms/case_add_requestor.rb
  app/services/mock_contact_id_provider.rb
  config/encrypted_private_beta_users.yml
  spec/services/mock_contact_id_provider_spec.rb
Labels: Approved

#1078 AP-1091 Change hardcoded opponent name
  app/services/ccms/case_add_requestor.rb
  config/ccms/ccms_keys.yml
  spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Labels: Approved

#1072 AP-934 attached document rationalisation
  app/controllers/providers/statement_of_cases_controller.rb
  app/forms/statement_of_cases/statement_of_case_form.rb
  app/models/attachment.rb
  app/models/legal_aid_application.rb
  app/models/pdf_file.rb
  app/models/statement_of_case.rb
  app/services/ccms/case_add_requestor.rb
  app/services/ccms/obtain_document_id_service.rb
  app/services/ccms/upload_documents_service.rb
  app/services/pdf_converter.rb
  app/services/reports/means_report_creator.rb
  app/services/reports/merits_report_creator.rb
  app/services/reports/reports_creator.rb
  app/views/providers/statement_of_cases/_uploaded_files.html.erb
  app/views/providers/statement_of_cases/show.html.erb
  app/workers/pdf_converter_worker.rb
  ccms_integration/ccms_spec.rb
  db/migrate/20191118142348_create_attachments.rb
  db/migrate/20191120104919_add_attachment_name_to_attachments.rb
  db/migrate/20191121143142_rename_column_on_submissions_documents.rb
  db/schema.rb
  lib/tasks/storage.rake
  spec/factories/attachments.rb
  spec/factories/ccms_submission_documents.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/statement_of_cases.rb
  spec/factories/submission_documents.rb
  spec/requests/providers/statement_of_case_spec.rb
  spec/services/ccms/case_add_requestor_spec.rb
  spec/services/ccms/obtain_document_id_service_spec.rb
  spec/services/ccms/upload_documents_service_spec.rb
  spec/services/pdf_converter_spec.rb
  spec/services/reports/means_report_creator_spec.rb
  spec/services/reports/merits_report_creator_spec.rb
  spec/workers/pdf_converter_worker_spec.rb
  storage/.keep
Labels: Approved, UAT

#1079 Speed up Circle CI tests
  .circleci/config.yml
Labels: ready for review

#1085 AP-1095 Fix widget to send zero values
  app/models/dashboard/widget_data_providers/daily_new_providers.rb
  spec/models/dashboard/widget_data_providers/daily_new_providers_spec.rb
Labels: Approved

#1086 AP-1098 Convert satisfaction scores to GDS standard
  app/models/dashboard/widget_data_providers/past_three_weeks_average_feedback_score.rb
  app/models/dashboard/widget_data_providers/past_weeks_average_feedback_score.rb
  app/models/dashboard/widget_data_providers/started_applications.rb
  app/models/dashboard/widget_data_providers/submitted_applications.rb
  spec/models/dashboard/widget_data_providers/past_three_weeks_average_feedback_score_spec.rb
  spec/models/dashboard/widget_data_providers/past_weeks_average_feedback_score_spec.rb
  spec/models/dashboard/widget_data_providers/started_applications_spec.rb
  spec/models/dashboard/widget_data_providers/submitted_applications_spec.rb
Labels: Approved

#1089 AP-1106 exclude providers not on whitelist from dashboard stats
  app/models/dashboard/widget_data_providers/daily_new_providers.rb
  app/models/dashboard/widget_data_providers/number_provider_firms.rb
  spec/models/dashboard/widget_data_providers/daily_new_providers_spec.rb
  spec/models/dashboard/widget_data_providers/number_provider_firms_spec.rb
Labels: Approved
