Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2020-03, with the labels that each got.

#1288 AP-1195: CCMS gross income
  app/models/applicant.rb
  app/models/cfe/v2/result.rb
  config/ccms/attribute_block_configs/non_passported.yml
  spec/factories/cfe_results.rb
  spec/factories/cfe_results/v2/mock_results.rb
  spec/models/applicant_spec.rb
  spec/models/cfe/v2/result_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
Labels: ready for review

#1289 AP-1240 Update vehicle copy. Remove unused copy from citizens section
  config/locales/en/citizens.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
Labels: ready for review

#1295 Ap-1199 CCMS Housing attributes
  app/models/applicant.rb
  app/models/cfe/v2/result.rb
  config/ccms/attribute_block_configs/non_passported.yml
  spec/factories/cfe_results.rb
  spec/factories/cfe_results/v2/mock_results.rb
  spec/models/applicant_spec.rb
  spec/models/cfe/v2/result_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
Labels: ready for review

#1296 AP-1202: CCMS pui contribution
  config/ccms/attribute_block_configs/non_passported.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
Labels: ready for review

#1302 FIX: update the production client_completed_means uid
  config/govuk_notify_templates.yml
Labels: ready for review

#1228 Ap 1204 cascade delete
  app/models/legal_aid_application.rb
  app/models/scheduled_mailing.rb
  db/migrate/20200207133614_add_foreign_key_to_scheduled_mailings.rb
  db/schema.rb
  spec/factories/scheduled_mailings.rb
  spec/jobs/scheduled_mailings_delivery_job_spec.rb
  spec/models/scheduled_mailing_spec.rb
  spec/requests/admin/legal_aid_applications_spec.rb
Labels: ready for review

#1306 AP-1200: Add CCMS land attributes
  app/services/ccms/attribute_value_generator.rb
  config/ccms/attribute_block_configs/non_passported.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
Labels: Approved

#1303 Dev-update: Add the better_errors and binding_of_caller gems
  Gemfile
  Gemfile.lock
Labels: Approved

#1304 Dev-update: Add redis to procfile
  Procfile
Labels: Approved

#1308 AP-1294 Add 2 hardcoded attributes
  config/ccms/attribute_block_configs/non_passported.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
Labels: Approved

#1305 Dev-update: Add Guard properly
  Gemfile
  Gemfile.lock
  Guardfile
  README.md
Labels: ready for review

#1307 AP-1260 Update content on application created
  app/views/providers/application_confirmations/show.html.erb
  config/locales/en/providers.yml
  spec/requests/providers/application_confirmations_spec.rb
Labels: Approved

#1309 Ap 1246 hard coded ccms attrs
  config/ccms/attribute_block_configs/non_passported.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
Labels: Approved

#1232 AP-1169 Set APPLY_CASE_MEANS_REVIEW attribute according to business rules
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/cfe/base_result.rb
  app/models/legal_aid_application.rb
  app/models/setting.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/manual_review_determiner.rb
  app/views/admin/settings/show.html.erb
  config/ccms/attribute_block_configs/base.yml
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  db/migrate/20200210162352_add_manually_review_all_cases_to_settings.rb
  db/schema.rb
  spec/factories/cfe_results.rb
  spec/factories/cfe_results/v1/mock_results.rb
  spec/factories/legal_aid_applications.rb
  spec/models/cfe/v1/result_spec.rb
  spec/models/cfe/v2/result_spec.rb
  spec/requests/providers/capital_assessment_results_spec.rb
  spec/services/ccms/manual_review_determiner_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: UAT

#1311 AP-1201: Shared ownership CCMS attributes
  app/services/ccms/attribute_value_generator.rb
  config/ccms/attribute_block_configs/non_passported.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
Labels: Approved

#1312 AP-1296: CCMS additional maintenance and prospects of success attributes
  app/services/ccms/attribute_value_generator.rb
  config/ccms/attribute_block_configs/non_passported.yml
  spec/factories/cfe_results.rb
  spec/factories/cfe_results/v2/mock_results.rb
  spec/models/applicant_spec.rb
  spec/models/cfe/v2/result_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
Labels: Approved

#1313 FIX: remove webhints accessibility warning
  app/helpers/page_template_helper.rb
  app/views/providers/application_confirmations/show.html.erb
  app/views/shared/page_templates/_default_page_template.html.erb
Labels: Approved

#1310 AP-1261 Change citizen start page to match prototype
  app/views/citizens/legal_aid_applications/index.html.erb
  config/locales/en/citizens.yml
  features/citizens/citizens.feature
Labels: UAT

#1322 AP-1262: Update citizen financial assessment references
  config/locales/en/citizens.yml
  features/citizens/citizens.feature
Labels: UAT

#1325 AP-1266 Content change to citizen declaration page
  config/locales/en/shared.yml
Labels: Approved, UAT

#1330 AP-1310: Update `none of these` checkbox handling
  app/views/shared/forms/_savings_and_investments_form.html.erb
  app/views/shared/forms/other_assets/_form.html.erb
  features/providers/civil_application_journey.feature
Labels: ready for review

#1328 AP-1303: Update submission_document handling
  app/models/ccms/submission.rb
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/ccms/submitters/add_case_service.rb
  app/services/ccms/submitters/obtain_document_id_service.rb
  app/services/ccms/submitters/upload_documents_service.rb
  ccms_integration/ccms_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
  spec/services/ccms/submitters/upload_documents_service_spec.rb
Labels: Approved

#1323 Ap 1217 income content
  app/models/transaction_type.rb
  app/views/shared/forms/_types_of_income_form.html.erb
  config/locales/en/shared.yml
  config/locales/en/transaction_types.yml
  features/citizens/citizens.feature
Labels: Approved

#1329 FIX: Add resolutions section to package.json
  package.json
  yarn.lock
Labels: ready for review

#1314 AP1270 - Record XML response in CCMS::SubmissionHistory
  app/services/ccms/parsers/applicant_add_response_parser.rb
  app/services/ccms/parsers/applicant_add_status_response_parser.rb
  app/services/ccms/parsers/applicant_search_response_parser.rb
  app/services/ccms/parsers/base_response_parser.rb
  app/services/ccms/parsers/case_add_response_parser.rb
  app/services/ccms/parsers/case_add_status_response_parser.rb
  app/services/ccms/parsers/reference_data_response_parser.rb
  spec/data/ccms/applicant_add_response_no_status.xml
  spec/data/ccms/case_add_response.xml
  spec/data/ccms/case_add_response_failure.xml
  spec/data/ccms/reference_data_response_exception.xml
  spec/data/ccms/reference_data_response_failure.xml
  spec/data/ccms/reference_data_response_without_status_free_text.xml
  spec/services/ccms/parsers/applicant_add_response_parser_spec.rb
  spec/services/ccms/parsers/applicant_add_status_response_parser_spec.rb
  spec/services/ccms/parsers/applicant_search_response_parser_spec.rb
  spec/services/ccms/parsers/case_add_response_parser_spec.rb
  spec/services/ccms/parsers/case_add_status_response_parser_spec.rb
  spec/services/ccms/parsers/reference_data_response_parser_spec.rb
Labels: Approved, UAT

#1334 AP-1300 Add Tranche 4 users
  .gitignore
  config/encrypted_private_beta_users.yml
  helm_deploy/apply-for-legal-aid/whitelisted_users.yaml
  lib/tasks/tranche_maker.rake
Labels: Approved, Changes Requested

#1324 Scheduled mailing fix
  app/mailers/submit_application_reminder_mailer.rb
  spec/mailers/submit_application_reminder_mailer_spec.rb
  spec/services/submit_application_reminder_service_spec.rb
Labels: Approved

#1336 ap-1259Update content
  app/views/providers/about_the_financial_assessments/show.html.erb
  config/locales/en/providers.yml
  features/step_definitions/civil_journey_steps.rb
  spec/requests/providers/about_the_financial_assessments_spec.rb
Labels: UAT

#1339 AP-1237: Update email date display
  app/mailers/submit_application_reminder_mailer.rb
  spec/mailers/submit_application_reminder_mailer_spec.rb
  spec/services/submit_application_reminder_service_spec.rb
Labels: ready for review

#1340 Ap 1276 benefit check content
  app/views/providers/check_benefits/_check_benefits_result.html.erb
  config/locales/en/providers.yml
  features/providers/civil_application_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  spec/requests/providers/check_benefits_spec.rb
Labels: Approved, UAT

#1316 Ap 1116 accessibility attach documents
  app/controllers/providers/statement_of_cases_controller.rb
  app/forms/statement_of_cases/statement_of_case_form.rb
  app/javascript/src/statement_of_case_file_upload.js
  app/views/providers/statement_of_cases/_uploaded_files.html.erb
  app/views/providers/statement_of_cases/show.html.erb
  app/views/shared/forms/_error_summary.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  db/migrate/20200117163347_drop_pdf_files.rb
  db/schema.rb
  features/providers/civil_application_journey.feature
  features/support/steps_helper.rb
  spec/requests/providers/statement_of_case_spec.rb
Labels: Approved, UAT Success

#1343 AP-1327 BUGFIX transaction period not populated
  app/models/legal_aid_application.rb
Labels: Approved

#1354 remove rake task
  lib/tasks/scheduled_mailer.rake
Labels: Approved

#1355 Ap 1219 declaration moved to check merits page
  app/controllers/providers/check_merits_answers_controller.rb
  app/controllers/providers/merits_declarations_controller.rb
  app/models/concerns/legal_aid_application_state_machine.rb
  app/services/flow/flows/provider_merits.rb
  app/views/providers/check_merits_answers/show.html.erb
  app/views/providers/merits_declarations/show.html.erb
  app/views/shared/forms/_list_items.html.erb
  config/locales/en/providers.yml
  features/providers/civil_application_journey.feature
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/merits_declarations_spec.rb
Labels: Ready to merge

#1341 Rename state means_completed to provider_assessing_means
  app/controllers/citizens/declarations_controller.rb
  app/controllers/providers/about_the_financial_assessments_controller.rb
  app/controllers/providers/check_passported_answers_controller.rb
  app/controllers/providers/check_provider_answers_controller.rb
  app/models/concerns/legal_aid_application_state_machine.rb
  app/services/flow/flows/provider_capital.rb
  app/services/test_application_creation_service.rb
  config/locales/en/model_enum_translations.yml
  db/migrate/20200319152301_replace_state_value.rb
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/citizens/declarations_spec.rb
  spec/requests/providers/about_the_financial_assessments_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/means_summaries_spec.rb
  spec/requests/providers/restrictions_spec.rb
Labels: Approved, UAT

#1353 AP-1311: Move provider declaration
  app/controllers/providers/declarations_controller.rb
  app/views/providers/declarations/show.html.erb
  app/views/providers/legal_aid_applications/index.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/civil_application_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/requests/providers/declarations_spec.rb
Labels: UAT

#1349 AP-1304 extract errors doc upload
  app/models/ccms/submission.rb
  app/services/ccms/parsers/base_response_parser.rb
  app/services/ccms/parsers/document_id_response_parser.rb
  app/services/ccms/parsers/document_upload_response_parser.rb
  app/services/ccms/submitters/add_case_service.rb
  app/workers/ccms/submission_process_worker.rb
  spec/data/ccms/document_id_response_failure.xml
  spec/services/ccms/parsers/document_id_response_parser_spec.rb
Labels: Approved, UAT

#1360 AP-1336 Update seed data and add column
  db/migrate/20200327115015_update_name_in_transaction_types.rb
  db/migrate/20200327115101_add_column_to_transaction_types.rb
  db/schema.rb
Labels: Approved, UAT, ready for review

#1359 Ap-1324 adding a new state
  app/jobs/bank_transactions_analyser_job.rb
  app/models/concerns/legal_aid_application_state_machine.rb
  config/locales/en/model_enum_translations.yml
  spec/factories/legal_aid_applications.rb
  spec/jobs/bank_transactions_analyser_job_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/scheduled_mailing_spec.rb
Labels: Approved, UAT, ready for review

#1358 AP-1309 all calls to use V2 of CFE API
  app/services/cfe/base_service.rb
  app/services/cfe/obtain_assessment_result_service.rb
  features/cassettes/Civil_application_journeys/Receives_benefits_and_completes_the_application.yml
  spec/services/cfe/obtain_assessment_result_service_spec.rb
Labels: Approved, UAT
