Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2020-12, with the labels that each got.

#2069 Update test ccms xml details
  spec/data/ccms/case_add_response.xml
  spec/data/ccms/case_add_response_failure.xml
Labels: Approved

#2070 AP-1793 Update the citizen start page
  config/locales/en/citizens.yml
Labels: Ready to merge

#2058 AP-1496 Accessible Statement of Case delete links
  app/helpers/accessible_link_helper.rb
  app/views/providers/statement_of_cases/_uploaded_files.html.erb
  spec/helpers/accessible_link_helper.rb
  spec/helpers/accessible_link_helper_spec.rb
Labels: Approved, question

#2059 AP-1635 Start page copy change
  app/views/providers/legal_aid_applications/index.html.erb
  config/locales/en/generic.yml
  config/locales/en/providers.yml
  features/providers/civil_application_journey.feature
  features/step_definitions/civil_journey_steps.rb
Labels: Approved, UAT

#2021 AP-1463, AP-1477 and AP-1479 Update and standardise check answers pages design (WIP)
  app/controllers/providers/has_dependants_controller.rb
  app/helpers/capital_helper.rb
  app/helpers/check_answers_helper.rb
  app/services/flow/flows/provider_capital.rb
  app/services/flow/flows/provider_dependants.rb
  app/services/flow/flows/provider_start.rb
  app/views/citizens/accounts/index.html.erb
  app/views/citizens/check_answers/_bank_accounts.html.erb
  app/views/citizens/check_answers/_student_finance.html.erb
  app/views/citizens/check_answers/index.html.erb
  app/views/providers/check_passported_answers/show.html.erb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/means_summaries/show.html.erb
  app/views/providers/merits_reports/show.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_client_details.html.erb
  app/views/shared/check_answers/_delegated_functions.html.erb
  app/views/shared/check_answers/_dependants.html.erb
  app/views/shared/check_answers/_income_summary.html.erb
  app/views/shared/check_answers/_item.html.erb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/check_answers/_no_link_item.html.erb
  app/views/shared/check_answers/_no_link_long_item.html.erb
  app/views/shared/check_answers/_one_change_link_long_answers_section.erb
  app/views/shared/check_answers/_proceedings_details.html.erb
  app/views/shared/check_answers/_property.html.erb
  app/views/shared/check_answers/_restrictions.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/check_your_answers.feature
  features/providers/civil_application_journey.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/dependants_controller_spec.rb
  spec/requests/providers/has_dependants_controller_spec.rb
  spec/requests/providers/has_other_dependants_controller_spec.rb
  spec/requests/providers/offline_accounts_spec.rb
Labels: Ready to merge

#2076 Bug-fix: Webpacker pdf fix
  app/helpers/pdf_helper.rb
  app/views/admin/legal_aid_applications/submissions/show.html.erb
  app/views/layouts/pdf.html.erb
Labels: Approved, UAT Success

#2060 AP-1705 Add hint text to statement of case screen
  app/views/providers/statement_of_cases/show.html.erb
  config/locales/en/providers.yml
Labels: Approved, UAT

#2075 AP-1670: Update Feedback Mailer to get correct translations for Notify feedback personalisations
  app/mailers/feedback_mailer.rb
Labels: Approved, UAT

#2082 Ap 1886 add overcommit gem
  .overcommit.yml
  Gemfile
  Gemfile.lock
  README.md
Labels: Approved

#2043 AP-1817 checkbox bugfix
  app/webpack/src/checkbox_control.js
Labels: Approved, UAT

#2071 AP-1858: Update the /additional_accounts page to include latest content
  app/controllers/citizens/additional_accounts_controller.rb
  app/views/citizens/additional_accounts/new.html.erb
  config/locales/cy/citizens.yml
  config/locales/en/citizens.yml
  features/citizens/citizens.feature
  features/citizens/citizens_welsh.feature
  spec/requests/citizens/additional_accounts_spec.rb
Labels: Approved, UAT

#2051 Ap 1807 applicant email
  app/mailers/concerns/notify_template_methods.rb
  app/mailers/notify_mailer.rb
  app/mailers/resend_link_request_mailer.rb
  app/mailers/submit_citizen_financial_reminder_mailer.rb
  app/services/submit_citizen_reminder_service.rb
  config/govuk_notify_templates.yml
  spec/mailers/notify_mailer_spec.rb
  spec/mailers/submit_citizen_financial_reminder_mailer_spec.rb
  spec/services/submit_citizen_reminder_service_spec.rb
Labels: Approved, UAT

#2062 Convert jQuery in table-select-all.js to javascript
  app/webpack/src/table-select-all.js
Labels: Approved, UAT

#2083 AP-1888 Display error summaries on additional accounts screens
  app/controllers/citizens/additional_accounts_controller.rb
  app/forms/applicants/open_banking_consent_form.rb
  app/views/citizens/additional_accounts/_error.html.erb
  app/views/citizens/additional_accounts/index.html.erb
  app/views/citizens/additional_accounts/new.html.erb
Labels: Approved, UAT

#2061 Ap 1139 ask for opponent name
  README.md
  app/controllers/providers/respondent_names_controller.rb
  app/controllers/providers/respondents_controller.rb
  app/forms/respondents/respondent_form.rb
  app/forms/respondents/respondent_name_form.rb
  app/models/legal_aid_application.rb
  app/models/opponent.rb
  app/services/flow/flows/provider_merits.rb
  app/views/providers/respondent_names/show.html.erb
  app/views/providers/respondents/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/migrate/20201127134906_remove_opponents_table.rb
  db/migrate/20201130151951_add_name_to_respondents.rb
  db/schema.rb
  features/providers/civil_application_journey.feature
  spec/factories/opponents.rb
  spec/factories/respondents.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/opponent_spec.rb
  spec/requests/providers/respondent_names_controller_spec.rb
  yarn.lock
Labels: Approved, UAT

#2084 AP-1884: Remove Notify development env from config and helm_deploy
  README.md
  config/application.rb
  config/govuk_notify_templates.yml
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/mailers/submit_application_reminder_mailer_spec.rb
  spec/mailers/submit_citizen_financial_reminder_mailer_spec.rb
  spec/mailers/submit_provider_financial_reminder_mailer_spec.rb
Labels: Approved, UAT

#2081 Ap 1872 completion email
  app/controllers/citizens/check_answers_controller.rb
  app/mailers/citizen_confirmation_mailer.rb
  app/services/citizen_completion_email_service.rb
  config/govuk_notify_templates.yml
  spec/mailers/citizen_confirmation_mailer_spec.rb
Labels: Approved, UAT

#2085 Record CFE API interaction
  lib/tasks/cfe_printer.rake
  lib/tasks/helpers/cfe_payload_recorder.rb
Labels: Approved

#2057 AP-1878 update styling to match GDS
  app/mailers/submit_application_reminder_mailer.rb
  spec/mailers/submit_application_reminder_mailer_spec.rb
  spec/services/submit_application_reminder_service_spec.rb
Labels: Approved, UAT

#2089 remove empty file
  Dockerfile.redc
Labels: Approved

#2088 add new retry for curl:
  Dockerfile
Labels: ready for review

#2086 AP-1820 accessibility feature tests
  README.md
  app/views/providers/legal_aid_applications/index.html.erb
  app/views/shared/check_answers/_dependants.html.erb
  app/views/shared/check_answers/_income_summary.html.erb
  app/views/shared/check_answers/_merits.html.erb
  features/accessibility/citizen.feature
  features/accessibility/provider.feature
  features/cassettes/Provider_accessibility/I_complete_the_client_details_section_of_a_passported_application_and_it_is_accessible.yml
  features/cassettes/Provider_accessibility/I_complete_the_financial_assessment_eligibility_section_for_a_non-passported_application.yml
  features/cassettes/Provider_accessibility/I_complete_the_non-passported_means_assessment_and_it_is_accessible.yml
  features/cassettes/Provider_accessibility/I_start_a_new_application.yml
  features/cassettes/Provider_accessibility/I_start_a_new_application_and_it_is_accessible.yml
  features/cassettes/Provider_accessibility/I_start_a_new_non-passported_application.yml
  features/cassettes/Provider_accessibility/I_start_a_new_non-passported_application_and_enter_client_details.yml
  features/cassettes/Provider_accessibility/I_start_a_new_non-passported_application_and_it_is_accessible.yml
  features/step_definitions/accessibility.rb
  features/step_definitions/civil_journey_steps.rb
  features/support/env.rb
Labels: Approved, Ready to merge

#2097 AP-1909 Remove better_errors gem
  Gemfile
  Gemfile.lock
Labels: Approved

#2093 AP-1900 Remove "the opponent's name" content from the statement of case page
  app/views/providers/statement_of_cases/show.html.erb
  config/locales/en/providers.yml
Labels: Approved, UAT Success

#2090 AP-1852 add feature flag for cash payments
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  db/migrate/20201210161115_add_cash_payment_flag_to_settings.rb
  db/schema.rb
  lib/tasks/setup_db_for_testing.rake
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
Labels: Approved, UAT

#2103 AP-1870: Update prometheus alerting
  helm_deploy/apply-for-legal-aid/templates/network-policy.yaml
  helm_deploy/apply-for-legal-aid/templates/service-monitor.yaml
Labels: Approved

#2099 Update staging ccmssoa credentials
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: Approved

#2098 Ap 1854 refactor error summaries
  app/views/citizens/additional_accounts/_error.html.erb
  app/views/citizens/additional_accounts/index.html.erb
  app/views/citizens/additional_accounts/new.html.erb
  app/views/citizens/banks/_error.html.erb
  app/views/citizens/banks/index.html.erb
  app/views/providers/applicant_bank_accounts/show.html.erb
  app/views/providers/confirm_offices/show.html.erb
  app/views/providers/has_other_dependants/show.html.erb
  app/views/providers/legal_aid_applications/search.html.erb
  app/views/providers/no_income_summaries/show.html.erb
  app/views/providers/no_outgoings_summaries/show.html.erb
  app/views/providers/remove_dependant/show.html.erb
  app/views/shared/_error.html.erb
Labels: Approved, UAT

#2080 AP-1881 Add debugging and reset ccms_reason
  app/controllers/admin/reports_controller.rb
  app/controllers/providers/use_ccms_controller.rb
  app/models/concerns/base_state_machine.rb
  app/models/concerns/non_passported_state_machine.rb
  app/models/concerns/passported_state_machine.rb
  app/services/reports/mis/non_passported_applications_report.rb
  package.json
  spec/concerns/non_passported_state_machine_spec.rb
  spec/concerns/passported_state_machine_spec.rb
  spec/factories/legal_aid_applications.rb
  yarn.lock
Labels: Approved, UAT

#2091 AP-1907 Fix unknown ccms reason
  app/controllers/providers/use_ccms_controller.rb
  app/models/concerns/base_state_machine.rb
  spec/requests/providers/use_ccms_spec.rb
Labels: Approved

#2106 add standard js
  .overcommit.yml
  package.json
  yarn.lock
Labels: Approved

#2092 AP-1495 Move file list to below upload button
  app/controllers/providers/statement_of_cases_controller.rb
  app/views/providers/statement_of_cases/show.html.erb
Labels: Approved

#2109 Ap 1901 policy disregards
  .env.sample
  app/controllers/providers/policy_disregards_controller.rb
  app/forms/providers/policy_disregards_form.rb
  app/helpers/check_answers_helper.rb
  app/helpers/dependant_helper.rb
  app/helpers/policy_disregards_helper.rb
  app/models/legal_aid_application.rb
  app/models/policy_disregards.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/policy_disregards/show.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_one_link_section.html.erb
  app/views/shared/forms/policy_disregards/_form.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/migrate/20201215120821_create_policy_disregards_table.rb
  db/schema.rb
  features/accessibility/provider.feature
  features/providers/check_your_answers.feature
  features/providers/civil_application_journey.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/factories/legal_aid_applications.rb
  spec/factories/policy_disregards.rb
  spec/helpers/policy_disregards_helper_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
  spec/requests/providers/means_summaries_spec.rb
  spec/requests/providers/other_assets_spec.rb
  spec/requests/providers/policy_disregards_controller_spec.rb
  spec/requests/providers/restrictions_spec.rb
Labels: ready for review

#2117 Fix: Change staging date to allow testing between xmas and new-year
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: ready for review

#2127 Tech-debt: remove asset config
  config/environments/production.rb
  config/environments/test.rb
Labels: Approved
