Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2020-06, with the labels that each got.

#1476 Ap 1392 circle test fix
  README.md
  config/environments/test.rb
  features/cassettes/Civil_application_journeys/Completes_the_application_using_address_lookup.yml
  features/cassettes/Civil_application_journeys/Completes_the_application_using_manual_address.yml
  features/cassettes/Civil_application_journeys/Completes_the_merits_application_for_applicant_that_does_not_receive_benefits.yml
  features/cassettes/Civil_application_journeys/Completes_the_merits_application_for_applicant_that_does_not_receive_passported_benefits.yml
  features/cassettes/Civil_application_journeys/Enter_feedback_within_provider_journey.yml
  features/cassettes/Civil_application_journeys/Enter_feedback_within_provider_journey_then_click_Back.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_clear_proceeding_on_the_proceeding_page.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_select_multiple_proceeding_types.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_view_the_client_completed_means_answers.yml
  features/cassettes/Civil_application_journeys/I_can_see_that_the_applicant_does_not_receive_benefits.yml
  features/cassettes/Civil_application_journeys/I_can_see_that_the_applicant_receives_benefits.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_address_from_the_check_your_answers_page.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_address_manually_from_the_check_your_answers_page.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_client_details_after_a_failed_benefit_check.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_email_address_from_the_about_financial_assessment_page.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_email_from_the_check_your_answers_page.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_first_name_from_the_check_your_answers_page.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_the_proceeding_type_from_the_check_your_answers_page.yml
  features/cassettes/Civil_application_journeys/I_want_to_return_to_check_your_answers_from_address_lookup.yml
  features/cassettes/Civil_application_journeys/I_want_to_return_to_check_your_answers_from_address_select.yml
  features/cassettes/Civil_application_journeys/I_want_to_return_to_the_check_your_answers_page_without_changing_email.yml
  features/cassettes/Civil_application_journeys/I_want_to_return_to_the_check_your_answers_page_without_changing_first_name.yml
  features/cassettes/Civil_application_journeys/I_want_to_return_to_the_check_your_answers_page_without_changing_proceeding_type.yml
  features/cassettes/Civil_application_journeys/No_results_returned_is_seen_on_screen_when_invalid_proceeding_search_entered.yml
  features/cassettes/Civil_application_journeys/Receives_benefits_and_completes_the_application.yml
  features/cassettes/Civil_application_journeys/View_feedback_form_within_provider_journey.yml
  features/cassettes/Pathways_from_check_your_answers/I_do_not_use_delegated_functions.yml
  features/cassettes/Pathways_from_check_your_answers/I_do_not_use_delegated_functions_for_a_passported_journey.yml
  features/cassettes/Pathways_from_check_your_answers/I_use_delegated_functions_and_a_substantive_application.yml
  features/cassettes/Pathways_from_check_your_answers/I_use_delegated_functions_and_a_substantive_application_for_a_passported_journey.yml
  features/cassettes/Pathways_from_check_your_answers/I_use_delegated_functions_and_will_return_later.yml
  features/providers/civil_application_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/cassettes/benefit_check_service/missing_credential.yml
  spec/cassettes/benefit_check_service/service_error.yml
  spec/cassettes/benefit_check_service/successful_call.yml
  spec/cassettes/check_benefits_requests/GET_/providers/applications/_application_id/check_benefits/generates_a_new_check_benefit_result.yml
  spec/cassettes/check_benefits_requests/GET_/providers/applications/_application_id/check_benefits/returns_http_success.yml
Labels: Approved

#1471 AP1444 Use new CFE Assessment POST response
  app/services/cfe/create_assessment_service.rb
  spec/cassettes/CFE_SubmissionManager/_call/completes_process.yml
  spec/services/cfe/create_assessment_service_spec.rb
Labels: Approved, WIP

#1466 AP-1428 add WSDL location to non-passported case add requestor
  app/services/ccms/requestors/non_passported_case_add_requestor.rb
  config/ccms/attribute_block_configs/non_passported.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: Approved, UAT

#1489 AP-1389 Rename Home and Back liks
  .rubocop.yml
  app/controllers/citizens/citizen_base_controller.rb
  app/models/legal_aid_application.rb
  app/presenters/applicant_account_presenter.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/requestors/applicant_add_requestor.rb
  app/services/cfe/submission_manager.rb
  app/services/cleanup_capital_attributes.rb
  app/services/flow/base_flow_service.rb
  app/services/legal_aid_applications/calculation_date_service.rb
  app/services/mock_benefit_check_service.rb
  app/services/true_layer/bank_data_import_service.rb
  app/views/providers/declarations/show.html.erb
  app/views/shared/forms/_applicant_form.html.erb
  features/support/env.rb
  spec/requests/providers/applicants_spec.rb
  spec/requests/providers/legal_aid_applications_spec.rb
Labels: Approved, UAT

#1483 AP1115 Fix screen reader issues with multiple H1s on the Respondants page
  app/javascript/src/respondent_detail.js
  app/lib/govuk_elements_form_builder/form_builder.rb
  app/views/providers/respondents/_respondent_detail.html.erb
  spec/lib/govuk_elements_form_builder/form_builder_spec.rb
Labels: Approved

#1500 CircleCI Update: Enable test timings
  .circleci/config.yml
  Gemfile
  Gemfile.lock
Labels: Approved

#1493 AP-1414: provider review application details
  app/assets/stylesheets/moj_banner.scss
  app/views/providers/check_provider_answers/_read_only.html.erb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/check_provider_answers/_standard.html.erb
  app/views/providers/check_provider_answers/index.html.erb
  config/locales/en/providers.yml
  features/cassettes/Non-passported_applicant_journeys/I_want_the_check_provider_answers_page_to_correctly_display_while_waiting_for_client_to_provide_data.yml
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
Labels: Approved, UAT

#1490 AP-1411 Explanatory copy
  app/views/shared/forms/_identify_types_of_outgoings_form.html.erb
  app/views/shared/forms/_types_of_income_form.html.erb
  config/locales/en/shared.yml
Labels: Approved, UAT

#1503 remove v1 references and factories
  ccms_integration/ccms_spec.rb
  spec/factories/cfe_results.rb
  spec/factories/cfe_results/v1/mock_results.rb
  spec/factories/legal_aid_applications.rb
  spec/models/cfe/v1/result_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/cfe/obtain_assessment_result_service_spec.rb
Labels: Approved, ready for review

#1507 AP-1473 feature flag for new student loan
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  db/migrate/20200610213903_add_student_loan_feature_flag_to_settings.rb
  db/schema.rb
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
Labels: Approved, UAT

#1502 Change Circle CI unit test output method
  .circleci/config.yml
Labels: Approved, ready for review

#1504 AP-1450 capture possible errors from true layer
  app/controllers/admin_users/omniauth_callbacks_controller.rb
  app/controllers/applicants/omniauth_callbacks_controller.rb
  app/controllers/auth_controller.rb
  app/controllers/citizens/accounts_controller.rb
  app/controllers/concerns/providers/authorizable.rb
  spec/mailers/submit_provider_financial_reminder_mailer_spec.rb
Labels: Approved, UAT

#1509 AP-1474 create new irregular payment table and model
  app/models/irregular_income.rb
  app/models/legal_aid_application.rb
  db/migrate/20200611123802_create_irregular_incomes.rb
  db/schema.rb
  spec/models/irregular_income_spec.rb
Labels: ready for review

#1508 AP-1446 Flow around offline bank accounts
  app/controllers/citizens/additional_accounts_controller.rb
  spec/requests/citizens/additional_accounts_spec.rb
Labels: Approved, UAT

#1470 AP-1367 Caseworker review section of means report
  app/models/cfe/remarked_transaction.rb
  app/models/cfe/remarked_transaction_collection.rb
  app/models/cfe/remarks.rb
  app/models/cfe/v2/result.rb
  app/services/cfe/create_outgoings_service.rb
  app/views/providers/means_reports/_caseworker_review.html.erb
  app/views/providers/means_reports/show.html.erb
  app/views/shared/check_answers/_deductions_details.html.erb
  app/views/shared/check_answers/_outgoings_details.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  lib/tasks/cfe_printer.rake
  lib/tasks/helpers/cfe_api_displayer.rb
  spec/factories/cfe_results/v2/mock_results.rb
  spec/factory_specs/cfe_result_factory_spec.rb
  spec/models/cfe/remarked_transaction_collection_spec.rb
  spec/models/cfe/remarked_transaction_spec.rb
  spec/models/cfe/remarks_spec.rb
  spec/models/cfe/v2/result_spec.rb
Labels: Approved, UAT

#1518 AP-1486: true layer date formatting
  app/services/true_layer/api_client.rb
  spec/services/true_layer/bank_data_import_service_spec.rb
  spec/services/true_layer/importers/import_transactions_service_spec.rb
Labels: Approved

#1492 AP-1442 Don't send reminder mails when using CCMS
  app/controllers/providers/check_benefits_controller.rb
  app/controllers/providers/open_banking_consents_controller.rb
  app/forms/legal_aid_applications/open_banking_consent_form.rb
  app/jobs/post_submission_processing_job.rb
  app/mailers/base_apply_mailer.rb
  app/mailers/citizen_completed_means_mailer.rb
  app/mailers/feedback_mailer.rb
  app/mailers/notify_mailer.rb
  app/mailers/resend_link_request_mailer.rb
  app/mailers/submission_confirmation_mailer.rb
  app/mailers/submit_application_reminder_mailer.rb
  app/models/concerns/legal_aid_application_state_machine.rb
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transaction_date.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/returns_http_success.yml
  spec/factories/legal_aid_applications.rb
  spec/factories/scheduled_mailings.rb
  spec/jobs/post_submission_processing_job_spec.rb
  spec/mailers/submit_provider_financial_reminder_mailer_spec.rb
  spec/models/scheduled_mailing_spec.rb
  spec/requests/providers/check_benefits_spec.rb
  spec/requests/providers/open_banking_consents_spec.rb
Labels: UAT

#1523 AP-1469 mark student loan as archived
  app/services/populators/transaction_type_populator.rb
  db/migrate/20200616135325_mark_student_loan_transaction_type_as_archived.rb
  db/schema.rb
  features/providers/categorizing_bank_transactions.feature
  spec/models/transaction_type_spec.rb
  spec/services/populators/transaction_type_populator_spec.rb
Labels: Approved, UAT

#1517 AP-1465 send student loan data to CFE
  app/models/concerns/cfe_submission_state_machine.rb
  app/models/irregular_income.rb
  app/services/cfe/create_irregular_incomes_service.rb
  app/services/cfe/submission_manager.rb
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_checkboxes_for_transactions_already_assigned_to_another_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_other_applicants_transactions.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_transactions_that_do_not_match_the_operation_on_the_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_selected_transactions.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transaction_amount.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transaction_date.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transactions_matching_the_operation_on_the_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/renders_the_transactions_page.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/returns_http_success.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_checkboxes_for_transactions_already_assigned_to_another_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_other_applicants_transactions.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_transactions_that_do_not_match_the_operation_on_the_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_selected_transactions.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transaction_amount.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transaction_date.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transactions_matching_the_operation_on_the_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/renders_the_transactions_page.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/returns_http_success.yml
  spec/cassettes/Providers_TransactionsController/call_to_Check_Financial_Eligibility_Service_is_successful/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_checkboxes_for_transactions_already_assigned_to_another_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/call_to_Check_Financial_Eligibility_Service_is_successful/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transaction_date.yml
  spec/cassettes/Providers_TransactionsController/call_to_Check_Financial_Eligibility_Service_is_successful/GET_providers/incoming_transactions/does_not_show_transactions_that_do_not_match_the_operation_on_the_transaction_type.yml
  spec/factories/cfe_results/state_benefit_types/mock_state_benefit_type_result.rb
  spec/factories/irregular_incomes.rb
  spec/requests/providers/transactions_spec.rb
  spec/services/cfe/create_irregular_incomes_service_spec.rb
  spec/services/cfe/submission_manager_spec.rb
Labels: Approved

#1522 AP-1440: Submit CSV transaction report to CCMS
  .rubocop_todo.yml
  app/models/attachment.rb
  app/models/legal_aid_application.rb
  app/presenters/bank_transaction_presenter.rb
  app/services/ccms/requestors/document_id_requestor.rb
  app/services/ccms/requestors/document_upload_requestor.rb
  app/services/ccms/submitters/obtain_document_id_service.rb
  app/services/ccms/submitters/upload_documents_service.rb
  app/services/reports/bank_transaction_report_creator.rb
  app/services/reports/reports_creator.rb
  spec/factories/attachments.rb
  spec/factories/legal_aid_applications.rb
  spec/presenters/bank_transaction_presenter_spec.rb
  spec/services/ccms/requestors/document_id_requestor_spec.rb
  spec/services/ccms/requestors/document_upload_requestor_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
  spec/services/ccms/submitters/upload_documents_service_spec.rb
  spec/services/reports/bank_transaction_report_creator_spec.rb
  spec/services/reports/reports_creator_spec.rb
Labels: Approved

#1521 AP-1455 Increases polling times to allow for CCMS delays
  app/models/ccms/submission.rb
  app/workers/ccms/submission_process_worker.rb
  spec/models/ccms/submission_spec.rb
Labels: Approved, UAT

#1529 AP1485 BugFix - Return false after a Raven.capture_exception
  app/services/benefit_check_service.rb
  spec/services/benefit_check_service_spec.rb
Labels: Approved

#1528 Rubocop tidy
  .rubocop.yml
  .rubocop_todo.yml
  bin/bundle
  bin/rails
  bin/rake
  bin/rspec
  bin/setup
  bin/spring
  bin/update
  config/application.rb
  config/environments/production.rb
  config/puma.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: ready for review

#1511 Ap 1466 student finance cya
  app/models/irregular_income.rb
  app/models/legal_aid_application.rb
  app/views/citizens/check_answers/_student_finance.html.erb
  app/views/citizens/check_answers/index.html.erb
  config/locales/en/citizens.yml
  spec/factories/irregular_incomes.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/citizens/check_answers_spec.rb
Labels: Approved, UAT

#1539 BugFix Run JavaScript tests in CircleCI as part of unit tests job
  .circleci/config.yml
Labels: ready for review

#1549 AP1494 Add tranche 7 users
  config/encrypted_private_beta_users.yml
  helm_deploy/apply-for-legal-aid/whitelisted_users.yaml
  lib/tasks/tranche_maker.rake
Labels: Approved, ready for review

#1545 Enforce ordering of CCMS SubmissionHistories in specs
  spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
Labels: Approved

#1554 AP-1470 Fix typo on means report
  config/locales/en/shared.yml
Labels: UAT

#1555 FIX: Add cucumber to guard
  Gemfile
  Gemfile.lock
  Guardfile
Labels: Approved
