Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2020-08, with the labels that each got.

#1625 FIX: Update check_passported_answers event
  app/models/concerns/passported_state_machine.rb
Labels: Approved

#1622 AP-1554: geckoboard feedback update
  app/jobs/dashboard/feedback_item_job.rb
  app/models/dashboard/single_object/feedback.rb
  app/models/feedback.rb
  app/services/dashboard_event_handler.rb
  spec/factories/feedbacks.rb
  spec/jobs/dashboard/feedback_item_job_spec.rb
  spec/models/dashboard/single_object/feedback_spec.rb
  spec/services/dashboard_event_handler_spec.rb
Labels: Approved

#1621 AP-1461: Remove the LegalAidApplication state column
  db/migrate/20200729140115_remove_legal_aid_application_state_column.rb
Labels: Approved

#1629 Fix AASM deprecation warning
  Gemfile
  Gemfile.lock
Labels: ready for review

#1628 AP-1315 Remove details_response from Provider
  app/services/provider_details_creator.rb
  db/migrate/20200803154318_remove_details_response_from_providers.rb
  db/schema.rb
Labels: Approved

#1617 Notify sentry when a Firm has no permission
  app/models/provider.rb
  spec/factories/firms.rb
  spec/models/provider_spec.rb
Labels: Approved

#1608 Ap 614 reminder email client
  app/controllers/citizens/resend_link_requests_controller.rb
  app/mailers/resend_link_request_mailer.rb
  app/views/citizens/resend_link_requests/update.html.erb
  config/govuk_notify_templates.yml
  config/locales/en/citizens.yml
  spec/mailers/resend_link_request_mailer_spec.rb
Labels: Approved, ready for review

#1603 AP1408 Provider open banking consent page redesign
  app/controllers/providers/open_banking_consents_controller.rb
  app/forms/legal_aid_applications/open_banking_consent_form.rb
  app/models/concerns/non_passported_state_machine.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/open_banking_consents/show.html.erb
  app/views/shared/forms/_open_banking_consents.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  db/migrate/20200723102331_remove_citizen_uses_online_banking_from_legal_aid_applications.rb
  db/schema.rb
  features/providers/civil_application_journey.feature
  features/providers/non_passported_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/open_banking_consents_spec.rb
Labels: UAT

#1636 DAC: Update Circle CI
  .circleci/config.yml
Labels: Approved

#1632 AP-1592: Ensure provider contact ID presence
  app/services/provider_details_creator.rb
  spec/services/provider_details_creator_spec.rb
Labels: Approved

#1635 AP-1557 Display correct means result when manual_check_required is set
  app/models/cfe/base_result.rb
  features/providers/civil_application_journey.feature
  spec/models/cfe/v2/result_spec.rb
Labels: Ready to merge

#1637 AP-1566 Display firm name to citizen
  app/views/citizens/legal_aid_applications/index.html.erb
  spec/requests/citizens/legal_aid_applications_spec.rb
Labels: Ready to merge

#1644 FIX: Update ProviderDetailsCreator
  app/services/provider_details_creator.rb
  spec/services/provider_details_creator_spec.rb
Labels: Approved

#1627 AP-1318: Update authorisation for users
  .gitattributes
  app/controllers/concerns/providers/authorizable.rb
  app/models/dashboard/widget_data_providers/daily_new_providers.rb
  app/models/dashboard/widget_data_providers/number_provider_firms.rb
  app/models/provider.rb
  config/initializers/whitelisted_users.rb
  helm_deploy/apply-for-legal-aid/whitelisted_users.yaml
  helm_deploy/apply-for-legal-aid/whitelisted_users_exclude.yaml
  lib/tasks/tranche_maker.rake
  spec/factories/providers.rb
  spec/models/dashboard/widget_data_providers/daily_new_providers_spec.rb
  spec/models/dashboard/widget_data_providers/number_provider_firms_spec.rb
  spec/models/provider_spec.rb
  spec/requests/providers/legal_aid_applications_spec.rb
Labels: Approved, Blocked

#1619 AP1317 Update XML to use contact id from provider record
  .gitattributes
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/mock_contact_id_provider.rb
  app/services/provider_details_creator.rb
  config/encrypted_private_beta_users.yml
  spec/services/mock_contact_id_provider_spec.rb
  spec/services/provider_details_creator_spec.rb
Labels: Blocked, ready for review

#1645 AP1562 Proceeding Types: Inform screen reader users to tab out of serach box to see results
  app/javascript/src/modules/proceedings.js
  app/views/providers/proceedings_types/index.html.erb
  config/locales/en/providers.yml
Labels: UAT

#1655 AP1567 Add a page break before sections for print view
  app/assets/stylesheets/helpers.scss
  app/views/providers/submitted_applications/show.html.erb
Labels: UAT

#1634 AP1555 Show expanded detail only for citizen on the types of income and outgoing pages
  Dockerfile
  app/views/citizens/identify_types_of_incomes/show.html.erb
  app/views/citizens/identify_types_of_outgoings/show.html.erb
  app/views/providers/identify_types_of_incomes/show.html.erb
  app/views/providers/identify_types_of_outgoings/show.html.erb
  app/views/shared/forms/_identify_types_of_outgoings_form.html.erb
  app/views/shared/forms/_types_of_income_form.html.erb
  spec/requests/citizens/identify_types_of_incomes_spec.rb
  spec/requests/citizens/identify_types_of_outgoings_spec.rb
  spec/requests/providers/identify_types_of_incomes_spec.rb
  spec/requests/providers/identify_types_of_outgoings_spec.rb
Labels: UAT

#1664 BUGFIX AASM Transition error on check provider answers page
  app/models/concerns/base_state_machine.rb
  spec/requests/providers/check_benefits_spec.rb
Labels: ready for review

#1640 AP-1378 Fix colour contrast on check_benefits
  app/assets/stylesheets/providers/legal_aid_applications.scss
  app/views/providers/check_benefits/_how_we_checked.html.erb
  app/views/providers/check_benefits/_use_ccms.html.erb
  app/views/providers/use_ccms/show.html.erb
  config/locales/en/providers.yml
Labels: Approved, UAT

#1646 AP-1223 Add hint text to email field
  app/views/providers/email_addresses/show.html.erb
  config/locales/en/providers.yml
  features/providers/civil_application_journey.feature
Labels: UAT

#1647 AP-1575 Add hint text to bank selection screen
  app/views/citizens/banks/index.html.erb
  config/locales/en/citizens.yml
  features/citizens/citizens.feature
Labels: UAT

#1651 BugFix: Prometheus alerts
  helm_deploy/prometheus/prometheus-alerts-production.yaml
  helm_deploy/prometheus/prometheus-alerts-staging.yaml
  helm_deploy/prometheus/prometheus-alerts-uat.yaml
Labels: Approved

#1667 Fix: update serialize-javascript
  package.json
  yarn.lock
Labels: Approved

#1662 AP1540 Accessibility fix for Savings and Investments and other assets page
  app/views/shared/forms/_offline_accounts_form.html.erb
  app/views/shared/forms/_savings_and_investments_form.html.erb
  app/views/shared/forms/other_assets/_form.html.erb
  spec/requests/providers/savings_and_investments_spec.rb
Labels: Approved, Ready to merge

#1648 AP-1319 Combined User Admin PRs
  .gitattributes
  README.md
  app/controllers/concerns/providers/authorizable.rb
  app/controllers/saml_idp_controller.rb
  app/models/dashboard/widget_data_providers/daily_new_providers.rb
  app/models/dashboard/widget_data_providers/number_provider_firms.rb
  app/models/host_env.rb
  app/models/provider.rb
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/mock_contact_id_provider.rb
  app/services/mock_provider_details_retriever.rb
  app/services/provider_details_creator.rb
  app/services/provider_details_retriever.rb
  config/application.rb
  config/encrypted_private_beta_users.yml
  config/environments/test.rb
  config/initializers/whitelisted_users.rb
  db/seeds.rb
  db/seeds/test_provider_populator.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  helm_deploy/apply-for-legal-aid/whitelisted_users.yaml
  helm_deploy/apply-for-legal-aid/whitelisted_users_exclude.yaml
  lib/tasks/tranche_maker.rake
  spec/factories/providers.rb
  spec/models/dashboard/widget_data_providers/daily_new_providers_spec.rb
  spec/models/dashboard/widget_data_providers/number_provider_firms_spec.rb
  spec/models/host_env_spec.rb
  spec/models/provider_spec.rb
  spec/requests/providers/legal_aid_applications_spec.rb
  spec/requests/saml_sessions_spec.rb
  spec/services/mock_contact_id_provider_spec.rb
  spec/services/mock_provider_details_retriever_spec.rb
  spec/services/provider_details_creator_spec.rb
  spec/services/provider_details_retriever_spec.rb
Labels: Approved, Ready to merge

#1665 BugFix: Property value page had a missing translation for the hint
  app/views/providers/property_values/_form.html.erb
  config/locales/en/providers.yml
Labels: Approved

#1668 Fix seeding providers users
  db/seeds/test_provider_populator.rb
Labels: ready for review

#1663 ap-1542 accessibility on statement of case page
  app/views/providers/statement_of_cases/show.html.erb
Labels: Approved, Ready to merge

#1650 Provide more detail on auth error from true layer
  app/controllers/auth_controller.rb
Labels: Approved

#1669 Ap 1590 remve login
  app/services/admin/provider_details_service.rb
  app/services/provider_details_creator.rb
  db/migrate/20200813132316_remove_user_login_from_provider.rb
  db/schema.rb
  db/seeds/test_provider_populator.rb
  spec/services/provider_details_creator_spec.rb
Labels: Approved

#1586 AP1527 Accessibility Error Summary fix
  app/lib/govuk_elements_form_builder/form_builder.rb
  app/views/citizens/accounts/gather.html.erb
  app/views/citizens/banks/_error.html.erb
  app/views/providers/address_selections/show.html.erb
  app/views/providers/confirm_offices/show.html.erb
  app/views/providers/has_other_dependants/show.html.erb
  app/views/providers/legal_aid_applications/_error.html.erb
  app/views/providers/remove_dependant/show.html.erb
  app/views/shared/forms/_date_input_fields.html.erb
  app/views/shared/forms/_error_summary.html.erb
  app/views/shared/forms/_next_action_buttons.html.erb
  app/views/shared/forms/_success_message.html.erb
  config/locales/en/helpers.yml
  spec/lib/govuk_elements_form_builder/form_builder_spec.rb
  spec/requests/providers/client_received_legal_helps_spec.rb
Labels: Approved, UAT

#1681 AP1587 geckoboard nonpassported
  app/models/dashboard/widget_data_providers/applications.rb
  spec/factories/legal_aid_applications.rb
  spec/models/dashboard/widget_data_providers/applications_spec.rb
Labels: UAT

#1683 AP-1588: Geckoboard client emails
  app/jobs/dashboard/applicant_email_job.rb
  app/models/dashboard/single_object/applicant_email.rb
  app/services/citizen_email_service.rb
  app/services/dashboard_event_handler.rb
  spec/jobs/dashboard/applicant_email_job_spec.rb
  spec/models/dashboard/single_object/applicant_email_spec.rb
  spec/services/citizen_email_service_spec.rb
  spec/services/dashboard_event_handler_spec.rb
Labels: UAT Success, ready for review

#1686 AP-1409 - Simplify DWP benefit check result page
  app/controllers/providers/non_passported_client_instructions_controller.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/check_benefits/_applicant_details.html.erb
  app/views/providers/check_benefits/_check_benefits_result.html.erb
  app/views/providers/check_benefits/_how_we_checked.html.erb
  app/views/providers/non_passported_client_instructions/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/civil_application_journey.feature
  features/providers/non_passported_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  spec/requests/providers/check_benefits_spec.rb
  spec/requests/providers/non_passported_client_instructions.rb
  spec/requests/providers/substantive_applications_spec.rb
Labels: UAT

#1687 AP-1410 Amend start of citizen journey
  app/controllers/citizens/information_controller.rb
  app/services/flow/flows/citizen_start.rb
  app/views/citizens/information/show.html.erb
  app/views/citizens/legal_aid_applications/index.html.erb
  config/locales/en/citizens.yml
  config/routes.rb
  features/citizens/citizens.feature
  spec/helpers/check_answer_url_helper_spec.rb
  spec/requests/citizens/information_spec.rb
  spec/services/flow/base_flow_service_spec.rb
Labels: UAT

#1696 AP1512 WIP access denied
  app/controllers/auth_controller.rb
  spec/requests/applicants/omniauth_callbacks_spec.rb
  spec/requests/auth_spec.rb
Labels: WIP

#1688 AP1583 Update feedback difficulty text for provider and citizen
  app/controllers/feedback_controller.rb
  app/views/feedback/new.html.erb
  config/locales/en/feedback.yml
  features/citizens/citizens.feature
  features/providers/civil_application_journey.feature
Labels: Approved, UAT
