Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2020-05, with the labels that each got.

#1421 BugFix - Update Geckoboard DeclinedConsent to a percentage
  app/models/dashboard/widget_data_providers/percentage_declined_open_banking.rb
  app/models/dashboard/widget_data_providers/total_declined_open_banking.rb
  app/models/legal_aid_application.rb
  app/services/dashboard_event_handler.rb
  spec/models/dashboard/widget_data_providers/percentage_declined_open_banking_spec.rb
Labels: Approved, ready for review

#1420 AP1340 Validation for categorising bank transactions
  app/controllers/providers/income_summary_controller.rb
  app/models/legal_aid_application.rb
  app/views/providers/income_summary/_income_type_item.html.erb
  app/views/providers/income_summary/index.html.erb
  config/locales/en/activemodel.yml
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/bank_transactions.rb
  spec/factories/legal_aid_applications.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/income_summary_spec.rb
Labels: UAT

#1424 AP1362 Send Sentry message when CFE fails to submit
  Gemfile
  app/models/scheduled_mailing.rb
  app/services/benefit_check_service.rb
  app/services/ccms/submitters/base_submission_service.rb
  app/services/cfe/obtain_assessment_result_service.rb
  app/services/cfe/submission_manager.rb
  app/services/govuk_emails/email_monitor.rb
  app/services/slack_alert_sender.rb
  app/workers/slack_alert_sender_worker.rb
  config/application.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/models/scheduled_mailing_spec.rb
  spec/services/benefit_check_service_spec.rb
  spec/services/cfe/submission_manager_spec.rb
  spec/services/govuk_emails/email_monitor_spec.rb
  spec/services/slack_alert_sender_spec.rb
  spec/workers/slack_alert_sender_worker_spec.rb
Labels: Approved, ready for review

#1426 AP1416 Outgoing catergorised validation
  app/controllers/providers/income_summary_controller.rb
  app/controllers/providers/outgoings_summary_controller.rb
  app/models/legal_aid_application.rb
  app/views/providers/outgoings_summary/_outgoing_type_item.html.erb
  app/views/providers/outgoings_summary/index.html.erb
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/bank_transactions.rb
  spec/factories/legal_aid_applications.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/outgoings_summary_spec.rb
Labels: UAT

#1418 AP-1208 Non-passported means report
  .rubocop.yml
  app/assets/stylesheets/check-your-answers.scss
  app/controllers/providers/means_reports_controller.rb
  app/helpers/check_answers_helper.rb
  app/models/cfe/v2/result.rb
  app/services/reports/means_report_creator.rb
  app/views/providers/means_reports/show.html.erb
  app/views/shared/check_answers/_deductions_details.html.erb
  app/views/shared/check_answers/_income_details.html.erb
  app/views/shared/check_answers/_income_result.html.erb
  app/views/shared/check_answers/_outgoings_details.html.erb
  app/views/shared/means_report/_item.html.erb
  app/views/shared/means_report/_total.html.erb
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  spec/factories/cfe_results/v2/mock_results.rb
  spec/factory_specs/cfe_result_factory_spec.rb
Labels: UAT

#1444 AP-1380: Update geckoboard feedback dataset
  app/models/dashboard/widget_data_providers/feedback_scores.rb
  spec/models/dashboard/widget_data_providers/feedback_scores_spec.rb
Labels: Approved

#1445 AP-1424 Add tranche 6 users
  config/encrypted_private_beta_users.yml
  helm_deploy/apply-for-legal-aid/whitelisted_users.yaml
  lib/tasks/tranche_maker.rake
Labels: question, ready for review

#1446 AP-1404: Add transaction_id to the CFE bank transactions
  app/services/cfe/create_other_income_service.rb
  app/services/cfe/create_outgoings_service.rb
  app/services/cfe/create_state_benefits_service.rb
  spec/services/cfe/create_other_income_service_spec.rb
  spec/services/cfe/create_outgoings_service_spec.rb
  spec/services/cfe/create_state_benefits_service_spec.rb
Labels: Approved

#1443 AP-1385 Update default setting of manually review all cases
  db/migrate/20200514080421_update_manually_review_all_cases.rb
  db/schema.rb
  features/providers/civil_application_journey.feature
  features/support/env.rb
  spec/factories/cfe_results/v1/mock_results.rb
  spec/models/cfe/v1/result_spec.rb
  spec/requests/admin/settings_spec.rb
Labels: WIP, ready for review

#1441 Ap 1250 income breakdown
  app/models/cfe/v2/result.rb
  app/views/providers/capital_income_assessment_results/_deductions.html.erb
  app/views/providers/capital_income_assessment_results/_disposable_income.html.erb
  app/views/providers/capital_income_assessment_results/_income.html.erb
  app/views/providers/capital_income_assessment_results/_outgoings.html.erb
  app/views/providers/capital_income_assessment_results/_result_details.html.erb
  config/locales/en/providers.yml
  features/cassettes/Civil_application_journeys/Completes_the_merits_application_for_applicant_that_does_not_receive_passported_benefits.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_view_the_client_completed_means_answers.yml
Labels: Approved, UAT

#1436 AP 1383 Allocate disregarded benefits
  app/controllers/providers/identify_types_of_incomes_controller.rb
  app/models/bank_transaction.rb
  app/models/legal_aid_application.rb
  app/models/transaction_type.rb
  app/views/providers/income_summary/_income_type_item.html.erb
  app/views/providers/income_summary/index.html.erb
  db/sample_data/bank_transactions_2.csv
  features/providers/categorizing_bank_transactions.feature
  features/providers/civil_application_journey.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
  features/support/env.rb
  features/support/steps_helper.rb
  spec/models/bank_transaction_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/transaction_type_spec.rb
Labels: Approved, UAT

#1450 AP1375 Contact Solicitor if additional bank accounts are offline
  app/controllers/citizens/additional_accounts_controller.rb
  app/services/flow/flows/citizen_start.rb
  app/views/citizens/additional_accounts/new.html.erb
  config/locales/en/citizens.yml
  config/locales/en/helpers.yml
  features/cassettes/Citizen_journey/Follow_citizen_journey_from_Accounts_page.yml
  features/citizens/citizens.feature
  spec/requests/citizens/additional_accounts_spec.rb
Labels: ready for review

#1456 Fix the circle ci script
  .circleci/config.yml
Labels: Approved

#1460 change text for boolean
  app/mailers/feedback_mailer.rb
Labels: ready for review

#1458 Add my email address to test users
  config/initializers/mock_saml.rb
Labels: Approved

#1457 AP-1419: Save-as-draft update
  app/controllers/providers/capital_assessment_results_controller.rb
  app/controllers/providers/capital_income_assessment_results_controller.rb
  app/views/providers/capital_assessment_results/show.html.erb
  app/views/providers/capital_income_assessment_results/show.html.erb
  config/routes.rb
  spec/requests/providers/capital_assessment_results_spec.rb
  spec/requests/providers/capital_income_assessment_results_spec.rb
Labels: Approved

#1447 Ap 1384 select disregard benefits
  app/controllers/providers/transactions_controller.rb
  app/helpers/transaction_type_helper.rb
  app/views/providers/transactions/_disregarded_list.html.erb
  app/views/providers/transactions/show.html.erb
  config/locales/en/providers.yml
  config/locales/en/transaction_types.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_view_the_client_completed_means_answers.yml
  features/cassettes/Completing_and_checking_means_answers_backwards_and_forwards/I_add_a_benefits_category_and_add_transactions_to_included_and_excluded_benefits.yml
  features/cassettes/Completing_and_checking_means_answers_backwards_and_forwards/I_navigate_to_the_Check_your_answers_page_and_then_add_some_outgoing_transaction_types.yml
  features/cassettes/Non-passported_applicant_journeys/Selects_and_categorises_bank_transactions_into_transaction_types.yml
  features/providers/categorizing_bank_transactions.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_checkboxes_for_transactions_already_assigned_to_another_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_other_applicants_transactions.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_transactions_that_do_not_match_the_operation_on_the_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_selected_transactions.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transaction_amount.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transaction_date.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transactions_matching_the_operation_on_the_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/renders_the_transactions_page.yml
  spec/cassettes/Providers_TransactionsController/GET_citizens/outgoing_transactions/behaves_like_GET_providers/transactions/returns_http_success.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_checkboxes_for_transactions_already_assigned_to_another_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_other_applicants_transactions.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_transactions_that_do_not_match_the_operation_on_the_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_selected_transactions.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transaction_amount.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transaction_date.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transactions_matching_the_operation_on_the_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/renders_the_transactions_page.yml
  spec/cassettes/Providers_TransactionsController/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/returns_http_success.yml
  spec/cassettes/Providers_TransactionsController/call_to_Check_Financial_Eligibility_Service_is_successful/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/does_not_show_checkboxes_for_transactions_already_assigned_to_another_transaction_type.yml
  spec/cassettes/Providers_TransactionsController/call_to_Check_Financial_Eligibility_Service_is_successful/GET_providers/incoming_transactions/behaves_like_GET_providers/transactions/When_there_are_transactions/shows_the_transaction_date.yml
  spec/cassettes/Providers_TransactionsController/call_to_Check_Financial_Eligibility_Service_is_successful/GET_providers/incoming_transactions/does_not_show_transactions_that_do_not_match_the_operation_on_the_transaction_type.yml
  spec/requests/providers/transactions_spec.rb
  spec/services/cfe/obtain_state_benefit_types_service_spec.rb
Labels: Approved
