Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2020-04, with the labels that each got.

#1369 FIX: Update the yarn, kind-of dependancy
  package.json
  yarn.lock
Labels: Approved, ready for review

#1363 bump guard version
  Gemfile.lock
Labels: Approved, ready for review

#1361 AP-1325 Analyse state benefits
  app/jobs/bank_transactions_analyser_job.rb
  app/models/concerns/legal_aid_application_state_machine.rb
  app/services/cfe/base_service.rb
  app/services/cfe/obtain_state_benefit_types_service.rb
  app/services/state_benefit_analyser_service.rb
  db/migrate/20200327171336_add_meta_data_to_bank_transactions.rb
  db/sample_data/bank_transactions.csv
  db/schema.rb
  spec/factories/transaction_types.rb
  spec/jobs/bank_transactions_analyser_job_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/citizens/declarations_spec.rb
  spec/services/cfe/obtain_state_benefit_types_service_spec.rb
  spec/services/state_benefit_analyser_service_spec.rb
Labels: Approved

#1364 WIP. AP-1337 Add new states to CFESubmission state machine
  app/models/concerns/cfe_submission_state_machine.rb
  bin/uat_deploy
  spec/models/concerns/cfe_submission_state_machine_spec.rb
  spec/services/cfe/obtain_assessment_result_service_spec.rb
  spec/services/cfe/submission_manager_spec.rb
Labels: Approved

#1371 AP-1335 CFE other_income_service
  app/models/transaction_type.rb
  app/services/cfe/create_other_income_service.rb
  db/migrate/20200327115101_add_column_to_transaction_types.rb
  spec/factories/bank_transactions.rb
  spec/models/transaction_type_spec.rb
  spec/services/cfe/create_other_income_service_spec.rb
Labels: ready for review

#1380 FIX: Update TransactionType seeding to fix broken migration
  app/models/transaction_type.rb
  db/migrate/20190313174812_add_archived_at_to_transaction_types.rb
  spec/models/transaction_type_spec.rb
Labels: Approved, ready for review

#1375 AP-1338 Add non-passported services to submission manager
  app/models/cfe/submission.rb
  app/models/concerns/cfe_submission_state_machine.rb
  app/services/cfe/create_other_income_service.rb
  app/services/cfe/submission_manager.rb
  spec/models/concerns/cfe_submission_state_machine_spec.rb
  spec/services/cfe/create_other_income_service_spec.rb
  spec/services/cfe/submission_manager_spec.rb
Labels: Approved, UAT, ready for review

#1381 AP-1349 Tranche 5 users
  config/encrypted_private_beta_users.yml
  helm_deploy/apply-for-legal-aid/whitelisted_users.yaml
  lib/tasks/tranche_maker.rake
Labels: ready for review

#1342 AP-1305: Non passported apply case means review
  app/services/ccms/manual_review_determiner.rb
  spec/services/ccms/manual_review_determiner_spec.rb
Labels: Approved, UAT

#1388 AP1357 Update circleci to notify slack of approvals waiting
  .circleci/config.yml
Labels: ready for review

#1386 Ap 1332 feedback questions
  app/controllers/feedback_controller.rb
  app/mailers/feedback_mailer.rb
  app/models/concerns/translatable_model_attribute.rb
  app/models/feedback.rb
  app/views/feedback/new.html.erb
  config/locales/en/feedback.yml
  config/locales/en/model_enum_translations.yml
  db/migrate/20200408135701_add_difficulty_to_feedback.rb
  db/schema.rb
  spec/factories/feedbacks.rb
  spec/requests/feedbacks_spec.rb
Labels: Approved, UAT

#1391 AP-1359: Update circle sequence
  .circleci/config.yml
Labels: ready for review

#1395 Ap 1350 fix feedback
  app/controllers/feedback_controller.rb
  app/models/feedback.rb
  app/views/feedback/new.html.erb
  config/locales/en/activerecord.yml
  config/locales/en/feedback.yml
  config/locales/en/helpers.yml
  features/providers/civil_application_journey.feature
  spec/requests/admin/feedback_spec.rb
  spec/requests/feedbacks_spec.rb
Labels: Approved

#1397 AP-1372 Dependants CFE data bug
  app/models/dependant.rb
  app/services/cfe/create_dependants_service.rb
  spec/models/dependant_spec.rb
Labels: Approved, UAT

#1399 AP1341 Content updates to income summary and transactions pages
  app/views/providers/income_summary/index.html.erb
  app/views/providers/transactions/show.html.erb
  config/locales/en/providers.yml
  config/locales/en/transaction_types.yml
  features/providers/civil_application_journey.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  spec/requests/providers/transactions_spec.rb
Labels: Approved

#1398 AP69 Citizen declines open banking
  app/controllers/citizens/consents_controller.rb
  app/controllers/citizens/contact_providers_controller.rb
  app/forms/applicants/open_banking_consent_form.rb
  app/models/concerns/legal_aid_application_state_machine.rb
  app/services/flow/flows/citizen_start.rb
  app/views/citizens/consents/show.html.erb
  app/views/citizens/contact_providers/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/citizens.yml
  config/locales/en/model_enum_translations.yml
  config/routes.rb
  features/citizens/citizens.feature
  spec/factories/legal_aid_applications.rb
  spec/requests/citizens/consent_spec.rb
  spec/requests/citizens/contact_provider_spec.rb
Labels: Approved

#1409 AP1387 Scheduled Mailing bug when used delegated functions is false
  app/controllers/providers/used_delegated_functions_controller.rb
  spec/requests/providers/used_delegated_functions_spec.rb
Labels: ready for review

#1408 Ap 1344 change client details
  app/controllers/providers/check_benefits_controller.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/check_benefits/_check_benefits_result.html.erb
  config/locales/en/providers.yml
  features/providers/civil_application_journey.feature
  spec/requests/providers/applicant_details_spec.rb
Labels: ready for review

#1407 AP-1386 Send outgoings data to CFE
  .rubocop.yml
  app/models/concerns/cfe_submission_state_machine.rb
  app/models/savings_amount.rb
  app/services/cfe/create_outgoings_service.rb
  app/services/cfe/submission_manager.rb
  db/sample_data/bank_transactions_2.csv
  features/cassettes/Civil_application_journeys/Completes_the_merits_application_for_applicant_that_does_not_receive_passported_benefits.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_view_the_client_completed_means_answers.yml
  spec/models/concerns/cfe_submission_state_machine_spec.rb
  spec/services/cfe/create_assessment_service_spec.rb
  spec/services/cfe/create_outgoings_service_spec.rb
  spec/services/cfe/create_state_benefits_service_spec.rb
  spec/services/cfe/submission_manager_spec.rb
  spec/services/malware_scanner_spec.rb
  spec/services/pdf_converter_spec.rb
  spec/services/true_layer/importers/import_provider_service_spec.rb
Labels: Approved, UAT

#1417 Update README for authentication
  README.md
Labels: Approved

#1413 AP-1368 Update copy on transaction pages
  app/views/providers/outgoings_summary/index.html.erb
  config/locales/en/providers.yml
  config/locales/en/transaction_types.yml
  features/providers/civil_application_journey.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  spec/requests/citizens/identify_types_of_outgoings_spec.rb
  spec/requests/providers/identify_types_of_outgoings_spec.rb
  spec/requests/providers/transactions_spec.rb
Labels: Approved

#1406 AP1369 Declined open banking consent tracker
  app/models/dashboard/widget_data_providers/total_declined_open_banking.rb
  app/models/legal_aid_application.rb
  app/services/dashboard_event_handler.rb
  spec/factories/legal_aid_applications.rb
  spec/models/dashboard/widget_data_providers/total_declined_open_banking_spec.rb
Labels: Approved
