Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2020-07, with the labels that each got.

#1562 Ap 717 accessibility
  app/views/providers/address_selections/show.html.erb
  app/views/providers/addresses/_form.html.erb
Labels: Approved, UAT

#1557 AP-1225: Improve dependant handling
  app/controllers/providers/dependants/assets_values_controller.rb
  app/controllers/providers/dependants/details_controller.rb
  app/controllers/providers/dependants/full_time_educations_controller.rb
  app/controllers/providers/dependants/monthly_incomes_controller.rb
  app/controllers/providers/dependants/relationships_controller.rb
  app/controllers/providers/dependants_controller.rb
  app/controllers/providers/has_other_dependants_controller.rb
  app/controllers/providers/remove_dependant_controller.rb
  app/forms/dependant_form/assets_value_form.rb
  app/forms/dependant_form/details_form.rb
  app/forms/dependant_form/full_time_education_form.rb
  app/forms/dependant_form/monthly_income_form.rb
  app/forms/dependant_form/relationship_form.rb
  app/forms/legal_aid_applications/dependant_form.rb
  app/helpers/check_answers_helper.rb
  app/helpers/dependant_helper.rb
  app/policies/legal_aid_application_policy.rb
  app/services/flow/flows/provider_dependants.rb
  app/views/providers/dependants/_form.html.erb
  app/views/providers/dependants/assets_values/show.html.erb
  app/views/providers/dependants/details/show.html.erb
  app/views/providers/dependants/full_time_educations/show.html.erb
  app/views/providers/dependants/index.html.erb
  app/views/providers/dependants/monthly_incomes/show.html.erb
  app/views/providers/dependants/new.html.erb
  app/views/providers/dependants/relationships/show.html.erb
  app/views/providers/dependants/show.html.erb
  app/views/providers/has_dependants/show.html.erb
  app/views/providers/has_other_dependants/show.html.erb
  app/views/providers/remove_dependant/show.html.erb
  app/views/shared/check_answers/_dependants.html.erb
  app/views/shared/check_answers/_no_link_item.html.erb
  app/views/shared/forms/_has_dependants_form.html.erb
  app/views/shared/forms/dependants/_assets_value.html.erb
  app/views/shared/forms/dependants/_details.html.erb
  app/views/shared/forms/dependants/_full_time_educations.html.erb
  app/views/shared/forms/dependants/_monthly_incomes.html.erb
  app/views/shared/forms/dependants/_relationship.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/forms/dependant_form/details_form_spec.rb
  spec/forms/legal_aid_applications/dependant_form_spec.rb
  spec/helpers/check_answer_url_helper_spec.rb
  spec/helpers/dependant_helper_spec.rb
  spec/helpers/providers_helper_spec.rb
  spec/requests/providers/dependants/assets_values_spec.rb
  spec/requests/providers/dependants/details_spec.rb
  spec/requests/providers/dependants/full_time_educations_spec.rb
  spec/requests/providers/dependants/monthly_incomes_spec.rb
  spec/requests/providers/dependants/relationships_spec.rb
  spec/requests/providers/dependants_controller_spec.rb
  spec/requests/providers/dependants_spec.rb
  spec/requests/providers/has_dependants_controller_spec.rb
  spec/requests/providers/has_dependants_spec.rb
  spec/requests/providers/has_other_dependants_controller_spec.rb
  spec/requests/providers/remove_dependant_controller_spec.rb
Labels: Approved

#1561 Ap 1487 upd8 k8s
  helm_deploy/apply-for-legal-aid/charts/postgresql-6.2.0.tgz
  helm_deploy/apply-for-legal-aid/charts/postgresql-8.10.13.tgz
  helm_deploy/apply-for-legal-aid/requirements.lock
  helm_deploy/apply-for-legal-aid/requirements.yaml
  helm_deploy/apply-for-legal-aid/templates/deployment_metrics.yaml
  helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
  helm_deploy/apply-for-legal-aid/templates/deployment_worker.yaml
  helm_deploy/apply-for-legal-aid/templates/ingress.yaml
Labels: Approved

#1567 AP-1490 Disregarded benefits not being sent to CFE
  README.md
  app/services/cfe/create_state_benefits_service.rb
  spec/factories/bank_transactions.rb
  spec/services/cfe/create_state_benefits_service_spec.rb
Labels: Approved

#1546 Ap 1417 student finance
  app/controllers/citizens/student_finances/annual_amounts_controller.rb
  app/controllers/citizens/student_finances_controller.rb
  app/forms/legal_aid_applications/student_finance_form.rb
  app/forms/student_finances/annual_amount_form.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/citizen_capital.rb
  app/views/citizens/additional_accounts/index.html.erb
  app/views/citizens/check_answers/_student_finance.html.erb
  app/views/citizens/student_finances/annual_amounts/show.html.erb
  app/views/citizens/student_finances/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/citizens.yml
  config/locales/en/helpers.yml
  config/routes.rb
  db/migrate/20200619123658_add_student_finance_to_legal_aid_application.rb
  db/schema.rb
  features/citizens/citizens.feature
  spec/factories/legal_aid_applications.rb
  spec/requests/citizens/check_answers_spec.rb
  spec/requests/citizens/identify_types_of_incomes_spec.rb
  spec/requests/citizens/student_finance/annual_amounts_spec.rb
  spec/requests/citizens/student_finance_spec.rb
Labels: Approved, UAT

#1570 update kubectl version
  Dockerfile
Labels: ready for review

#1559 AP-1475: Student loan tidy
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/services/cfe/submission_manager.rb
  app/services/flow/flows/citizen_capital.rb
  app/views/admin/settings/show.html.erb
  app/views/citizens/check_answers/_student_finance.html.erb
  app/views/citizens/check_answers/index.html.erb
  app/views/citizens/student_finances/annual_amounts/show.html.erb
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  db/migrate/20200702122054_remove_student_loan_feature_flag.rb
  db/schema.rb
  features/cassettes/Civil_application_journeys/Completes_the_merits_application_for_applicant_that_does_not_receive_passported_benefits.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_view_the_client_completed_means_answers.yml
  features/citizens/citizens.feature
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
  spec/requests/citizens/check_answers_spec.rb
  spec/requests/citizens/identify_types_of_incomes_spec.rb
  spec/services/cfe/submission_manager_spec.rb
Labels: ready for review

#1530 ap -678 bugfix mailer arguments
  app/mailers/submit_citizen_financial_reminder_mailer.rb
  app/mailers/submit_provider_financial_reminder_mailer.rb
  app/services/submit_citizen_reminder_service.rb
  app/services/submit_provider_reminder_service.rb
  spec/factories/legal_aid_applications.rb
  spec/jobs/citizen_complete_means_job_spec.rb
  spec/mailers/submit_citizen_financial_reminder_mailer_spec.rb
  spec/services/submit_citizen_reminder_service_spec.rb
Labels: Approved, UAT

#1577 Add new rubocop cops
  .rubocop.yml
  bin/rspec
  features/support/vcr.rb
  spec/helpers/money_helper_spec.rb
Labels: ready for review

#1576 AP-1500 / AP-1501 Permissions for Providers and firms
  app/models/actor_permission.rb
  app/models/firm.rb
  app/models/permission.rb
  app/models/provider.rb
  config/locales/en/providers.yml
  db/migrate/20200708102815_create_permissions_table.rb
  db/migrate/20200709112844_create_actor_permissions.rb
  db/migrate/20200709135901_add_unique_index_to_actor_permissions.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/permissions.rb
  spec/factories/permissions.rb
  spec/models/firm_spec.rb
  spec/models/provider_spec.rb
Labels: Approved

#1579 AP-1118 add an alert for screenreaders
  app/views/providers/address_selections/show.html.erb
Labels: Approved, UAT

#1578 AP-1513 change passported client details
  app/models/concerns/legal_aid_application_state_machine.rb
  app/views/providers/check_benefits/_check_benefits_result.html.erb
  app/views/providers/check_benefits/_how_we_checked.html.erb
  app/views/providers/check_benefits/_use_ccms.html.erb
  config/locales/en/providers.yml
  features/cassettes/Civil_application_journeys/I_am_instructed_to_use_CCMS_on_the_passported_journey_with_an_applicant_does_not_receive_benefits.yml
  features/providers/civil_application_journey.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
Labels: Approved, ready for review

#1575 AP1451 Don't show disregarded benefits on the applicants check answers page
  app/helpers/user_transactions_helper.rb
  app/models/transaction_type.rb
  features/citizens/citizens.feature
  spec/factories/legal_aid_applications.rb
  spec/helpers/user_transactions_helper_spec.rb
  spec/models/transaction_type_spec.rb
Labels: Approved, UAT

#1580 AP-1437: provider student loan handling
  .rubocop.yml
  app/views/providers/income_summary/index.html.erb
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_applications.rb
Labels: Approved

#1581 AP-1517 Send correct income contribution to CCMS
  app/services/ccms/attribute_value_generator.rb
  config/ccms/attribute_block_configs/base.yml
  config/ccms/attribute_block_configs/non_passported.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
Labels: Approved

#1593 Update MockContactIdProvider
  app/services/mock_contact_id_provider.rb
  config/encrypted_private_beta_users.yml
  helm_deploy/apply-for-legal-aid/whitelisted_users.yaml
  lib/tasks/tranche_maker.rake
  spec/services/mock_contact_id_provider_spec.rb
Labels: ready for review

#1588 AP-1518 Gracefully handle True Layer auth errors
  app/controllers/auth_controller.rb
  app/controllers/citizens/consents_controller.rb
  config/initializers/omniauth.rb
  config/locales/en/citizens.yml
  spec/requests/auth_spec.rb
Labels: ready for review

#1594 ap-1526 add monzo and tesco to the bank list
  config/banks.yml
Labels: Approved, UAT

#1592 Ap 1502 admin permissions
  app/controllers/admin/roles/permissions_controller.rb
  app/controllers/admin/roles_controller.rb
  app/models/firm.rb
  app/views/admin/roles/_form.html.erb
  app/views/admin/roles/index.html.erb
  app/views/admin/roles/permissions/show.html.erb
  app/views/layouts/admin.html.erb
  config/locales/en/admin.yml
  config/locales/en/layouts.yml
  config/routes.rb
  spec/factories/firms.rb
  spec/models/firm_spec.rb
  spec/requests/admin/roles/permissions_spec.rb
  spec/requests/admin/roles_spec.rb
Labels: Approved, UAT

#1602 FIX: Update provider_used_delegated_functions event
  app/models/concerns/legal_aid_application_state_machine.rb
Labels: Approved

#1605 AP-1314 Add new fields to the Provider(User) table
  db/migrate/20200724083605_add_new_provider_table_fields.rb
  db/schema.rb
Labels: Approved

#1609 Update ProviderDetailsRetriever to replace space with %20 in url
  app/services/mock_provider_details_retriever.rb
  app/services/provider_details_retriever.rb
  spec/cassettes/encoded_provider_details_api.yml
  spec/cassettes/provider_details_api.yml
  spec/services/mock_provider_details_retriever_spec.rb
  spec/services/provider_details_retriever_spec.rb
Labels: ready for review

#1606 AP-1412: Update client completed means content
  app/views/providers/client_completed_means/show.html.erb
  config/locales/en/providers.yml
  features/providers/categorizing_bank_transactions.feature
  features/providers/civil_application_journey.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  spec/requests/providers/client_completed_means_spec.rb
Labels: Approved, UAT

#1600 AP-1534: Add Error message outputs
  app/views/shared/forms/_identify_types_of_outgoings_form.html.erb
  app/views/shared/forms/_types_of_income_form.html.erb
Labels: Approved, UAT

#1601 AP-1531: Add focus state to button-as-link
  app/assets/stylesheets/providers/legal_aid_applications.scss
Labels: Approved, UAT

#1607 AP-1394: Add source column to feedback admin page
  app/views/admin/feedback/_feedbacks.erb
  config/locales/en/admin.yml
Labels: Approved, ready for review
