Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2020-09, with the labels that each got.

#1709 AP-1634 Re-instate trueLayer sandbox credentials for staging
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: Approved

#1702 AP-1589: Geckoboard provider update
  app/jobs/dashboard/provider_data_job.rb
  app/models/dashboard/single_object/provider_data.rb
  app/models/legal_aid_application.rb
  app/models/provider.rb
  app/services/dashboard_event_handler.rb
  spec/jobs/dashboard/provider_data_job_spec.rb
  spec/models/dashboard/single_object/provider_data_spec.rb
  spec/services/dashboard_event_handler_spec.rb
Labels: Approved

#1656 AP1563 Accessibility: Abbreviation tags for screen readers
  app/controllers/citizens/consents_controller.rb
  app/forms/applicants/open_banking_consent_form.rb
  app/views/admin/submitted_applications_reports/_submitted_applications.html.erb
  app/views/citizens/consents/show.html.erb
  app/views/layouts/_footer.html.erb
  app/views/privacy_policy/index.html.erb
  app/views/providers/check_benefits/_check_benefits_result.html.erb
  app/views/providers/check_benefits/_use_ccms.html.erb
  app/views/providers/end_of_applications/show.html.erb
  app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/providers/open_banking_consents/show.html.erb
  app/views/providers/start/index.html.erb
  app/views/providers/submitted_applications/show.html.erb
  app/views/providers/use_ccms/show.html.erb
  app/views/shared/_application_ref.html.erb
  app/views/shared/forms/_open_banking_consents.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/admin.yml
  config/locales/en/citizens.yml
  config/locales/en/layouts.yml
  config/locales/en/privacy_policy.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  spec/requests/citizens/consent_spec.rb
  spec/requests/providers/check_benefits_spec.rb
  spec/requests/providers/use_ccms_spec.rb
Labels: Approved, UAT

#1711 AP-1643 Clear TrueLayer errors
  app/controllers/citizens/accounts_controller.rb
Labels: UAT

#1712 AP-1641 Improve display of TrueLayer errors
  app/controllers/citizens/accounts_controller.rb
  app/controllers/citizens/consents_controller.rb
  app/services/true_layer/api_client.rb
  app/views/citizens/accounts/gather.html.erb
  config/locales/en/citizens.yml
  spec/requests/citizens/accounts_spec.rb
Labels: UAT

#1704 AP-1606 Display residual balance flag on means report
  app/models/cfe/remarks.rb
  app/views/providers/means_reports/_caseworker_review.html.erb
  config/locales/en/providers.yml
  spec/models/cfe/remarks_spec.rb
Labels: Approved, UAT

#1721 close a h2 tag
  app/views/citizens/legal_aid_applications/index.html.erb
Labels: Approved

#1718 Amend the <abbr> styling
  app/assets/stylesheets/layout.scss
Labels: Approved

#1720 repair broken translation@
  config/locales/en/providers.yml
Labels: Approved

#1717 Rubocop Update: update cops and fixes
  .rubocop.yml
  app/helpers/check_answers_helper.rb
Labels: Approved

#1722 AP-1647 Re-fix DWP text
  app/views/providers/check_benefits/_check_benefits_result.html.erb
  config/locales/en/providers.yml
Labels: Approved

#1723 AP-1585 Migrate to new Sentry platform
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: ready for review

#1719 AP1512 Subclass oauth2
  app/lib/omniauth/strategies/laa_oauth2.rb
  app/lib/omniauth/strategies/true_layer.rb
  spec/lib/omniauth/strategies/laa_o_auth2_spec.rb
  spec/spec_helper.rb
Labels: Approved

#1726 Fix yarn security issue
  yarn.lock
Labels: ready for review

#1738 Fix security vulnerability in bl library
  yarn.lock
Labels: Approved

#1716 ap-1609 accessibility fixes for images
  app/views/citizens/accounts/gather.html.erb
  app/views/citizens/banks/_bank.html.erb
  app/views/providers/income_summary/_add_other_income.html.erb
  app/views/providers/outgoings_summary/_add_other_outgoings.erb
Labels: Approved, UAT

#1737 AP-1558 Fix back button behaviour in merits screens
  app/controllers/providers/check_merits_answers_controller.rb
  app/views/providers/date_client_told_incidents/show.html.erb
  app/views/providers/respondents/show.html.erb
  app/views/providers/start_merits_assessments/show.html.erb
  app/views/providers/statement_of_cases/show.html.erb
  app/views/providers/success_likely/index.html.erb
  app/views/providers/success_prospects/show.html.erb
  features/providers/civil_application_journey.feature
  spec/requests/providers/check_merits_answers_spec.rb
Labels: ready for review

#1708 Ap 1598 offline accounts non-passported
  app/controllers/providers/applicant_bank_accounts_controller.rb
  app/controllers/providers/offline_savings_accounts_controller.rb
  app/forms/savings_amounts/offline_savings_accounts_form.rb
  app/helpers/capital_helper.rb
  app/models/legal_aid_application.rb
  app/services/cfe/create_capitals_service.rb
  app/services/flow/flows/provider_capital.rb
  app/services/flow/flows/provider_vehicle.rb
  app/views/providers/applicant_bank_accounts/show.html.erb
  app/views/providers/offline_savings_accounts/show.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/forms/_offline_savings_accounts_form.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  features/providers/civil_application_journey.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/bank_accounts.rb
  spec/requests/providers/applicant_bank_accounts_spec.rb
  spec/requests/providers/capital_assessment_results_spec.rb
  spec/requests/providers/capital_income_assessment_results_spec.rb
  spec/requests/providers/offline_savings_accounts_spec.rb
  spec/requests/providers/vehicles/regular_uses_spec.rb
  spec/requests/providers/vehicles_spec.rb
  spec/services/cfe/create_capitals_service_spec.rb
Labels: Approved, UAT

#1724 Ap 1615 a11y start button
  app/javascript/src/start_button.js
  app/views/citizens/legal_aid_applications/index.html.erb
  app/views/providers/legal_aid_applications/index.html.erb
  app/views/providers/start/index.html.erb
Labels: Approved, UAT

#1728 Ap 1613 accessibility definition lists
  app/views/citizens/check_answers/index.html.erb
  app/views/shared/check_answers/_merits.html.erb
Labels: Approved, UAT

#1734 AP-1612 Make screen readers ignore null table cells
  app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/providers/transactions/show.html.erb
Labels: Approved, UAT

#1725 AP-1638 Display running balance on caseworker bank transactions csv
  app/presenters/bank_transaction_presenter.rb
  app/services/true_layer/importers/import_transactions_service.rb
  db/migrate/20200903165732_add_running_balance_to_bank_transactions.rb
  db/schema.rb
  spec/factories/bank_transactions.rb
  spec/presenters/bank_transaction_presenter_spec.rb
  spec/services/true_layer/importers/import_transactions_service_spec.rb
  spec/support/true_layer_mock_data.rb
Labels: Approved, UAT

#1740 Backup db script fix
  Dockerfile
  bin/cleanup_manual_snapshots
  bin/create_manual_snapshot
  helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
Labels: WIP

#1747 Database Backup: revert staging test changes
  Dockerfile
  bin/cleanup_manual_snapshots
  bin/create_manual_snapshot
  helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
Labels: Approved

#1744 AP-1657 account details on transaction csv
  app/models/bank_account.rb
  app/presenters/bank_transaction_presenter.rb
  app/views/citizens/accounts/index.html.erb
  app/views/providers/applicant_bank_accounts/show.html.erb
  spec/presenters/bank_transaction_presenter_spec.rb
Labels: Approved, UAT

#1748 AP-1644 Prevent duplicate bank providers
  app/services/true_layer/importers/import_provider_service.rb
  spec/services/true_layer/importers/import_provider_service_spec.rb
Labels: Approved, UAT

#1752 update comment with new file path
  helm_deploy/prometheus/prometheus-alerts-uat.yaml
Labels: ready for review

#1754 staging test
  Dockerfile
  bin/cleanup_manual_snapshots
  bin/create_manual_snapshot
  helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
Labels: ready for review

#1756 revert to prod credentials for backup scripts:
  bin/cleanup_manual_snapshots
  bin/create_manual_snapshot
Labels: Approved

#1763 AP-1667 Reset sessions on login
  app/controllers/citizens/legal_aid_applications_controller.rb
  app/controllers/providers/confirm_offices_controller.rb
  spec/requests/applicants/omniauth_callbacks_spec.rb
  spec/requests/citizens/accounts_spec.rb
  spec/services/cfe/create_capitals_service_spec.rb
Labels: Approved, UAT

#1755 Ap 1658 feedback question
  app/controllers/feedback_controller.rb
  app/views/feedback/new.html.erb
  config/locales/en/feedback.yml
  features/providers/civil_application_journey.feature
  spec/requests/feedbacks_spec.rb
Labels: question

#1753 AP-1642 update credentials
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: Approved, UAT

#1741 AP1639 income/outgoing on caseworker csv report
  app/controllers/providers/transactions_controller.rb
  app/presenters/bank_transaction_presenter.rb
  spec/factories/transaction_types.rb
  spec/presenters/bank_transaction_presenter_spec.rb
  spec/requests/providers/transactions_spec.rb
Labels: Approved, UAT

#1771 Revert "AP-1642 update credentials"
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: ready for review

#1772 AP1639 Add selected_by 'System' metadata for bank transactions
  app/services/state_benefit_analyser_service.rb
  spec/factories/bank_transactions.rb
  spec/services/state_benefit_analyser_service_spec.rb
Labels: UAT, ready for review

#1775 revert cronjob schedule in UAT and staging
  helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
Labels: ready for review

#1773 Ap 1642 password rotation
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: Approved

#1774 AP-938 Remove provider roles from profile screen
  app/views/providers/providers/show.html.erb
  spec/requests/providers/providers_spec.rb
Labels: Approved, UAT

#1764 AP-1656 Copy change
  app/services/cfe/create_capitals_service.rb
  config/locales/en/shared.yml
  spec/services/cfe/create_capitals_service_spec.rb
Labels: Approved, UAT

#1789 move the to_s to fix tests
  app/models/legal_aid_application.rb
  spec/services/cfe/create_capitals_service_spec.rb
Labels: ready for review

#1790 Remove omniauth debugging - ticket AP1512
  app/lib/omniauth/strategies/laa_oauth2.rb
  app/lib/omniauth/strategies/true_layer.rb
  spec/lib/omniauth/strategies/laa_o_auth2_spec.rb
  spec/spec_helper.rb
Labels: Approved

#1794 AP-1620 Make table header contrast accessible
  app/assets/stylesheets/table-sort.scss
Labels: Approved, UAT

#1787 AP-1680 Update readme and add user for portal login
  README.md
  db/seeds/test_provider_populator.rb
Labels: Approved

#1781 AP-1655: add data to admin report
  app/forms/legal_aid_applications/used_delegated_functions_form.rb
  app/models/legal_aid_application.rb
  app/services/reports/mis/application_detail_csv_line.rb
  db/migrate/20200917082925_add_used_delegated_functions_reported_on_to_legal_aid_application.rb
  db/schema.rb
  spec/factories/legal_aid_applications.rb
  spec/forms/legal_aid_applications/used_delegated_functions_form_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: Approved

#1791 AP-1666 Remove duplicate Geckoboard datasets
  app/models/dashboard/widget_data_providers/daily_new_providers.rb
  app/models/dashboard/widget_data_providers/feedback_scores.rb
  app/models/provider.rb
  app/services/dashboard_event_handler.rb
  helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
  spec/models/dashboard/widget_data_providers/daily_new_providers_spec.rb
  spec/models/dashboard/widget_data_providers/feedback_scores_spec.rb
  spec/services/dashboard_event_handler_spec.rb
Labels: Approved, UAT

#1765 AP1637 Prometheus HTTP status alerts
  helm_deploy/prometheus/prometheus-alerts-production.yaml
  helm_deploy/prometheus/prometheus-alerts-staging.yaml
  helm_deploy/prometheus/prometheus-alerts-uat.yaml
Labels: ready for review

#1782 AP-1665 Set default responsibility for firms
  app/models/firm.rb
  spec/models/firm_spec.rb
Labels: Approved, UAT

#1783 AP-1668 List firm permissions
  app/views/admin/firms/index.html.erb
  config/locales/en/admin.yml
  spec/factories/firms.rb
  spec/models/firm_spec.rb
  spec/requests/admin/firms_spec.rb
  spec/requests/providers/check_benefits_spec.rb
Labels: Approved, UAT

#1797 AP-1648 Add CCMS applicant if no applicant ref returned
  app/services/ccms/submitters/obtain_applicant_reference_service.rb
  spec/data/ccms/applicant_search_response_results_no_details.xml
  spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
Labels: Approved, UAT

#1793 AP1618 Update content of use_ccms page
  config/locales/en/providers.yml
Labels: Approved

#1800 AP-1624 Fix inaccurate heading structure
  app/views/providers/income_summary/_add_other_income.html.erb
  app/views/providers/outgoings_summary/_add_other_outgoings.erb
Labels: Approved, UAT

#1788 AP-1610: Update confirm_office view
  app/lib/govuk_elements_form_builder/form_builder.rb
  app/views/providers/confirm_offices/show.html.erb
  config/locales/en/providers.yml
  spec/lib/govuk_elements_form_builder/form_builder_spec.rb
Labels: Approved

#1792 Ap 1569 no income outgoing
  app/controllers/providers/no_income_summaries_controller.rb
  app/controllers/providers/no_outgoings_summaries_controller.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_capital.rb
  app/services/flow/flows/provider_dependants.rb
  app/views/providers/income_summary/_income_type_item.html.erb
  app/views/providers/no_income_summaries/show.html.erb
  app/views/providers/no_outgoings_summaries/show.html.erb
  app/views/providers/outgoings_summary/_outgoing_type_item.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/categorizing_bank_transactions.feature
  features/providers/civil_application_journey.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
  features/support/steps_helper.rb
  spec/requests/providers/client_completed_means_spec.rb
  spec/requests/providers/has_dependants_controller_spec.rb
  spec/requests/providers/has_other_dependants_controller_spec.rb
  spec/requests/providers/no_income_summaries_spec.rb
  spec/requests/providers/no_outgoings_summaries_spec.rb
Labels: Approved, UAT

#1803 AP-1623 add the proceeding meaning to aria label
  app/views/shared/forms/proceedings_types/_proceeding_type_form.html.erb
Labels: Approved

#1806 AP-1625 More descriptive links for screenreaders
  app/helpers/accessible_link_helper.rb
  app/views/providers/about_the_financial_assessments/show.html.erb
  app/views/providers/address_selections/show.html.erb
  app/views/providers/bank_transactions/_list_selected.html.erb
  app/views/providers/has_other_dependants/show.html.erb
  app/views/providers/income_summary/_income_type_item.html.erb
  app/views/providers/outgoings_summary/_outgoing_type_item.html.erb
  app/views/shared/check_answers/_item.html.erb
  app/views/shared/check_answers/_one_change_link_long_answers_section.erb
  app/views/shared/check_answers/_one_link_section.html.erb
  app/views/shared/check_answers/_only_link_section.html.erb
  app/views/shared/forms/proceedings_types/_proceeding_type.html.erb
  config/locales/en/providers.yml
  spec/helpers/accessible_link_helper.rb
Labels: Approved, UAT

#1808 Reduce calls to Geckoboard
  app/models/legal_aid_application.rb
Labels: ready for review

#1811 AP-1626: Update result details header
  app/views/providers/capital_income_assessment_results/_result_details.html.erb
Labels: Approved, UAT

#1813 TECH-DEBT: remove webhint from Circle CI
  .circleci/config.yml
Labels: ready for review

#1814 Fix flaky postcode test
  features/cassettes/Civil_application_journeys/Completes_the_application_using_manual_address.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_address_manually_from_the_check_your_answers_page.yml
  features/providers/civil_application_journey.feature
  spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/a_postcode_has_been_entered_before/but_the_lookup_does_not_return_any_valid_results/renders_the_manual_address_selection_page.yml
  spec/requests/providers/address_selections_spec.rb
Labels: Approved

#1819 Tech-Debt: remove yarn warnings
  package.json
  yarn.lock
Labels: Approved

#1815 Add extra state transition to fix production errors
  app/models/concerns/base_state_machine.rb
Labels: Approved

#1292 Update ruby to 2.7.1
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: Approved

#1798 AP-1545 Record providers email and page on feedback
  app/controllers/concerns/backable.rb
  app/controllers/feedback_controller.rb
  app/controllers/saml_sessions_controller.rb
  app/controllers/test/sessions_controller.rb
  app/mailers/concerns/notify_template_methods.rb
  app/mailers/feedback_mailer.rb
  app/views/feedback/new.html.erb
  config/application.rb
  config/govuk_notify_templates.yml
  config/locales/en/feedback.yml
  config/locales/en/helpers.yml
  config/routes.rb
  db/migrate/20200921143900_add_email_to_feedback.rb
  db/seeds/test_provider_populator.rb
  features/providers/civil_application_journey.feature
  spec/rails_helper.rb
  spec/requests/feedbacks_spec.rb
  spec/requests/saml_sessions_spec.rb
  spec/services/govuk_emails/email_monitor_spec.rb
Labels: Approved, UAT
