Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2020-01, with the labels that each got.

#1147 Reduce line length to 180
  .rubocop_todo.yml
  Guardfile
  app/services/ccms/add_case_service.rb
  app/services/cfe/obtain_assessment_result_service.rb
  bin/bundle
  config/initializers/whitelisted_users.rb
  spec/requests/providers/check_provider_answers_spec.rb
Labels: Approved

#1134 AP590 Notify Provider When Citizen Completes Means
  app/controllers/citizens/declarations_controller.rb
  app/mailers/citizen_completed_means_mailer.rb
  app/services/provider_email_service.rb
  app/services/smoke_test/test_emails.rb
  config/govuk_notify_templates.yml
  spec/cassettes/ProviderEmailService/_send_email/sending_the_email/sends_an_email_with_the_right_parameters.yml
  spec/cassettes/smoke_test_emails.yml
  spec/mailers/citizen_completed_means_mailer_spec.rb
  spec/mailers/notify_mailer_spec.rb
  spec/services/provider_email_service_spec.rb
  spec/services/smoke_test/test_emails_spec.rb
Labels: Approved

#1098 AP-1126 Add new cronjob for database backups
  Dockerfile
  README.md
  bin/cleanup_manual_snapshots
  bin/create_manual_snapshot
  helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml
Labels: ready for review

#1150 Update year in licence file
  LICENCE.md
Labels: ready for review

#1156 Amend DB backup cronjob schedule
  helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml
Labels: ready for review

#1162 AP1164 Redirect provider when citizen completes means
  app/services/provider_email_service.rb
  spec/services/provider_email_service_spec.rb
Labels: Approved

#1166 AP1140 Production Logout
  helm_deploy/apply-for-legal-aid/values-production.yaml
Labels: Approved

#1161 AP1143 Add provider username to submitted applications report
  app/views/admin/submitted_applications_reports/_submitted_applications.html.erb
  config/locales/en/admin.yml
Labels: Approved

#1164 AP-1162: Implement new status controller setup
  .circleci/config.yml
  Dockerfile
  app/controllers/status_controller.rb
  config/routes.rb
  spec/requests/status_spec.rb
  spec/routing/routes_spec.rb
Labels: UAT, ready for review

#1160 AP1086&AP1138 Open banking consent page
  app/controllers/concerns/flowable.rb
  app/controllers/providers/online_bankings_controller.rb
  app/controllers/providers/open_banking_consents_controller.rb
  app/controllers/providers/use_ccms_controller.rb
  app/forms/applicants/uses_online_banking_form.rb
  app/forms/legal_aid_applications/open_banking_consent_form.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_start.rb
  app/views/citizens/consents/show.html.erb
  app/views/providers/online_bankings/show.html.erb
  app/views/providers/open_banking_consents/show.html.erb
  app/views/providers/use_ccms/show.html.erb
  app/views/shared/forms/_check_boxes.html.erb
  app/views/shared/forms/_open_banking_consents.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/migrate/20200106094725_add_provider_citizen_consented_to_legal_aid_applications.rb
  db/migrate/20200106113041_remove_uses_online_banking_from_applicants.rb
  db/schema.rb
  features/providers/civil_application_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/applicants.rb
  spec/factories/legal_aid_applications.rb
  spec/lib/govuk_elements_form_builder/form_builder_spec.rb
  spec/requests/providers/check_benefits_spec.rb
  spec/requests/providers/online_bankings_spec.rb
  spec/requests/providers/open_banking_consents_spec.rb
  spec/requests/providers/substantive_applications_spec.rb
  spec/requests/providers/use_ccms_spec.rb
Labels: UAT

#1165 AP1082 Update email addresses page
  app/views/providers/email_addresses/show.html.erb
  config/locales/en/helpers.yml
  spec/requests/providers/email_addresses_spec.rb
Labels: UAT

#1178 AP1181 - Bug fix Proceeding Types in IE11
  app/javascript/packs/application.js
Labels: UAT

#1179 Auto screenshot cucumber failures
  .circleci/config.yml
  features/support/env.rb
  features/support/screenshot_helper.rb
Labels: ready for review

#1180 fix issue of running db backups in non-prod env
  helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
  helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml
Labels: Approved

#1177 Ap 1160 reset counter
  helm_deploy/apply-for-legal-aid/templates/cronjob-reset-started-apps-counter.yaml
Labels: question

#1159 Ap 1170 scheduled mailings
  .rubocop_todo.yml
  app/jobs/post_submission_processing_job.rb
  app/jobs/scheduled_mailings_delivery_job.rb
  app/mailers/submission_confirmation_mailer.rb
  app/mailers/submit_application_reminder_mailer.rb
  app/models/concerns/legal_aid_application_state_machine.rb
  app/models/legal_aid_application.rb
  app/models/scheduled_mailing.rb
  app/services/smoke_test/test_emails.rb
  app/services/submit_application_reminder_service.rb
  config/initializers/mock_saml.rb
  db/migrate/20200108162334_create_scheduled_mailings.rb
  db/schema.rb
  helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml
  lib/tasks/jobs/scheduled_mailings.rake
  spec/cassettes/SubmitApplicationReminderService/_send_email/creates_two_scheduled_mailing_records.yml
  spec/factories/scheduled_mailings.rb
  spec/jobs/post_submission_processing_job_spec.rb
  spec/jobs/scheduled_mailings_delivery_job_spec.rb
  spec/mailers/submission_confirmation_mailer_spec.rb
  spec/mailers/submit_application_reminder_mailer_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/scheduled_mailing_spec.rb
  spec/services/submit_application_reminder_service_spec.rb
Labels: ready for review

#1188 Add new whitelisted users
  config/encrypted_private_beta_users.yml
  helm_deploy/apply-for-legal-aid/whitelisted_users.yaml
Labels: ready for review

#1101 New user update
  .env.sample
  README.md
  bin/install_clamav_on_mac
  bin/setup
  docs/git-crypt.md
Labels: Approved

#1187 AP-1171 increase replica count
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: Approved

#1193 AP1141 Feedback on Signout
  .rubocop_todo.yml
  app/assets/stylesheets/success_message.scss
  app/controllers/feedback_controller.rb
  app/controllers/saml_sessions_controller.rb
  app/helpers/page_template_helper.rb
  app/views/feedback/new.html.erb
  app/views/feedback/show.html.erb
  app/views/shared/forms/_success_message.html.erb
  app/views/shared/page_templates/_default_page_template.html.erb
  config/locales/en/feedback.yml
  spec/requests/feedbacks_spec.rb
  spec/requests/saml_sessions_spec.rb
Labels: UAT

#1189 ap-1146-Update content "respondent" to "opponent"
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/civil_application_journey.feature
Labels: ready for review

#1202 Bump prometheus_exporter from 0.4.16 to 0.4.17
  Gemfile.lock
  helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml
Labels: ready for review

#1181 AP1185 - Invalid Statement of case files are being allowed to be uploaded
  app/forms/statement_of_cases/statement_of_case_form.rb
  app/services/ccms/obtain_document_id_service.rb
  app/services/pdf_converter.rb
  config/locales/en/activemodel.yml
  spec/fixtures/files/documents/hello_world1.pdf
  spec/fixtures/files/empty_file
  spec/fixtures/files/empty_file.pdf
  spec/requests/providers/statement_of_case_spec.rb
Labels: ready for review

#1204 Bug fix for PdfConverter
  app/services/pdf_converter.rb
Labels: ready for review

#1205 AP-1177 Update README to explain Provider details retrieval process
  README.md
Labels: ready for review
