Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2021-03, with the labels that each got.

#2310 Ap 2039 assigned scope
  README.md
  app/controllers/providers/has_other_proceedings_controller.rb
  app/controllers/providers/proceedings_types_controller.rb
  app/controllers/providers/used_delegated_functions_controller.rb
  app/models/application_proceeding_type.rb
  app/models/application_proceeding_types_scope_limitation.rb
  app/models/legal_aid_application.rb
  app/models/proceeding_type.rb
  app/services/add_assigned_scope_limitation_service.rb
  app/services/proceeding_types_service.rb
  db/migrate/20210218165806_create_join_table_application_proceeding_type_scope_limitation.rb
  db/schema.rb
  docs/ApplicationProceedingTypesORM.png
  spec/factories/application_proceeding_types.rb
  spec/models/application_proceeding_type_spec.rb
  spec/models/proceeding_type_spec.rb
  spec/rails_helper.rb
  spec/requests/providers/proceedings_types_spec.rb
  spec/services/proceeding_types_service_spec.rb
Labels: Approved, UAT

#2309 Update formbuilder in proceedings types forms
  app/controllers/providers/has_other_proceedings_controller.rb
  app/forms/providers/has_other_proceedings_form.rb
  app/views/providers/has_other_proceedings/show.html.erb
  app/views/providers/proceedings_types/index.html.erb
  app/views/shared/forms/proceedings_types/_proceeding_type_form.html.erb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
Labels: Approved, UAT

#2325 AP-2006: Turn off prepared cache statements to avoid cached DB querie…
  config/database.yml
Labels: Approved

#2327 AP-2090 bug fix application reminder
  app/controllers/providers/used_delegated_functions_controller.rb
  app/services/submit_application_reminder_service.rb
  spec/cassettes/SubmitApplicationReminderService/_send_email/SubmitApplicationReminderMailer_already_exists/adds_two_new_mailer_jobs.yml
  spec/cassettes/SubmitApplicationReminderService/_send_email/SubmitApplicationReminderMailer_already_exists/cancels_pre-existing_jobs.yml
  spec/requests/providers/used_delegated_functions_spec.rb
  spec/services/submit_application_reminder_service_spec.rb
Labels: Approved

#2320 AP-2057 Replace sentry-raven with sentry-ruby gem
  Gemfile
  Gemfile.lock
  app/controllers/admin_users/omniauth_callbacks_controller.rb
  app/controllers/applicants/omniauth_callbacks_controller.rb
  app/controllers/auth_controller.rb
  app/controllers/citizens/gather_transactions_controller.rb
  app/controllers/concerns/providers/authorizable.rb
  app/controllers/providers/transactions_controller.rb
  app/helpers/providers_helper.rb
  app/models/provider.rb
  app/models/scheduled_mailing.rb
  app/services/address_lookup_service.rb
  app/services/benefit_check_service.rb
  app/services/ccms/payload_generators/entity_attributes_generator.rb
  app/services/ccms/submitters/base_submission_service.rb
  app/services/cfe/submission_manager.rb
  app/services/govuk_emails/email_monitor.rb
  app/services/malware_scanner.rb
  app/services/true_layer/api_client.rb
  app/services/true_layer_error_decoder.rb
  config/initializers/omniauth.rb
  config/initializers/raven.rb
  config/initializers/sentry.rb
  config/initializers/sidekiq.rb
  spec/models/provider_spec.rb
  spec/models/scheduled_mailing_spec.rb
  spec/services/address_lookup_service_spec.rb
  spec/services/benefit_check_service_spec.rb
  spec/services/ccms/payload_generators/entity_attributes_generator_spec.rb
  spec/services/cfe/submission_manager_spec.rb
  spec/services/govuk_emails/email_monitor_spec.rb
  spec/services/malware_scanner_spec.rb
  spec/services/true_layer_error_decoder_spec.rb
Labels: Approved

#2298 AP-2004 Remove back link from Application Created page
  app/views/providers/application_confirmations/show.html.erb
Labels: Approved, UAT

#2302 AP-2011 email refactor
  README.md
  app/controllers/citizens/resend_link_requests_controller.rb
  app/controllers/feedback_controller.rb
  app/jobs/email_monitor_job.rb
  app/jobs/govuk_notify_mailer_job.rb
  app/jobs/post_submission_processing_job.rb
  app/jobs/scheduled_mailings_delivery_job.rb
  app/mailers/citizen_completed_means_mailer.rb
  app/mailers/citizen_confirmation_mailer.rb
  app/mailers/feedback_mailer.rb
  app/mailers/notify_mailer.rb
  app/mailers/resend_link_request_mailer.rb
  app/mailers/submission_confirmation_mailer.rb
  app/mailers/submit_application_reminder_mailer.rb
  app/mailers/submit_citizen_financial_reminder_mailer.rb
  app/mailers/submit_provider_financial_reminder_mailer.rb
  app/mailers/undeliverable_email_alert_mailer.rb
  app/models/scheduled_mailing.rb
  app/models/sent_email.rb
  app/services/citizen_completion_email_service.rb
  app/services/citizen_email_service.rb
  app/services/govuk_emails/delivery_man.rb
  app/services/govuk_emails/email.rb
  app/services/govuk_emails/email_monitor.rb
  app/services/govuk_emails/monitor.rb
  app/services/job_queue.rb
  app/services/provider_email_service.rb
  app/services/submit_application_reminder_service.rb
  app/services/submit_citizen_reminder_service.rb
  app/services/submit_provider_reminder_service.rb
  db/migrate/20210222105725_add_new_status_to_scheduled_mailings.rb
  db/migrate/20210223134124_drop_sent_emails.rb
  db/schema.rb
  helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml
  spec/factories/scheduled_mailings.rb
  spec/factories/sent_emails.rb
  spec/jobs/email_monitor_job_spec.rb
  spec/jobs/govuk_notify_mailer_job_spec.rb
  spec/jobs/post_submission_processing_job_spec.rb
  spec/jobs/scheduled_mailings_delivery_job_spec.rb
  spec/mailers/citizen_completed_means_mailer_spec.rb
  spec/mailers/citizen_confirmation_mailer_spec.rb
  spec/mailers/feedback_mailer_spec.rb
  spec/mailers/notify_mailer_spec.rb
  spec/mailers/resend_link_request_mailer_spec.rb
  spec/mailers/submit_application_reminder_mailer_spec.rb
  spec/mailers/undeliverable_email_alert_mailer_spec.rb
  spec/mock_objects/mock_queued_job.rb
  spec/models/scheduled_mailing_spec.rb
  spec/requests/citizens/resend_link_requests_spec.rb
  spec/requests/feedbacks_spec.rb
  spec/services/citizen_email_service_spec.rb
  spec/services/govuk_emails/delivery_man_spec.rb
  spec/services/govuk_emails/email_monitor_spec.rb
  spec/services/govuk_emails/monitor_spec.rb
  spec/services/job_queue_spec.rb
  spec/services/provider_email_service_spec.rb
  spec/support/time_matcher.rb
Labels: Approved

#2334 BugFix - Revert the data scrubbing for sentry config
  config/initializers/sentry.rb
Labels: ready for review

#2333 AP-2067/2071 Content changes on cash_income and cash_outgoings screen
  app/views/shared/partials/_revealing_checkbox.html.erb
  config/locales/cy/shared.yml
  config/locales/en/shared.yml
Labels: Approved

#2335 AP 2077 Update content on means check your answers page
  config/locales/en/shared.yml
  config/locales/en/transaction_types.yml
  features/accessibility/citizen.feature
  features/citizens/citizens.feature
  spec/models/aggregated_cash_income_spec.rb
  spec/models/aggregated_cash_outgoings_spec.rb
  spec/requests/citizens/cash_incomes_spec.rb
  spec/requests/citizens/cash_outgoings_spec.rb
Labels: ready for review

#2332 BugFix Remove active support and sidekiq logger from sentry
  config/initializers/sentry.rb
Labels: Approved

#2321 AP-1998 integrate backend proceedings type search with frontend
  app/controllers/v1/proceeding_types_controller.rb
  app/services/proceeding_type_full_text_search.rb
  app/webpack/src/helpers.js
  app/webpack/src/modules/proceedings.js
  app/webpack/src/proceeding_types.js
  spec/javascript/modules/proceedings.spec.js
  spec/javascript/proceeding_types.spec.js
  spec/requests/proceeding_types/index_proceeding_types_spec.rb
  spec/services/proceeding_type_full_text_search_spec.rb
Labels: Approved, UAT

#2338 AP-2062: Update monthly cash payment labels to use full month names a…
  app/models/base_aggregated_cash_transaction.rb
  app/views/shared/_cash_transactions.html.erb
  app/views/shared/check_answers/_no_link_cash_transaction_item.html.erb
  config/locales/en/dates.yml
  config/locales/en/shared.yml
  spec/models/aggregated_cash_income_spec.rb
Labels: Approved, UAT

#2326 Ap 2063 duplicate entity id
  config/ccms/means_entity_configs/non_passported.yml
Labels: Approved

#2324 AP-2064: Move ccms attrs to the land entity in the ccms payload to av…
  ccms_integration/example_payloads/NonPassportedFullMonty.xml
  ccms_integration/helpers/ccms_payload_analyser.rb
  config/ccms/attribute_block_configs/non_passported.yml
Labels: Approved

#2352 Fix delegated functions date format in cucumber
  features/support/steps_helper.rb
Labels: Approved

#2336 AP-2073 Fix spacing issue on income and outgoings summary pages
  app/views/providers/income_summary/index.html.erb
  app/views/providers/outgoings_summary/index.html.erb
Labels: UAT

#2337 AP-2076 Update content on capital income assessment result
  config/locales/en/providers.yml
Labels: Approved

#2345 AP-1982 formbuilder for cash payments forms
  app/controllers/citizens/cash_incomes_controller.rb
  app/controllers/citizens/cash_outgoings_controller.rb
  app/views/citizens/cash_incomes/_cash_income_form.html.erb
  app/views/citizens/cash_outgoings/_cash_outgoings_form.html.erb
  app/views/shared/partials/_revealing_checkbox.html.erb
  features/citizens/citizens.feature
  spec/requests/citizens/cash_incomes_spec.rb
  spec/requests/citizens/cash_outgoings_spec.rb
Labels: Approved, UAT

#2347 AP 2089 - DWP override prep
  app/controllers/admin/settings_controller.rb
  app/controllers/providers/check_client_details_controller.rb
  app/controllers/providers/evidence_of_benefits_controller.rb
  app/controllers/providers/received_benefit_confirmations_controller.rb
  app/forms/settings/setting_form.rb
  app/models/dwp_override.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  app/views/providers/check_client_details/show.html.erb
  app/views/providers/evidence_of_benefits/show.html.erb
  app/views/providers/received_benefit_confirmations/show.html.erb
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  config/routes.rb
  db/migrate/20210305123318_add_dwp_override_flag_to_settings.rb
  db/migrate/20210305145638_create_dwp_overrides.rb
  db/schema.rb
  lib/tasks/setup_db_for_testing.rake
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
  spec/requests/providers/check_client_details_spec.rb
  spec/requests/providers/evidence_of_benefits_spec.rb
  spec/requests/providers/received_benefit_confirmations_spec.rb
Labels: Approved, UAT

#2343 AP-2075 Content changes on income summary page
  app/views/shared/_cash_transactions.html.erb
  config/locales/en/transaction_types.yml
Labels: Approved, UAT

#2362 Add new DWP Override flow to service
  Gemfile
  app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
  app/services/flow/flows/provider_dwp_override.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/key_point.rb
  app/services/flow/provider_flow_service.rb
  app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
  config/routes.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
Labels: Approved

#2373 Bugfix: Re-add old CFE Result models
  app/models/cfe/v1/result.rb
  app/models/cfe/v2/result.rb
Labels: Approved, ready for review

#2375 BugFix - Capture exceptions in DeliveryMan when mailers raise an error
  app/services/govuk_emails/delivery_man.rb
  spec/services/govuk_emails/delivery_man_spec.rb
Labels: Approved

#2342 AP-2088 Fix Change Proceeding Types link
  app/views/shared/forms/proceedings_types/_proceeding_type.html.erb
Labels: Approved, UAT

#2328 AP-2046 Use new assigned scope limitations association
  README.md
  app/controllers/providers/has_other_proceedings_controller.rb
  app/controllers/providers/proceedings_types_controller.rb
  app/controllers/providers/used_delegated_functions_controller.rb
  app/models/application_proceeding_type.rb
  app/models/application_scope_limitation.rb
  app/models/assigned_df_scope_limitation.rb
  app/models/assigned_substantive_scope_limitation.rb
  app/models/legal_aid_application.rb
  app/services/add_assigned_scope_limitation_service.rb
  app/services/add_scope_limitation_service.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/legal_framework/add_assigned_scope_limitation_service.rb
  app/services/legal_framework/proceeding_types_service.rb
  app/services/legal_framework/remove_proceeding_type_service.rb
  app/services/proceeding_types_service.rb
  app/views/providers/limitations/show.html.erb
  app/views/shared/check_answers/_emergency_limitations.html.erb
  app/views/shared/check_answers/_substantive_limitations.html.erb
  config/environments/development.rb
  db/migrate/20210226113705_run_scope_limitations_migrator.rb
  db/migrate/20210226133024_add_type_to_application_proceeding_types_scope_limitations.rb
  db/migrate/20210302142433_drop_foreign_key_constraints_on_join_table.rb
  db/migrate/20210309195130_add_unique_idex_to_application_proceeding_types_scope_limitations.rb
  db/migration_helpers/scope_limitations_migrator.rb
  db/schema.rb
  db/seeds.rb
  features/step_definitions/civil_journey_steps.rb
  spec/cassettes/CitizenEmailService/_send_email/sending_the_email/sends_an_email_with_the_right_parameters.yml
  spec/factories/legal_aid_applications.rb
  spec/factory_specs/legal_aid_application_factory_spec.rb
  spec/migration_helpers/scope_limitations_migrator_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/proceedings_types_spec.rb
  spec/requests/providers/used_delegated_functions_spec.rb
  spec/services/add_scope_limitation_service_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/legal_framework/proceeding_types_service_spec.rb
  spec/services/legal_framework/remove_proceeding_type_service_spec.rb
  spec/services/proceeding_types_service_spec.rb
Labels: Approved, UAT

#2369 AP-2082 DWP Override Blue Box
  app/controllers/providers/check_benefits_controller.rb
  app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
  app/services/flow/flows/provider_dwp_override.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
  app/webpack/stylesheets/interruption-panel.scss
  config/locales/en/providers.yml
  features/providers/civil_application_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/requests/providers/check_benefits_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
Labels: Approved, UAT

#2372 AP-2094 remove jquery from table sort js
  app/webpack/src/table-sort.js
Labels: Approved, UAT

#2355 AP-2095 remove respondent-details.js
  app/webpack/src/respondent_detail.js
Labels: Approved, UAT

#2374 AP-2083: Add the confirm client details page for the DWP Override flow
  app/controllers/providers/check_benefits_controller.rb
  app/controllers/providers/check_client_details_controller.rb
  app/forms/providers/check_client_details_form.rb
  app/services/flow/flows/provider_dwp_override.rb
  app/views/providers/check_client_details/show.html.erb
  app/views/shared/forms/_next_action_buttons.html.erb
  app/webpack/stylesheets/govuk-secondary-button.scss
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/civil_application_journey.feature
  spec/requests/providers/check_client_details_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
Labels: Approved, UAT

#2386 AP-2046Z Application/Scope Limitation migration scripts
  .rubocop.yml
  app/models/assigned_df_scope_limitation.rb
  app/models/assigned_substantive_scope_limitation.rb
  lib/tasks/helpers/scope_limitations_migrator.rb
  lib/tasks/scope_limitations_migrator.rake
  spec/lib/migration_helpers/scope_limitations_migrator_spec.rb
  spec/requests/admin/settings_spec.rb
Labels: ready for review

#2370 AP 2084 DWP Confirm Benefits Received
  app/controllers/providers/check_provider_answers_controller.rb
  app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
  app/controllers/providers/received_benefit_confirmations_controller.rb
  app/forms/providers/received_benefit_confirmation_form.rb
  app/models/dwp_override.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_dwp_override.rb
  app/views/providers/received_benefit_confirmations/show.html.erb
  app/views/shared/forms/received_benefit_confirmation/_form.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  features/providers/civil_application_journey.feature
  spec/requests/providers/check_client_details_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
  spec/requests/providers/received_benefit_confirmations_spec.rb
Labels: Approved, UAT

#2387 BugFix application reminder no delegated functions & transition error
  app/mailers/submit_application_reminder_mailer.rb
  app/models/concerns/base_state_machine.rb
  spec/requests/admin/settings_spec.rb
Labels: Approved

#2388 Move developer documentation from readme to confluence pages
  README.md
  lib/tasks/helpers/scope_limitations_migrator.rb
Labels: Approved

#2357 AP-2087 Require Caseworker review if DWP result has been overridden
  app/controllers/providers/means_reports_controller.rb
  app/models/cfe/base_result.rb
  app/models/legal_aid_application.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/manual_review_determiner.rb
  app/services/reports/means_report_creator.rb
  app/views/providers/means_reports/_caseworker_review.html.erb
  app/views/providers/means_reports/show.html.erb
  config/locales/en/providers.yml
  db/migrate/20210309111908_add_unique_index_to_dwp_overrides.rb
  db/schema.rb
  spec/factories/dwp_overrides.rb
  spec/models/cfe/v3/result_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/services/ccms/manual_review_determiner_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: Approved, UAT

#2300 Ccms report generator
  app/controllers/admin/reports_controller.rb
  app/controllers/application_controller.rb
  app/controllers/providers/provider_base_controller.rb
  app/services/reports/reports_types_creator.rb
  app/views/admin/reports/index.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/admin.yml
  config/routes.rb
  spec/factories/ccms_submission_histories.rb
  spec/factories/ccms_submissions.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/admin/reports_spec.rb
  spec/services/reports/reports_types_creator_spec.rb
  spec/services/true_layer/bank_data_import_service_spec.rb
Labels: Approved

#2389 Tech debt/db anonymiser
  .github/workflows/anonymise_check.yml
  Gemfile
  Gemfile.lock
  README.md
  db/anonymise/rules.rb
  lib/tasks/db.rake
  scripts/db_export.sh
  scripts/migration_hook.rb
Labels: Approved, UAT

#2398 Tech-debt: update respondent rule
  db/anonymise/rules.rb
Labels: ready for review

#2401 Tech-debt: Update anonymise rules
  db/anonymise/rules.rb
Labels: Approved

#2399 AP-2138 Add AttemptsToSettle model
  app/models/legal_aid_application.rb
  app/models/proceeding_merits_task/attempts_to_settle.rb
  db/anonymise/rules.rb
  db/migrate/20210319110509_create_attempts_to_settle.rb
  db/schema.rb
Labels: Approved

#2381 AP-2046-G Use ApplicationProceedingTypesScopeLimtiations model
  README.md
  app/controllers/providers/has_other_proceedings_controller.rb
  app/controllers/providers/proceedings_types_controller.rb
  app/controllers/providers/used_delegated_functions_controller.rb
  app/models/application_proceeding_type.rb
  app/models/application_scope_limitation.rb
  app/models/legal_aid_application.rb
  app/services/add_assigned_scope_limitation_service.rb
  app/services/add_scope_limitation_service.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/legal_framework/add_assigned_scope_limitation_service.rb
  app/services/legal_framework/proceeding_types_service.rb
  app/services/legal_framework/remove_proceeding_type_service.rb
  app/services/proceeding_types_service.rb
  app/views/providers/limitations/show.html.erb
  app/views/shared/check_answers/_emergency_limitations.html.erb
  app/views/shared/check_answers/_substantive_limitations.html.erb
  config/environments/development.rb
  db/migrate/20210302142433_drop_foreign_key_constraints_on_join_table.rb
  db/schema.rb
  db/seeds.rb
  features/providers/civil_application_journey.feature
  features/step_definitions/civil_journey_steps.rb
  lib/tasks/helpers/scope_limitations_migrator.rb
  spec/cassettes/CitizenEmailService/_send_email/sending_the_email/sends_an_email_with_the_right_parameters.yml
  spec/factories/legal_aid_applications.rb
  spec/factory_specs/legal_aid_application_factory_spec.rb
  spec/migration_helpers/scope_limitations_migrator_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/proceedings_types_spec.rb
  spec/requests/providers/used_delegated_functions_spec.rb
  spec/services/add_scope_limitation_service_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/legal_framework/proceeding_types_service_spec.rb
  spec/services/legal_framework/remove_proceeding_type_service_spec.rb
  spec/services/proceeding_types_service_spec.rb
Labels: Approved

#2405 Tech-debt: Update fake saml logon
  app/controllers/saml_idp_controller.rb
Labels: Approved

#2395 AP-2133 Namespace Incident model
  app/controllers/providers/date_client_told_incidents_controller.rb
  app/forms/incidents/told_on_form.rb
  app/models/application_merits_task/incident.rb
  app/models/incident.rb
  app/models/legal_aid_application.rb
  config/locales/cy/activemodel.yml
  config/locales/en/activemodel.yml
  spec/factories/incidents.rb
  spec/forms/incidents/told_on_form_spec.rb
  spec/requests/providers/date_client_told_incidents_spec.rb
Labels: Approved

#2356 AP-2066 Update content for identify types of income page
  app/views/shared/forms/_types_of_income_form.html.erb
  config/locales/cy/shared.yml
  config/locales/en/shared.yml
Labels: Approved, UAT

#2402 Fix statement of case uploading by moving delete buttons outside of f…
  app/views/providers/statement_of_cases/show.html.erb
Labels: Approved, UAT

#2406 AP 2104 dwp error styling
  app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
  app/webpack/stylesheets/alternative-error-style.scss
  app/webpack/stylesheets/application.scss
Labels: Approved, UAT

#2403 AP-2136 Namespace StatementOfCase model
  app/controllers/providers/statement_of_cases_controller.rb
  app/forms/statement_of_cases/statement_of_case_form.rb
  app/models/application_merits_task/statement_of_case.rb
  app/models/legal_aid_application.rb
  app/models/statement_of_case.rb
  config/locales/cy/activemodel.yml
  config/locales/en/activemodel.yml
  features/accessibility/provider.feature
  features/providers/civil_application_journey.feature
  spec/factories/statement_of_cases.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/statement_of_case_spec.rb
Labels: Approved

#2394 AP-1821 Remove jQuery
  app/webpack/src/admin-delete.js
  app/webpack/src/bank_transactions.js
  app/webpack/src/continue_button.js
  app/webpack/src/helpers.js
  app/webpack/src/no_script.js
  app/webpack/src/start_button.js
  app/webpack/src/success_prospects.js
  app/webpack/src/worker_waiter.js
  app/webpack/stylesheets/providers/legal_aid_applications.scss
  config/webpack/environment.js
  features/support/wait_for_ajax.rb
  spec/javascript/worker_waiter.spec.js
Labels: Approved

#2414 Security: yarn update
  package.json
  yarn.lock
Labels: Approved, security

#2410 AP-2134 Rename Respondent model
  app/controllers/providers/check_merits_answers_controller.rb
  app/controllers/providers/opponent_names_controller.rb
  app/controllers/providers/opponents_controller.rb
  app/controllers/providers/respondent_names_controller.rb
  app/forms/opponents/opponent_form.rb
  app/forms/opponents/opponent_name_form.rb
  app/models/application_merits_task/opponent.rb
  app/models/legal_aid_application.rb
  app/models/respondent.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/flow/flows/provider_merits.rb
  app/services/reports/mis/application_detail_csv_line.rb
  app/views/providers/check_merits_answers/show.html.erb
  app/views/providers/merits_reports/show.html.erb
  app/views/providers/opponent_names/show.html.erb
  app/views/providers/opponents/show.html.erb
  app/views/providers/statement_of_cases/show.html.erb
  app/views/providers/submitted_applications/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/ccms/attribute_block_configs/base.yml
  config/locales/cy/activemodel.yml
  config/locales/cy/helpers.yml
  config/locales/cy/shared.yml
  config/locales/en/activemodel.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20210322122007_rename_respondents_table_to_opponents.rb
  db/schema.rb
  features/accessibility/provider.feature
  features/providers/civil_application_journey.feature
  spec/factories/legal_aid_applications.rb
  spec/factories/opponents.rb
  spec/forms/opponents/opponent_form_spec.rb
  spec/lib/govuk_elements_form_builder/form_builder_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/opponent_names_spec.rb
  spec/requests/providers/opponents_spec.rb
  spec/requests/providers/respondents_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
  spec/services/ccms/submitters/upload_documents_service_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: Approved, UAT

#2382 AP-2085 DWP Does the provider have passported evidence page
  app/controllers/providers/evidence_of_benefits_controller.rb
  app/controllers/providers/has_evidence_of_benefits_controller.rb
  app/controllers/providers/received_benefit_confirmations_controller.rb
  app/forms/legal_aid_applications/has_evidence_of_benefit_form.rb
  app/services/flow/flows/provider_dwp_override.rb
  app/views/providers/evidence_of_benefits/show.html.erb
  app/views/providers/has_evidence_of_benefits/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/migrate/20210312110904_rename_evidence_available_to_has_evidence_of_benefit.rb
  db/schema.rb
  features/providers/civil_application_journey.feature
  features/step_definitions/civil_journey_steps.rb
  features/support/steps_helper.rb
  spec/factories/dwp_overrides.rb
  spec/factories/legal_aid_applications.rb
  spec/forms/legal_aid_applications/has_evidence_of_benefits_form_spec.rb
  spec/requests/admin/settings_spec.rb
  spec/requests/providers/evidence_of_benefits_spec.rb
  spec/requests/providers/has_evidence_of_benefits_spec.rb
  spec/requests/providers/received_benefit_confirmations_spec.rb
Labels: Approved, UAT Success

#2408 Ap 2149 fix full text search
  Gemfile.lock
  app/models/proceeding_type.rb
  app/services/proceeding_type_full_text_search.rb
  app/webpack/src/modules/proceedings.js
  spec/javascript/modules/proceedings.spec.js
  spec/requests/proceeding_types/index_proceeding_types_spec.rb
  spec/services/proceeding_type_full_text_search_spec.rb
Labels: Approved, UAT

#2415 AP-2047 remove the application scope limitations code
  .rubocop.yml
  app/models/application_scope_limitation.rb
  app/models/legal_aid_application.rb
  db/anonymise/rules.rb
  db/migrate/20210323113558_drop_table_application_scope_limitations.rb
  db/schema.rb
  lib/tasks/helpers/scope_limitations_migrator.rb
  lib/tasks/scope_limitations_migrator.rake
  spec/lib/migration_helpers/scope_limitations_migrator_spec.rb
  spec/migration_helpers/scope_limitations_migrator_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: Approved, UAT

#2436 Tech debt:remove mimemagic
  Gemfile
  Gemfile.lock
  app/forms/statement_of_cases/statement_of_case_form.rb
Labels: Approved

#2400 Ap 2124 instance names
  app/models/bank_account.rb
  app/services/ccms/requestors/case_add_requestor.rb
  config/ccms/means_entity_configs/non_passported.yml
  config/ccms/means_entity_configs/passported.yml
  spec/data/ccms/case_add_request.xml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
Labels: Approved, UAT
