Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2021-05, with the labels that each got.

#2511 Fix the rake task to migrate submitted_at attribute
  lib/tasks/migrate_submitted_at.rake
Labels: ready for review

#2506 AP-2261: new proceeding types
  app/services/proceeding_type_populator.rb
  app/services/proceeding_type_scope_limitations_populator.rb
  db/seeds/legal_framework/proceeding_type_scope_limitations.csv
  db/seeds/legal_framework/proceeding_types.csv
  db/seeds/legal_framework/scope_limitations.csv
  spec/services/proceeding_type_populator_spec.rb
  spec/services/proceeding_type_scope_limitations_populator_spec.rb
Labels: Approved, UAT

#2483 Rake task to list cucumber steps
  Gemfile
  Gemfile.lock
  lib/tasks/cucumber_steps.rake
Labels: Approved

#2522 Tech-Debt: REXML update
  Gemfile
  Gemfile.lock
  app/views/saml_idp/idp/saml_post.html.erb
  features/providers/mock_saml.feature
  features/step_definitions/civil_journey_steps.rb
  spec/requests/saml_idp_spec.rb
Labels: Approved

#2540 bug-fix: Flicking feature
  features/step_definitions/civil_journey_steps.rb
Labels: Approved

#2531 AP-2277 update scope limitations page
  app/views/providers/limitations/_proceeding_type.html.erb
  app/views/providers/limitations/show.html.erb
  app/views/shared/forms/_next_action_buttons.html.erb
  config/locales/en/providers.yml
  features/providers/civil_application_journey.feature
  spec/requests/providers/limitations_spec.rb
Labels: Approved, UAT

#2516 Ap 2249 update the admin reports
  app/services/reports/mis/application_detail_csv_line.rb
  app/services/reports/mis/non_passported_application_csv_line.rb
  spec/requests/admin/reports_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
  spec/services/reports/mis/non_passported_application_csv_line_spec.rb
  spec/services/reports/mis/non_passported_applications_report_spec.rb
Labels: Approved, UAT

#2545 AP-1898 update content on about the financial assessment page
  app/views/providers/about_the_financial_assessments/show.html.erb
  config/locales/en/providers.yml
  features/accessibility/provider.feature
  features/providers/civil_application_journey.feature
  features/providers/non_passported_journey.feature
Labels: Approved, UAT

#2543 AP-1896 update content on open banking provider consent page
  app/views/providers/open_banking_consents/show.html.erb
  config/locales/en/providers.yml
Labels: Approved, UAT

#2544 AP-1897 update content on non passported client instructions page
  app/views/providers/non_passported_client_instructions/show.html.erb
  config/locales/en/providers.yml
Labels: Approved, UAT

#2537 AP-2289 duplicate DF dates on application_proceeding_type
  app/controllers/providers/limitations_controller.rb
Labels: Approved

#2546 AP-2278 select at least one domestic abuse proceeding
  app/controllers/providers/has_other_proceedings_controller.rb
  app/views/providers/proceedings_types/index.html.erb
  app/views/shared/forms/proceedings_types/_proceeding_type_form.html.erb
  app/webpack/stylesheets/providers/legal_aid_applications.scss
  config/locales/en/providers.yml
  spec/requests/providers/has_other_proceedings_controller_spec.rb
Labels: Approved, UAT

#2548 Tech-debt/Flickering tests
  spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb
  spec/requests/providers/proceeding_merits_task/involved_children_spec.rb
Labels: Approved

#2538 Ap 2233 check delegated functions page
  app/controllers/providers/confirm_multiple_delegated_functions_controller.rb
  app/controllers/providers/used_multiple_delegated_functions_controller.rb
  app/models/concerns/binary_choice_form.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/confirm_multiple_delegated_functions/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/civil_application_journey.feature
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/confirm_multiple_delegated_functions_dates_spec.rb
  spec/requests/providers/used_multiple_delegated_functions_spec.rb
Labels: Approved

#2552 Ap 2286 merge opponent details
  app/controllers/providers/application_merits_task/opponents_controller.rb
  app/controllers/providers/opponent_names_controller.rb
  app/forms/opponents/opponent_form.rb
  app/forms/opponents/opponent_name_form.rb
  app/services/flow/flows/provider_merits.rb
  app/views/providers/application_merits_task/opponents/show.html.erb
  app/views/providers/opponent_names/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/locales/cy/shared.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  features/accessibility/provider.feature
  features/providers/civil_application_journey.feature
  spec/requests/providers/application_merits_task/opponents_spec.rb
  spec/requests/providers/opponent_names_spec.rb
Labels: Approved

#2558 Ap-2146 update heading sizes and hierarchy on 'add another' pages
  app/views/providers/application_merits_task/has_other_involved_children/show.html.erb
  app/views/providers/has_other_dependants/show.html.erb
  app/views/providers/has_other_proceedings/show.html.erb
Labels: Approved, UAT

#2554 AP-2241 LASPO page
  app/controllers/providers/has_other_proceedings_controller.rb
  app/controllers/providers/in_scope_of_laspos_controller.rb
  app/forms/legal_aid_applications/in_scope_of_laspo_form.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/in_scope_of_laspos/show.html.erb
  app/views/providers/used_multiple_delegated_functions/show.html.erb
  app/views/shared/check_answers/_delegated_functions.html.erb
  app/views/shared/check_answers/_proceedings_details.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/migrate/20210518095337_add_in_scope_of_laspo.rb
  db/schema.rb
  features/providers/civil_application_journey.feature
  spec/factories/proceeding_types.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/in_scope_of_laspos_controller_spec.rb
  spec/requests/providers/proceedings_types_spec.rb
Labels: Approved, UAT

#2567 AP-2080 update cash transactions error messages
  app/models/base_aggregated_cash_transaction.rb
  config/locales/en/errors.yml
  config/locales/en/transaction_types.yml
  spec/models/aggregated_cash_income_spec.rb
  spec/models/aggregated_cash_outgoings_spec.rb
  spec/requests/citizens/cash_incomes_spec.rb
  spec/requests/citizens/cash_outgoings_spec.rb
Labels: Approved, UAT

#2572 AP-2153 add hint text to offline account checkbox
  config/locales/en/shared.yml
Labels: Approved, UAT

#2561 AP-2204 fix bug where df date_reported_on was not being stored for cases where df date was over a month old
  app/controllers/providers/used_delegated_functions_controller.rb
  app/forms/legal_aid_applications/confirm_delegated_functions_date_form.rb
  app/forms/legal_aid_applications/used_multiple_delegated_functions_form.rb
  spec/forms/legal_aid_applications/confirm_delegated_functions_date_form_spec.rb
  spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb
Labels: Approved, UAT

#2573 AP-2096 update restrictions content
  app/views/providers/restrictions/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/accessibility/provider.feature
  features/providers/check_your_answers.feature
  features/providers/civil_application_journey.feature
  features/providers/non_passported_journey.feature
Labels: Approved, UAT

#2570 AP 2285 increase emergency cost limit
  app/controllers/providers/limitations_controller.rb
  app/forms/legal_aid_applications/emergency_cost_override_form.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/limitations/_legacy_proceeding_types.html.erb
  app/views/providers/limitations/_multi_proceeding_types.html.erb
  app/views/providers/limitations/_multi_proceeding_types_with_df.html.erb
  app/views/providers/limitations/show.html.erb
  app/views/shared/check_answers/_emergency_costs.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  db/migrate/20210520071320_add_emergency_cost_limitation_to_legal_aid_application.rb
  db/schema.rb
  features/cassettes/Emergency_cost_override/Provider_is_prompted_to_override_emergency_cost_limitation.yml
  features/providers/civil_application_journey.feature
  features/providers/emergency_cost_override.feature
  features/step_definitions/civil_journey_steps.rb
  spec/forms/legal_aid_applications/emergency_cost_override_form_spec.rb
  spec/requests/providers/limitations_spec.rb
Labels: Approved, UAT
