Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2021-04, with the labels that each got.

#2409 AP-2111 Use transaction_period as basis for cash payment months
  app/models/base_aggregated_cash_transaction.rb
  app/webpack/src/modules/proceedings.js
  spec/models/aggregated_cash_income_spec.rb
  spec/models/aggregated_cash_outgoings_spec.rb
  spec/requests/citizens/cash_incomes_spec.rb
  spec/requests/citizens/cash_outgoings_spec.rb
Labels: Approved, UAT

#2424 Ap 1960 specify a lead proceeding
  app/controllers/providers/has_other_proceedings_controller.rb
  app/models/application_proceeding_type.rb
  app/models/legal_aid_application.rb
  app/services/ccms/requestors/case_add_requestor.rb
  db/migrate/20210324140533_add_lead_type_to_application_proc_types.rb
  db/schema.rb
  features/step_definitions/civil_journey_steps.rb
  lib/tasks/set_lead_proceeding.rake
  spec/models/application_proceeding_type_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
Labels: Approved

#2444 AP-2188: prevent duplicate scope limitations
  Guardfile
  app/models/application_proceeding_type.rb
  features/cassettes/Civil_application_journeys/Allows_return_to_and_proceed_from_Delegated_Function_date_view.yml
  features/providers/civil_application_journey.feature
  spec/models/application_proceeding_type_spec.rb
Labels: Approved, UAT Success

#2429 Add BinaryChoiceForm controller and update additional accounts contro…
  app/controllers/citizens/additional_accounts_controller.rb
  app/controllers/providers/applicant_bank_accounts_controller.rb
  app/controllers/providers/check_client_details_controller.rb
  app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
  app/controllers/providers/confirm_offices_controller.rb
  app/controllers/providers/has_other_dependants_controller.rb
  app/controllers/providers/has_other_proceedings_controller.rb
  app/controllers/providers/no_income_summaries_controller.rb
  app/controllers/providers/no_outgoings_summaries_controller.rb
  app/controllers/providers/remove_dependant_controller.rb
  app/controllers/providers/remove_dependants_controller.rb
  app/forms/providers/check_client_details_form.rb
  app/forms/providers/has_other_proceedings_form.rb
  app/models/concerns/binary_choice_form.rb
  app/services/flow/flows/provider_dependants.rb
  app/views/citizens/additional_accounts/index.html.erb
  app/views/citizens/additional_accounts/new.html.erb
  app/views/providers/applicant_bank_accounts/show.html.erb
  app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
  app/views/providers/confirm_offices/show.html.erb
  app/views/providers/has_other_dependants/show.html.erb
  app/views/providers/has_other_proceedings/show.html.erb
  app/views/providers/invalid_logins/show.html.erb
  app/views/providers/no_income_summaries/show.html.erb
  app/views/providers/no_outgoings_summaries/show.html.erb
  app/views/providers/remove_dependants/show.html.erb
  config/locales/cy/citizens.yml
  config/locales/en/citizens.yml
  config/locales/en/providers.yml
  config/routes.rb
  spec/helpers/providers_helper_spec.rb
  spec/requests/citizens/additional_accounts_spec.rb
  spec/requests/providers/applicant_bank_accounts_spec.rb
  spec/requests/providers/check_client_details_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
  spec/requests/providers/confirm_offices_spec.rb
  spec/requests/providers/has_other_dependants_controller_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/no_income_summaries_spec.rb
  spec/requests/providers/no_outgoings_summaries_spec.rb
  spec/requests/providers/remove_dependant_controller_spec.rb
Labels: Approved, Changes Requested, UAT

#2445 Ap 2140 Namespace Merits task controllers
  app/controllers/providers/application_merits_task/date_client_told_incidents_controller.rb
  app/controllers/providers/application_merits_task/opponents_controller.rb
  app/controllers/providers/application_merits_task/statement_of_cases_controller.rb
  app/controllers/providers/check_merits_answers_controller.rb
  app/controllers/providers/date_client_told_incidents_controller.rb
  app/controllers/providers/opponents_controller.rb
  app/controllers/providers/proceeding_merits_task/chances_of_success_controller.rb
  app/controllers/providers/statement_of_cases_controller.rb
  app/controllers/providers/success_likely_controller.rb
  app/services/flow/flows/provider_merits.rb
  app/services/migration_helpers/state_changer.rb
  app/views/providers/application_merits_task/date_client_told_incidents/show.html.erb
  app/views/providers/application_merits_task/opponents/show.html.erb
  app/views/providers/application_merits_task/statement_of_cases/_uploaded_files.html.erb
  app/views/providers/application_merits_task/statement_of_cases/show.html.erb
  app/views/providers/proceeding_merits_task/chances_of_success/index.html.erb
  app/views/providers/success_prospects/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  spec/requests/providers/application_merits_task/date_client_told_incidents_spec.rb
  spec/requests/providers/application_merits_task/opponents_spec.rb
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/date_client_told_incidents_spec.rb
  spec/requests/providers/opponents_spec.rb
  spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
  spec/requests/providers/statement_of_case_spec.rb
  spec/requests/providers/success_likely_spec.rb
Labels: Approved, UAT

#2458 Update styling and confirm dwp form
  app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
  app/webpack/stylesheets/alternative-error-style.scss
  app/webpack/stylesheets/application.scss
  app/webpack/stylesheets/interruption-panel.scss
Labels: ready for review

#2460 rake task has been run so remove it
  lib/tasks/set_lead_proceeding.rake
Labels: Approved

#2452 AP-2131 Apply Legal framework service call
  .env.sample
  README.md
  app/models/legal_aid_application.rb
  app/models/legal_framework.rb
  app/models/legal_framework/merits_task_list.rb
  app/models/legal_framework/serializable_merits_task.rb
  app/models/legal_framework/serializable_merits_task_list.rb
  app/models/legal_framework/submission.rb
  app/models/legal_framework/submission_history.rb
  app/services/legal_framework/base_service.rb
  app/services/legal_framework/merits_tasks_retriever_service.rb
  app/services/legal_framework/merits_tasks_service.rb
  app/services/legal_framework/submission_error.rb
  config/application.rb
  db/anonymise/rules.rb
  db/migrate/20210401124208_create_legal_framework_submissions.rb
  db/migrate/20210401124219_create_legal_framework_submission_histories.rb
  db/migrate/20210407081304_create_legal_framework_merits_task_list.rb
  db/schema.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/factories/legal_framework_serializable_merits_task.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/factories/legal_framework_submissions.rb
  spec/models/legal_framework/merits_task_list_spec.rb
  spec/models/legal_framework/serializable_merits_task_list_spec.rb
  spec/models/legal_framework/serializable_merits_task_spec.rb
  spec/services/legal_framework/merits_tasks_retriever_service_spec.rb
  spec/services/legal_framework/merits_tasks_service_spec.rb
  spec/support/shared_examples/legal_framework_failures_shared_examples.rb
Labels: ready for review

#2467 AP-2224: Fix logging
  config/environments/production.rb
  config/initializers/filter_parameter_logging.rb
Labels: ready for review

#2478 Ignore git crypt folder
  .git-crypt/.gitattributes
  .git-crypt/keys/default/0/0389955D7A5A0696C8595A13A4DFF913E2FBBDD6.gpg
  .git-crypt/keys/default/0/241F98B8409DFD1F81726FB52AA46844975B44FA.gpg
  .git-crypt/keys/default/0/55BDC285DEE8FF6512A7CF666FEA91FDA251073C.gpg
  .git-crypt/keys/default/0/7AE4540A0273EBB3EC62B7BDFFC34BE026FC6B18.gpg
  .git-crypt/keys/default/0/7F6D3B095238754680D42F49886C4C04BB346D41.gpg
  .git-crypt/keys/default/0/938E7C9398E84D06C798BE272BB4E15C26B77368.gpg
  .git-crypt/keys/default/0/9EAE286FB9078CE6C63AAAA294E0BE13C4047208.gpg
  .git-crypt/keys/default/0/FF66FFC7854287EFB3B2DDC91BBB1B3B0572A4E1.gpg
Labels: ready for review

#2468 AP-2034: Update hint text for searching multiple proceedings
  config/locales/en/providers.yml
Labels: Approved, UAT

#2475 Re-instate database section accidentally remvoed from README
  README.md
Labels: Approved

#2482 Rotate the sentry keys for 3 environments
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: ready for review

#2488 AP-2258 Add modsecurity to our ingress
  helm_deploy/apply-for-legal-aid/templates/ingress.yaml
Labels: Approved

#2474 AP-2172 Add used_delegated_functions columns and rake task
  app/models/application_proceeding_type.rb
  app/models/legal_aid_application.rb
  db/migrate/20210408162032_add_delegated_functions_date_to_application_proceeding_types.rb
  db/schema.rb
  lib/tasks/move_delegated_functions_data.rake
  spec/models/application_proceeding_type_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/means_summaries_spec.rb
Labels: Approved, UAT

#2493 BugFix Fix broken rake task to pluck id for applications
  lib/tasks/move_delegated_functions_data.rake
Labels: Approved

#2462 AP-2141 Involved Children controller
  app/controllers/providers/application_merits_task/has_other_involved_children_controller.rb
  app/controllers/providers/application_merits_task/involved_children_controller.rb
  app/controllers/providers/application_merits_task/remove_involved_child_controller.rb
  app/forms/providers/application_merits_task/involved_child_form.rb
  app/models/application_merits_task/involved_child.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_merits.rb
  app/views/providers/application_merits_task/has_other_involved_children/show.html.erb
  app/views/providers/application_merits_task/involved_children/_form.html.erb
  app/views/providers/application_merits_task/involved_children/new.html.erb
  app/views/providers/application_merits_task/involved_children/show.html.erb
  app/views/providers/application_merits_task/remove_involved_child/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  spec/factories/application_merits_task/involved_children.rb
  spec/forms/providers/application_merits_task/involved_child_form_spec.rb
  spec/models/application_proceeding_type_spec.rb
  spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
  spec/requests/providers/application_merits_task/involved_children_spec.rb
  spec/requests/providers/application_merits_task/remove_involved_child_spec.rb
Labels: Approved

#2487 Ap 2230 date field bug
  Gemfile.lock
  app/forms/applicants/basic_details_form.rb
  app/forms/concerns/date_field_builder.rb
  app/forms/incidents/told_on_form.rb
  app/forms/legal_aid_applications/delegated_functions_date_form.rb
  app/forms/legal_aid_applications/dependant_form.rb
  app/forms/legal_aid_applications/used_delegated_functions_form.rb
Labels: Approved

#2469 AP-2197: Update privacy policy content
  app/views/privacy_policy/index.html.erb
  config/locales/cy/activemodel.yml
  config/locales/cy/citizens.yml
  config/locales/cy/dates.yml
  config/locales/cy/feedback.yml
  config/locales/cy/generic.yml
  config/locales/cy/helpers.yml
  config/locales/cy/privacy_policy.yml
  config/locales/cy/shared.yml
  config/locales/cy/transaction_types.yml
  config/locales/en/privacy_policy.yml
  features/accessibility/citizen.feature
  features/citizens/citizens.feature
  features/citizens/citizens_welsh.feature
  features/providers/civil_application_journey.feature
  lib/tasks/helpers/cy_helper.rb
  spec/requests/privacy_policy_spec.rb
Labels: Approved, UAT

#2476 AP-2191: Add delegated functions to the multiple proceedings journey
  app/controllers/providers/used_multiple_delegated_functions_controller.rb
  app/forms/concerns/date_field_builder.rb
  app/forms/legal_aid_applications/used_multiple_delegated_functions_form.rb
  app/models/application_proceeding_type.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_start.rb
  app/services/substantive_application_deadline_calculator.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/limitations/show.html.erb
  app/views/providers/used_multiple_delegated_functions/show.html.erb
  app/views/shared/check_answers/_delegated_functions.html.erb
  app/views/shared/check_answers/_item.html.erb
  app/views/shared/check_answers/_proceedings_details.html.erb
  app/webpack/stylesheets/providers/proceeding_types.scss
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/migrate/20210423180431_add_name_to_proceeding_types.rb
  db/schema.rb
  db/seeds/legal_framework/proceeding_types.csv
  features/cassettes/Civil_application_journeys/Completes_the_application_using_address_lookup.yml
  features/providers/civil_application_journey.feature
  features/support/steps_helper.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/proceeding_types.rb
  spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb
  spec/models/application_proceeding_type_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/requests/providers/used_multiple_delegated_functions_spec.rb
Labels: Approved, UAT

#2503 Bug-fix: update flickering test
  spec/models/application_proceeding_type_spec.rb
Labels: Approved

#2457 AP-2142: Implement ProceedingMeritsTask::AttemptsToSettleForm
  app/controllers/providers/proceeding_merits_task/attempts_to_settle_controller.rb
  app/forms/providers/proceeding_merits_task/attempts_to_settle_form.rb
  app/models/application_proceeding_type.rb
  app/models/legal_aid_application.rb
  app/models/proceeding_merits_task/attempts_to_settle.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/proceeding_merits_task/attempts_to_settle/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  db/migrate/20210409102038_change_attempts_to_settle_belongs_to.rb
  db/schema.rb
  spec/forms/providers/proceeding_merits_task/attempts_to_settle_form_spec.rb
  spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
Labels: ready for review

#2505 Bug-fix: Address flickering test
  spec/requests/providers/application_merits_task/remove_involved_child_spec.rb
Labels: Approved

#2464 AP-2143: Setup initial files for proceeding merits and involved children
  app/controllers/providers/proceeding_merits_task/involved_children_controller.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/proceeding_merits_task/involved_children/show.html.erb
  config/routes.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/proceeding_merits_task/application_proceeding_type_involved_children.rb
  spec/requests/providers/proceeding_merits_task/involved_children_spec.rb
Labels: Approved
