Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2021-12, with the labels that each got.

#3137 AP-2719 BUGFIX: Substantive scope limitations appearing on Emergency Applications
  app/services/ccms/requestors/case_add_requestor.rb
  spec/data/ccms/mp_df_case_add_request.xml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: Approved

#3146 Fix: Restart CCMS submissions
  app/models/concerns/base_state_machine.rb
  spec/services/ccms_restart_submissions_spec.rb
Labels: Approved

#3127 AP-2565 Move HMRC call
  app/controllers/providers/applicant_employed_controller.rb
  app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
  app/views/providers/applicant_employed/index.html.erb
  app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
  app/webpack/stylesheets/interruption-panel.scss
  config/locales/en/providers.yml
  features/accessibility/provider.feature
  features/providers/civil_application_journey.feature
  features/providers/non_passported_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/applicant_employed_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
Labels: UAT, Approved

#3153 AP-2718: restart ccms submissions
  app/controllers/admin/settings_controller.rb
  app/services/ccms/restart_submissions.rb
  app/services/ccms_restart_submissions.rb
  lib/tasks/restart_ccms_submissions.rake
  spec/requests/admin/settings_spec.rb
  spec/services/ccms/restart_submissions_spec.rb
Labels: Approved

#3149 Tech Debt: Update minor ruby version
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: Approved

#3136 Add hmrc field to admin report
  app/services/reports/mis/application_detail_csv_line.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: UAT, Approved

#3150 AP-2555 remote restore anonymised DB to uat
  README.md
  lib/tasks/db.rake
  scripts/restore_anonymised_db.sh
Labels: Ready for review

#3162 Create codeql-analysis.yml
  codeql-analysis.yml
Labels: Ready for review

#3163 Fix: CodeQL location
  .github/workflows/codeql-analysis.yml
Labels: Ready for review

#3169 bugfix: use correct namespace env var
  bin/uat_deploy
Labels: Ready for review

#3172 ap-2730: Create document_categories table
  app/models/document_category.rb
  app/services/document_category_populator.rb
  db/anonymise/rules.rb
  db/migrate/20211209083010_create_document_categories.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/document_categories.csv
  db/seeds/document_categories.rb
  spec/factories/document_categories.rb
  spec/models/document_category_spec.rb
  spec/services/document_category_populator_spec.rb
Labels: Approved

#3167 AP-2747 Increase memory on digest export cron job
  helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
Labels: Approved

#3168 AP-2729 Add evidence upload feature flag
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  db/migrate/20211208161719_add_evidence_upload_flag_to_settings.rb
  db/schema.rb
  lib/tasks/setup_db_for_testing.rake
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
Labels: UAT, Approved

#3154 AP-2564 New Employment status page
  app/controllers/providers/applicant_employed_controller.rb
  app/forms/applicants/employed_form.rb
  app/models/applicant.rb
  app/models/concerns/base_state_machine.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_dwp_override.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/applicant_employed/index.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  db/migrate/20211126133758_add_new_employment_statuses_to_applicant.rb
  db/schema.rb
  features/accessibility/provider.feature
  features/cassettes/Civil_application_journeys/A_negative_benefit_check_allows_the_solicitor_to_override_the_result.yml
  features/cassettes/Provider_accessibility/I_start_a_new_application_and_declare_I_am_self-employed.yml
  features/providers/civil_application_journey.feature
  features/providers/emergency_cost_override.feature
  features/providers/non_passported_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  spec/factories/applicants.rb
  spec/forms/applicants/employed_form_spec.rb
  spec/models/applicant_spec.rb
  spec/requests/providers/address_selections_spec.rb
  spec/requests/providers/addresses_spec.rb
  spec/requests/providers/applicant_employed_spec.rb
  spec/requests/providers/check_benefits_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
  spec/requests/providers/has_evidence_of_benefits_spec.rb
  spec/requests/providers/provider_base_controller_spec.rb
  spec/requests/providers/received_benefit_confirmations_spec.rb
Labels: UAT, Approved

#3165 AP-2714 send delete request with AJAX
  app/controllers/providers/delete_controller.rb
  app/controllers/v1/legal_aid_applications_controller.rb
  app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/shared/partials/_modal_dialogue.html.erb
  app/webpack/src/modal-dialogue.js
  config/routes.rb
  spec/requests/providers/delete_controller_spec.rb
  spec/requests/v1/legal_aid_applications_spec.rb
Labels: UAT, Approved

#3173 AP-2731 Add required_document_categories field
  app/models/document_category.rb
  app/models/legal_aid_application.rb
  db/migrate/20211209141633_add_required_document_categories_to_legal_aid_applications.rb
  db/schema.rb
  spec/models/legal_aid_application_spec.rb
Labels: Approved

#3176 Fix spelling of eligibility on means report
  config/locales/en/providers.yml
Labels: Approved

#3158 AP-2568 Parse HMRC response
  app/models/hmrc/employment.rb
  app/models/hmrc/employment_income_summary.rb
  app/models/hmrc/employment_payment.rb
  app/models/hmrc/response.rb
  spec/factories/hmrc/responses.rb
  spec/factory_helpers/hmrc_response/use_case_one.rb
  spec/factory_specs/hmrc_response/use_case_one_helper_spec.rb
  spec/models/hmrc/employment_income_summary_spec.rb
  spec/models/hmrc/employment_payment_spec.rb
  spec/models/hmrc/employment_spec.rb
  spec/models/hmrc/response_spec.rb
  spec/workers/hmrc/result_worker_spec.rb
Labels: Approved

#3178 fix warning text icons
  app/views/layouts/application.html.erb
  app/views/providers/substantive_applications/show.html.erb
Labels: UAT, Approved

#3183 ap-2732: create required_document_category_analyser
  app/models/legal_aid_application.rb
  app/services/required_document_category_analyser.rb
  spec/factories/legal_aid_applications.rb
  spec/models/legal_aid_application_spec.rb
  spec/services/required_document_category_analyser_spec.rb
Labels: Approved

#3177 Ap2567 hmrc results
  app/controllers/providers/employment_incomes_controller.rb
  app/forms/legal_aid_applications/employment_income_form.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/employment_incomes/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/migrate/20211209134144_add_employment_attrs_to_legal_aid_application.rb
  db/schema.rb
  spec/requests/providers/client_completed_means_spec.rb
  spec/requests/providers/employed_incomes_spec.rb
Labels: Approved

#3189 AP-2399 Delete unused source files
  app/forms/legal_aid_applications/used_delegated_functions_form.rb
  spec/forms/legal_aid_applications/used_delegated_functions_form_spec.rb
Labels: Approved

#3186 Testing bugfix
  spec/factories/legal_aid_applications.rb
Labels: Approved

#3188 AP-2550: Rename CCMS fixture files
  spec/data/ccms/case_add_request.xml
  spec/data/ccms/df_case_add_request.xml
  spec/data/ccms/mp_case_add_request.xml
  spec/services/ccms/requestors/case_add_requestor_spec.rb
Labels: Approved

#3184 AP-2763 Test to ensure 100% code coverage
  spec/models/legal_aid_application_spec.rb
Labels: Approved

#3185 AP-2362:improve report generation
  app/services/reports/base_report_creator.rb
  app/services/reports/means_report_creator.rb
  app/services/reports/merits_report_creator.rb
  spec/services/reports/means_report_creator_spec.rb
  spec/services/reports/merits_report_creator_spec.rb
Labels: UAT, Approved

#3174 AP-2733 Change copy on has_benefit_evidence page
  app/helpers/gov_uk_form_helper.rb
  app/views/providers/has_evidence_of_benefits/show.html.erb
  config/locales/en/providers.yml
  spec/requests/providers/has_evidence_of_benefits_spec.rb
Labels: UAT, Approved

#3191 AP-2570 Add No HMRC data page
  app/controllers/providers/employment_incomes_controller.rb
  app/controllers/providers/no_employment_incomes_controller.rb
  app/forms/legal_aid_applications/employment_income_form.rb
  app/forms/legal_aid_applications/no_employment_income_form.rb
  app/models/hmrc/response.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/employment_incomes/show.html.erb
  app/views/providers/no_employment_incomes/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/data/20211125142125_add_employment_to_permissions_table.rb
  db/data_schema.rb
  db/migrate/20211210144834_add_full_employment_details_to_legal_aid_application.rb
  db/migrate/20211214154807_rename_employment_information_details.rb
  db/schema.rb
  db/seeds/permissions.rb
  features/providers/employed_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/models/hmrc/response_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/client_completed_means_spec.rb
  spec/requests/providers/employed_incomes_spec.rb
  spec/requests/providers/no_employment_incomes_spec.rb
Labels: UAT, Approved

#3195 AP-2766 update script to delete file
  scripts/restore_anonymised_db.sh
Labels: UAT, Approved

#3179 Ap 2572 cya income
  app/views/providers/means_summaries/show.html.erb
  app/views/shared/check_answers/_employed_income.html.erb
  config/locales/en/shared.yml
Labels: Approved

#3204 AP-2777: Update HMRC request handling
  app/controllers/providers/use_ccms_employed_controller.rb
  app/services/hmrc/interface/submission_service.rb
  app/services/reports/mis/non_passported_applications_report.rb
  config/application.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/requests/providers/use_ccms_employed_spec.rb
  spec/services/hmrc/interface/submission_service_spec.rb
Labels: UAT, Approved

#3203 AP-2682 OpenStruct issues
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/providers/address_selections_controller.rb
  app/forms/providers/received_benefit_confirmation_form.rb
  app/helpers/capital_helper.rb
  app/helpers/check_answers_helper.rb
  app/helpers/user_transactions_helper.rb
  app/services/legal_framework/proceeding_types/all.rb
  app/views/shared/forms/received_benefit_confirmation/_form.html.erb
  spec/helpers/policy_disregards_helper_spec.rb
  spec/services/bank_holiday_retriever_service_spec.rb
  spec/services/true_layer/banks_retriever_spec.rb
  spec/spec_helper.rb
Labels: UAT, Approved

#3200 Ap 2571 hmrc record exists
  app/services/flow/flows/provider_capital.rb
  app/views/providers/employment_incomes/show.html.erb
  config/locales/en/providers.yml
  features/step_definitions/civil_journey_steps.rb
  spec/requests/providers/applicant_employed_spec.rb
  spec/requests/providers/client_completed_means_spec.rb
  spec/requests/providers/employed_incomes_spec.rb
  spec/requests/providers/received_benefit_confirmations_spec.rb
Labels: Approved

#3196 ap-2724: Remove dependency on application proceeding type from merits…
  app/services/reports/merits_report_creator.rb
Labels: Approved

#3205 AP-2778 digest exporter cron
  app/services/digest_exporter.rb
  helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
  spec/services/digest_exporter_spec.rb
Labels: Approved

#3210 SPIKE: revert employed question flow
  app/services/flow/flows/provider_dwp_override.rb
  app/services/flow/flows/provider_start.rb
  features/accessibility/provider.feature
  features/cassettes/Provider_accessibility/I_start_a_new_application_and_declare_I_am_self-employed.yml
  features/providers/civil_application_journey.feature
  features/providers/emergency_cost_override.feature
  features/providers/non_passported_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  spec/requests/providers/address_selections_spec.rb
  spec/requests/providers/addresses_spec.rb
  spec/requests/providers/applicant_employed_spec.rb
  spec/requests/providers/check_benefits_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
  spec/requests/providers/has_evidence_of_benefits_spec.rb
  spec/requests/providers/provider_base_controller_spec.rb
  spec/requests/providers/received_benefit_confirmations_spec.rb
Labels: Approved

#3225 AP-2782 Prevent duplicate HMRC requests
  app/services/hmrc/create_responses_service.rb
  spec/services/hmrc/create_responses_service_spec.rb
Labels: Ready for review

#3209 bugfix: always show employment section
  app/views/providers/means_summaries/show.html.erb
Labels: Approved
