Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2021-06, with the labels that each got.

#2562 AP-2267 BugFix - Update predwp check to be more accurate
  app/models/concerns/base_state_machine.rb
  app/models/legal_aid_application.rb
  spec/mailers/feedback_mailer_spec.rb
Labels: Approved, UAT Success

#2586 AP-2276 Add migration to remove two columns from ChancesOfSuccess
  db/migrate/20210602110352_remove_legal_aid_application_association_from_chances_of_success.rb
  db/migrate/20210602114709_remove_submitted_at_from_chances_of_success.rb
  db/schema.rb
Labels: Approved

#2560 AP-2097 Admin report cron job
  README.md
  app/controllers/admin/reports_controller.rb
  app/jobs/reports_uploader_job.rb
  app/models/admin_report.rb
  db/anonymise/rules.rb
  db/migrate/20210518114357_admin_reports.rb
  db/schema.rb
  helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
  lib/tasks/jobs/create_admin_reports.rake
  spec/factories/admin_report.rb
  spec/jobs/reports_uploader_job_spec.rb
  spec/requests/admin/reports_spec.rb
Labels: Approved, UAT Success

#2583 Add example multi-proc payloads
  ccms_integration/example_payloads/multi_proc/NonPassportedMultiProc.xml
  ccms_integration/example_payloads/multi_proc/PassportedMultiProc.xml
Labels: ready for review

#2590 AP-2294 linked children update
  app/controllers/concerns/providers/draftable.rb
  app/controllers/providers/proceeding_merits_task/linked_children_controller.rb
  app/forms/providers/proceeding_merits_task/linked_children_form.rb
  app/models/application_merits_task/involved_child.rb
  app/models/application_proceeding_type.rb
  app/models/proceeding_merits_task/application_proceeding_type_linked_child.rb
  app/services/flow/flows/provider_merits.rb
  app/views/providers/proceeding_merits_task/linked_children/show.html.erb
  config/locales/en/providers.yml
  db/anonymise/rules.rb
  db/migrate/20210601084320_rename_apt_involved_children_to_apt_linked_children.rb
  db/schema.rb
  features/providers/merits_task_list.feature
  features/step_definitions/civil_journey_steps.rb
  features/support/steps_helper.rb
  spec/factories/proceeding_merits_task/application_proceeding_type_involved_children.rb
  spec/factories/proceeding_merits_task/application_proceeding_type_linked_children.rb
  spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb
  spec/helpers/providers_helper_spec.rb
  spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
Labels: Approved

#2589 AP-2282 update spacing on clients bank accounts page
  app/views/providers/applicant_bank_accounts/show.html.erb
Labels: Approved, UAT

#2599 add full stops to hint text
  app/views/providers/dependants/_form.html.erb
  config/locales/cy/citizens.yml
  config/locales/cy/generic.yml
  config/locales/cy/helpers.yml
  config/locales/cy/shared.yml
  config/locales/en/citizens.yml
  config/locales/en/generic.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
Labels: Approved, UAT

#2602 Tech-Debt: remove yarn warnings
  package.json
  yarn.lock
Labels: Approved

#2598 AP-2330 Add PASSPORTED_NINO attribute to passported payloads
  config/ccms/attribute_block_configs/base.yml
  config/ccms/attribute_block_configs/non_passported.yml
  spec/data/ccms/case_add_request.xml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: Approved

#2603 Update tag text in transactions table
  app/helpers/transaction_type_helper.rb
  config/locales/en/activemodel.yml
Labels: Approved, UAT

#2581 AP-2290 Assign first domestic abuse proceeding as lead
  app/controllers/providers/has_other_proceedings_controller.rb
  app/forms/base_form.rb
  app/forms/legal_aid_applications/has_other_proceedings_form.rb
  app/models/application_proceeding_type.rb
  app/models/legal_aid_application.rb
  app/models/proceeding_type.rb
  app/services/lead_proceeding_assignment_service.rb
  app/services/legal_framework/proceeding_types_service.rb
  config/locales/en/activerecord.yml
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/proceeding_types.rb
  spec/factory_specs/legal_aid_application_factory_spec.rb
  spec/models/application_proceeding_type_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/proceeding_type_spec.rb
  spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
  spec/requests/providers/application_merits_task/opponents_spec.rb
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/merits_reports_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
  spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
  spec/requests/providers/proceedings_types_spec.rb
  spec/requests/providers/submitted_applications_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/lead_proceeding_assignment_service_spec.rb
  spec/services/reports/merits_report_creator_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
  spec/services/reports/mis/application_details_report_spec.rb
Labels: Approved

#2608 AP-2328 Add new ccms attribute to check passported or not
  config/ccms/attribute_block_configs/base.yml
  config/ccms/attribute_block_configs/non_passported.yml
  spec/data/ccms/case_add_request.xml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: Approved, UAT

#2613 Ap-2300 Add example multi-children XML and commentary
  ccms_integration/example_payloads/multi_proc/MP_1333535_PP_multi children.xml
  ccms_integration/example_payloads/multi_proc/MP_1333536_1333535_commentary.pdf
  ccms_integration/example_payloads/multi_proc/MP_1333536_NP_multi children.xml
Labels: ready for review

#2607 AP-2339: Update submitted application view
  app/views/providers/submitted_applications/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/locales/en/providers.yml
Labels: Approved, UAT

#2623 added cucumber feature test
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant/I_am_able_to_create_a_passported_application_with_Cap_Contribs_3k_and_with_restrictions.yml
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant/I_am_able_to_create_a_passported_application_without_Cap_Contribs_and_with_no_restrictions.yml
  features/providers/check_ccms_autogrant.feature
  features/step_definitions/ccms_auto_grant_steps.rb
  features/step_definitions/civil_journey_steps.rb
Labels: Approved

#2622 Ap 2301 remove proceeding before court
  app/controllers/providers/proceedings_before_the_courts_controller.rb
  app/forms/chances_of_successes/proceedings_before_the_court_form.rb
  app/services/flow/flows/provider_merits.rb
  app/services/reports/mis/application_detail_csv_line.rb
  app/views/providers/proceedings_before_the_courts/show.html.erb
  app/views/shared/check_answers/_merits_orig.html.erb
  config/locales/cy/activemodel.yml
  config/locales/cy/helpers.yml
  config/locales/en/activemodel.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/migrate/20210616092032_remove_proceeding_before_the_courts_from_chances_of_successes.rb
  db/schema.rb
  spec/factories/chances_of_successes.rb
  spec/requests/providers/proceedings_before_the_court_spec.rb
Labels: Approved

#2612 AP-2344 Include gateway evidence documents to ccms upload
  app/services/ccms/requestors/document_id_requestor.rb
  app/services/ccms/requestors/document_upload_requestor.rb
  app/services/ccms/submitters/obtain_document_id_service.rb
  spec/services/ccms/requestors/document_upload_requestor_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
Labels: Approved, UAT Success

#2609 AP-2349 Add extra logic around task completion for chances of success
  app/controllers/providers/proceeding_merits_task/chances_of_success_controller.rb
  spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
Labels: UAT

#2626 AP-2268 update button styling
  app/views/providers/application_merits_task/statement_of_cases/show.html.erb
Labels: Approved, UAT

#2617 AP-2331 Non-passported dependant child attributes in CCMS payload
  app/models/dependant.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/ccms/requestors/non_passported_case_add_requestor.rb
  config/ccms/attribute_block_configs/non_passported.yml
  config/ccms/means_entity_configs/non_passported.yml
  spec/factories/dependants.rb
  spec/factories/legal_aid_applications.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
  spec/support/xml_extractor.rb
Labels: Approved, UAT

#2632 AP-2359: Reduce Dashboard::UpdaterJob calls to geckoboard
  app/services/dashboard_event_handler.rb
  spec/services/dashboard_event_handler_spec.rb
Labels: Approved

#2633 Remove ModSecurity for UAT
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: ready for review

#2618 AP-2283 client bank accounts
  app/controllers/providers/applicant_bank_accounts_controller.rb
  app/controllers/providers/offline_savings_accounts_controller.rb
  app/forms/savings_amounts/offline_savings_accounts_form.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/applicant_bank_accounts/show.html.erb
  app/views/providers/check_passported_answers/show.html.erb
  app/views/providers/means_summaries/show.html.erb
  app/views/providers/offline_savings_accounts/show.html.erb
  app/views/providers/submitted_applications/show.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_offline_savings_accounts.html.erb
  app/views/shared/check_answers/_property.html.erb
  config/locales/cy/shared.yml
  config/locales/en/errors.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  features/accessibility/provider.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  spec/requests/providers/applicant_bank_accounts_spec.rb
  spec/requests/providers/offline_savings_accounts_spec.rb
Labels: Approved, UAT

#2636 AP-2372: BugFix for DF and DWP override routing issue
  app/models/legal_aid_application.rb
  spec/factories/dwp_overrides.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/substantive_applications_spec.rb
Labels: Approved, UAT

#2627 AP-2360 Remove trailing whitespaces for Applicant and Dependant
  app/forms/applicants/basic_details_form.rb
  app/forms/base_form.rb
  app/forms/legal_aid_applications/dependant_form.rb
  app/forms/opponents/opponent_form.rb
  app/forms/providers/application_merits_task/involved_child_form.rb
  lib/tasks/clean_whitespaces.rake
  spec/requests/providers/applicant_details_spec.rb
  spec/requests/providers/application_merits_task/involved_children_spec.rb
  spec/requests/providers/application_merits_task/opponents_spec.rb
  spec/requests/providers/dependants_controller_spec.rb
Labels: Approved, UAT Success

#2637 AP-2371 Use STAGING environment on CCMS
  db/seeds/test_provider_populator.rb
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: Approved

#2638 Fix Rake Job for cleaning whitespaces
  lib/tasks/clean_whitespaces.rake
Labels: Approved

#2645 BugFix - Create admin report when none exists
  app/controllers/admin/reports_controller.rb
Labels: ready for review

#2646 BugFix Separate flickering test for multiple used delegated functions
  spec/requests/providers/used_multiple_delegated_functions_spec.rb
Labels: Approved

#2611 AP-2159 Add new result panels and selection options
  app/controllers/providers/capital_assessment_results_controller.rb
  app/controllers/providers/capital_income_assessment_results_controller.rb
  app/services/results_panel_selector.rb
  app/views/shared/assessment_results/_partially_eligible_capital.html.erb
  app/views/shared/assessment_results/_partially_eligible_capital_income.html.erb
  app/views/shared/assessment_results/_partially_eligible_income.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  spec/factories/cfe_results/v4/mock_results.rb
  spec/factories/cfe_results/v4/results.rb
  spec/services/results_panel_selector_spec.rb
Labels: Approved, UAT

#2654 Bugfix: test that falls over if proc types in wrong order
  spec/services/legal_framework/proceeding_types_service_spec.rb
Labels: Approved

#2652 BugFix: Address flickering tests
  spec/requests/providers/applicant_bank_accounts_spec.rb
Labels: Approved

#2661 BugFix: Flickering Multiple DF dates
  spec/requests/providers/used_multiple_delegated_functions_spec.rb
Labels: Approved

#2650 AP-2366: Update FeedbackMailer
  app/mailers/feedback_mailer.rb
  spec/mailers/feedback_mailer_spec.rb
Labels: Approved, UAT

#2624 AP-2326: Ensure some blocks are omitted from passported XML
  app/services/ccms/attribute_value_generator.rb
  config/ccms/attribute_block_configs/base.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/support/xml_extractor.rb
Labels: Approved

#2656 Ap-2334 add NP CCMS attribute
  config/ccms/attribute_block_configs/non_passported.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
Labels: Approved, UAT

#2655 AP-2275 Remove obsolete routes in config/routes.rb
  config/routes.rb
Labels: Approved, UAT Success

#2671 BugFix File uploads / Attachment creation errors for multiple attachments
  app/services/pdf_converter.rb
  spec/services/pdf_converter_spec.rb
Labels: Approved, UAT Success

#2625 AP-2329 Add CHILD_PARTIES_C attribute for each proceeding
  app/models/proceeding_type.rb
  config/ccms/attribute_block_configs/base.yml
  spec/data/ccms/case_add_request.xml
  spec/data/ccms/mp_case_add_request.xml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/legal_framework/proceeding_types_service_spec.rb
Labels: Approved

#2651 AP-2321 Show uploaded files names on check answers page
  app/forms/providers/gateway_evidence_form.rb
  app/forms/statement_of_cases/statement_of_case_form.rb
  app/helpers/attachments_helper.rb
  app/views/providers/check_merits_answers/show.html.erb
  app/views/providers/gateway_evidences/show.html.erb
  app/views/providers/submitted_applications/show.html.erb
  app/views/shared/check_answers/_item.html.erb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/check_answers/_merits_orig.html.erb
  app/views/shared/check_answers/_no_link_item.html.erb
  db/migrate/20210621100811_add_original_filename_to_attachments.rb
  db/schema.rb
  features/providers/civil_application_journey.feature
  features/providers/multi_proceedings.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/gateway_evidences.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/statement_of_cases.rb
  spec/helpers/attachments_helper_spec.rb
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
  spec/requests/providers/gateway_evidence_spec.rb
Labels: Approved, UAT Success

#2630 AP-2291 remove back link if there are no proceedings
  app/services/flow/flows/provider_start.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/proceedings_types/index.html.erb
  app/webpack/src/modules/proceedings.js
  features/providers/pathways_from_check_your_answers.feature
  features/step_definitions/civil_journey_steps.rb
Labels: Approved, UAT

#2629 Ap 2324 ccms false passported
  config/ccms/attribute_block_configs/base.yml
  spec/data/ccms/case_add_request.xml
  spec/data/ccms/mp_case_add_request.xml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: Approved, UAT

#2681 BugFix Allow for existing attachments with no original filenames
  app/helpers/attachments_helper.rb
  spec/helpers/attachments_helper_spec.rb
Labels: Approved
