Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2021-07, with the labels that each got.

#2668 BugFix: Address BigDecimal rounding issues
  spec/requests/providers/applicant_bank_accounts_spec.rb
  spec/services/true_layer/bank_data_import_service_spec.rb
Labels: Approved

#2643 AP-2356: Always create task list
  app/controllers/providers/capital_assessment_results_controller.rb
  spec/requests/providers/capital_assessment_results_spec.rb
Labels: Approved

#2667 Update button text
  app/views/citizens/banks/index.html.erb
  app/views/citizens/consents/show.html.erb
  features/accessibility/citizen.feature
  features/citizens/citizens.feature
  features/citizens/citizens_welsh.feature
Labels: Approved, UAT

#2670 AP-2335 add omitted attributes and tests for Non passported
  config/ccms/attribute_block_configs/non_passported.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
Labels: Approved, UAT

#2685 Tech debt/fix chance of success routing flicker
  spec/factories/legal_aid_applications.rb
Labels: ready for review

#2680 AP-2336 add childcare boolean attribute
  config/ccms/attribute_block_configs/non_passported.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
Labels: Approved, UAT

#2647 AP-2370 Include results by proceeding type on Means report
  app/models/cfe/base_result.rb
  app/models/cfe/v4/result.rb
  app/services/ccms/attribute_value_generator.rb
  app/views/providers/means_reports/show.html.erb
  app/views/shared/check_answers/_income_result.html.erb
  app/views/shared/check_answers/_offline_savings_accounts.html.erb
  app/views/shared/means_report/_proceeding_eligibility.html.erb
  config/locales/en/providers.yml
  db/schema.rb
  spec/factories/cfe_results/v4/mock_results.rb
  spec/factories/cfe_results/v4/results.rb
  spec/models/cfe/v4/result_spec.rb
  spec/services/reports/means_report_creator_spec.rb
Labels: Approved

#2682 AP-2298 display all labels
  app/helpers/capital_helper.rb
  app/helpers/policy_disregards_helper.rb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_no_link_item.html.erb
  app/views/shared/check_answers/_one_link_section.html.erb
  config/locales/en/shared.yml
  features/providers/check_your_answers.feature
  features/providers/civil_application_journey.feature
  features/providers/complete_and_check_means_answers.feature
  features/step_definitions/civil_journey_steps.rb
  spec/helpers/policy_disregards_helper_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
Labels: Approved, On Hold, UAT

#2669 CCMS payload YAMLizer
  bin/yamlizer
  ccms_integration/example_payloads/multi_proc/MP_1333535_PP_multi children.yml
  ccms_integration/example_payloads/multi_proc/MP_1333536_NP_multi children.yml
  lib/tasks/helpers/ccms_payload_yamlizer.rb
  spec/lib/task_helpers/ccms_payload_yamlizer_spec.rb
Labels: Approved

#2694 Update declaration to explain statutory charge
  config/locales/en/providers.yml
  config/locales/en/shared.yml
Labels: Approved, UAT

#2693 Update content on already shared financial info page
  config/locales/en/errors.yml
  spec/requests/errors_spec.rb
Labels: Approved, UAT

#2692 AP-2337 add omitted CCMS attrs for non passported
  config/ccms/attribute_block_configs/non_passported.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
Labels: Approved, UAT

#2691 AP-2384 Allow for missing gateway evidence in merits report
  app/views/providers/means_reports/show.html.erb
  app/views/providers/merits_reports/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  features/providers/multi_proceedings.feature
  features/step_definitions/civil_journey_steps.rb
Labels: Approved, UAT

#2704 AP-2112 Bank account balance when there are no trasactions
  app/models/bank_account.rb
  app/models/irregular_income.rb
  app/models/legal_aid_application.rb
  app/views/providers/submitted_applications/_irregular_incomes_table.html.erb
  app/views/providers/submitted_applications/show.html.erb
  app/views/shared/check_answers/_bank_transaction_table.html.erb
  config/locales/en/providers.yml
  spec/models/bank_account_spec.rb
  spec/models/irregular_income_spec.rb
  spec/models/legal_aid_application_spec.rb
Labels: Approved, UAT

#2695 AP-2333 Dependant attributes
  app/models/dependant.rb
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/ccms/requestors/non_passported_case_add_requestor.rb
  config/ccms/attribute_block_configs/non_passported.yml
  config/ccms/means_entity_configs/non_passported.yml
  spec/models/dependant_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
Labels: Approved, UAT

#2697 AP-2382 Include all income and outgoings in certificate
  app/views/providers/submitted_applications/_irregular_incomes_table.html.erb
Labels: Approved, UAT

#2720 AP-2390 update cost limit error message
  config/locales/en/activemodel.yml
Labels: Approved, UAT

#2679 AP-2161 CCMS submission retries
  app/services/ccms/ccms_error.rb
  app/services/ccms/submitters/add_applicant_service.rb
  app/services/ccms/submitters/add_case_service.rb
  app/services/ccms/submitters/base_submission_service.rb
  app/services/ccms/submitters/check_applicant_status_service.rb
  app/services/ccms/submitters/check_case_status_service.rb
  app/services/ccms/submitters/obtain_applicant_reference_service.rb
  app/services/ccms/submitters/obtain_case_reference_service.rb
  app/services/ccms/submitters/obtain_document_id_service.rb
  app/services/ccms/submitters/upload_documents_service.rb
  app/services/reports/base_report_creator.rb
  app/workers/ccms/submission_process_worker.rb
  config/initializers/sidekiq_middleware.rb
  spec/services/ccms/submitters/add_applicant_service_spec.rb
  spec/services/ccms/submitters/add_case_service_spec.rb
  spec/services/ccms/submitters/check_applicant_status_service_spec.rb
  spec/services/ccms/submitters/check_case_status_service_spec.rb
  spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
  spec/services/ccms/submitters/obtain_case_reference_service_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
  spec/services/ccms/submitters/upload_documents_service_spec.rb
  spec/services/reports/bank_transactions/bank_transaction_report_creator_spec.rb
  spec/services/reports/means_report_creator_spec.rb
  spec/services/reports/merits_report_creator_spec.rb
  spec/workers/ccms/submission_process_worker_spec.rb
Labels: Approved, UAT

#2724 Tech debt/rubocop fix
  .rubocop.yml
  spec/helpers/hash_format_helper_spec.rb
Labels: ready for review

#2711 AP-2358 fix checkbox deselect bug
  app/webpack/src/checkbox_control.js
Labels: Approved, UAT

#2700 Ap 2376 review cucumber tests
  features/accessibility/provider.feature
  features/cassettes/Civil_application_journeys/I_want_to_change_client_details_after_a_failed_benefit_check.yml
  features/cassettes/Civil_application_journeys/Receives_benefits_and_completes_the_application_happy_path_no_back_button.yml
  features/cassettes/Provider_journey_using_the_back_button/I_want_to_return_to_check_your_answers_from_address_select.yml
  features/cassettes/Provider_journey_using_the_back_button/Tests_the_back_button_across_multiple_pages.yml
  features/providers/back_button.feature
  features/providers/civil_application_journey.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
Labels: Approved

#2715 AP-2411 update DF dates error messages
  app/forms/legal_aid_applications/used_delegated_functions_form.rb
  app/forms/legal_aid_applications/used_multiple_delegated_functions_form.rb
  config/locales/en/activemodel.yml
  spec/forms/legal_aid_applications/used_delegated_functions_form_spec.rb
  spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb
  spec/requests/providers/used_delegated_functions_spec.rb
  spec/requests/providers/used_multiple_delegated_functions_spec.rb
Labels: Approved, UAT

#2722 AP-2392 link error to radio buttons
  app/forms/legal_aid_applications/has_other_proceedings_form.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
Labels: Approved, UAT

#2126 AP-2155: Ruby-3 update
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  app/models/dashboard/widget_data_providers/applications.rb
  app/models/dashboard/widget_data_providers/number_provider_firms.rb
  app/models/dashboard/widget_data_providers/pending_ccms_submissions.rb
  app/models/dashboard/widget_data_providers/percentage_declined_open_banking.rb
  app/services/banking/bank_transaction_balance_calculator.rb
  app/services/cfe/create_assessment_service.rb
  features/support/env.rb
Labels: Approved, UAT

#2721 AP-2306: Remove deprecation warnings
  config/initializers/omniauth.rb
Labels: Approved, UAT Success

#2710 AP-2273 cash transactions none of the above
  app/controllers/citizens/cash_incomes_controller.rb
  app/controllers/citizens/cash_outgoings_controller.rb
  app/models/cash_transaction.rb
  app/views/citizens/cash_incomes/_cash_income_form.html.erb
  app/views/citizens/cash_outgoings/_cash_outgoings_form.html.erb
  app/views/shared/forms/_types_of_outgoings_form.html.erb
  db/migrate/20210712112003_add_no_cash_income_and_outgoings.rb
  db/schema.rb
  spec/requests/citizens/cash_incomes_spec.rb
  spec/requests/citizens/cash_outgoings_spec.rb
Labels: Approved, UAT

#2731 Bug-fix: Geckoboard fix
  app/models/dashboard/single_object/applicant_email.rb
  app/models/dashboard/single_object/feedback.rb
  app/models/dashboard/single_object/provider_data.rb
  app/models/dashboard/widget.rb
  app/models/dashboard/widget_data_providers/applications.rb
  app/models/dashboard/widget_data_providers/number_provider_firms.rb
  app/models/dashboard/widget_data_providers/pending_ccms_submissions.rb
  app/models/dashboard/widget_data_providers/percentage_declined_open_banking.rb
Labels: Approved

#2719 AP-2397 update content on confirm DF page
  app/controllers/providers/confirm_multiple_delegated_functions_controller.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/confirm_multiple_delegated_functions/show.html.erb
  config/locales/en/providers.yml
  features/providers/civil_application_journey.feature
  features/providers/pathways_from_check_your_answers.feature
Labels: Approved, UAT

#2730 Ap 2398 back link dwp override
  app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
  features/providers/pathways_from_check_your_answers.feature
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
Labels: Approved

#2734 AP-2400 DWP abbreviation
  app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
  config/locales/en/providers.yml
Labels: Approved, UAT

#2726 AP-2412: CCMS submission on/off setting
  .circleci/config.yml
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/concerns/base_state_machine.rb
  app/models/concerns/non_passported_state_machine.rb
  app/models/concerns/passported_state_machine.rb
  app/models/legal_aid_application.rb
  app/models/setting.rb
  app/services/ccms_restart_submissions.rb
  app/services/enable_ccms_submission.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  config/locales/en/model_enum_translations.yml
  db/migrate/20210720115125_add_enable_ccms_submission_to_setting.rb
  db/schema.rb
  lib/tasks/restart_ccms_submissions.rake
  lib/tasks/setup_db_for_testing.rake
  spec/factories/legal_aid_applications.rb
  spec/models/setting_spec.rb
  spec/services/ccms_restart_submissions_spec.rb
  spec/services/enable_ccms_submission_spec.rb
  spec/services/reports/reports_creator_spec.rb
Labels: Approved, UAT

#2727 AP-2402 Remove abbr tags from page titles
  app/views/citizens/consents/show.html.erb
  app/views/providers/use_ccms/show.html.erb
  app/views/providers/use_ccms_employed/index.html.erb
  config/locales/cy/citizens.yml
  config/locales/en/citizens.yml
  config/locales/en/providers.yml
Labels: Approved, Ready for review, UAT

#2733 AP-2403 update tag styles
  app/helpers/tag_helper.rb
  app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
  app/webpack/stylesheets/application.scss
  app/webpack/stylesheets/tags.scss
Labels: Approved, UAT

#2723 AP-2406 application detail report
  app/models/application_proceeding_type.rb
  app/models/cfe/base_result.rb
  app/models/dependant.rb
  app/models/legal_aid_application.rb
  app/services/reports/mis/application_detail_csv_line.rb
  features/providers/civil_application_journey.feature
  lib/tasks/mp_pop.rake
  spec/factory_specs/legal_aid_application_factory_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/services/legal_framework/proceeding_types_service_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: Ready to merge

#2735 AP-2405 update font size of radio button labels
  app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
  app/webpack/stylesheets/interruption-panel.scss
Labels: Ready to merge

#2743 Tech-Debt: Flickering numbers
  app/services/true_layer/importers/import_account_balance_service.rb
Labels: Ready for review

#2744 Fix: Trailing erb close after merge
  app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
Labels: Ready for review

#2752 Fix: More decimal failures
  spec/factories/bank_accounts.rb
Labels: Ready for review

#2751 Fix: The overnight update job rake task
  helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
  lib/tasks/jobs/dashboard_updater.rake
Labels: Ready for review

#2736 Ap 2391 proceeding type search
  app/services/proceeding_type_full_text_search.rb
  db/seeds/legal_framework/proceeding_types.csv
  features/providers/civil_application_journey.feature
  spec/services/proceeding_type_full_text_search_spec.rb
Labels: Approved

#2753 AP-2433 stop text in tag from wrapping
  app/helpers/tag_helper.rb
Labels: Approved, UAT

#2653 Ap 2367 implement cost override
  app/controllers/providers/limitations_controller.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/limitations/_legacy_proceeding_types.html.erb
  app/views/shared/check_answers/_emergency_costs.html.erb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/check_answers/_merits_orig.html.erb
  config/locales/en/shared.yml
  features/providers/civil_application_journey.feature
  spec/requests/providers/limitations_spec.rb
Labels: On Hold, Ready to merge
