Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2021-11, with the labels that each got.

#2985 Update Dependabot
  .github/dependabot.yml
Labels: Approved

#3008 Manual update of multiple gems
  Gemfile.lock
Labels: Approved

#2992 Update content
  config/locales/en/providers.yml
  features/providers/non_passported_journey.feature
Labels: UAT, Approved

#2988 Amend heading on client start page
  config/locales/en/citizens.yml
Labels: UAT, Approved

#2987 AP-2615 LegalAidApplication - use Proceeding
  app/models/legal_aid_application.rb
  app/models/proceeding.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/proceedings.rb
  spec/factory_specs/legal_aid_application_factory_spec.rb
  spec/models/legal_aid_application_spec.rb
Labels: Approved

#3011 AP-2603 Add digest_extracted_at field to Settings
  db/migrate/20211102100659_add_digest_extracted_at_to_settings.rb
  db/schema.rb
Labels: Approved

#3013 AP-2642 Fix Scope Limitations bug in XML payload
  app/models/application_proceeding_type.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/requestors/case_add_requestor.rb
  spec/data/ccms/mp_df_case_add_request.xml
  spec/models/application_proceeding_type_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
Labels: UAT, Approved

#3023 Add test coverage for invalid uploaded file header 🇧🇷
  app/controllers/concerns/providers/application_dependable.rb
  spec/requests/providers/gateway_evidence_spec.rb
Labels: Approved

#2991 AP-2623 Use Proceeding model in ApplicationHelper
  app/helpers/application_helper.rb
  app/views/shared/check_answers/_merits.html.erb
Labels: UAT, Approved

#2990 AP-2593 Use Proceeding in ApplicationsDetailsCSVLine
  app/models/application_proceeding_type.rb
  app/models/proceeding.rb
  app/services/reports/mis/application_detail_csv_line.rb
  spec/factories/legal_aid_applications.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: UAT, Approved

#3021 AP-2535 fix table sort arrows
  app/helpers/table_sort_helper.rb
  app/webpack/stylesheets/table-sort.scss
Labels: UAT, Approved

#3020 AP-2648 Add Extra fields to Proceeding table
  app/models/proceeding.rb
  app/services/proceeding_sync_service.rb
  db/data/20211103105816_populate_extra_proceedings_fields.rb
  db/data_schema.rb
  db/migrate/20211103105546_add_extra_fields_to_proceedings.rb
  db/migrate/20211103112548_set_new_proceeding_fields_to_not_null.rb
  db/schema.rb
  spec/factories/proceedings.rb
Labels: UAT, Approved

#2986 AP-2599: Call HMRC Interface
  app/controllers/providers/applicant_employed_controller.rb
  app/helpers/hash_format_helper.rb
  app/lib/hmrc/interface_error.rb
  app/lib/sidekiq/exhausted_failure_message.rb
  app/lib/sidekiq/in_progress_warning_message.rb
  app/models/applicant.rb
  app/models/hmrc/response.rb
  app/models/legal_aid_application.rb
  app/services/hmrc/create_responses_service.rb
  app/services/hmrc/interface/base_service.rb
  app/services/hmrc/interface/result_service.rb
  app/services/hmrc/interface/submission_service.rb
  app/services/hmrc/sentry_ignore_this_sidekiq_fail_error.rb
  app/views/admin/legal_aid_applications/submissions/show.html.erb
  app/workers/ccms/submission_process_worker.rb
  app/workers/hmrc/base_worker.rb
  app/workers/hmrc/result_worker.rb
  app/workers/hmrc/submission_worker.rb
  config/initializers/sentry.rb
  db/migrate/20211105083833_update_hmrc_responses.rb
  db/schema.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/factories/hmrc/response.rb
  spec/helpers/hash_format_helper_spec.rb
  spec/models/applicant_spec.rb
  spec/models/hmrc/response_spec.rb
  spec/requests/providers/applicant_employed_spec.rb
  spec/services/hmrc/create_responses_service_spec.rb
  spec/services/hmrc/interface/result_service_spec.rb
  spec/services/hmrc/interface/submission_service_spec.rb
  spec/workers/hmrc/result_worker_spec.rb
  spec/workers/hmrc/submission_worker_spec.rb
Labels: UAT, Approved

#3028 AP-2609 Mark purgeable service
  app/services/mark_purgeable_service.rb
  db/migrate/20211104141141_add_purgeable_tolegal_aid_applications.rb
  db/schema.rb
  helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
  lib/tasks/purge.rake
  spec/services/mark_purgeable_service_spec.rb
Labels: Approved

#3019 AP-2618 Use Proceedings on Limitations views
  app/views/providers/limitations/_proceeding_type.html.erb
  app/views/providers/limitations/_proceeding_types.html.erb
  app/views/providers/limitations/_proceeding_types_with_df.html.erb
  features/accessibility/provider.feature
  features/providers/civil_application_journey.feature
  features/providers/merits_task_list.feature
  features/step_definitions/debug_steps.rb
Labels: Approved

#3027 FIX: Update tests
  app/views/shared/check_answers/_substantive_limitations.html.erb
Labels: Approved

#3022 Ap 2619 convert merits tasks flow to use proceeding
  app/controllers/providers/proceeding_merits_task/attempts_to_settle_controller.rb
  app/controllers/providers/proceeding_merits_task/chances_of_success_controller.rb
  app/controllers/providers/proceeding_merits_task/linked_children_controller.rb
  app/controllers/providers/proceeding_merits_task/success_prospects_controller.rb
  app/helpers/task_list_helper.rb
  app/models/proceeding.rb
  app/services/flow/flows/provider_merits.rb
  app/views/providers/proceeding_merits_task/attempts_to_settle/show.html.erb
  app/views/providers/proceeding_merits_task/chances_of_success/index.html.erb
  app/views/providers/proceeding_merits_task/linked_children/show.html.erb
  app/views/providers/proceeding_merits_task/success_prospects/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  features/providers/merits_task_list.feature
  features/step_definitions/civil_journey_steps.rb
  spec/helpers/providers_helper_spec.rb
  spec/helpers/task_list_helper_spec.rb
  spec/models/proceeding_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
  spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
  spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb
Labels: Approved

#3042 AP-2669 add new annotations for deployment
  bin/uat_deploy
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: Approved

#3050 AP-2643: Update CircleCI images
  .circleci/config.yml
Labels: Ready for review

#3034 Ap 2624 xml payload
  app/controllers/providers/check_passported_answers_controller.rb
  app/controllers/providers/submitted_applications_controller.rb
  app/models/concerns/delegated_functions.rb
  app/models/legal_aid_application.rb
  app/models/proceeding.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/proceeding_sync_service.rb
  app/views/providers/limitations/show.html.erb
  app/views/providers/submitted_applications/show.html.erb
  app/views/shared/check_answers/_delegated_functions.html.erb
  app/views/shared/check_answers/_proceedings_details.html.erb
  app/views/shared/check_answers/_substantive_limitations.html.erb
  config/ccms/attribute_block_configs/base.yml
  config/ccms/attribute_block_configs/non_passported.yml
  db/migrate/20211103151811_add_ccms_matter_code_to_proceedings.rb
  db/schema.rb
  features/cassettes/Pathways_from_check_your_answers/I_go_back_and_change_the_proceedings_on_an_application_with_multiple_proceedings.yml
  features/providers/civil_application_journey.feature
  features/providers/emergency_cost_override.feature
  features/providers/pathways_from_check_your_answers.feature
  features/step_definitions/civil_journey_steps.rb
  features/step_definitions/debug_steps.rb
  spec/data/ccms/mp_case_add_request.xml
  spec/data/ccms/mp_df_case_add_request.xml
  spec/factories/legal_aid_applications.rb
  spec/factories/proceedings.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/proceeding_spec.rb
  spec/rails_helper.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
  spec/requests/providers/limitations_spec.rb
  spec/requests/providers/submitted_applications_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_benefits_attrs_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/ccms/submitters/add_case_service_spec.rb
Labels: UAT, Approved

#3058 add test for method only used in CCMS tests
  app/models/concerns/delegated_functions.rb
  spec/models/legal_aid_application_spec.rb
Labels: Approved

#2823 Tech-Debt: Remove sidekiq alive
  Gemfile
  Gemfile.lock
  bin/sidekiq_health_check
  helm_deploy/apply-for-legal-aid/templates/deployment_worker.yaml
Labels: Ready for review

#3059 migartion to add ccms_matter_cocde to existing proceedings
  db/data/20211112125241_add_ccms_matter_code_to_proccedings.rb
  db/data_schema.rb
Labels: Ready for review

#2989 AP-2616 Merit report to use Proceeding
  app/controllers/providers/merits_reports_controller.rb
  app/models/application_proceeding_type.rb
  app/models/proceeding_merits_task/chances_of_success.rb
  app/views/providers/merits_reports/show.html.erb
  app/views/shared/check_answers/_delegated_functions.html.erb
  features/providers/civil_application_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/factory_helpers/application_proceeding_type_helper.rb
  spec/requests/providers/check_provider_answers_spec.rb
Labels: UAT, Approved

#3010 AP-2617 Use Proceedings in shared CYA partials
  app/views/shared/check_answers/_emergency_limitations.html.erb
Labels: UAT, Approved

#3051 AP-2622 Remove unneeded SubmittedApplication code
  app/controllers/providers/submitted_applications_controller.rb
  app/views/providers/submitted_applications/show.html.erb
Labels: UAT, Approved

#3052 AP-2627 Remove unused CheckMeritsAnswers code
  app/controllers/providers/check_merits_answers_controller.rb
  app/views/providers/check_merits_answers/show.html.erb
Labels: UAT, Approved

#3061 AP-2626 Create new proceeding removal service
  app/controllers/providers/has_other_proceedings_controller.rb
  app/models/application_proceeding_type.rb
  app/models/proceeding.rb
  app/services/lead_proceeding_assignment_service.rb
  app/services/legal_framework/lead_application_proceeding_type_assignment_service.rb
  app/services/legal_framework/lead_proceeding_assignment_service.rb
  app/services/legal_framework/proceeding_types_service.rb
  app/services/legal_framework/remove_proceeding_service.rb
  app/services/proceeding_sync_service.rb
  app/views/providers/has_other_proceedings/show.html.erb
  features/providers/civil_application_journey.feature
  features/step_definitions/debug_steps.rb
  features/support/env.rb
  spec/models/application_proceeding_type_spec.rb
  spec/rails_helper.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/proceedings_types_spec.rb
  spec/services/lead_proceeding_assignment_service_spec.rb
  spec/services/legal_framework/lead_application_proceeding_type_assignment_service_spec.rb
  spec/services/legal_framework/lead_proceeding_assignment_service_spec.rb
  spec/services/proceeding_sync_service_spec.rb
Labels: UAT, Approved

#3026 AP-2607 Extract applications to digest
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/models/application_digest.rb
  app/models/proceeding.rb
  app/services/digest_exporter.rb
  app/services/digest_extractor.rb
  app/services/working_day_calculator.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  db/schema.rb
  helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
  lib/tasks/digest.rake
  spec/cassettes/ApplicationDigest/create_or_update/delegated_functions/delegated_functions_used/returns_true_and_dates.yml
  spec/factories/application_digests.rb
  spec/factories/legal_aid_applications.rb
  spec/models/application_digest_spec.rb
  spec/models/proceeding_spec.rb
  spec/rails_helper.rb
  spec/services/digest_exporter_spec.rb
  spec/services/digest_extractor_spec.rb
Labels: UAT, Approved

#3066 AP-2636 Add feature flag for employed journeys
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  db/migrate/20211112174848_add_employed_journey_flag_to_settings.rb
  db/schema.rb
  lib/tasks/setup_db_for_testing.rake
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
Labels: UAT, Approved

#3068 AP-2591 Amend label content on assets page
  config/locales/en/providers.yml
  config/locales/en/shared.yml
Labels: UAT, Approved

#3065 AP-2583: Update `financial` typo
  config/locales/cy/shared.yml
  config/locales/en/shared.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: Approved

#3067 Tech debt: Update YAML.safe_load instantiation pattern
  app/models/legal_framework/serializable_merits_task_list.rb
  app/services/metrics/sidekiq_queue_sizes.rb
Labels: Approved

#3078 AP-2396 Update emergency cost override CYA wording
  config/locales/en/shared.yml
Labels: UAT, Approved

#3082 Fix: Gemfile.lock platforms
  Gemfile.lock
Labels: Ready for review

#3081 AP-2598: Update student finance content
  app/views/providers/income_summary/index.html.erb
  app/views/providers/means_summaries/show.html.erb
  app/views/providers/no_income_summaries/show.html.erb
  config/locales/en/providers.yml
  features/providers/non_passported_journey.feature
Labels: Ready for review

#3079 AP-2664 remove specific ModSecurity rule
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: Approved

#3087 AP-2633 Fix ingress annotation for UAT deployments
  bin/uat_deploy
Labels: Ready for review

#3060 AP-2199 accessible modal
  app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/shared/partials/_modal_dialogue.html.erb
  app/webpack/src/modal-dialogue.js
  app/webpack/src/no_script.js
  app/webpack/stylesheets/application.scss
  app/webpack/stylesheets/helpers.scss
  app/webpack/stylesheets/modal-dialogue.scss
  app/webpack/stylesheets/no-script.scss
  config/locales/en/shared.yml
  features/providers/deleting_applications.feature
  features/step_definitions/civil_journey_steps.rb
Labels: UAT, Approved

#3089 AP-2614 remove conditionally revealed text
  app/views/providers/substantive_applications/show.html.erb
Labels: UAT, Approved

#3088 AP-2633 Configure UAT live cluster deployments
  .circleci/config.yml
  bin/uat_deploy_to_live
  helm_deploy/apply-for-legal-aid/values-live-uat.yaml
Labels: Approved

#3092 AP-2659: Update cucumber gem
  .github/dependabot.yml
  Gemfile
  Gemfile.lock
  features/step_definitions/civil_journey_steps.rb
  features/support/env.rb
Labels: Approved

#3064 Ap 2621 convert delegated functions controller to use proceedings
  app/controllers/providers/confirm_delegated_functions_dates_controller.rb
  app/controllers/providers/confirm_multiple_delegated_functions_controller.rb
  app/controllers/providers/used_delegated_functions_controller.rb
  app/controllers/providers/used_multiple_delegated_functions_controller.rb
  app/forms/legal_aid_applications/confirm_delegated_functions_date_form.rb
  app/forms/legal_aid_applications/used_multiple_delegated_functions_form.rb
  app/models/concerns/delegated_functions.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/confirm_multiple_delegated_functions/show.html.erb
  app/views/providers/used_delegated_functions/show.html.erb
  app/views/providers/used_multiple_delegated_functions/show.html.erb
  app/views/shared/check_answers/_emergency_limitations.html.erb
  config/routes.rb
  features/step_definitions/civil_journey_steps.rb
  spec/forms/legal_aid_applications/confirm_delegated_functions_date_form_spec.rb
  spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb
  spec/models/aggregated_cash_income_spec.rb
  spec/models/application_proceeding_type_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/confirm_delegated_functions_date_spec.rb
  spec/requests/providers/substantive_applications_spec.rb
  spec/requests/providers/used_delegated_functions_spec.rb
  spec/requests/providers/used_multiple_delegated_functions_spec.rb
  spec/services/delegated_functions_date_service_spec.rb
Labels: Approved

#3080 update passported dwp check result content
  app/views/providers/check_benefits/_check_benefits_result.html.erb
  config/locales/en/providers.yml
  features/accessibility/provider.feature
  features/providers/back_button.feature
  features/providers/civil_application_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  spec/requests/providers/check_benefits_spec.rb
Labels: Approved

#3100 Fix live deployments for long branch names
  bin/uat_deploy
  bin/uat_deploy_to_live
Labels: Ready for review

#3110 Fix live deployments for long branch names
  bin/uat_deploy
  bin/uat_deploy_to_live
Labels: Approved

#3094 AP-2610 Delete purgeable applications
  app/services/destroy_purgeable_service.rb
  app/webpack/src/modal-dialogue.js
  helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
  lib/tasks/purge.rake
  spec/services/destroy_purgeable_service_spec.rb
Labels: Approved

#3108 AP-2651 update before you continue page
  app/views/providers/capital_introductions/show.html.erb
  config/locales/en/providers.yml
  features/providers/civil_application_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  spec/requests/providers/capital_introductions_spec.rb
Labels: UAT, Approved

#3120 AP-2701 - Clean up live-1 UAT deployments
  .circleci/config.yml
  bin/uat_deploy
  bin/uat_deploy_to_live
  helm_deploy/apply-for-legal-aid/values-live-uat.yaml
Labels: Approved

#3122 ap-2697 Add employment permissions
  app/models/provider.rb
  db/data/20211125142125_add_employment_to_permissions_table.rb
  db/data_schema.rb
  spec/models/provider_spec.rb
Labels: Approved

#3121 AP-2566 update continue financial assessment page
  app/views/providers/client_completed_means/show.html.erb
  config/locales/en/providers.yml
  features/accessibility/provider.feature
  features/providers/categorizing_bank_transactions.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/civil_application_journey.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  spec/requests/providers/client_completed_means_spec.rb
Labels: UAT, Approved

#3126 bugfix: display correct response on means report
  app/models/legal_aid_application.rb
  app/views/shared/check_answers/_assets.html.erb
Labels: Approved

#3111 AP-2704 Export Application Digest to Google Sheet
  app/services/digest_exporter.rb
  config/environments/development.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-live-uat.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  lib/tasks/digest.rake
Labels: Approved

#3128 AP-2649 update secondary heading sizes
  app/views/providers/applicant_bank_accounts/show.html.erb
  app/views/providers/has_other_dependants/show.html.erb
  app/views/providers/has_other_proceedings/show.html.erb
  app/views/providers/no_income_summaries/show.html.erb
  app/views/providers/no_outgoings_summaries/show.html.erb
  config/locales/en/providers.yml
Labels: UAT, Approved
