Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2021-08, with the labels that each got.

#2755 AP-2386: Add logging to report creators
  app/services/reports/means_report_creator.rb
  app/services/reports/merits_report_creator.rb
Labels: Approved

#2756 Ap 2145 remove admin screen
  app/controllers/admin/providers_controller.rb
  app/views/admin/providers/check.html.erb
  app/views/admin/providers/new.html.erb
  app/views/admin/user_dashboard/index.html.erb
  config/locales/en/admin.yml
  spec/requests/admin/providers_spec.rb
Labels: Approved

#2759 Ap 2385 release merits task list
  app/models/legal_framework/merits_task_list.rb
  app/services/flow/flows/provider_capital.rb
  app/services/flow/flows/provider_merits.rb
  features/accessibility/provider.feature
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant/I_am_able_to_create_a_passported_application_with_Cap_Contribs_3k_and_with_restrictions.yml
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant/I_am_able_to_create_a_passported_application_without_Cap_Contribs_and_with_no_restrictions.yml
  features/cassettes/Civil_application_journeys/Completes_the_application_using_manual_address.yml
  features/cassettes/Civil_application_journeys/Completes_the_merits_application_for_applicant_that_does_not_receive_passported_benefits.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_view_the_client_completed_means_answers.yml
  features/cassettes/Civil_application_journeys/I_can_see_that_the_applicant_receives_benefits.yml
  features/cassettes/Provider_accessibility/I_complete_the_non-passported_means_assessment_and_it_is_accessible.yml
  features/cassettes/Provider_accessibility/I_complete_the_non-passported_merits_assessment_and_it_is_accessible.yml
  features/providers/check_ccms_autogrant.feature
  features/providers/civil_application_journey.feature
  features/providers/merits_task_list.feature
  features/step_definitions/civil_journey_steps.rb
  spec/models/legal_framework/merits_task_list_spec.rb
  spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
  spec/requests/providers/capital_assessment_results_spec.rb
  spec/requests/providers/capital_income_assessment_results_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
  spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb
Labels: Approved, UAT

#2725 AP-2393 Ensure Proceedings are displayed in a consistent order
  app/services/legal_framework/merits_tasks_retriever_service.rb
  app/views/providers/has_other_proceedings/show.html.erb
Labels: Approved, Ready to merge

#2758 Ap 2353 remove unused content translations
  config/locales/cy/citizens.yml
  config/locales/cy/shared.yml
  config/locales/en/citizens.yml
  config/locales/en/shared.yml
Labels: Approved

#2757 Fix: Change pause_submission event handling
  app/controllers/providers/check_merits_answers_controller.rb
  app/models/concerns/base_state_machine.rb
  app/models/legal_aid_application.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/services/reports/reports_creator_spec.rb
Labels: Approved

#2762 Update Ruby minor version
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
Labels: Approved

#2782 Tech-debt: Update PR template
  docs/pull_request_template.md
Labels: Approved

#2781 Tech-Debt: Remove unused gems
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
Labels: Approved

#2776 AP-2429: Reduce time spent running unit tests
  .circleci/config.yml
  .github/workflows/i18n_checks.yml
  README.md
  spec/i18n_spec.rb
  spec/models/applicant_spec.rb
  spec/models/application_merits_task/involved_child_spec.rb
  spec/models/application_merits_task/opponent_spec.rb
  spec/models/bank_account_spec.rb
  spec/models/dependant_spec.rb
  spec/models/proceeding_type_spec.rb
  spec/services/ccms/attribute_configuration_spec.rb
  spec/services/ccms/attribute_value_generator_spec.rb
  spec/services/ccms/case_add_requestor_factory_spec.rb
  spec/services/ccms/manual_review_determiner_spec.rb
  spec/services/ccms/parsers/applicant_add_response_parser_spec.rb
  spec/services/ccms/parsers/applicant_add_status_response_parser_spec.rb
  spec/services/ccms/parsers/applicant_search_response_parser_spec.rb
  spec/services/ccms/parsers/case_add_response_parser_spec.rb
  spec/services/ccms/parsers/case_add_status_response_parser_spec.rb
  spec/services/ccms/parsers/document_id_response_parser_spec.rb
  spec/services/ccms/parsers/document_upload_response_parser_spec.rb
  spec/services/ccms/parsers/reference_data_response_parser_spec.rb
  spec/services/ccms/payload_generators/entity_attributes_generator_spec.rb
  spec/services/ccms/requestors/applicant_add_requestor_spec.rb
  spec/services/ccms/requestors/applicant_add_status_requestor_spec.rb
  spec/services/ccms/requestors/applicant_search_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_benefits_attrs_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_status_requestor_spec.rb
  spec/services/ccms/requestors/document_id_requestor_spec.rb
  spec/services/ccms/requestors/document_upload_requestor_spec.rb
  spec/services/ccms/requestors/reference_data_requestor_spec.rb
  spec/services/ccms/submitters/add_applicant_service_spec.rb
  spec/services/ccms/submitters/add_case_service_spec.rb
  spec/services/ccms/submitters/check_applicant_status_service_spec.rb
  spec/services/ccms/submitters/check_case_status_service_spec.rb
  spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
  spec/services/ccms/submitters/obtain_case_reference_service_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
  spec/services/ccms/submitters/upload_documents_service_spec.rb
  spec/services/pdf_converter_spec.rb
  spec/spec_helper.rb
Labels: Approved

#2754 AP-2434 proceedings search screenreader msg
  app/views/providers/proceedings_types/index.html.erb
  app/webpack/src/modules/proceedings.js
Labels: Approved

#2793 Delegated functions dates should appear on page
  app/forms/legal_aid_applications/used_multiple_delegated_functions_form.rb
  features/cassettes/Pathways_from_check_your_answers/I_go_back_and_change_the_delegated_functions_on_an_application_with_multiple_proceedings.yml
  features/providers/pathways_from_check_your_answers.feature
  features/step_definitions/civil_journey_steps.rb
  spec/requests/providers/used_multiple_delegated_functions_spec.rb
Labels: Ready for review

#2802 AP-2467 BUGFIX PT search not handling multiple spaces search terms
  app/services/proceeding_type_full_text_search.rb
  spec/services/proceeding_type_full_text_search_spec.rb
Labels: Approved

#2785 AP-2416: Handle accented characters
  app/controllers/concerns/providers/application_dependable.rb
Labels: Ready to merge

#2809 AP-2453: Prep for update default branch
  .circleci/config.yml
  .github/workflows/anonymise_check.yml
  .github/workflows/brakeman-analysis.yml
  README.md
  docs/pull_request_template.md
Labels: Ready for review

#2795 Delegated functions dates should appear on page
  app/forms/legal_aid_applications/used_multiple_delegated_functions_form.rb
  features/cassettes/Pathways_from_check_your_answers/I_go_back_and_change_the_delegated_functions_on_an_application_with_multiple_proceedings.yml
  features/providers/pathways_from_check_your_answers.feature
  features/step_definitions/civil_journey_steps.rb
  spec/requests/providers/used_multiple_delegated_functions_spec.rb
Labels: Ready to merge

#2778 AP-2244 Remove override dwp results feqture flag
  app/controllers/admin/settings_controller.rb
  app/controllers/providers/check_benefits_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/services/use_ccms_arbiter.rb
  app/views/admin/settings/show.html.erb
  config/locales/cy/helpers.yml
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  db/migrate/20210805072930_remove_override_dwp_results_feature_flag.rb
  db/schema.rb
  features/accessibility/provider.feature
  features/providers/civil_application_journey.feature
  features/providers/non_passported_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  features/step_definitions/civil_journey_steps.rb
  lib/tasks/setup_db_for_testing.rake
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
  spec/requests/providers/check_benefits_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/services/use_ccms_arbiter_spec.rb
Labels: UAT, Approved

#2801 Ap2303 Update page titles across application
  app/views/citizens/means_test_results/show.html.erb
  app/views/providers/capital_income_assessment_results/show.html.erb
  app/views/providers/has_other_dependants/show.html.erb
  app/views/providers/proceeding_merits_task/attempts_to_settle/show.html.erb
  app/views/providers/proceeding_merits_task/chances_of_success/index.html.erb
  app/views/providers/proceeding_merits_task/linked_children/show.html.erb
  app/views/providers/proceeding_merits_task/success_prospects/show.html.erb
  config/locales/en/citizens.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/locales/en/transaction_types.yml
Labels: UAT, Approved

#2820 AP-2463 improve proceedings search keyboard navigation
  app/views/providers/proceedings_types/index.html.erb
  app/views/shared/forms/proceedings_types/_proceeding_type_form.html.erb
  features/step_definitions/civil_journey_steps.rb
Labels: UAT, Approved

#2824 Tech-Debt: Remove codecov
  Gemfile
  Gemfile.lock
  README.md
  spec/spec_helper.rb
Labels: Approved

#2828 Fix sort order screenreader message
  app/helpers/table_sort_helper.rb
Labels: UAT, Approved

#2829 AP-2425 Display proceedings in correct order
  app/webpack/src/modules/proceedings.js
Labels: UAT, Approved
