Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2021-09, with the labels that each got.

#2848 AP-2448 Add translation for failed address lookup
  config/locales/en/forms.yml
Labels: UAT, Approved

#2842 AP-2355 Use class inheritance for forms
  app/forms/addresses/address_form.rb
  app/forms/addresses/address_lookup_form.rb
  app/forms/addresses/address_selection_form.rb
  app/forms/applicants/basic_details_form.rb
  app/forms/applicants/email_form.rb
  app/forms/applicants/employed_form.rb
  app/forms/applicants/open_banking_consent_form.rb
  app/forms/base_file_uploader_form.rb
  app/forms/base_form.rb
  app/forms/chances_of_successes/success_likely_form.rb
  app/forms/chances_of_successes/success_prospect_form.rb
  app/forms/citizens/other_assets_form.rb
  app/forms/incidents/told_on_form.rb
  app/forms/legal_aid_applications/dependant_form.rb
  app/forms/legal_aid_applications/emergency_cost_override_form.rb
  app/forms/legal_aid_applications/has_dependants_form.rb
  app/forms/legal_aid_applications/has_evidence_of_benefit_form.rb
  app/forms/legal_aid_applications/has_other_proceedings_form.rb
  app/forms/legal_aid_applications/in_scope_of_laspo_form.rb
  app/forms/legal_aid_applications/open_banking_consent_form.rb
  app/forms/legal_aid_applications/outstanding_mortgage_form.rb
  app/forms/legal_aid_applications/own_home_form.rb
  app/forms/legal_aid_applications/own_vehicle_form.rb
  app/forms/legal_aid_applications/percentage_home_form.rb
  app/forms/legal_aid_applications/property_value_form.rb
  app/forms/legal_aid_applications/restrictions_form.rb
  app/forms/legal_aid_applications/shared_ownership_form.rb
  app/forms/legal_aid_applications/student_finance_form.rb
  app/forms/legal_aid_applications/substantive_application_form.rb
  app/forms/opponents/opponent_form.rb
  app/forms/providers/application_merits_task/involved_child_form.rb
  app/forms/providers/gateway_evidence_form.rb
  app/forms/providers/office_form.rb
  app/forms/providers/policy_disregards_form.rb
  app/forms/providers/proceeding_merits_task/attempts_to_settle_form.rb
  app/forms/providers/proceeding_merits_task/linked_children_form.rb
  app/forms/providers/received_benefit_confirmation_form.rb
  app/forms/savings_amounts/offline_accounts_form.rb
  app/forms/savings_amounts/offline_savings_accounts_form.rb
  app/forms/savings_amounts/savings_amounts_form.rb
  app/forms/settings/setting_form.rb
  app/forms/statement_of_cases/statement_of_case_form.rb
  app/forms/student_finances/annual_amount_form.rb
  app/forms/vehicle_form/age_form.rb
  app/forms/vehicle_form/estimated_value_form.rb
  app/forms/vehicle_form/remaining_payment_form.rb
  app/forms/vehicle_form/used_regularly_form.rb
  app/views/shared/forms/_applicant_form.html.erb
  spec/forms/base_form_spec.rb
Labels: Approved

#2830 AP-2426 Fix highlighting of numbers in proceedings search results
  app/webpack/src/modules/proceedings.js
Labels: UAT, Approved

#2850 Tech-Debt: Reduce Geckoboard noise
  app/models/legal_aid_application.rb
  app/services/dashboard_event_handler.rb
  spec/services/dashboard_event_handler_spec.rb
Labels: Approved

#2852 AP-2501 Incorrect legend on /check_client_details
  app/views/providers/check_client_details/show.html.erb
Labels: UAT, Approved

#2854 AP-2496 Add JS to deselect previously selected proceeding item
  app/webpack/src/modules/proceedings.js
Labels: UAT, Approved

#2772 AP-2439 Give namespaces meaningful names
  app/services/ccms/payload_generators/entity_attributes_generator.rb
  app/services/ccms/requestors/applicant_add_requestor.rb
  app/services/ccms/requestors/applicant_add_status_requestor.rb
  app/services/ccms/requestors/applicant_search_requestor.rb
  app/services/ccms/requestors/base_requestor.rb
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/ccms/requestors/case_add_status_requestor.rb
  app/services/ccms/requestors/document_id_requestor.rb
  app/services/ccms/requestors/document_upload_requestor.rb
  app/services/ccms/requestors/non_passported_case_add_requestor.rb
  app/services/ccms/requestors/reference_data_requestor.rb
  ccms_integration/example_payloads/multi_proc/MP_1333536_NP_multi children.xml
  docs/pull_request_template.md
  spec/data/ccms/applicant_add_status_request.xml
  spec/data/ccms/case_add_request.xml
  spec/data/ccms/case_add_status_request.xml
  spec/data/ccms/mp_case_add_request.xml
  spec/services/ccms/requestors/applicant_add_requestor_spec.rb
  spec/services/ccms/requestors/applicant_add_status_requestor_spec.rb
  spec/services/ccms/requestors/applicant_search_requestor_spec.rb
  spec/services/ccms/requestors/case_add_status_requestor_spec.rb
  spec/services/ccms/requestors/document_id_requestor_spec.rb
  spec/services/ccms/requestors/document_upload_requestor_spec.rb
  spec/services/ccms/requestors/reference_data_requestor_spec.rb
  spec/services/ccms/submitters/add_applicant_service_spec.rb
  spec/services/ccms/submitters/add_case_service_spec.rb
  spec/services/ccms/submitters/check_applicant_status_service_spec.rb
  spec/services/ccms/submitters/check_case_status_service_spec.rb
  spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
  spec/services/ccms/submitters/obtain_case_reference_service_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
  spec/support/soap_matchers.rb
Labels: Approved

#2876 AP-2507- ccms failures
  app/services/true_layer/api_client.rb
  spec/factories/legal_aid_applications.rb
  spec/models/aggregated_cash_income_spec.rb
Labels: Approved

#2877 update circle config rename master to main
  .circleci/config.yml
Labels: Ready for review

#2873 AP-2502 Remove default cost limitations to a separate model
  app/models/default_cost_limitation.rb
  app/models/proceeding_type.rb
  app/services/proceeding_type_populator.rb
  db/anonymise/rules.rb
  db/migrate/20210423180431_add_name_to_proceeding_types.rb
  db/migrate/20210913102726_create_default_cost_limitations.rb
  db/migrate/20210913110123_drop_cost_limitations_from_proceeding_types.rb
  db/migrate/20210913150028_re_seed.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/legal_framework/proceeding_types.csv
  spec/factories/default_cost_limtiations.rb
  spec/factories/proceeding_types.rb
  spec/models/aggregated_cash_income_spec.rb
  spec/models/default_cost_limitation_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/proceeding_type_spec.rb
  spec/services/proceeding_type_full_text_search_spec.rb
  spec/services/proceeding_type_populator_spec.rb
Labels: UAT, Approved

#2847 AP-2472: CCMS updates
  Gemfile
  Gemfile.lock
  app/models/ccms/submission.rb
  app/models/concerns/ccms_submission_state_machine.rb
  app/services/ccms/submitters/base_submission_service.rb
  app/workers/ccms/submission_process_worker.rb
  config/initializers/sentry.rb
  spec/models/ccms/submission_spec.rb
  spec/spec_helper.rb
  spec/workers/ccms/submission_process_worker_spec.rb
Labels: UAT, Approved

#2885 AP-2472: Fix rubocop issue
  app/workers/ccms/submission_process_worker.rb
Labels: Ready for review

#2878 AP-2500 remove title text for labelled elements
  app/helpers/accessible_navigation_helper.rb
  spec/helpers/accessible_navigation_helper_spec.rb
Labels: Approved

#2888 AP-2506: Improve handling of email errors
  app/services/govuk_emails/delivery_man.rb
  spec/services/govuk_emails/delivery_man_spec.rb
Labels: Approved

#2887 AP-2510 Remove data seed from schema migration
  db/migrate/20210913150028_re_seed.rb
Labels: Approved

#2884 Remove pii from Kibana logs
  config/initializers/filter_parameter_logging.rb
Labels: UAT, Approved

#2846 AP-2497 Alternative alerting mechanism
  app/controllers/admin_users/omniauth_callbacks_controller.rb
  app/controllers/applicants/omniauth_callbacks_controller.rb
  app/controllers/auth_controller.rb
  app/controllers/citizens/gather_transactions_controller.rb
  app/controllers/concerns/providers/authorizable.rb
  app/controllers/providers/transactions_controller.rb
  app/controllers/test/generate_error_controller.rb
  app/helpers/providers_helper.rb
  app/lib/alert_manager.rb
  app/lib/slack_alerter.rb
  app/mailers/exception_alert_mailer.rb
  app/models/application_proceeding_type.rb
  app/models/provider.rb
  app/models/setting.rb
  app/services/address_lookup_service.rb
  app/services/benefit_check_service.rb
  app/services/ccms/payload_generators/entity_attributes_generator.rb
  app/services/cfe/submission_manager.rb
  app/services/govuk_emails/delivery_man.rb
  app/services/govuk_emails/monitor.rb
  app/services/legal_framework/merits_tasks_service.rb
  app/services/malware_scanner.rb
  app/services/true_layer/api_client.rb
  app/services/true_layer_error_decoder.rb
  config/application.rb
  config/govuk_notify_templates.yml
  config/initializers/omniauth.rb
  config/routes.rb
  db/migrate/20210901160225_add_alert_via_sentry_to_settings.rb
  db/schema.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/factories/addresses.rb
  spec/factories/applicants.rb
  spec/lib/alert_manager_spec.rb
  spec/lib/slack_alerter_spec.rb
  spec/mailers/exception_alert_mailer_spec.rb
  spec/models/application_proceeding_type_spec.rb
  spec/models/provider_spec.rb
  spec/models/setting_spec.rb
  spec/requests/test/generate_error_controller_spec.rb
  spec/services/address_lookup_service_spec.rb
  spec/services/benefit_check_service_spec.rb
  spec/services/ccms/payload_generators/entity_attributes_generator_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/cfe/submission_manager_spec.rb
  spec/services/govuk_emails/delivery_man_spec.rb
  spec/services/govuk_emails/monitor_spec.rb
  spec/services/legal_framework/merits_tasks_service_spec.rb
  spec/services/malware_scanner_spec.rb
  spec/services/true_layer_error_decoder_spec.rb
Labels: Approved
