Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2021-02, with the labels that each got.

#2229 BUGFIX NightlyJob, undo timezone adherence for cleaning ecr images
  bin/delete_ecr_images
Labels: ready for review

#2226 Update the long_date form for i18n localisation
  config/locales/cy/dates.yml
  config/locales/en/dates.yml
  spec/helpers/transaction_period_helper_spec.rb
Labels: Approved

#2220 AP-1971 add new formbuilder to success prospects page
  app/controllers/providers/success_prospects_controller.rb
  app/forms/merits_assessments/success_prospect_form.rb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/forms/_success_prospect_form.html.erb
  app/views/shared/forms/success_prospect/_success_prospect_item.html.erb
  config/locales/cy/shared.yml
  config/locales/en/shared.yml
Labels: Approved, UAT

#2209 AP-1972 use new formbuilder on statement of case page
  app/views/providers/statement_of_cases/show.html.erb
  features/providers/civil_application_journey.feature
  spec/requests/providers/statement_of_case_spec.rb
Labels: Approved, UAT

#2228 AP-1964 Post cash transactions to CFE
  app/models/concerns/cfe_submission_state_machine.rb
  app/services/cfe/create_cash_transactions_service.rb
  app/services/cfe/obtain_assessment_result_service.rb
  app/services/cfe/submission_manager.rb
  spec/cassettes/CFE_SubmissionManager/_call/allow_cash_payment_setting_is_true/when_the_application_is_non-passported/completes_process.yml
  spec/cassettes/CFE_SubmissionManager/_call/allow_cash_payment_setting_is_true/when_the_application_is_passported/completes_process.yml
  spec/cassettes/CFE_SubmissionManager/_call/when_the_application_is_non-passported/completes_process.yml
  spec/services/cfe/create_cash_transactions_service_spec.rb
  spec/services/cfe/obtain_assessment_result_service_spec.rb
  spec/services/cfe/submission_manager_spec.rb
Labels: Approved

#2219 AP-1957 delegated functions date confirmation page
  app/controllers/providers/delegated_functions_dates_controller.rb
  app/controllers/providers/used_delegated_functions_controller.rb
  app/forms/legal_aid_applications/delegated_functions_date_form.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/delegated_functions_dates/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/civil_application_journey.feature
  features/support/steps_helper.rb
  spec/forms/legal_aid_applications/delegated_functions_date_form_spec.rb
  spec/requests/providers/delegated_functions_date_spec.rb
  spec/requests/providers/used_delegated_functions_spec.rb
Labels: UAT, ready for review

#2238 Tech debt: brakeman fixes
  app/controllers/admin/legal_aid_applications_controller.rb
  app/controllers/errors_controller.rb
  app/views/errors/show.html.erb
  spec/requests/admin/legal_aid_applications_controller_spec.rb
Labels: ready for review

#2239 Create brakeman-analysis.yml
  .github/workflows/brakeman-analysis.yml
Labels: Approved

#2255 BugFix reverse rubocop fix for bin/bundle file
  .rubocop.yml
  bin/bundle
Labels: ready for review

#2252 AP-1965 Removed hard-coded data from BankAccount model
  app/models/bank_account.rb
  bin/bundle
  spec/factories/bank_transactions.rb
  spec/models/bank_account_spec.rb
Labels: Approved

#2221 AP-1956 Calculate balances for every transaction in CSV file
  app/jobs/bank_transactions_analyser_job.rb
  app/models/bank_account.rb
  app/models/bank_transaction.rb
  app/models/legal_aid_application.rb
  app/services/banking/bank_transaction_balance_calculator.rb
  app/services/banking/bank_transactions_trimmer.rb
  app/services/banking/state_benefit_analyser_service.rb
  app/services/reports/bank_transactions/bank_transaction_report_creator.rb
  app/services/reports/bank_transactions/bank_transaction_sorter.rb
  app/services/reports/bank_transactions/base_transaction_sorter.rb
  app/services/reports/bank_transactions/first_day_transaction_sorter.rb
  app/services/reports/bank_transactions/ordering_error.rb
  app/services/reports/bank_transactions/subsequent_day_transaction_sorter.rb
  app/services/state_benefit_analyser_service.rb
  app/services/true_layer/bank_data_import_service.rb
  spec/jobs/bank_transactions_analyser_job_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/services/banking/bank_transaction_balance_calculator_spec.rb
  spec/services/banking/bank_transactions_trimmer_spec.rb
  spec/services/cfe/create_capitals_service_spec.rb
  spec/services/reports/bank_transactions/bank_transaction_sorter_spec.rb
  spec/services/reports/bank_transactions/first_day_transaction_sorter_spec.rb
  spec/services/reports/bank_transactions/mock_bank_transaction.rb
  spec/services/reports/bank_transactions/subsequent_day_transaction_sorter_spec.rb
  spec/services/state_benefit_analyser_service_spec.rb
  spec/spec_helper.rb
Labels: Approved, UAT

#2249 AP-1999 Ignore duplicate state benefits in same transaction
  app/services/banking/state_benefit_analyser_service.rb
  spec/services/banking/state_benefit_analyser_service_spec.rb
  spec/services/state_benefit_analyser_service_spec.rb
Labels: Approved, UAT

#2265 AP-2008 Remove references to student loan
  app/models/concerns/cfe_submission_state_machine.rb
  spec/models/concerns/cfe_submission_state_machine_spec.rb
  spec/services/cfe/submission_manager_spec.rb
Labels: Approved

#2254 Upgrade helm chart for UAT bitnami-postgresql
  helm_deploy/apply-for-legal-aid/Chart.lock
  helm_deploy/apply-for-legal-aid/Chart.yaml
  helm_deploy/apply-for-legal-aid/charts/postgresql-10.2.8.tgz
  helm_deploy/apply-for-legal-aid/charts/postgresql-8.10.14.tgz
Labels: Approved

#2258 AP-1996 show checkbox errors on revealed fields
  app/views/providers/other_assets/_second_home_conditional_checkbox.html.erb
  app/views/shared/forms/revealing_checkbox/_attribute.html.erb
Labels: Approved, UAT

#2250 AP-1970: Parse CFE V3 response and add relevant tests for it
  app/models/cfe/v3/result.rb
  app/services/cfe/obtain_assessment_result_service.rb
  spec/factories/cfe_results.rb
  spec/factories/cfe_results/v3/mock_results.rb
  spec/factories/legal_aid_applications.rb
  spec/factory_specs/cfe_result_factory_spec.rb
  spec/models/cfe/v3/result_spec.rb
  spec/requests/providers/means_reports_spec.rb
  spec/services/cfe/obtain_assessment_result_service_spec.rb
  spec/services/reports/means_report_creator_spec.rb
Labels: Approved, UAT

#2267 AP-1968: Update styling and read_only values for the means report
  app/helpers/check_answers_helper.rb
  app/views/layouts/pdf.html.erb
  app/views/providers/means_reports/show.html.erb
  app/views/shared/check_answers/_capital_result.html.erb
  app/views/shared/check_answers/_income_result.html.erb
  app/views/shared/check_answers/_item.html.erb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/check_answers/_no_link_item.html.erb
  app/views/shared/check_answers/_one_link_section.html.erb
  app/views/shared/check_answers/_property.html.erb
  app/views/shared/check_answers/_restrictions.html.erb
  app/webpack/stylesheets/check-your-answers.scss
Labels: Approved, UAT

#2275 AP-2020 Update other capital ccms attributes
  ccms_integration/example_payloads/Dave_Fabby_CaseAddPayload.xml
  ccms_integration/example_payloads/NonPassportedFullMonty.csv
  ccms_integration/example_payloads/NonPassportedFullMonty.xml
  ccms_integration/example_payloads/PassportedSingleProceedingNonMol.xml
  ccms_integration/example_payloads/PassportedSingleProceedingNonMolDelegated.xml
  config/ccms/attribute_block_configs/base.yml
  config/ccms/attribute_block_configs/non_passported.yml
  spec/data/ccms/case_add_request.xml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: Approved, UAT, UAT Success

#2274 ap-2019 update text on CCMS attribute
  config/ccms/attribute_block_configs/non_passported.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
Labels: Approved, UAT, UAT Success

#2273 AP-2018 Update the bank account type labels
  app/models/bank_account.rb
  spec/models/bank_account_spec.rb
  spec/presenters/bank_transaction_presenter_spec.rb
Labels: Approved, UAT, UAT Success

#2280 AP-2036: Remove validation of no selected bank transactions and add c…
  app/models/cash_transaction.rb
  app/models/cfe/v3/result.rb
  app/models/legal_aid_application.rb
  app/views/shared/check_answers/_bank_transaction_table.html.erb
  app/views/shared/check_answers/_income_summary.html.erb
  spec/factories/cfe_results/v3/mock_results.rb
  spec/models/bank_transaction_spec.rb
  spec/models/cash_transaction_spec.rb
  spec/services/cfe/obtain_assessment_result_service_spec.rb
Labels: Approved, UAT

#2283 AP-2045: Update ManualReviewDeterminer to flag submissions as needing…
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/manual_review_determiner.rb
  spec/data/ccms/case_add_request.xml
  spec/requests/providers/capital_assessment_results_spec.rb
  spec/requests/providers/capital_income_assessment_results_spec.rb
  spec/services/ccms/manual_review_determiner_spec.rb
Labels: Approved

#2294 BugFix: Update step helper
  features/support/steps_helper.rb
Labels: Approved, ready for review

#2289 ap-2038 remove sign in link from citizen views
  app/views/layouts/_header.html.erb
  features/citizens/citizens.feature
Labels: Approved, UAT Success

#2290 ap-2043 add quote marks for proper separation
  app/views/providers/income_summary/_income_type_item.html.erb
  app/views/providers/outgoings_summary/_outgoing_type_item.html.erb
Labels: Approved, UAT

#2304 Remove leftover code
  app/views/layouts/_header.html.erb
Labels: Approved

#2306 AP-2007 Hide logging mailer arguments for security
  app/jobs/govuk_notify_mailer_job.rb
Labels: Approved

#2293 AP-2032: update os api handling
  app/services/address_lookup_service.rb
  features/cassettes/Civil_application_journeys/Completes_the_application_using_address_lookup.yml
  features/cassettes/Civil_application_journeys/Completes_the_application_using_manual_address.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_clear_proceeding_on_the_proceeding_page.yml
  features/cassettes/Civil_application_journeys/I_am_instructed_to_use_CCMS_on_the_passported_journey_with_an_applicant_does_not_receive_benefits.yml
  features/cassettes/Civil_application_journeys/I_am_instructed_to_use_CCMS_when_the_applicant_is_not_eligible.yml
  features/cassettes/Civil_application_journeys/I_can_see_that_the_applicant_does_not_receive_benefits.yml
  features/cassettes/Civil_application_journeys/I_can_see_that_the_applicant_receives_benefits.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_address_from_the_check_your_answers_page.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_address_manually_from_the_check_your_answers_page.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_client_details_after_a_failed_benefit_check.yml
  features/cassettes/Civil_application_journeys/I_want_to_return_to_check_your_answers_from_address_select.yml
  features/cassettes/Civil_application_journeys/No_results_returned_is_seen_on_screen_when_invalid_proceeding_search_entered.yml
  features/cassettes/Non-passported_applicant_journeys/I_want_the_check_provider_answers_page_to_correctly_display_while_waiting_for_client_to_provide_data.yml
  features/cassettes/Provider_accessibility/I_complete_the_financial_assessment_eligibility_section_for_a_non-passported_application.yml
  features/cassettes/Provider_accessibility/I_start_a_new_application.yml
  features/cassettes/Provider_accessibility/I_start_a_new_application_and_it_is_accessible.yml
  features/cassettes/Provider_accessibility/I_start_a_new_non-passported_application.yml
  features/cassettes/Provider_accessibility/I_start_a_new_non-passported_application_and_enter_client_details.yml
  features/cassettes/Provider_accessibility/I_start_a_new_non-passported_application_and_it_is_accessible.yml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/a_postcode_has_been_entered_before/but_the_lookup_does_not_return_any_valid_results/renders_the_manual_address_selection_page.yml
  spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/a_postcode_has_been_entered_before/performs_an_address_lookup_with_the_provided_postcode.yml
  spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/a_postcode_has_been_entered_before/renders_the_address_selection_page.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/the_applicant_s_address_used_s_address_lookup_service/should_redirect_to_the_address_lookup_page.yml
  spec/cassettes/providers_legal_aid_application_proceedings_type_requests/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/the_applicant_s_address_used_s_address_lookup_service/should_redirect_to_the_address_lookup_page.yml
  spec/fixtures/files/address_lookups/no_results.json
  spec/fixtures/files/address_lookups/success.json
Labels: Approved, UAT

#2299 AP-2023 BugFix Restrictions page error not appearing correctly
  app/views/providers/restrictions/show.html.erb
Labels: Approved, UAT Success

#2288 AP-2021 Changed the citizen flow to redirect correctly
  app/services/flow/flows/citizen_capital.rb
  features/citizens/citizens.feature
  spec/requests/citizens/identify_types_of_incomes_spec.rb
Labels: Approved, UAT

#2305 AP-2024 error now works when police_notified is blank
  app/forms/respondents/respondent_form.rb
  config/locales/en/activemodel.yml
  spec/forms/respondents/respondent_form_spec.rb
Labels: Approved, UAT

#2303 AP-2033: Fix PDF generation
  Dockerfile
  app/views/layouts/pdf.html.erb
  app/webpack/stylesheets/check-your-answers.scss
Labels: Approved, UAT

#2296 AP-2044: Fix bug to ensure the student loan record for an application…
  app/controllers/citizens/student_finances/annual_amounts_controller.rb
  app/forms/legal_aid_applications/student_finance_form.rb
  spec/requests/citizens/student_finance/annual_amounts_spec.rb
Labels: Approved, UAT

#2297 AP-1890 non-passported formbuilder
  app/controllers/providers/applicant_details_controller.rb
  app/controllers/providers/applicants_controller.rb
  app/controllers/providers/date_client_told_incidents_controller.rb
  app/controllers/providers/delegated_functions_dates_controller.rb
  app/controllers/providers/dependants_controller.rb
  app/controllers/providers/policy_disregards_controller.rb
  app/controllers/providers/provider_base_controller.rb
  app/controllers/providers/used_delegated_functions_controller.rb
  app/forms/legal_aid_applications/delegated_functions_date_form.rb
  app/forms/legal_aid_applications/dependant_form.rb
  app/forms/providers/policy_disregards_form.rb
  app/helpers/gov_uk_form_helper.rb
  app/views/providers/applicant_employed/index.html.erb
  app/views/providers/confirm_offices/show.html.erb
  app/views/providers/delegated_functions_dates/show.html.erb
  app/views/providers/dependants/_form.html.erb
  app/views/providers/email_addresses/show.html.erb
  app/views/providers/has_dependants/show.html.erb
  app/views/providers/has_other_dependants/show.html.erb
  app/views/providers/legal_aid_applications/search.html.erb
  app/views/providers/policy_disregards/show.html.erb
  app/views/providers/remove_dependant/show.html.erb
  app/views/providers/select_offices/show.html.erb
  app/views/shared/_cash_transactions.html.erb
  app/views/shared/forms/_applicant_form.html.erb
  app/views/shared/forms/_check_boxes.html.erb
  app/views/shared/forms/_offline_savings_accounts_form.html.erb
  app/views/shared/forms/_open_banking_consents.html.erb
  app/views/shared/forms/policy_disregards/_form.html.erb
  app/views/shared/partials/_revealing_checkbox.html.erb
  config/locales/cy/activemodel.yml
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/forms/legal_aid_applications/delegated_functions_date_form_spec.rb
  spec/forms/legal_aid_applications/dependant_form_spec.rb
  spec/requests/providers/applicant_details_spec.rb
  spec/requests/providers/applicants_spec.rb
  spec/requests/providers/concerns/draftable_spec.rb
  spec/requests/providers/date_client_told_incidents_spec.rb
  spec/requests/providers/delegated_functions_date_spec.rb
  spec/requests/providers/policy_disregards_controller_spec.rb
  spec/requests/providers/used_delegated_functions_spec.rb
Labels: Approved, UAT
