Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2021-01, with the labels that each got.

#2138 AP-1857 Add pry-rescue gems
  Gemfile
  Gemfile.lock
  README.md
  spec/rails_helper.rb
Labels: Approved

#2143 Capture exceptions during entity attributes generation
  app/services/ccms/payload_generators/entity_attributes_generator.rb
  spec/services/ccms/payload_generators/entitiy_attributes_generator_spec.rb
Labels: ready for review

#2122 AP-1903 Display correct Assessment Results Panel if disregards have been selected
  app/controllers/providers/capital_assessment_results_controller.rb
  app/controllers/providers/capital_income_assessment_results_controller.rb
  app/models/legal_aid_application.rb
  app/models/policy_disregards.rb
  app/services/results_panel_selector.rb
  app/views/providers/capital_assessment_results/show.html.erb
  app/views/providers/capital_income_assessment_results/_capital_contribution_required.html.erb
  app/views/providers/capital_income_assessment_results/_eligible.html.erb
  app/views/providers/capital_income_assessment_results/_not_eligible.html.erb
  app/views/providers/capital_income_assessment_results/show.html.erb
  app/views/shared/assessment_results/_capital_and_income_contribution_required.html.erb
  app/views/shared/assessment_results/_capital_contribution_required.html.erb
  app/views/shared/assessment_results/_eligible.html.erb
  app/views/shared/assessment_results/_income_contribution_required.html.erb
  app/views/shared/assessment_results/_manual_check_disregards.html.erb
  app/views/shared/assessment_results/_manual_check_disregards_restrictions.html.erb
  app/views/shared/assessment_results/_manual_check_required.html.erb
  app/views/shared/assessment_results/_not_eligible.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  spec/factories/respondents.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/capital_assessment_results_spec.rb
  spec/requests/providers/capital_income_assessment_results_spec.rb
  spec/requests/providers/respondent_names_controller_spec.rb
  spec/services/results_panel_selector_spec.rb
Labels: Approved, UAT

#2145 Fix: Speed up rubocop
  .rubocop.yml
Labels: Approved

#2146 Fix: policy disregards tests
  features/accessibility/provider.feature
  features/providers/civil_application_journey.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/feature_flagged_steps.rb
  spec/requests/providers/other_assets_controller_spec.rb
Labels: Approved

#2140 AP-1933 - Feature flag for multiple proceedings
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  db/migrate/20210106155819_add_multiple_proceedings_flag_to_settings.rb
  db/schema.rb
  lib/tasks/setup_db_for_testing.rake
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
Labels: Approved, UAT

#2147 AdminPage: Return result for empty cfe submission result
  app/views/admin/legal_aid_applications/submissions/show.html.erb
  spec/helpers/hash_format_helper_spec.rb
Labels: Approved

#2157 AP-1954 Remove account holder duplication
  app/models/bank_account.rb
  app/services/ccms/attribute_value_generator.rb
  config/ccms/attribute_block_configs/base.yml
  config/ccms/attribute_block_configs/non_passported.yml
  spec/fixtures/files/ccms_keys/standard_ccms_keys.yml
  spec/models/bank_account_spec.rb
Labels: Approved

#2153 AP-1941 Add date_submitted to non-passported csv
  app/models/legal_aid_application.rb
  app/services/reports/mis/non_passported_application_csv_line.rb
  spec/services/reports/mis/non_passported_application_csv_line_spec.rb
  spec/services/reports/mis/non_passported_applications_report_spec.rb
Labels: Approved

#2163 AP-1959 BUGFIX do not set provider step to delete
  app/controllers/concerns/providers/application_dependable.rb
Labels: Approved

#2170 Fix: rename variables inline with new rubocop
  spec/factories/cash_transactions.rb
  spec/models/aggregated_cash_income_spec.rb
Labels: ready for review

#2149 AP-1917: Identify non live feedback
  app/mailers/feedback_mailer.rb
  config/govuk_notify_templates.yml
Labels: Approved

#2158 AP-1938: admin search
  app/controllers/admin/legal_aid_applications_controller.rb
  app/views/admin/legal_aid_applications/index.html.erb
  config/locales/en/admin.yml
  config/locales/en/generic.yml
  config/locales/en/helpers.yml
  config/routes.rb
  features/admin/application_list.feature
  features/step_definitions/admin_steps.rb
  spec/requests/admin/legal_aid_applications_controller_spec.rb
Labels: Approved

#2154 AP-1934 Show savings account as "none declared" on caseworker means report
  app/models/legal_aid_application.rb
  app/views/shared/check_answers/_assets.html.erb
  config/locales/en/providers.yml
Labels: Changes Requested

#2175 AP-1859 Update CCMS TODOs
  app/models/bank_account.rb
  app/services/ccms/requestors/case_add_requestor.rb
Labels: Approved

#2183 Reduce log pollution in the testing environment
  README.md
  config/environments/test.rb
Labels: Approved

#2181 Ap 1524 display cash
  app/controllers/providers/income_summary_controller.rb
  app/controllers/providers/outgoings_summary_controller.rb
  app/models/cash_transaction.rb
  app/views/providers/income_summary/index.html.erb
  app/views/providers/outgoings_summary/index.html.erb
  app/views/shared/_cash_transactions.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  db/migrate/20210115142828_update_column_type_on_cash_transactions.rb
  db/migrate/20210115142908_delete_column_on_cash_transactions.rb
  db/migrate/20210115155032_reinstate_cash_transaction_index.rb
  db/schema.rb
  spec/models/cash_transaction_spec.rb
Labels: Approved, UAT

#2178 Tech-debt: Rubocop tidy
  .rubocop_todo.yml
  Guardfile
  app/mailers/feedback_mailer.rb
  app/models/ccms/submission.rb
  app/models/cfe/remarks.rb
  app/services/admin/provider_details_service.rb
  app/services/ccms/payload_generators/entity_attributes_generator.rb
  app/services/reports/base_report_creator.rb
  app/services/reports/means_report_creator.rb
  app/services/reports/merits_report_creator.rb
  spec/models/ccms/submission_spec.rb
  spec/services/ccms/payload_generators/entity_attributes_generator_spec.rb
Labels: ready for review

#2179 AP1925 multiple proceedings search
  app/controllers/providers/proceedings_types_controller.rb
  app/services/proceeding_types_service.rb
  app/views/providers/proceedings_types/index.html.erb
  app/views/shared/forms/proceedings_types/_legacy_proceeding_type_form.html.erb
  app/views/shared/forms/proceedings_types/_proceeding_type_form.html.erb
  app/webpack/src/modules/proceedings.js
  config/locales/en/providers.yml
  features/accessibility/provider.feature
  features/providers/civil_application_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/requests/providers/proceedings_types_spec.rb
  spec/services/proceeding_types_service_spec.rb
Labels: Approved, UAT

#2164 AP-1927 : Add page for reviewing and removing proceedings
  app/controllers/providers/has_other_proceedings_controller.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/has_other_proceedings/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/civil_application_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/proceeding_types.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/proceedings_types_spec.rb
Labels: Approved, UAT

#2190 AP-1976 fix silencing logs around certain functions
  app/services/true_layer/importers/import_accounts_service.rb
  app/services/true_layer/importers/import_provider_service.rb
  app/services/true_layer/importers/import_transactions_service.rb
  config/environments/test.rb
Labels: Approved

#2192 ap-1910 update end of application content
  app/views/providers/end_of_applications/show.html.erb
  config/locales/en/providers.yml
Labels: Approved, UAT

#2184 AP-1967: Initial fix for mean summary CYA page for non passported jou…
  app/views/shared/check_answers/_assets.html.erb
  config/locales/en/shared.yml
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/substantive_applications_spec.rb
  spec/services/reports/reports_creator_spec.rb
Labels: Approved, UAT

#2195 AP-1988: Fix redirect from check provider answers page to forward to …
  app/controllers/providers/check_provider_answers_controller.rb
  spec/requests/providers/check_provider_answers_spec.rb
Labels: Approved

#2193 AP-1991 Shift the citizen completed means mailer to a later stage
  app/controllers/citizens/check_answers_controller.rb
  app/jobs/bank_transactions_analyser_job.rb
  spec/jobs/bank_transactions_analyser_job_spec.rb
Labels: Approved, UAT

#2194 AP-1962 Remove overriden ccms_submission method
  app/models/concerns/base_state_machine.rb
  app/models/legal_aid_application.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/admin/legal_aid_applications/submissions_controller_spec.rb
  spec/requests/admin/submitted_applications_reports_spec.rb
  spec/services/reports/reports_creator_spec.rb
Labels: Approved, UAT

#2196 AP-1955 Reduce size of statement of case uploads
  app/forms/statement_of_cases/statement_of_case_form.rb
  config/locales/en/providers.yml
Labels: Approved, UAT

#2152 AP-1937 Citizens CYA for cash receipts and payments
  app/helpers/check_answers_helper.rb
  app/helpers/transaction_type_helper.rb
  app/models/base_aggregated_cash_transaction.rb
  app/models/cash_transaction.rb
  app/services/flow/flows/citizen_capital.rb
  app/views/citizens/cash_incomes/_cash_income_form.html.erb
  app/views/citizens/check_answers/_cash_transactions.html.erb
  app/views/citizens/check_answers/index.html.erb
  app/views/shared/check_answers/_no_link_cash_transaction_item.html.erb
  app/views/shared/partials/_revealing_checkbox.html.erb
  config/locales/cy/activemodel.yml
  config/locales/cy/citizens.yml
  config/locales/cy/dates.yml
  config/locales/cy/shared.yml
  config/locales/en/activemodel.yml
  config/locales/en/citizens.yml
  config/locales/en/shared.yml
  features/cassettes/Citizen_journey/Follow_citizen_journey_from_Accounts_page_selecting_both_income_and_outgoing_categories.yml
  features/cassettes/Citizen_journey/Follow_citizen_journey_from_Accounts_page_selecting_no_income_or_outgoing_categories.yml
  features/citizens/citizens.feature
  spec/models/cash_transaction_spec.rb
  spec/requests/citizens/check_answers_spec.rb
  spec/requests/citizens/identify_types_of_outgoings_spec.rb
  spec/services/cfe/create_capitals_service_spec.rb
Labels: Approved, UAT

#2205 AP-1990 remove jQuery from checkbox_control.js
  app/views/providers/other_assets/_form.html.erb
  app/views/shared/forms/_offline_accounts_form.html.erb
  app/views/shared/forms/_savings_and_investments_form.html.erb
  app/views/shared/forms/policy_disregards/_form.html.erb
  app/webpack/src/checkbox_control.js
  features/providers/civil_application_journey.feature
Labels: Approved, UAT

#2208 AP-1973 Convert substantive form to use new formbuilder
  app/views/providers/substantive_applications/show.html.erb
Labels: Approved, UAT

#2223 BUGFIX Use DateTime instead of Time class for strptime method
  bin/delete_ecr_images
Labels: Approved

#2224 Reapply bugfix that has somehow got lost
  app/services/cfe/create_capitals_service.rb
Labels: Approved

#2213 AP-1974 Send alert emails to apply team when mail undeliverable
  app/mailers/undeliverable_email_alert_mailer.rb
  app/services/govuk_emails/email_monitor.rb
  config/govuk_notify_templates.yml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/mailers/undeliverable_email_alert_mailer_spec.rb
  spec/services/cfe/create_capitals_service_spec.rb
  spec/services/govuk_emails/email_monitor_spec.rb
  spec/spec_helper.rb
Labels: Approved

#2210 AP-1958 Proceeding Type full text search
  app/models/proceeding_type.rb
  app/services/proceeding_type_full_text_search.rb
  db/migrate/20210126151112_add_text_searchable_to_proceeding_types.rb
  db/schema.rb
  spec/factories/proceeding_types.rb
  spec/services/proceeding_type_full_text_search_spec.rb
Labels: Approved
