Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2022-07, with the labels that each got.

#4036 Fix: Update review_application page
  app/views/shared/_review_application.html.erb
Labels: Ready for review

#4037 [AP-3283] Remove non_passported_client_instructions page
  .rubocop_todo.yml
  app/controllers/providers/non_passported_client_instructions_controller.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/non_passported_client_instructions/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  features/accessibility/provider.feature
  features/providers/civil_application_journey.feature
  features/providers/non_passported_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  spec/requests/providers/non_passported_client_instructions.rb
  spec/requests/providers/open_banking_consents_spec.rb
  spec/requests/providers/substantive_applications_spec.rb
Labels: UAT, Approved

#4035 AP-3276 remove deprecated header class
  app/helpers/application_helper.rb
Labels: UAT, Approved

#4047 add safe operator when checking for dwp_benefit type
  app/models/uploaded_evidence_collection.rb
Labels: Ready for review

#4046 AP-3269: remove Rails 7 deprecation warnings
  app/services/reports/means_report_creator.rb
  app/services/reports/merits_report_creator.rb
  app/views/providers/means_reports/show.html.erb
  app/views/providers/merits_reports/show.html.erb
Labels: UAT

#4032 AP-3203 Update none of these checkboxes content
  app/views/providers/means/other_assets/show.html.erb
  app/views/providers/means/policy_disregards/show.html.erb
  app/views/shared/forms/_types_of_income_form.html.erb
  app/views/shared/forms/_types_of_outgoings_form.html.erb
  config/locales/cy/shared.yml
  config/locales/en/citizens.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/accessibility/citizen.feature
  features/accessibility/provider.feature
  features/citizens/citizens.feature
  features/citizens/citizens_welsh.feature
  features/providers/check_ccms_autogrant.feature
  features/providers/check_multiple_employment.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/check_your_answers.feature
  features/providers/civil_application_journey.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/employed_journey.feature
  features/providers/non_passported_journey.feature
  spec/requests/providers/identify_types_of_outgoings_spec.rb
  spec/requests/providers/means/identify_types_of_incomes_spec.rb
Labels: UAT, Approved

#4048 AP-3295: Get and store client involvement type
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/legal_framework/add_proceeding_service.rb
  app/services/legal_framework/base_api_call.rb
  app/services/legal_framework/client_involvement_types/all.rb
  app/services/legal_framework/proceeding_types/all.rb
  config/ccms/attribute_block_configs/base.yml
  config/ccms/attribute_block_configs/non_passported.yml
  db/migrate/20220708123323_add_client_involvement_type_fields_to_proceedings.rb
  db/schema.rb
  spec/cassettes/LegalFramework_ClientInvolvementTypes_All/_call/makes_one_external_call.yml
  spec/cassettes/LegalFramework_ClientInvolvementTypes_All/_call/returns_the_expected_number_of_results.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/displays_errors.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/renders_index.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/calls_the_add_proceeding_service.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/redirects_to_next_step.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/when_LegalFramework_ProceedingTypesService_call_returns_false/displays_errors.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/when_LegalFramework_ProceedingTypesService_call_returns_false/renders_index.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/when_the_applicant_s_address_used_address_lookup_service/redirects_to_the_address_lookup_page.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/when_the_applicant_s_address_used_manual_entry/redirects_to_the_manual_address_page_lookup_page.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/displays_no_errors.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/does_not_displays_the_proceeding_types.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/returns_http_success.yml
  spec/data/ccms/non_default_client_involvement_type.xml
  spec/factories/proceedings.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/legal_framework/client_involvement_types/all_spec.rb
Labels: UAT, Approved

#4056 AP-3229 update savings and investments label content on CYA page
  config/locales/en/shared.yml
Labels: UAT, Approved

#4058 AP-3300 update consent content
  app/views/providers/open_banking_consents/show.html.erb
  config/locales/en/providers.yml
  features/providers/bank_statement_upload.feature
Labels: UAT, Approved

#4044 [AP-3264] provider means questions flow
  app/controllers/providers/bank_statements_controller.rb
  app/controllers/providers/means/cash_incomes_controller.rb
  app/controllers/providers/means/cash_outgoings_controller.rb
  app/controllers/providers/means/student_finances_controller.rb
  app/models/base_aggregated_cash_transaction.rb
  app/models/concerns/non_passported_state_machine.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_capital.rb
  app/services/flow/flows/provider_dependants.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/flows/provider_vehicle.rb
  app/views/providers/means_summaries/show.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_bank_statements.html.erb
  app/views/shared/check_answers/_employed_income.html.erb
  app/views/shared/check_answers/_full_employment_details.html.erb
  app/views/shared/check_answers/_student_finance.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/errors.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/accessibility/provider.feature
  features/providers/bank_statement_upload.feature
  features/providers/categorizing_bank_transactions.feature
  features/providers/check_your_answers.feature
  features/providers/civil_application_journey.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/bank_statement_uploaded_steps.rb
  spec/concerns/non_passported_state_machine_spec.rb
  spec/factories/legal_aid_applications.rb
  spec/models/aggregated_cash_income_spec.rb
  spec/models/aggregated_cash_outgoings_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/bank_statements_spec.rb
  spec/requests/providers/identify_types_of_outgoings_spec.rb
  spec/requests/providers/means/cash_incomes_controller_spec.rb
  spec/requests/providers/means/cash_outgoings_spec.rb
  spec/requests/providers/means/employed_incomes_spec.rb
  spec/requests/providers/means/full_employment_details_controller_spec.rb
  spec/requests/providers/means/has_dependants_controller_spec.rb
  spec/requests/providers/means/has_other_dependants_controller_spec.rb
  spec/requests/providers/means/identify_types_of_incomes_spec.rb
  spec/requests/providers/means/student_finance_spec.rb
Labels: Approved

#4084 Ap 3265 Bank Statement blue result panel
  app/controllers/providers/means_summaries_controller.rb
  app/controllers/providers/no_eligibility_assessments_controller.rb
  app/models/concerns/non_passported_state_machine.rb
  app/models/legal_aid_application.rb
  app/services/ccms/manual_review_determiner.rb
  app/services/flow/flows/provider_capital.rb
  app/services/results_panel_selector.rb
  app/views/providers/capital_income_assessment_results/show.html.erb
  app/views/providers/means_summaries/show.html.erb
  app/views/providers/merits_task_lists/show.html.erb
  app/views/providers/no_eligibility_assessments/show.html.erb
  app/views/providers/open_banking_consents/show.html.erb
  app/views/shared/assessment_results/_no_cfe_result.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/means_summaries_spec.rb
  spec/requests/providers/no_eligibility_assessments_spec.rb
  spec/services/ccms/manual_review_determiner_spec.rb
Labels: Approved

#4096 AP-3205 remove old content, list and translations add new title
  app/views/providers/about_the_financial_assessments/show.html.erb
  config/locales/en/providers.yml
  features/accessibility/provider.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
Labels: UAT, Approved

#4097 AP-3215 truelayer guidance
  app/controllers/providers/open_banking_guidances_controller.rb
  app/helpers/application_helper.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/open_banking_consents/show.html.erb
  app/views/providers/open_banking_guidances/show.html.erb
  app/webpack/images/open_banking/select_bank.png
  app/webpack/images/open_banking/sharing.png
  app/webpack/images/open_banking/success.png
  config/locales/en/providers.yml
  config/routes.rb
  features/accessibility/provider.feature
  features/providers/change_email.feature
  features/providers/civil_application_journey.feature
  features/providers/non_passported_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  spec/requests/providers/applicant_employed_spec.rb
  spec/requests/providers/open_banking_consents_spec.rb
  spec/requests/providers/open_banking_guidances_controller_spec.rb
  spec/requests/providers/substantive_applications_spec.rb
Labels: UAT, Approved

#4115 AP-3330 add employed applicant to feature tests for bank statement evidence
  features/providers/bank_statement_flow.feature
  features/providers/bank_statement_upload.feature
  features/step_definitions/bank_statement_uploaded_steps.rb
Labels: Approved

#4108 AP-2324: Update dependant content
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
Labels: UAT, Approved

#4092 Ap 3338 create blank cfe result for bank_statement_upload journey
  app/controllers/providers/no_eligibility_assessments_controller.rb
  app/models/cfe/base_result.rb
  app/models/cfe/empty/empty_result.rb
  app/models/cfe/empty/result.rb
  app/models/concerns/cfe_submission_state_machine.rb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  spec/factories/cfe_results/empty/mock_results.rb
  spec/factories/cfe_results/empty/results.rb
  spec/factories/legal_aid_applications.rb
  spec/models/cfe/empty/result_spec.rb
  spec/requests/providers/no_eligibility_assessments_spec.rb
Labels: UAT, Approved

#4124 AP-3358: Add feature flag for mini-loop
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  db/migrate/20220727125202_add_mini_loop_flag_to_settings.rb
  db/schema.rb
  lib/tasks/setup_db_for_testing.rake
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
Labels: Ready for review

#4129 Ap 3338 blank cfe v0 1
  app/controllers/providers/no_eligibility_assessments_controller.rb
  app/models/cfe/base_result.rb
  app/models/cfe/empty/empty_result.rb
  app/models/cfe/empty/result.rb
  app/models/concerns/cfe_submission_state_machine.rb
  app/services/results_panel_selector.rb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  spec/factories/cfe_results/empty/mock_results.rb
  spec/factories/cfe_results/empty/results.rb
  spec/factories/legal_aid_applications.rb
  spec/models/cfe/empty/result_spec.rb
  spec/requests/providers/no_eligibility_assessments_spec.rb
Labels: Approved

#4126 BUGFIX: update error message content
  config/locales/en/activemodel.yml
Labels: UAT, Approved

#4117 AP-3337 display error on field when file is not uploaded
  app/views/providers/bank_statements/show.html.erb
  app/views/shared/means/_student_finances.html.erb
Labels: UAT, Approved

#4116 Ap 3281 add csv file type to bank_statement upload
  app/forms/providers/bank_statement_form.rb
  app/webpack/src/dropzone.js
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  spec/fixtures/files/sample_csv.csv
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
  spec/requests/providers/bank_statements_spec.rb
  spec/requests/v1/bank_statements_spec.rb
  spec/requests/v1/statement_of_cases_spec.rb
Labels: UAT, Approved

#4099 Ap 3278 ccms submission
  app/models/cfe/empty/result.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/reports/reports_creator.rb
  spec/models/cfe/empty/result_spec.rb
Labels: Approved
