Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2022-10, with the labels that each got.

#4354 Define backoffLimit for jobs, with default as fallback
  helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-metrics.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: Ready for review

#4375 Fix flaky document upload spec
  features/providers/bank_statement_flow.feature
Labels: Ready for review

#4353 AP-3495: remove scope_limitation fields from Proceeding
  db/migrate/20220915131126_remove_proceedings_scope_limitations.rb
  db/schema.rb
Labels: Ready for review

#4298 AP-3468: Update default scopes input fields
  app/controllers/providers/proceeding_loop/emergency_defaults_controller.rb
  app/forms/proceedings/emergency_defaults_form.rb
  app/forms/proceedings/substantive_defaults_form.rb
  app/models/scope_limitation.rb
  app/views/providers/proceeding_loop/emergency_defaults/show.html.erb
  app/views/providers/proceeding_loop/substantive_defaults/show.html.erb
  app/views/shared/scope_limitations/_hearing_date.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/shared.yml
  spec/cassettes/Proceedings_EmergencyDefaultsForm/_save/when_the_submission_is_valid/and_the_user_accepts_the_defaults/sets_the_default_values.yml
  spec/cassettes/Proceedings_EmergencyDefaultsForm/_save/when_the_submission_is_valid/and_the_user_accepts_the_defaults/updates_the_accepted_emergency_defaults_value.yml
  spec/cassettes/Proceedings_EmergencyDefaultsForm/_save/when_the_submission_is_valid/and_the_user_accepts_the_defaults/without_calling_the_subject/creates_a_scope_limitation_object.yml
  spec/cassettes/Proceedings_EmergencyDefaultsForm/_save/when_the_submission_is_valid/and_the_user_rejects_the_defaults/sets_the_default_values.yml
  spec/cassettes/Proceedings_EmergencyDefaultsForm/_save/when_the_submission_is_valid/and_the_user_rejects_the_defaults/updates_the_accepted_emergency_defaults_value.yml
  spec/cassettes/Proceedings_EmergencyDefaultsForm/_save/when_the_submission_is_valid/and_the_user_rejects_the_defaults/without_calling_the_subject/does_not_create_a_scope_limitation_object.yml
  spec/cassettes/Proceedings_EmergencyDefaultsForm/_save/when_the_user_doesn_t_answer_the_question/without_calling_the_subject/does_not_create_a_scope_limitation_object.yml
  spec/cassettes/Proceedings_EmergencyDefaultsForm/da001_applicant_with_df.yml
  spec/cassettes/Proceedings_EmergencyDefaultsForm/da001_defendant_with_df.yml
  spec/factories/proceedings.rb
  spec/factories/scope_limitations.rb
  spec/forms/proceedings/emergency_defaults_form_spec.rb
  spec/models/scope_limitation_spec.rb
Labels: UAT, Approved

#4389 Eager load the application in CI
  .circleci/config.yml
  config/environments/test.rb
Labels: Approved

#4387 Add safe operator to chained method call
  app/controllers/providers/transactions_controller.rb
Labels: Approved

#4399 Use default Docker version in CircleCI
  .circleci/config.yml
Labels: Approved

#4355 AP-3459 regular payment frequencies
  app/models/regular_transaction.rb
  app/views/providers/means/regular_incomes/show.html.erb
  app/views/providers/means/regular_outgoings/show.html.erb
  config/locales/en/transaction_types.yml
  features/providers/enhanced_bank_upload/check_your_answers.feature
  features/providers/enhanced_bank_upload/enhanced_bank_upload_flow.feature
  spec/models/regular_transaction_spec.rb
Labels: UAT, Approved

#4386 Refresh our SimpleCov config
  .circleci/config.yml
  .simplecov
  features/support/env.rb
  lib/tasks/simplecov_parallel.rake
  spec/simplecov_helper.rb
  spec/spec_helper.rb
Labels: Ready for review, Approved, Discussion

#4405 [AP-3536] Add current and saving account totals to bank statement uploads
  app/helpers/capital_helper.rb
  app/services/flow/flows/provider_vehicle.rb
  app/views/shared/check_answers/_assets.html.erb
  features/providers/bank_statement_flow.feature
  features/providers/check_your_answers.feature
  features/providers/enhanced_bank_upload/check_your_answers.feature
  features/providers/means_report.feature
  features/step_definitions/bank_statement_uploaded_steps.rb
  features/step_definitions/enhanced_bank_upload_steps.rb
  features/step_definitions/means_report_steps.rb
Labels: Approved

#4391 [AP-3527] means report for enhanced bank upload
  app/controllers/providers/capital_income_assessment_results_controller.rb
  app/helpers/means_report_helper.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/means_reports/_with_bank_statement_uploads.html.erb
  app/views/providers/means_reports/_with_cfe_result_details.html.erb
  app/views/providers/means_reports/show.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_deductions_details.html.erb
  app/views/shared/check_answers/_income_details.html.erb
  app/views/shared/check_answers/_income_result.html.erb
  app/views/shared/check_answers/_offline_savings_accounts.html.erb
  app/views/shared/check_answers/_outgoings_details.html.erb
  app/views/shared/means_report/_item.html.erb
  config/locales/en/shared.yml
  features/providers/means_report.feature
  features/step_definitions/means_report_steps.rb
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/factories/legal_aid_applications.rb
  spec/helpers/means_report_helper_spec.rb
  spec/requests/providers/capital_income_assessment_results_spec.rb
  spec/services/reports/means_report_creator_spec.rb
Labels: Approved

#4417 Fix flaky document upload spec
  features/providers/check_your_answers.feature
Labels: Ready for review

#4388 Use strong_migrations gem
  Gemfile
  Gemfile.lock
  config/initializers/strong_migrations.rb
Labels: Ready to merge

#4423 AP-3491: Add mini-loop merits client_denial_of_allegations question
  app/controllers/providers/application_merits_task/client_denial_of_allegations_controller.rb
  app/controllers/providers/capital_assessment_results_controller.rb
  app/forms/providers/application_merits_task/client_denial_of_allegation_form.rb
  app/models/application_merits_task/allegation.rb
  app/models/legal_aid_application.rb
  app/models/legal_framework/merits_task_list.rb
  app/models/legal_framework/serializable_merits_task.rb
  app/models/legal_framework/serializable_merits_task_list.rb
  app/services/flow/flows/provider_merits.rb
  app/services/legal_framework/merits_tasks_retriever_service.rb
  app/services/legal_framework/merits_tasks_service.rb
  app/views/providers/application_merits_task/client_denial_of_allegations/show.html.erb
  app/views/providers/check_merits_answers/show.html.erb
  app/views/providers/merits_reports/show.html.erb
  app/views/providers/merits_task_lists/_task_list_section.html.erb
  app/views/shared/_review_application.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20221013114916_create_allegation.rb
  db/schema.rb
  spec/factories/allegations.rb
  spec/factories/legal_framework_merits_task_list.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/forms/providers/application_merits_task/client_denial_of_allegation_form_spec.rb
  spec/models/legal_framework/merits_task_list_spec.rb
  spec/models/legal_framework/serializable_merits_task_spec.rb
  spec/requests/providers/application_merits_task/client_denial_of_allegation_spec.rb
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
  spec/requests/providers/capital_assessment_results_spec.rb
  spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
  spec/services/legal_framework/merits_tasks_retriever_service_spec.rb
  spec/services/legal_framework/merits_tasks_service_spec.rb
Labels: Ready for review

#4437 Discussion: check DB anonymizer rules when commiting
  .overcommit.yml
Labels: Discussion

#4366 Providers can submit housing benefit data
  app/controllers/providers/means/housing_benefits_controller.rb
  app/controllers/providers/means/identify_types_of_incomes_controller.rb
  app/controllers/providers/means_summaries_controller.rb
  app/controllers/providers/transactions_controller.rb
  app/forms/providers/means/housing_benefit_form.rb
  app/forms/providers/means/regular_income_form.rb
  app/forms/providers/means/regular_outgoings_form.rb
  app/helpers/user_transactions_helper.rb
  app/models/legal_aid_application.rb
  app/models/regular_transaction.rb
  app/models/transaction_type.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/means/housing_benefits/show.html.erb
  app/views/providers/means_summaries/_income_assessment.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/helpers.yml
  config/routes.rb
  db/migrate/20220928154516_add_applicant_in_receipt_of_housing_benefit_to_legal_aid_applications.rb
  db/schema.rb
  features/providers/check_your_answers.feature
  features/providers/enhanced_bank_upload/check_your_answers.feature
  features/providers/enhanced_bank_upload/enhanced_bank_upload_flow.feature
  features/providers/means_report.feature
  features/step_definitions/check_your_answers_steps.rb
  features/step_definitions/generic_steps.rb
  features/step_definitions/means_report_steps.rb
  features/support/hooks.rb
  spec/factories/regular_transactions.rb
  spec/factories/transaction_types.rb
  spec/forms/providers/means/housing_benefit_form_spec.rb
  spec/forms/providers/means/regular_income_form_spec.rb
  spec/forms/providers/means/regular_outgoings_form_spec.rb
  spec/helpers/providers_helper_spec.rb
  spec/helpers/user_transactions_helper_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/regular_transaction_spec.rb
  spec/models/transaction_type_spec.rb
  spec/requests/providers/client_completed_means_spec.rb
  spec/requests/providers/income_summary_spec.rb
  spec/requests/providers/means/housing_benefits_controller_spec.rb
  spec/requests/providers/means/regular_outgoings_controller_spec.rb
  spec/requests/providers/transactions_spec.rb
Labels: Ready to merge

#4439 Replace `.to_not` expectations with `.not_to`
  features/step_definitions/civil_journey_steps.rb
  features/step_definitions/merits_task_steps.rb
  spec/forms/applicants/basic_details_form_spec.rb
  spec/forms/legal_aid_applications/restrictions_form_spec.rb
  spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb
  spec/helpers/policy_disregards_helper_spec.rb
  spec/models/address_spec.rb
  spec/models/applicant_spec.rb
  spec/models/cfe/v4/result_spec.rb
  spec/models/legal_framework/merits_task_list_spec.rb
  spec/requests/citizens/gather_transactions_spec.rb
  spec/requests/providers/address_selections_spec.rb
  spec/requests/providers/addresses_spec.rb
  spec/requests/providers/bank_transactions_spec.rb
  spec/requests/providers/check_benefits_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
  spec/requests/providers/limitations_spec.rb
  spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
  spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
  spec/requests/providers/submitted_applications_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/ccms/submitters/check_case_status_service_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
  spec/services/dashboard_event_handler_spec.rb
  spec/services/govuk_emails/delivery_man_spec.rb
  spec/services/hmrc/create_responses_service_spec.rb
  spec/services/malware_scanner_spec.rb
  spec/services/populators/transaction_type_populator_spec.rb
  spec/services/reports/reports_creator_spec.rb
Labels: Approved

#4435 AP-3492: Add merits question 08 - Client Undertakings
  app/controllers/providers/application_merits_task/client_offered_undertakings_controller.rb
  app/forms/providers/application_merits_task/client_offered_undertakings_form.rb
  app/models/application_merits_task/undertaking.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_merits.rb
  app/views/providers/application_merits_task/client_offered_undertakings/show.html.erb
  app/views/providers/check_merits_answers/show.html.erb
  app/views/providers/merits_reports/show.html.erb
  app/views/shared/_review_application.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20221017130541_create_undertakings.rb
  db/schema.rb
  spec/factories/undertakings.rb
  spec/forms/providers/application_merits_task/client_offered_undertakings_form_spec.rb
  spec/requests/providers/application_merits_task/client_offered_undertakings_controller_spec.rb
Labels: Approved

#4427 Fix flaky `ProviderDetailsCreator` spec
  spec/services/provider_details_creator_spec.rb
Labels: Ready for review

#4416 Remove redundant regular incomes flow
  app/services/flow/flows/provider_capital.rb
  spec/requests/providers/means/regular_incomes_controller_spec.rb
Labels: Approved

#4438 AP-3559 means summary page employment details section display logic
  app/views/providers/means_summaries/_income_assessment.html.erb
  features/providers/check_your_answers.feature
  features/providers/enhanced_bank_upload/check_your_answers.feature
  features/step_definitions/check_your_answers_steps.rb
  features/step_definitions/enhanced_bank_upload_steps.rb
Labels: UAT, Approved

#4454 ap-3525: Display new proceeding detail partial when miniloop enabled
  app/helpers/proceeding_helper.rb
  app/views/shared/_review_application.html.erb
  app/views/shared/check_answers/_proceeding_details_section.html.erb
  config/locales/en/shared.yml
  spec/helpers/proceeding_helper_spec.rb
Labels: UAT

#4432 Use `govuk_inset_text` ViewComponent helper
  app/views/admin/legal_aid_applications/index.html.erb
  app/views/citizens/consents/show.html.erb
  app/views/citizens/means_test_results/show.html.erb
  app/views/providers/addresses/show.html.erb
  app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
  app/views/providers/end_of_applications/show.html.erb
  app/views/providers/gateway_evidences/show.html.erb
  app/views/providers/means/has_dependants/show.html.erb
  app/views/providers/start/index.html.erb
  app/views/providers/transactions/show.html.erb
Labels: Approved

#4465 Use `<h2>` tag for nested fieldset headings
  app/views/providers/means/housing_benefits/show.html.erb
  app/views/providers/means/regular_incomes/show.html.erb
  app/views/providers/means/regular_outgoings/show.html.erb
Labels: Approved

#4404 Refactor regular transaction forms
  app/controllers/providers/means/housing_benefits_controller.rb
  app/forms/providers/means/housing_benefit_form.rb
  app/forms/providers/means/regular_income_form.rb
  app/forms/providers/means/regular_outgoings_form.rb
  app/forms/providers/means/regular_transaction_form.rb
  app/models/legal_aid_application.rb
  app/views/providers/means/housing_benefits/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  spec/forms/providers/means/housing_benefit_form_spec.rb
  spec/forms/providers/means/regular_outgoings_form_spec.rb
  spec/forms/providers/means/regular_transaction_form_spec.rb
  spec/requests/providers/means/housing_benefits_controller_spec.rb
Labels: Ready to merge

#4468 Fix flaky proceeding helper spec
  app/helpers/proceeding_helper.rb
  spec/helpers/proceeding_helper_spec.rb
Labels: Approved

#4463 Resolve SonarCloud Bugs
  app/views/admin/firms/index.html.erb
  app/views/citizens/legal_aid_applications/index.html.erb
  app/views/layouts/mailer.html.erb
  app/views/layouts/pdf.html.erb
  app/views/providers/means/employment_incomes/show.html.erb
  app/views/saml_idp/idp/saml_post.html.erb
  app/views/shared/_results_total_bold_row.html.erb
  app/webpack/src/details-polyfill.js
  spec/requests/providers/capital_income_assessment_results_spec.rb
Labels: Approved

#4448 AP-3561: Update merit question flow
  app/controllers/providers/application_merits_task/statement_of_cases_controller.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/merits_loop.rb
  features/cassettes/mini-loop_additional_merits_questions/Clicking_the_merits_questions_out_of_sequence_allow_a_group_to_be_completed_regardless_of_start_point.yml
  features/providers/merits_task_list.feature
  features/providers/mini-loop/merits_questions.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_framework_merits_task_list.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/requests/providers/application_merits_task/client_denial_of_allegation_spec.rb
  spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
  spec/requests/providers/application_merits_task/opponents_spec.rb
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
  spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb
  spec/services/flow/merits_loop_spec.rb
Labels: Ready for review

#4476 fix review page housing benefit
  app/views/shared/_review_application.html.erb
Labels: Approved

#4450 [AP-3654] amend housing benefit content
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  config/locales/en/transaction_types.yml
  features/providers/enhanced_bank_upload/check_your_answers.feature
  features/providers/enhanced_bank_upload/enhanced_bank_upload_flow.feature
Labels: UAT, Approved

#4466 [AP-3573] certificate page for bank statement upload
  app/views/providers/means_summaries/_income_assessment.html.erb
  app/views/providers/review_and_print_applications/show.html.erb
  app/views/providers/submitted_applications/show.html.erb
  app/views/shared/check_answers/_housing_benefit.html.erb
  app/views/shared/check_answers/_income_cash_payments.html.erb
  app/views/shared/check_answers/_income_summary.html.erb
  app/views/shared/check_answers/_outgoings_cash_payments.html.erb
  app/views/shared/review_application/_income_payments_and_assets.html.erb
  app/views/shared/review_application/_income_payments_and_assets_for_bank_statement_upload.html.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/review_and_print.feature
  features/step_definitions/generic_steps.rb
  features/step_definitions/means_report_steps.rb
  features/step_definitions/review_and_print_steps.rb
  spec/requests/providers/submitted_applications_spec.rb
Labels: Approved

#4431 Use `govuk_accordion` ViewComponent helper
  app/views/providers/capital_assessment_results/_result_details.html.erb
  app/views/providers/capital_assessment_results/show.html.erb
  app/views/providers/capital_income_assessment_results/_bank_statements.html.erb
  app/views/providers/capital_income_assessment_results/_deductions.html.erb
  app/views/providers/capital_income_assessment_results/_disposable_income.html.erb
  app/views/providers/capital_income_assessment_results/_employment_income.html.erb
  app/views/providers/capital_income_assessment_results/_other_income.html.erb
  app/views/providers/capital_income_assessment_results/_outgoings.html.erb
  app/views/providers/capital_income_assessment_results/_result_details.html.erb
  app/views/providers/capital_income_assessment_results/show.html.erb
  app/views/shared/_other_assets.html.erb
  app/views/shared/_property_results.html.erb
  app/views/shared/_restrictions.html.erb
  app/views/shared/_savings_and_investments.html.erb
  app/views/shared/_total_capital.html.erb
  app/views/shared/_vehicle_results.erb
Labels: Ready to merge

#4473 AP-3572: Update merits task handling
  app/services/legal_framework/merits_tasks_service.rb
  spec/services/legal_framework/merits_tasks_service_spec.rb
Labels: UAT, Approved
