Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2022-02, with the labels that each got.

#3399 ap-2773: Update content on Check if you can continue using this service page
  config/locales/en/providers.yml
  features/accessibility/provider.feature
  features/providers/civil_application_journey.feature
  features/providers/non_passported_journey.feature
  features/providers/pathways_from_check_your_answers.feature
Labels: Approved

#3400 AP-2735 new evidence upload page
  app/controllers/providers/check_merits_answers_controller.rb
  app/controllers/providers/uploaded_evidence_collections_controller.rb
  app/controllers/v1/uploaded_evidence_collections_controller.rb
  app/forms/providers/uploaded_evidence_collection_form.rb
  app/forms/providers/uploaded_evidence_submission_form.rb
  app/models/attachment.rb
  app/models/document_category.rb
  app/models/legal_aid_application.rb
  app/models/uploaded_evidence_collection.rb
  app/services/flow/flows/provider_merits.rb
  app/services/required_document_category_analyser.rb
  app/validators/document_category_validator.rb
  app/views/providers/uploaded_evidence_collections/_upload_evidence.html.erb
  app/views/providers/uploaded_evidence_collections/_uploaded_files.html.erb
  app/views/providers/uploaded_evidence_collections/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20220121103950_create_uploaded_evidence_collection.rb
  db/schema.rb
  spec/factories/attachments.rb
  spec/factories/uploaded_evidence_collections.rb
  spec/models/document_category_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/requests/v1/uploaded_evidence_collections_spec.rb
Labels: Approved

#3421 Fix: Use new docker image for tests
  .circleci/config.yml
  .github/workflows/ci-docker-image.yml
  docker/apply_ci.dockerfile
Labels: Approved

#3436 AP-2851 - Update UAT ingress host
  app/models/host_env.rb
  bin/uat_deploy
  helm_deploy/apply-for-legal-aid/templates/ingress.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/models/host_env_spec.rb
Labels: Approved

#3439 AP-2833: Remove Open Redirect Vulnerability
  app/controllers/citizens/legal_aid_applications_controller.rb
Labels: UAT, Approved

#3448 Fix: Welsh language features
  config/locales/cy/generic.yml
  features/citizens/citizens_welsh.feature
  features/step_definitions/citizens_steps.rb
Labels: Approved

#3441 AP-2865 Update hint text on file upload pages
  config/locales/en/providers.yml
Labels: UAT, Approved

#3447 AP-2851 Update ingress host values
  app/models/host_env.rb
  bin/uat_deploy
  helm_deploy/apply-for-legal-aid/templates/ingress.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/models/host_env_spec.rb
Labels: Ready for review

#3426 AP-2829: Add dropzone malware scanning
  app/controllers/v1/statement_of_cases_controller.rb
  app/forms/base_file_uploader_form.rb
  app/lib/malware_scanning.rb
  app/webpack/src/dropzone.js
  spec/requests/v1/statement_of_cases_spec.rb
Labels: UAT, Approved

#3442 AP-2793 update govuk frontend and formbuilder
  Gemfile
  Gemfile.lock
  app/views/citizens/cash_incomes/_cash_income_form.html.erb
  app/views/citizens/cash_outgoings/_cash_outgoings_form.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/providers/application_merits_task/involved_children/_form.html.erb
  app/views/providers/application_merits_task/statement_of_cases/_show_new.html.erb
  app/views/providers/capital_assessment_results/_result_details.html.erb
  app/views/providers/capital_income_assessment_results/_result_details.html.erb
  app/views/providers/check_provider_answers/_read_only.html.erb
  app/views/providers/employment_incomes/show.html.erb
  app/views/providers/income_summary/_income_type_item.html.erb
  app/views/providers/merits_task_lists/show.html.erb
  app/views/providers/outgoings_summary/_outgoing_type_item.html.erb
  app/views/providers/proceeding_merits_task/linked_children/show.html.erb
  app/views/providers/proceedings_types/index.html.erb
  app/views/providers/uploaded_evidence_collections/_upload_evidence.html.erb
  app/views/providers/used_multiple_delegated_functions/show.html.erb
  app/views/shared/_cash_transactions.html.erb
  app/views/shared/_show_errors.html.erb
  app/views/shared/forms/_applicant_form.html.erb
  app/views/shared/forms/_date_input_fields.html.erb
  app/views/shared/forms/_text_fields.html.erb
  app/views/shared/partials/_revealing_checkbox.html.erb
  app/webpack/src/dropzone.js
  app/webpack/src/modules/proceedings.js
  package.json
  yarn.lock
Labels: UAT, dependencies, javascript

#3463 AP-2867: Investigate admin report failing
  app/jobs/reports_uploader_job.rb
  app/services/reports/mis/application_details_report.rb
  spec/jobs/reports_uploader_job_spec.rb
  spec/services/reports/mis/application_details_report_spec.rb
Labels: Approved

#3470 BUGFIX: for UAT deploys
  db/migrate/20210407120727_create_join_table_application_proceeding_type_involved_children.rb
  db/migrate/20220204171301_delete_more_tables.rb
Labels: Approved

#3475 Fix puma and rails
  Gemfile
  Gemfile.lock
Labels: Ready for review, dependencies

#3472 Fix: Remove overnight test run
  .circleci/config.yml
  spec/spec_helper.rb
Labels: Approved

#3467 Remove commented out code
  features/step_definitions/admin_steps.rb
Labels: Approved

#3494 AP-2878: Update dropzone handling
  app/webpack/src/dropzone.js
Labels: Approved

#3462 ap-2881-blue-boxes-v2
  app/controllers/providers/capital_assessment_results_controller.rb
  app/controllers/providers/capital_income_assessment_results_controller.rb
  app/services/hmrc/mock_data/eligible_employment.json
  app/services/hmrc/mock_interface_response_service.rb
  app/services/manual_review_detailer.rb
  app/services/results_panel_selector.rb
  app/views/shared/assessment_results/_manual_check_disregards.html.erb
  app/views/shared/assessment_results/_manual_check_disregards_restrictions.html.erb
  app/views/shared/assessment_results/_manual_check_required.html.erb
  config/locales/en/shared.yml
  features/providers/civil_application_journey.feature
  spec/requests/providers/capital_assessment_results_spec.rb
  spec/requests/providers/capital_income_assessment_results_spec.rb
  spec/services/manual_review_detailer_spec.rb
  spec/services/results_panel_selector_spec.rb
Labels: Approved

#3500 Debug: Admin-report
  helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
Labels: Approved

#3495 LND: Test tidy
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  app/controllers/concerns/providers/authorizable.rb
  spec/services/hmrc/mock_interface_response_service_spec.rb
Labels: Approved

#3493 ap-2885: add path to date_client_told_incidents path step
  app/services/flow/flows/provider_merits.rb
  spec/helpers/providers_helper_spec.rb
  spec/requests/providers/application_merits_task/date_client_told_incidents_spec.rb
Labels: Approved

#3484 AP-2739 Evidence upload validation
  app/controllers/providers/uploaded_evidence_collections_controller.rb
  app/controllers/v1/uploaded_evidence_collections_controller.rb
  app/forms/providers/uploaded_evidence_collection_form.rb
  app/forms/providers/uploaded_evidence_submission_form.rb
  app/models/legal_aid_application.rb
  app/models/uploaded_evidence_collection.rb
  app/services/required_document_category_analyser.rb
  app/validators/document_category_validator.rb
  app/views/providers/uploaded_evidence_collections/_upload_evidence.html.erb
  app/views/providers/uploaded_evidence_collections/_uploaded_files.html.erb
  app/views/providers/uploaded_evidence_collections/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  db/seeds/document_categories.csv
  spec/models/document_category_spec.rb
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/requests/v1/uploaded_evidence_collections_spec.rb
  spec/services/required_document_category_analyser_spec.rb
Labels: UAT, Approved

#3496 AP-2874 evidence upload check answers page
  app/models/legal_aid_application.rb
  app/views/shared/check_answers/_merits.html.erb
  config/locales/en/shared.yml
  spec/factories/uploaded_evidence_collections.rb
  spec/models/legal_aid_application_spec.rb
Labels: UAT, Approved

#3507 AP-2908: Improve dropzone error handling
  app/controllers/providers/application_merits_task/statement_of_cases_controller.rb
  app/controllers/providers/uploaded_evidence_collections_controller.rb
  app/controllers/v1/statement_of_cases_controller.rb
  app/controllers/v1/uploaded_evidence_collections_controller.rb
  app/policies/legal_aid_application_policy.rb
  app/views/providers/application_merits_task/statement_of_cases/_show_new.html.erb
  app/views/providers/uploaded_evidence_collections/show.html.erb
  app/views/shared/forms/_error_summary_hidden.html.erb
  app/webpack/src/dropzone.js
  config/locales/en/activemodel.yml
  config/routes.rb
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/requests/v1/statement_of_cases_spec.rb
Labels: UAT, Approved

#3503 AP-2893 Skip evidence upload page if no documents required
  app/controllers/providers/check_merits_answers_controller.rb
  app/models/legal_aid_application.rb
  lib/tasks/employ.rake
  spec/factories/legal_framework_merits_task_list.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
Labels: UAT, Approved

#3522 Ap 2886 feature tests for evidence upload
  features/providers/evidence_upload.feature
  features/step_definitions/evidence_upload_steps.rb
Labels: Approved

#3521 AP-2877 Employment data alignment
  app/views/providers/employment_incomes/show.html.erb
Labels: Approved, Ready to merge
