Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2022-01, with the labels that each got.

#3233 AP-2723 Replace ApplicationProceedingTypes with Proceedings in CCMS code
  app/models/application_proceeding_type.rb
  app/models/proceeding.rb
  app/services/ccms/attribute_value_generator.rb
  spec/models/application_proceeding_type_spec.rb
  spec/models/proceeding_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: UAT, Approved

#3227 AP-2721 Remove ApplicationProceedingType from Merits Task List
  app/controllers/providers/proceeding_merits_task/attempts_to_settle_controller.rb
  app/controllers/providers/proceeding_merits_task/chances_of_success_controller.rb
  app/controllers/providers/proceeding_merits_task/linked_children_controller.rb
  app/controllers/providers/proceeding_merits_task/success_prospects_controller.rb
  app/forms/chances_of_successes/success_likely_form.rb
  app/forms/providers/proceeding_merits_task/linked_children_form.rb
  app/models/legal_framework/serializable_merits_task_list.rb
  app/models/proceeding_merits_task/attempts_to_settle.rb
  app/models/proceeding_merits_task/chances_of_success.rb
  app/services/flow/flows/provider_merits.rb
  app/services/legal_framework/merits_tasks_retriever_service.rb
  app/services/reports/mis/application_detail_csv_line.rb
  db/migrate/20211223105917_allow_null_apt_on_chances_of_success.rb
  db/schema.rb
  spec/factories/chances_of_successes.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/proceeding_merits_task/proceeding_linked_children.rb
  spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/legal_framework/serializable_merits_task_list_spec.rb
  spec/models/proceeding_merits_task/chances_of_success_spec.rb
  spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
  spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
  spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb
  spec/requests/providers/submitted_applications_spec.rb
  spec/services/legal_framework/merits_tasks_retriever_service_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: UAT, Approved

#3212 AP-2781 Remove remaining OpenStructs
  .rubocop_todo.yml
  app/helpers/user_transactions_helper.rb
  app/models/concerns/translatable_model_attribute.rb
  app/models/legal_aid_application.rb
  app/services/legal_framework/proceeding_types/proceeding.rb
  app/services/malware_scanner.rb
  config/initializers/mock_saml.rb
  lib/tasks/cucumber_steps.rake
  spec/cassettes/LegalFramework_ProceedingTypes_Proceeding/_call/has_the_expected_values_in_all_attributes.yml
  spec/cassettes/LegalFramework_ProceedingTypes_Proceeding/_call/returns_the_expected_object.yml
  spec/forms/concerns/date_field_builder_spec.rb
  spec/lib/omni_auth/strategies/moj_oauth2_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/services/govuk_emails/delivery_man_spec.rb
  spec/services/govuk_emails/email_spec.rb
  spec/services/legal_framework/proceeding_types/proceeding_spec.rb
  spec/services/pdf_converter_spec.rb
  spec/services/provider_details_creator_spec.rb
  spec/services/provider_details_retriever_spec.rb
Labels: UAT, Approved

#3267 Fix: Update staging ingress
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: Ready for review

#3262 Fix: CCMS tests were failing
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_benefits_attrs_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/ccms/submitters/add_case_service_spec.rb
  spec/services/ccms/submitters/upload_documents_service_spec.rb
Labels: Ready for review

#3223 AP-2679: Remove applicant_means_answers
  app/services/applicant_complete_means.rb
  app/services/save_applicant_means_answers.rb
  db/data_schema.rb
  db/migrate/20211222125827_remove_applicant_means_answers.rb
  db/schema.rb
  spec/requests/citizens/check_answers_spec.rb
  spec/services/save_applicant_means_answers_spec.rb
Labels: UAT, Approved

#3269 AP-2758: Migrate staging to live cluster
  .circleci/config.yml
  helm_deploy/apply-for-legal-aid/values-staging-legacy.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: Approved

#3266 Amend circleci config to delete dependabot deployments
  .circleci/config.yml
  bin/delete_dependabot_deployment
Labels: Approved

#3270 AP-2725 Do not create ApplicationProceedingTypes
  app/controllers/providers/has_other_proceedings_controller.rb
  app/controllers/providers/proceedings_types_controller.rb
  app/forms/legal_aid_applications/used_multiple_delegated_functions_form.rb
  app/forms/providers/proceeding_merits_task/attempts_to_settle_form.rb
  app/forms/providers/proceeding_merits_task/linked_children_form.rb
  app/models/application_merits_task/involved_child.rb
  app/services/legal_framework/lead_application_proceeding_type_assignment_service.rb
  app/services/legal_framework/proceeding_types_service.rb
  app/services/legal_framework/remove_proceeding_type_service.rb
  app/views/providers/proceedings_types/index.html.erb
  config/locales/en/activemodel.yml
  spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/proceedings_types_spec.rb
  spec/requests/providers/used_multiple_delegated_functions_spec.rb
  spec/services/legal_framework/lead_application_proceeding_type_assignment_service_spec.rb
  spec/services/legal_framework/proceeding_types_service_spec.rb
  spec/services/legal_framework/remove_proceeding_type_service_spec.rb
Labels: Approved

#3283 hardcode the deploy name for staging Apply
  .circleci/config.yml
  helm_deploy/apply-for-legal-aid/values-staging-legacy.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: Ready for review

#3284 update deploy name to match chart name
  .circleci/config.yml
  helm_deploy/apply-for-legal-aid/values-staging-legacy.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: Ready for review

#3297 Bump CircleCI Slack Orb to 4.5.2
  .circleci/config.yml
Labels: Approved

#3306 Fix: Flickering provider test
  spec/requests/providers/has_other_proceedings_controller_spec.rb
Labels: Approved

#3298 AP-2791: Migrate production to EKS 50/50
  .circleci/config.yml
  helm_deploy/apply-for-legal-aid/values-production-legacy.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
Labels: Approved

#3091 AP-2787: Ruby 3.1 update
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: UAT, Approved

#3285 AP-2737 Refactor ObtainDocumentIdService to use DocumentCategory
  app/models/document_category.rb
  app/models/legal_aid_application.rb
  app/services/ccms/submitters/obtain_document_id_service.rb
  spec/models/document_category_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
Labels: Approved

#3305 ap-2726: Convert specs to use proceedings
  spec/cassettes/DelegatedFunctionsDateService/sets_date_on_application_proceeding_type_records/returns_true.yml
  spec/cassettes/DelegatedFunctionsDateService/sets_date_on_application_proceeding_type_records/scheduling_reminder_mails/delegated_functions_on_at_least_one_proceeding_type/no_scheduled_mail_already_exists/creates_a_new_scheduled_mail.yml
  spec/cassettes/DelegatedFunctionsDateService/sets_date_on_application_proceeding_type_records/scheduling_reminder_mails/delegated_functions_on_at_least_one_proceeding_type/scheduled_mail_already_exists/replaces_existing_email_with_one_with_new_date.yml
  spec/cassettes/DelegatedFunctionsDateService/sets_date_on_application_proceeding_type_records/sets_the_substantive_application_deadline_on_date/DF_are_used_on_at_least_one_proceeding_type/sets_the_substantive_application_deadline_on_date.yml
  spec/cassettes/DelegatedFunctionsDateService/sets_date_on_proceeding_records/returns_true.yml
  spec/cassettes/DelegatedFunctionsDateService/sets_date_on_proceeding_records/scheduling_reminder_mails/delegated_functions_on_at_least_one_proceeding_type/no_scheduled_mail_already_exists/creates_a_new_scheduled_mail.yml
  spec/cassettes/DelegatedFunctionsDateService/sets_date_on_proceeding_records/scheduling_reminder_mails/delegated_functions_on_at_least_one_proceeding_type/scheduled_mail_already_exists/replaces_existing_email_with_one_with_new_date.yml
  spec/cassettes/DelegatedFunctionsDateService/sets_date_on_proceeding_records/sets_the_substantive_application_deadline_on_date/DF_are_used_on_at_least_one_proceeding_type/sets_the_substantive_application_deadline_on_date.yml
  spec/models/application_digest_spec.rb
  spec/rails_helper.rb
  spec/requests/providers/check_benefits_spec.rb
  spec/requests/providers/submitted_applications_spec.rb
  spec/services/delegated_functions_date_service_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: Approved

#3307 AP-2647 Remove duplicate Emergency Cost Limit section
  app/views/shared/check_answers/_merits.html.erb
  config/locales/en/shared.yml
Labels: UAT, Approved

#3316 ap-2800: migrate apply staging to live 100 percent
  .circleci/config.yml
  helm_deploy/apply-for-legal-aid/values-staging-legacy.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: Approved

#3317 AP-2806: Reset cronjob limits
  helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
Labels: Approved

#3287 AP-2736 attachment validation
  app/models/attachment.rb
  app/models/document_category.rb
  app/validators/document_category_validator.rb
  config/locales/en/activemodel.yml
  spec/models/attachment_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/validators/document_category_validator_spec.rb
Labels: Approved

#3319 AP-2801 production ingress weight to 100
  .circleci/config.yml
  helm_deploy/apply-for-legal-aid/values-live-uat.yaml
  helm_deploy/apply-for-legal-aid/values-production-legacy.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
Labels: Ready for review

#3309 AP-2802 Standardise Matter Type names on Proceeding rec
  db/data/20220111135820_standardise_matter_types.rb
  db/data_schema.rb
  db/schema.rb
Labels: Approved

#3228 AP-2774 Display solicitor answers on CYA when no HMRC data exists
  app/views/providers/means_summaries/show.html.erb
  app/views/shared/check_answers/_no_employed_income.html.erb
  config/locales/en/shared.yml
  features/providers/employed_journey.feature
Labels: UAT, Approved

#3226 AP-2775: HMRC stub data
  app/services/hmrc/create_responses_service.rb
  app/services/hmrc/mock_data/single_employment.json
  app/services/hmrc/mock_interface_response_service.rb
  config/application.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/services/hmrc/create_responses_service_spec.rb
  spec/services/hmrc/mock_interface_response_service_spec.rb
Labels: Approved

#3324 AP-2787: Ruby 3.1 update
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: Approved

#3339 AP-2769: Update Ingress API version
  helm_deploy/apply-for-legal-aid/templates/ingress.yaml
Labels: Approved

#3320 ap-2812 update specs to use with_proceedings trait
  spec/factories/legal_aid_applications.rb
  spec/factories/proceedings.rb
  spec/factory_specs/legal_aid_application_factory_spec.rb
  spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb
  spec/helpers/providers_helper_spec.rb
  spec/helpers/task_list_helper_spec.rb
  spec/mailers/submit_provider_financial_reminder_mailer_spec.rb
  spec/models/aggregated_cash_income_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/legal_framework/merits_task_list_spec.rb
  spec/requests/providers/about_the_financial_assessments_spec.rb
  spec/requests/providers/application_merits_task/date_client_told_incidents_spec.rb
  spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
  spec/requests/providers/application_merits_task/opponents_spec.rb
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
  spec/requests/providers/check_benefits_spec.rb
  spec/requests/providers/check_client_details_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/confirm_multiple_delegated_functions_dates_spec.rb
  spec/requests/providers/gateway_evidence_spec.rb
  spec/requests/providers/has_evidence_of_benefits_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/in_scope_of_laspos_controller_spec.rb
  spec/requests/providers/legal_aid_applications_spec.rb
  spec/requests/providers/means_reports_spec.rb
  spec/requests/providers/merits_reports_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/requests/providers/open_banking_consents_spec.rb
  spec/requests/providers/other_assets_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb
  spec/requests/providers/proceedings_types_spec.rb
  spec/requests/providers/received_benefit_confirmations_spec.rb
  spec/requests/providers/restrictions_spec.rb
  spec/requests/providers/substantive_applications_spec.rb
  spec/services/ccms/submitters/add_case_service_spec.rb
  spec/services/cfe/create_assessment_service_spec.rb
  spec/services/dashboard_event_handler_spec.rb
  spec/services/govuk_emails/delivery_man_spec.rb
  spec/services/legal_aid_applications/calculation_date_service_spec.rb
  spec/services/legal_framework/merits_tasks_service_spec.rb
  spec/services/reports/bank_transactions/bank_transaction_report_creator_spec.rb
  spec/services/reports/merits_report_creator_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
  spec/services/reports/mis/non_passported_applications_report_spec.rb
  spec/services/reports/reports_creator_spec.rb
  spec/services/submit_application_reminder_service_spec.rb
Labels: Approved

#3330 ap-2822 update woording on use CCMS panel
  config/locales/en/providers.yml
Labels: Approved

#3354 Implement data shortcut
  app/controllers/status_controller.rb
  config/routes.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/requests/status_spec.rb
Labels: Approved

#3353 ap-2818: Parse cfe result employment income
  app/models/cfe/v4/result.rb
  spec/factories/cfe_results/v4/mock_results.rb
  spec/factories/cfe_results/v4/results.rb
  spec/models/cfe/v4/result_spec.rb
Labels: Approved

#3299 AP-2547 Rationalise Admin Report
  app/controllers/admin/reports_controller.rb
  app/jobs/reports_uploader_job.rb
  app/models/admin_report.rb
  app/models/legal_aid_application.rb
  app/models/proceeding_merits_task/chances_of_success.rb
  app/services/reports/mis/application_detail_csv_line.rb
  app/services/reports/mis/application_details_report.rb
  app/views/admin/reports/index.html.erb
  config/routes.rb
  spec/factories/admin_report.rb
  spec/factories/admin_reports.rb
  spec/jobs/reports_uploader_job_spec.rb
  spec/requests/admin/reports_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
  spec/services/reports/mis/application_details_report_spec.rb
Labels: Approved

#3366 Fix: Update I18n-task gem
  Gemfile
  Gemfile.lock
Labels: Approved

#3368 AP-2814 Tidy up application_proceeding_types in traits
  app/models/legal_aid_application.rb
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/factory_helpers/application_proceeding_type_helper.rb
  spec/factory_specs/legal_aid_application_factory_spec.rb
  spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb
  spec/mailers/submit_application_reminder_mailer_spec.rb
  spec/requests/providers/means_summaries_spec.rb
  spec/requests/providers/used_multiple_delegated_functions_spec.rb
  spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
  spec/services/ccms/submitters/upload_documents_service_spec.rb
Labels: Approved

#3369 AP-2827 Capture exceptions during Report Generation
  app/jobs/reports_uploader_job.rb
  app/services/reports/mis/application_details_report.rb
  lib/tasks/jobs/create_admin_reports.rake
  spec/jobs/reports_uploader_job_spec.rb
  spec/services/reports/mis/application_details_report_spec.rb
Labels: Approved

#3370 AP-2815 Delete redundant APT conversion rake task
  lib/tasks/convert_application_proceeding_types.rake
Labels: Approved

#3367 AP-2752: Update the Privacy Policy text
  app/views/privacy_policy/index.html.erb
  config/locales/cy/privacy_policy.yml
  config/locales/en/privacy_policy.yml
  lib/tasks/helpers/cy_helper.rb
Labels: UAT, Approved

#3359 AP-2762 update button text on merits task list page
  app/views/providers/merits_task_lists/show.html.erb
  features/accessibility/provider.feature
  features/providers/check_ccms_autogrant.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/civil_application_journey.feature
  features/providers/merits_task_list.feature
Labels: UAT, Approved

#3382 Fix mock HMRC data generation
  app/services/hmrc/mock_interface_response_service.rb
  spec/services/hmrc/mock_interface_response_service_spec.rb
Labels: Ready for review

#3381 AP-2764: Update check_merits_answers confirmation bullet points
  app/helpers/application_helper.rb
  app/views/providers/check_merits_answers/show.html.erb
  app/views/shared/forms/_list_items.html.erb
  app/views/shared/forms/_list_with_items.html.erb
  config/locales/en/providers.yml
Labels: UAT, Approved

#3379 AP-2830 More info on recurring Sentry alert
  app/services/flow/base_flow_service.rb
Labels: Approved

#3332 AP-2734 add dropzone to statement of case page
  app/controllers/v1/statement_of_cases_controller.rb
  app/views/providers/application_merits_task/statement_of_cases/_show_new.html.erb
  app/views/providers/application_merits_task/statement_of_cases/_show_old.html.erb
  app/views/providers/application_merits_task/statement_of_cases/_uploaded_files.html.erb
  app/views/providers/application_merits_task/statement_of_cases/show.html.erb
  app/webpack/src/dropzone.js
  app/webpack/stylesheets/application.scss
  app/webpack/stylesheets/dropzone.scss
  config/locales/en/providers.yml
  config/routes.rb
  package.json
  spec/requests/v1/statement_of_cases_spec.rb
  yarn.lock
Labels: UAT, Approved

#3341 AP-2816 Send employment data to CFE
  app/controllers/providers/employment_incomes_controller.rb
  app/models/concerns/cfe_submission_state_machine.rb
  app/models/hmrc/employment.rb
  app/models/hmrc/employment_income_summary.rb
  app/models/hmrc/employment_payment.rb
  app/services/cfe/create_capitals_service.rb
  app/services/cfe/create_employments_service.rb
  app/services/cfe/submission_manager.rb
  app/services/hmrc/parsed_response/employment.rb
  app/services/hmrc/parsed_response/employment_income_summary.rb
  app/services/hmrc/parsed_response/employment_payment.rb
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant/I_am_able_to_create_a_passported_application_with_Cap_Contribs_3k_and_with_restrictions.yml
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant/I_am_able_to_create_a_passported_application_without_Cap_Contribs_and_with_no_restrictions.yml
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant_for_non_passported_applications/I_am_able_to_create_a_non_passported_application_with_cap_Contribs_3k_and_without_restrictions.yml
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant_for_non_passported_applications/I_am_able_to_create_a_non_passported_application_without_Income_or_Cap_Contribs_and_with_no_restrictions.yml
  features/cassettes/Citizen_journey/Follow_citizen_journey_from_Accounts_page_selecting_both_income_and_outgoing_categories.yml
  features/cassettes/Citizen_journey/Follow_citizen_journey_from_Accounts_page_selecting_no_income_or_outgoing_categories.yml
  features/cassettes/Citizen_journey_in_Welsh/Follow_citizen_journey_from_Accounts_page.yml
  features/cassettes/Civil_application_journeys/Allows_return_to_and_proceed_from_Delegated_Function_date_view.yml
  features/cassettes/Civil_application_journeys/Completes_the_application_using_address_lookup.yml
  features/cassettes/Civil_application_journeys/Completes_the_application_using_manual_address.yml
  features/cassettes/Civil_application_journeys/Completes_the_merits_application_for_applicant_that_does_not_receive_passported_benefits.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_clear_proceeding_on_the_proceeding_page.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_view_the_client_completed_means_answers.yml
  features/cassettes/Civil_application_journeys/I_am_instructed_to_use_CCMS_on_the_passported_journey_with_an_applicant_does_not_receive_benefits.yml
  features/cassettes/Civil_application_journeys/I_can_see_that_the_applicant_does_not_receive_benefits.yml
  features/cassettes/Civil_application_journeys/I_can_see_that_the_applicant_receives_benefits.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_address_from_the_check_your_answers_page.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_address_manually_from_the_check_your_answers_page.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_the_proceeding_type_from_the_check_your_answers_page.yml
  features/cassettes/Civil_application_journeys/No_results_returned_is_seen_on_screen_when_invalid_proceeding_search_entered.yml
  features/cassettes/Civil_application_journeys/Receives_benefits_and_completes_the_application_happy_path_no_back_button.yml
  features/cassettes/Completing_and_checking_means_answers_backwards_and_forwards/I_add_a_benefits_category_and_add_transactions_to_included_and_excluded_benefits.yml
  features/cassettes/Emergency_cost_override/Provider_is_prompted_to_override_emergency_cost_limitation.yml
  features/cassettes/Pathways_from_check_your_answers/I_go_back_and_change_the_delegated_functions_on_an_application_with_multiple_proceedings.yml
  features/cassettes/Pathways_from_check_your_answers/I_go_back_and_change_the_proceedings_on_an_application_with_multiple_proceedings.yml
  features/cassettes/Provider_accessibility/I_complete_the_non-passported_means_assessment_and_it_is_accessible.yml
  features/cassettes/Provider_accessibility/I_start_a_new_non-passported_application_and_enter_client_details.yml
  lib/tasks/employ.rake
  spec/cassettes/CFE_SubmissionManager/_call/when_the_application_is_non-passported/completes_process.yml
  spec/factories/hmrc/responses.rb
  spec/factory_helpers/hmrc_response/use_case_one.rb
  spec/models/hmrc/employment_income_summary_spec.rb
  spec/models/hmrc/employment_payment_spec.rb
  spec/models/hmrc/employment_spec.rb
  spec/services/cfe/create_cash_transactions_service_spec.rb
  spec/services/cfe/create_employments_service_spec.rb
  spec/services/cfe/submission_manager_spec.rb
  spec/services/hmrc/parsed_response/employment_income_summary_spec.rb
  spec/services/hmrc/parsed_response/employment_payment_spec.rb
  spec/services/hmrc/parsed_response/employment_spec.rb
Labels: UAT, Approved

#3380 AP-2813 Remove ProceedingType from CFE Result v4
  app/models/cfe/v4/result.rb
  spec/factories/cfe_results/v4/mock_results.rb
  spec/factories/proceedings.rb
  spec/models/cfe/v4/result_spec.rb
Labels: Approved

#3393 Fix: Update Mock HMRC data
  app/services/hmrc/create_responses_service.rb
  spec/services/hmrc/create_responses_service_spec.rb
Labels: Ready for review

#3387 AP-2750: Update the means_result content
  config/locales/en/shared.yml
  spec/requests/providers/capital_income_assessment_results_spec.rb
Labels: UAT, Approved

#3406 Fix: Update sidekiq-status and i18n - group other gem updates
  Gemfile
  Gemfile.lock
Labels: Ready for review

#3398 AP-2576 Add employment data to certificate
  app/controllers/providers/submitted_applications_controller.rb
  app/views/providers/submitted_applications/_employment_income_table.html.erb
  app/views/providers/submitted_applications/show.html.erb
  config/locales/en/providers.yml
  spec/requests/providers/submitted_applications_spec.rb
Labels: UAT, Approved

#3378 ap-2575: Add employment income to cfe results page
  app/views/providers/capital_income_assessment_results/_employment_income.html.erb
  app/views/providers/capital_income_assessment_results/_other_income.html.erb
  app/views/providers/capital_income_assessment_results/_result_details.html.erb
  config/locales/en/providers.yml
  spec/requests/providers/capital_income_assessment_results_spec.rb
Labels: Approved

#3407 Make changes to content on HMRC 'no data' page
  app/views/providers/no_employment_incomes/show.html.erb
  config/locales/en/providers.yml
Labels: UAT, Approved
