Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2022-09, with the labels that each got.

#4139 [AP-3368] Remove cash payments once the category has been removed
  app/controllers/providers/means/identify_types_of_incomes_controller.rb
  app/controllers/providers/means/identify_types_of_outgoings_controller.rb
  app/models/legal_aid_application_transaction_type.rb
  app/models/transaction_type.rb
  spec/models/legal_aid_application_transaction_type_spec.rb
  spec/models/transaction_type_spec.rb
  spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
  spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
Labels: Ready to merge

#4216 Remove `enable_employed_journey` setting
  app/controllers/admin/settings_controller.rb
  app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
  app/controllers/providers/provider_base_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/services/flow/flows/provider_start.rb
  app/services/hmrc/status_analyzer.rb
  app/views/admin/settings/show.html.erb
  app/views/providers/capital_income_assessment_results/_other_income.html.erb
  app/views/providers/capital_income_assessment_results/_result_details.html.erb
  app/views/providers/means_summaries/_income_assessment.html.erb
  app/views/providers/use_ccms_employed/index.html.erb
  app/views/shared/check_answers/_income_details.html.erb
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  features/providers/employed_journey.feature
  features/step_definitions/bank_statement_uploaded_steps.rb
  features/step_definitions/check_your_answers_steps.rb
  features/step_definitions/employment_setup_steps.rb
  features/step_definitions/means_report_steps.rb
  lib/tasks/employ.rake
  lib/tasks/setup_db_for_testing.rake
  spec/factories/legal_aid_applications.rb
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
  spec/requests/providers/applicant_employed_spec.rb
  spec/requests/providers/capital_income_assessment_results_spec.rb
  spec/requests/providers/client_completed_means_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
  spec/requests/providers/means_reports_spec.rb
  spec/requests/providers/submitted_applications_spec.rb
  spec/services/hmrc/status_analyzer_spec.rb
Labels: Approved, Ready to merge

#4253 AP-3190, AP-3193 and AP-3188: DAC accessibility changes
  app/views/providers/limitations/_cost_limits.html.erb
  app/views/providers/limitations/_proceeding_type.html.erb
  app/views/providers/limitations/_proceeding_types_with_df.html.erb
  config/locales/en/layouts.yml
Labels: Approved

#4263 AP-3197 Add table captions and make links descriptive
  app/views/citizens/accounts/index.html.erb
  app/views/providers/application_merits_task/has_other_involved_children/show.html.erb
  app/views/providers/bank_transactions/_list_selected.html.erb
  app/views/providers/check_client_details/show.html.erb
  app/views/providers/confirm_multiple_delegated_functions/show.html.erb
  app/views/providers/income_summary/_income_type_item.html.erb
  app/views/providers/means/employment_incomes/show.html.erb
  app/views/providers/outgoings_summary/_outgoing_type_item.html.erb
  config/locales/cy/citizens.yml
  config/locales/en/citizens.yml
  config/locales/en/providers.yml
Labels: Approved

#4243 Fix: Update CFE handling of capital ineligible results
  app/controllers/providers/capital_assessment_results_controller.rb
  app/controllers/providers/capital_income_assessment_results_controller.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/results_panel_selector.rb
  app/views/shared/assessment_results/_ineligible.html.erb
  config/locales/cy/shared.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  spec/factories/cfe_results/v2/mock_results.rb
  spec/factories/cfe_results/v3/mock_results.rb
  spec/factories/cfe_results/v4/mock_results.rb
  spec/factory_specs/v3/cfe_result_factory_spec.rb
  spec/factory_specs/v4/cfe_result_factory_spec.rb
  spec/models/cfe/v2/result_spec.rb
  spec/models/cfe/v3/result_spec.rb
  spec/models/cfe/v4/result_spec.rb
  spec/requests/providers/capital_assessment_results_spec.rb
  spec/requests/providers/capital_income_assessment_results_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: Approved

#4197 [AP-3423] - Add GovukComponents gem
  Gemfile
  Gemfile.lock
  app/views/layouts/application.html.erb
  config/locales/cy/layouts.yml
  config/locales/en/layouts.yml
Labels: Ready to merge

#4233 Remove `enable_employed_journey` column from settings
  app/models/setting.rb
  db/migrate/20220830144657_remove_enable_employed_journey_from_settings.rb
  db/schema.rb
Labels: Ready to merge

#4260 Fix currency validation bug
  app/services/currency_cleaner.rb
  spec/validators/currency_validator_spec.rb
Labels: Approved

#4300 Replace npm with yarn
  bin/setup
Labels: Approved

#4299 [Security] Selectively bump nth-check to 2.1.1
  package.json
  yarn.lock
Labels: Approved

#4261 Ap 3408 add los choice page
  app/controllers/providers/proceeding_loop/emergency_level_of_service_controller.rb
  app/controllers/providers/proceeding_loop/substantive_level_of_service_controller.rb
  app/forms/proceedings/emergency_level_of_service_form.rb
  app/forms/proceedings/substantive_level_of_service_form.rb
  app/services/flow/flows/provider_proceeding_loop.rb
  app/services/flow/proceeding_loop.rb
  app/services/legal_framework/proceeding_types/proceeding.rb
  app/views/providers/proceeding_loop/client_involvement_type/show.html.erb
  app/views/providers/proceeding_loop/confirm_delegated_functions_date/show.html.erb
  app/views/providers/proceeding_loop/delegated_functions/show.html.erb
  app/views/providers/proceeding_loop/emergency_defaults/show.html.erb
  app/views/providers/proceeding_loop/emergency_level_of_service/show.html.erb
  app/views/providers/proceeding_loop/substantive_defaults/show.html.erb
  app/views/providers/proceeding_loop/substantive_level_of_service/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/mini-loop/check_your_answers.feature
  features/providers/mini-loop/multi_proceeding.feature
  features/providers/mini-loop/single_proceeding.feature
  spec/cassettes/EmergencyDefaultsController/POST_/providers/applications/_legal_aid_application_id/emergency_defaults/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_the_provider_accepts_the_defaults/redirects_to_next_page.yml
  spec/cassettes/EmergencyDefaultsController/POST_/providers/applications/_legal_aid_application_id/emergency_defaults/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_the_provider_does_not_accept_the_defaults/redirects_to_next_page.yml
  spec/cassettes/EmergencyLevelOfServiceController/GET_/providers/applications/_legal_aid_application_id/emergency_level_of_service/_proceeding_id/when_the_provider_is_authenticated/displays_the_proceeding_header.yml
  spec/cassettes/EmergencyLevelOfServiceController/GET_/providers/applications/_legal_aid_application_id/emergency_level_of_service/_proceeding_id/when_the_provider_is_authenticated/returns_http_success.yml
  spec/cassettes/EmergencyLevelOfServiceController/GET_/providers/applications/_legal_aid_application_id/emergency_level_of_service/_proceeding_id/when_the_provider_is_authenticated/when_the_proceeding_has_more_than_one_possible_level_of_service/displays_a_message_that_the_level_of_service_cannot_be_changed.yml
  spec/cassettes/EmergencyLevelOfServiceController/GET_/providers/applications/_legal_aid_application_id/emergency_level_of_service/_proceeding_id/when_the_provider_is_authenticated/when_the_proceeding_has_only_one_possible_level_of_service/displays_a_message_that_the_level_of_service_cannot_be_changed.yml
  spec/cassettes/EmergencyLevelOfServiceController/POST_/providers/applications/_legal_aid_application_id/emergency_level_of_service/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/redirects_to_next_page.yml
  spec/cassettes/Proceedings_EmergencyLevelOfServiceForm/_save/when_the_submission_is_valid/and_the_user_selects_Family_Help_Higher_/updates_the_emergency_level_of_service_value.yml
  spec/cassettes/Proceedings_EmergencyLevelOfServiceForm/_save/when_the_submission_is_valid/and_the_user_selects_Full_Representation/updates_the_accepted_emergency_defaults_value.yml
  spec/cassettes/Proceedings_EmergencyLevelOfServiceForm/_save/when_the_user_doesn_t_answer_the_question/is_invalid.yml
  spec/cassettes/Proceedings_SubstantiveLevelOfServiceForm/_save/when_the_submission_is_valid/and_the_user_selects_Family_Help_Higher_/updates_the_substantive_level_of_service_value.yml
  spec/cassettes/Proceedings_SubstantiveLevelOfServiceForm/_save/when_the_submission_is_valid/and_the_user_selects_Full_Representation/updates_the_accepted_substantive_defaults_value.yml
  spec/cassettes/Proceedings_SubstantiveLevelOfServiceForm/_save/when_the_user_doesn_t_answer_the_question/generates_the_expected_error_message.yml
  spec/cassettes/Proceedings_SubstantiveLevelOfServiceForm/_save/when_the_user_doesn_t_answer_the_question/is_invalid.yml
  spec/cassettes/SubstantiveDefaultsController/POST_/providers/applications/_legal_aid_application_id/substantive_defaults/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_the_provider_accepts_the_defaults/redirects_to_next_page.yml
  spec/cassettes/SubstantiveDefaultsController/POST_/providers/applications/_legal_aid_application_id/substantive_defaults/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_the_provider_does_not_accept_the_defaults/redirects_to_next_page.yml
  spec/cassettes/SubstantiveLevelOfServiceController/GET_/providers/applications/_legal_aid_application_id/substantive_level_of_service/_proceeding_id/when_the_provider_is_authenticated/displays_the_proceeding_header.yml
  spec/cassettes/SubstantiveLevelOfServiceController/GET_/providers/applications/_legal_aid_application_id/substantive_level_of_service/_proceeding_id/when_the_provider_is_authenticated/returns_http_success.yml
  spec/cassettes/SubstantiveLevelOfServiceController/GET_/providers/applications/_legal_aid_application_id/substantive_level_of_service/_proceeding_id/when_the_provider_is_authenticated/when_the_proceeding_has_more_than_one_possible_level_of_service/displays_a_message_that_the_level_of_service_cannot_be_changed.yml
  spec/cassettes/SubstantiveLevelOfServiceController/GET_/providers/applications/_legal_aid_application_id/substantive_level_of_service/_proceeding_id/when_the_provider_is_authenticated/when_the_proceeding_has_only_one_possible_level_of_service/displays_a_message_that_the_level_of_service_cannot_be_changed.yml
  spec/cassettes/SubstantiveLevelOfServiceController/POST_/providers/applications/_legal_aid_application_id/substantive_level_of_service/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/redirects_to_next_page.yml
  spec/forms/proceedings/emergency_level_of_service_form_spec.rb
  spec/forms/proceedings/substantive_level_of_service_form_spec.rb
  spec/requests/providers/proceeding_loop/emergency_defaults_controller_spec.rb
  spec/requests/providers/proceeding_loop/emergency_level_of_service_spec.rb
  spec/requests/providers/proceeding_loop/substantive_defaults_controller_spec.rb
  spec/requests/providers/proceeding_loop/substantive_level_of_service_spec.rb
  spec/services/flow/proceeding_loop_spec.rb
Labels: UAT, Approved

#4272 AP-3457 content changes on bank statement upload page
  app/views/layouts/application.html.erb
  app/views/providers/bank_statements/_uploaded_files.html.erb
  app/views/providers/bank_statements/show.html.erb
  app/views/providers/check_merits_answers/show.html.erb
  app/views/providers/confirm_multiple_delegated_functions/show.html.erb
  app/views/providers/delete/show.html.erb
  app/views/providers/substantive_applications/show.html.erb
  app/views/shared/_applicant_declaration.html.erb
  app/views/shared/partials/_modal_dialogue.html.erb
  config/locales/en/layouts.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
Labels: UAT, Approved

#4314 Providers can submit more accurate income data
  app/controllers/providers/means/identify_types_of_incomes_controller.rb
  app/controllers/providers/means/regular_incomes_controller.rb
  app/forms/providers/means/regular_income_form.rb
  app/models/legal_aid_application.rb
  app/models/regular_transaction.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/means/regular_incomes/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20220902150227_create_regular_transactions.rb
  db/migrate/20220915104106_add_regular_transactions_indexes.rb
  db/schema.rb
  features/providers/check_your_answers.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/bank_statement_uploaded_steps.rb
  spec/factories/cash_transactions.rb
  spec/factories/regular_transactions.rb
  spec/forms/providers/means/regular_income_form_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/regular_transaction_spec.rb
  spec/requests/providers/client_completed_means_spec.rb
  spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
  spec/requests/providers/means/regular_incomes_controller_spec.rb
Labels: Ready to merge

#4325 Remove CCMS testing section from README
  README.md
Labels: Approved

#4326 Ensure correct flows use enhanced bank upload journey
  app/controllers/providers/means/identify_types_of_incomes_controller.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_capital.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/means_summaries/_income_assessment.html.erb
  features/providers/check_your_answers.feature
  features/providers/enhanced_bank_upload/check_your_answers.feature
  features/providers/enhanced_bank_upload/enhanced_bank_upload_flow.feature
  features/providers/non_passported_journey.feature
  features/step_definitions/bank_statement_uploaded_steps.rb
  features/step_definitions/enhanced_bank_upload_steps.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/bank_statements_spec.rb
  spec/requests/providers/client_completed_means_spec.rb
  spec/requests/providers/means/employed_incomes_spec.rb
  spec/requests/providers/means/full_employment_details_controller_spec.rb
  spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
Labels: Approved

#4336 [Security] Selectively bump terser to 5.15.0
  package.json
  yarn.lock
Labels: Approved

#4324 AP-3495: Refactor scope limitations
  app/forms/proceedings/emergency_defaults_form.rb
  app/forms/proceedings/substantive_defaults_form.rb
  app/models/proceeding.rb
  app/models/scope_limitation.rb
  app/services/legal_framework/add_proceeding_service.rb
  app/services/legal_framework/proceeding_types/defaults.rb
  db/anonymise/rules.rb
  db/migrate/20220915124637_create_scope_limitation.rb
  db/schema.rb
  lib/tasks/migrate_scope_limitations.rake
  spec/cassettes/LegalFramework_AddProceedingService/_call/correct_params/when_the_enable_loop_feature_flag/is_off/creates_scope_limitations.yml
  spec/cassettes/LegalFramework_AddProceedingService/_call/correct_params/when_the_enable_loop_feature_flag/is_off/does_not_create_scope_limitations.yml
  spec/cassettes/LegalFramework_AddProceedingService/_call/correct_params/when_the_enable_loop_feature_flag/is_on/does_not_create_scope_limitations.yml
  spec/cassettes/Proceedings_EmergencyDefaultsForm/_save/when_the_submission_is_valid/and_the_user_accepts_the_defaults/without_calling_the_subject/creates_a_scope_limitation_object.yml
  spec/cassettes/Proceedings_EmergencyDefaultsForm/_save/when_the_submission_is_valid/and_the_user_rejects_the_defaults/without_calling_the_subject/does_not_create_a_scope_limitation_object.yml
  spec/cassettes/Proceedings_EmergencyDefaultsForm/_save/when_the_user_doesn_t_answer_the_question/without_calling_the_subject/does_not_create_a_scope_limitation_object.yml
  spec/cassettes/Proceedings_SubstantiveDefaultsForm/_save/when_the_submission_is_valid/and_the_user_accepts_the_defaults/without_calling_the_subject/creates_a_scope_limitation_object.yml
  spec/cassettes/Proceedings_SubstantiveDefaultsForm/_save/when_the_submission_is_valid/and_the_user_rejects_the_defaults/without_calling_the_subject/does_not_create_a_scope_limitation_object.yml
  spec/cassettes/Proceedings_SubstantiveDefaultsForm/_save/when_the_user_doesn_t_answer_the_question/without_calling_the_subject/does_not_create_a_scope_limitation_object.yml
  spec/factories/proceedings.rb
  spec/factories/scope_limitations.rb
  spec/forms/proceedings/emergency_defaults_form_spec.rb
  spec/forms/proceedings/substantive_defaults_form_spec.rb
  spec/models/proceeding_spec.rb
  spec/models/scope_limitation_spec.rb
  spec/services/legal_framework/add_proceeding_service_spec.rb
  spec/services/legal_framework/proceeding_types/defaults_spec.rb
Labels: Ready for review, UAT

#4339 Use clamav in tests when explicitly tagged
  features/providers/bank_statement_upload.feature
  features/providers/evidence_upload.feature
  features/providers/merits_task_list.feature
  features/providers/statement_of_case_upload.feature
  features/support/hooks.rb
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
  spec/requests/providers/bank_statements_spec.rb
  spec/requests/providers/gateway_evidence_spec.rb
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/requests/status_spec.rb
  spec/requests/v1/bank_statements_spec.rb
  spec/requests/v1/statement_of_cases_spec.rb
  spec/requests/v1/uploaded_evidence_collections_spec.rb
  spec/services/malware_scanner_spec.rb
  spec/support/malware_scanner.rb
Labels: Ready for review, Discussion

#4302 AP-3460 enhanced bank upload regular outgoings
  app/controllers/providers/means/regular_outgoings_controller.rb
  app/forms/providers/means/regular_outgoings_form.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/means/regular_outgoings/show.html.erb
  app/views/providers/means_summaries/_income_assessment.html.erb
  app/webpack/stylesheets/dropzone.scss
  config/locales/en/activemodel.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/enhanced_bank_upload/check_your_answers.feature
  features/providers/enhanced_bank_upload/enhanced_bank_upload_flow.feature
  spec/factories/regular_transactions.rb
  spec/factories/transaction_types.rb
  spec/forms/providers/means/regular_outgoings_form_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/means/regular_outgoings_controller_spec.rb
  spec/requests/providers/means/student_finance_spec.rb
Labels: UAT, Approved

#4331 [AP-3451] retrieve cfe result using regular transactions
  app/controllers/providers/means_summaries_controller.rb
  app/models/cfe/submission.rb
  app/models/concerns/cfe_submission_state_machine.rb
  app/services/cfe/create_regular_transactions_service.rb
  app/services/cfe/service_set.rb
  app/services/flow/flows/provider_capital.rb
  spec/cassettes/CFE_SubmissionManager/_call/when_the_application_is_non-passported/completes_process.yml
  spec/cassettes/CFE_SubmissionManager/_call/when_the_application_is_non-passported_with_enhanced_bank_statement_upload_enabled/completes_process.yml
  spec/cassettes/CFE_SubmissionManager/_call/when_the_application_is_passported/completes_process.yml
  spec/factories/legal_aid_applications.rb
  spec/models/cfe/submission_spec.rb
  spec/models/concerns/cfe_submission_state_machine_spec.rb
  spec/requests/providers/means_summaries_spec.rb
  spec/services/cfe/create_regular_transactions_service_spec.rb
  spec/services/cfe/service_set_spec.rb
  spec/services/cfe/submission_manager_spec.rb
Labels: UAT, Approved
