Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2022-08, with the labels that each got.

#4137 Fix bug with miniloop settings page
  app/views/admin/settings/show.html.erb
Labels: Approved

#4125 ap-3361: add new permission for full s8
  app/models/provider.rb
  db/seeds/permissions.rb
  lib/tasks/full_section_8.rake
  spec/factories/permissions.rb
  spec/factories/providers.rb
  spec/models/provider_spec.rb
Labels: Approved

#4114 AP-3358: Start mini loop by splitting delegated functions
  app/controllers/providers/delegated_functions_controller.rb
  app/controllers/providers/in_scope_of_laspos_controller.rb
  app/forms/legal_aid_applications/used_multiple_delegated_functions_form.rb
  app/forms/proceedings/delegated_functions_form.rb
  app/helpers/proceeding_helper.rb
  app/models/proceeding.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/proceeding_loop.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/delegated_functions/show.html.erb
  app/views/shared/check_answers/_delegated_function_details.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/migrate/20220727075551_add_used_delegated_functions_to_proceeding.rb
  db/schema.rb
  features/providers/mini-loop/multi_proceeding.feature
  features/providers/mini-loop/single_proceeding.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/proceedings.rb
  spec/forms/legal_aid_applications/emergency_cost_override_form_spec.rb
  spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb
  spec/forms/proceedings/delegated_functions_form_spec.rb
  spec/helpers/proceeding_helper_spec.rb
  spec/models/aggregated_cash_income_spec.rb
  spec/models/application_digest_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/proceeding_spec.rb
  spec/requests/providers/delegated_functions_controller_spec.rb
  spec/requests/providers/in_scope_of_laspos_controller_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/flow/proceeding_loop_spec.rb
Labels: Approved

#4147 AP-3363 Filter proceeding types
  app/controllers/providers/proceedings_types_controller.rb
  app/services/legal_framework/base_api_call.rb
  app/services/legal_framework/proceeding_types/all.rb
  app/webpack/src/modules/proceedings.js
  features/cassettes/Check_multiple_employment/I_am_able_to_complete_an_application_for_an_employed_applicant_with_multiple_employers.yml
  features/cassettes/Check_pending_employment/I_am_able_to_complete_an_application_for_an_employed_applicant_with_pending_HMRC_request.yml
  features/cassettes/Check_single_employment/I_am_able_to_complete_an_application_for_an_employed_applicant_with_a_single_employer.yml
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant/I_am_able_to_create_a_passported_application_with_Cap_Contribs_3k_and_with_restrictions.yml
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant/I_am_able_to_create_a_passported_application_without_Cap_Contribs_and_with_no_restrictions.yml
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant_for_non_passported_applications/I_am_able_to_create_a_non_passported_application_with_cap_Contribs_3k_and_without_restrictions.yml
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant_for_non_passported_applications/I_am_able_to_create_a_non_passported_application_without_Income_or_Cap_Contribs_and_with_no_restrictions.yml
  features/cassettes/Civil_application_journeys/Allows_return_to_and_proceed_from_Delegated_Function_date_view.yml
  features/cassettes/Civil_application_journeys/Completes_the_application_using_address_lookup.yml
  features/cassettes/Civil_application_journeys/Completes_the_application_using_address_lookup_with_multiple_proceedings.yml
  features/cassettes/Civil_application_journeys/Completes_the_application_using_manual_address.yml
  features/cassettes/Civil_application_journeys/Completes_the_merits_application_for_applicant_that_does_not_receive_passported_benefits.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_clear_proceeding_on_the_proceeding_page.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_view_the_client_completed_means_answers.yml
  features/cassettes/Civil_application_journeys/I_am_instructed_to_use_CCMS_on_the_passported_journey_with_an_applicant_does_not_receive_benefits.yml
  features/cassettes/Civil_application_journeys/I_can_see_that_the_applicant_does_not_receive_benefits.yml
  features/cassettes/Civil_application_journeys/I_can_see_that_the_applicant_receives_benefits.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_address_from_the_check_your_answers_page.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_address_manually_from_the_check_your_answers_page.yml
  features/cassettes/Civil_application_journeys/I_want_to_change_the_proceeding_type_from_the_check_your_answers_page.yml
  features/cassettes/Civil_application_journeys/No_results_returned_is_seen_on_screen_when_invalid_proceeding_search_entered.yml
  features/cassettes/Civil_application_journeys/Receives_benefits_and_completes_the_application_happy_path_no_back_button.yml
  features/cassettes/Completing_and_checking_means_answers_backwards_and_forwards/I_add_a_benefits_category_and_add_transactions_to_included_and_excluded_benefits.yml
  features/cassettes/Emergency_cost_override/Provider_is_prompted_to_override_emergency_cost_limitation.yml
  features/cassettes/Pathways_from_check_your_answers/I_go_back_and_change_the_proceedings_on_an_application_with_multiple_proceedings.yml
  features/cassettes/Provider_accessibility/I_complete_the_non-passported_means_assessment_and_it_is_accessible.yml
  features/cassettes/Provider_accessibility/I_complete_the_non-passported_merits_assessment_and_it_is_accessible.yml
  features/cassettes/Provider_accessibility/I_start_a_new_non-passported_application_and_enter_client_details.yml
  spec/cassettes/LegalFramework_ProceedingTypes_All/_call/makes_one_external_call.yml
  spec/cassettes/LegalFramework_ProceedingTypes_All/_call/returns_the_expected_number_of_results.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/displays_errors.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/renders_index.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/calls_the_add_proceeding_service.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/redirects_to_next_step.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/when_LegalFramework_ProceedingTypesService_call_returns_false/displays_errors.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/when_LegalFramework_ProceedingTypesService_call_returns_false/renders_index.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/when_the_applicant_s_address_used_address_lookup_service/redirects_to_the_address_lookup_page.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/when_the_applicant_s_address_used_manual_entry/redirects_to_the_manual_address_page_lookup_page.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/displays_no_errors.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/does_not_displays_the_proceeding_types.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/returns_http_success.yml
  spec/services/legal_framework/proceeding_types/all_spec.rb
Labels: Approved

#4148 AP-3359: Add client involvement type to mini loop
  app/controllers/providers/proceeding_loop/client_involvement_type_controller.rb
  app/forms/proceedings/client_involvement_type_form.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/proceeding_loop.rb
  app/services/legal_framework/add_proceeding_service.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/proceeding_loop/client_involvement_type/show.html.erb
  app/views/shared/check_answers/_client_involvement_type_details.html.erb
  app/views/shared/check_answers/_delegated_function_details.erb
  app/views/shared/check_answers/_proceeding_details.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  features/cassettes/mini-loop/When_the_application_has_a_single_proceeding_and_I_m_going_to_use_delegated_functions.yml
  features/cassettes/mini-loop/When_the_application_has_a_single_proceeding_and_I_m_not_using_delegated_functions.yml
  features/cassettes/mini-loop/When_the_application_has_a_single_proceeding_and_I_m_using_delegated_functions.yml
  features/providers/mini-loop/multi_proceeding.feature
  features/providers/mini-loop/single_proceeding.feature
  spec/cassettes/ClientInvolvementTypeController/GET_/providers/applications/_legal_aid_application_id/client_involvement_type/_proceeding_id/when_the_provider_is_authenticated/displays_the_heading.yml
  spec/cassettes/ClientInvolvementTypeController/GET_/providers/applications/_legal_aid_application_id/client_involvement_type/_proceeding_id/when_the_provider_is_authenticated/returns_http_success.yml
  spec/cassettes/ClientInvolvementTypeController/POST_/providers/applications/_legal_aid_application_id/client_involvement_type/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/redirects_to_next_page.yml
  spec/cassettes/Proceedings_ClientInvolvementTypeForm/_save/when_the_client_involvement_type_submitted_is_valid/updates_the_proceeding.yml
  spec/forms/proceedings/client_involvement_type_form_spec.rb
  spec/requests/providers/in_scope_of_laspos_controller_spec.rb
  spec/requests/providers/proceeding_loop/client_involvement_type_controller_spec.rb
  spec/services/flow/proceeding_loop_spec.rb
Labels: UAT, Approved

#4155 Refactor Delegated Functions into mini-loop
  app/controllers/providers/delegated_functions_controller.rb
  app/controllers/providers/proceeding_loop/delegated_functions_controller.rb
  app/helpers/proceeding_helper.rb
  app/views/providers/proceeding_loop/delegated_functions/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  spec/requests/providers/proceeding_loop/delegated_functions_controller_spec.rb
Labels: Ready for review

#4162 AP-3378 add bank_statement filenames to review page
  app/views/providers/means_summaries/show.html.erb
  app/views/shared/_review_application.html.erb
  app/views/shared/check_answers/_bank_statements.html.erb
  config/locales/en/shared.yml
  features/providers/check_your_answers.feature
Labels: UAT, Approved

#4151 [AP-3386] means report changes for bank statement uploads
  app/models/legal_aid_application.rb
  app/views/providers/means_reports/_caseworker_review.html.erb
  app/views/providers/means_reports/_dependants.html.erb
  app/views/providers/means_reports/_income_cash_payments.html.erb
  app/views/providers/means_reports/_income_categories.html.erb
  app/views/providers/means_reports/_outgoings_cash_payments.html.erb
  app/views/providers/means_reports/_outgoings_categories.html.erb
  app/views/providers/means_reports/_proceeding_eligibility.html.erb
  app/views/providers/means_reports/_receives_benefits.html.erb
  app/views/providers/means_reports/_student_finance.html.erb
  app/views/providers/means_reports/_with_cfe_result_details.html.erb
  app/views/providers/means_reports/_without_cfe_result_details.erb
  app/views/providers/means_reports/show.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_bank_statements.html.erb
  app/views/shared/check_answers/_capital_result.html.erb
  app/views/shared/check_answers/_client_details.html.erb
  app/views/shared/check_answers/_deductions_details.html.erb
  app/views/shared/check_answers/_employed_income.html.erb
  app/views/shared/check_answers/_full_employment_details.html.erb
  app/views/shared/check_answers/_income_details.html.erb
  app/views/shared/check_answers/_income_result.html.erb
  app/views/shared/check_answers/_no_link_long_item.html.erb
  app/views/shared/check_answers/_outgoings_details.html.erb
  app/views/shared/check_answers/_property.html.erb
  app/views/shared/check_answers/_restrictions.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  config/locales/en/providers.yml
  features/providers/means_report.feature
  features/step_definitions/means_report_steps.rb
  spec/factories/attachments.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/identify_types_of_outgoings_spec.rb
  spec/requests/providers/means/employed_incomes_spec.rb
  spec/requests/providers/means/has_dependants_controller_spec.rb
  spec/requests/providers/means/has_other_dependants_controller_spec.rb
  spec/requests/providers/means/identify_types_of_incomes_spec.rb
  spec/requests/providers/means_reports_spec.rb
  spec/spec_helper.rb
Labels: Approved

#4167 Ap 3399 call CFE for some bank statement journey cases
  app/controllers/providers/no_eligibility_assessments_controller.rb
  app/views/providers/means_reports/_income_cash_payments.html.erb
  app/views/providers/means_reports/_outgoings_cash_payments.html.erb
  app/views/providers/means_reports/_without_cfe_result_details.erb
  app/views/shared/check_answers/_income_result.html.erb
  config/locales/en/providers.yml
  features/providers/means_report.feature
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/requests/providers/means_reports_spec.rb
  spec/requests/providers/no_eligibility_assessments_spec.rb
Labels: UAT, Approved

#4174 revert to use CCMS UAT in Apply UAT
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: Ready for review

#4171 [AP-3399] Means report regression test and tweaks
  app/views/providers/means_reports/_with_bank_statement_uploads.html.erb
  app/views/providers/means_reports/show.html.erb
  app/views/shared/check_answers/_income_result.html.erb
  config/locales/en/providers.yml
  features/providers/means_report.feature
  features/step_definitions/means_report_steps.rb
  spec/requests/providers/means_reports_spec.rb
Labels: Approved

#4169 AP-3364: Update the ingress classname handling
  helm_deploy/apply-for-legal-aid/templates/ingress.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: Approved

#4176 AP-3339 remove cfe-v5 feature flag
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/services/cfe/base_service.rb
  app/services/cfe/create_assessment_service.rb
  app/services/cfe/submission_manager.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  db/migrate/20220812134746_remove_enable_cfe_v5_from_settings.rb
  db/schema.rb
  features/cassettes/Check_multiple_employment/I_am_able_to_complete_an_application_for_an_employed_applicant_with_multiple_employers.yml
  features/cassettes/Check_pending_employment/I_am_able_to_complete_an_application_for_an_employed_applicant_with_pending_HMRC_request.yml
  features/cassettes/Check_single_employment/I_am_able_to_complete_an_application_for_an_employed_applicant_with_a_single_employer.yml
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant/I_am_able_to_create_a_passported_application_with_Cap_Contribs_3k_and_with_restrictions.yml
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant/I_am_able_to_create_a_passported_application_without_Cap_Contribs_and_with_no_restrictions.yml
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant_for_non_passported_applications/I_am_able_to_create_a_non_passported_application_with_cap_Contribs_3k_and_without_restrictions.yml
  features/cassettes/Checking_ccms_means_does_NOT_auto_grant_for_non_passported_applications/I_am_able_to_create_a_non_passported_application_without_Income_or_Cap_Contribs_and_with_no_restrictions.yml
  features/cassettes/Civil_application_journeys/Completes_the_merits_application_for_applicant_that_does_not_receive_passported_benefits.yml
  features/cassettes/Civil_application_journeys/I_am_able_to_view_the_client_completed_means_answers.yml
  features/cassettes/Civil_application_journeys/Receives_benefits_and_completes_the_application_happy_path_no_back_button.yml
  features/cassettes/Provider_accessibility/I_complete_the_non-passported_means_assessment_and_it_is_accessible.yml
  spec/cassettes/CFE_SubmissionManager/_call/standard_submission/non-passported_application/calls_all_the_services_it_manages.yml
  spec/cassettes/CFE_SubmissionManager/_call/when_the_application_is_non-passported/completes_process.yml
  spec/cassettes/CFE_SubmissionManager/_call/when_the_application_is_passported/completes_process.yml
  spec/cassettes/Proceedings_ClientInvolvementTypeForm/_save/when_the_client_involvement_type_submitted_is_missing/generates_the_expected_error_message.yml
  spec/cassettes/Proceedings_ClientInvolvementTypeForm/_save/when_the_client_involvement_type_submitted_is_missing/is_invalid.yml
  spec/factories/employments.rb
  spec/factories/proceedings.rb
  spec/forms/proceedings/client_involvement_type_form_spec.rb
  spec/models/concerns/cfe_submission_state_machine_spec.rb
  spec/requests/admin/settings_spec.rb
  spec/services/cfe/create_assessment_service_spec.rb
  spec/services/cfe/submission_manager_spec.rb
Labels: UAT, Approved

#4095 AP-3307 Handle CCMS returning Number Not Matched
  app/services/ccms/parsers/applicant_search_response_parser.rb
  app/services/ccms/requestors/base_requestor.rb
  features/providers/bank_statement_upload.feature
  spec/data/ccms/applicant_search_response_number_not_matched.xml
  spec/services/ccms/parsers/applicant_search_response_parser_spec.rb
Labels: UAT, Approved

#4154 AP-3374: Delegated Function date confirmation
  app/controllers/providers/proceeding_loop/confirm_delegated_functions_date_controller.rb
  app/controllers/providers/proceeding_loop/delegated_functions_controller.rb
  app/forms/proceedings/delegated_functions_form.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/proceeding_loop.rb
  app/views/providers/proceeding_loop/confirm_delegated_functions_date/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  features/cassettes/mini-loop/When_the_application_has_a_single_proceeding_and_I_m_going_to_use_an_old_delegated_functions_date.yml
  features/cassettes/mini-loop/When_the_application_has_multiple_proceedings_and_I_m_going_to_use_an_old_delegated_functions_date.yml
  features/cassettes/mini-loop/When_the_application_has_multiple_proceedings_and_I_m_using_delegated_functions.yml
  features/providers/mini-loop/check_your_answers.feature
  features/providers/mini-loop/multi_proceeding.feature
  features/providers/mini-loop/single_proceeding.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/forms/proceedings/delegated_functions_form_spec.rb
  spec/requests/providers/proceeding_loop/confirm_delegated_functions_date_controller_spec.rb
  spec/requests/providers/proceeding_loop/delegated_functions_controller_spec.rb
  spec/services/flow/proceeding_loop_spec.rb
Labels: UAT, Approved

#4188 AP-3388: Add feature flag for next loop stage
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  db/migrate/20220818102535_add_loop_flag_to_settings.rb
  db/schema.rb
  lib/tasks/setup_db_for_testing.rake
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
Labels: Ready for review, Approved

#4183 Fix: Date display
  config/initializers/date_formats.rb
  spec/requests/providers/substantive_applications_spec.rb
Labels: Ready for review

#4195 Move the credits and debits scope specs to correct class
  spec/models/legal_aid_application_transaction_type_spec.rb
  spec/models/transaction_type_spec.rb
Labels: Ready for review

#4194 Add myself to seeds
  config/initializers/mock_saml.rb
  db/seeds/test_provider_populator.rb
Labels: Approved

#4193 Update README.md to improve clarity
  README.md
Labels: Approved

#4202 Remove custom rules from Rubocop config
  .rubocop.yml
Labels: Approved

#4220 [AP-3365] conditional display of cash payment CYA sections
  app/views/providers/means_summaries/_income_assessment.html.erb
  features/providers/check_your_answers.feature
Labels: Approved

#4218 Ap 3443 Add enhanced bank statement upload journey feature flag
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  config/locales/en/helpers.yml
  db/migrate/20220824162240_add_enhanced_bank_upload_feature_flag_to_settings.rb
  db/schema.rb
  lib/tasks/setup_db_for_testing.rake
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
Labels: Approved

#4217 Fix flaky rack-attack spec
  spec/requests/feedbacks_spec.rb
Labels: Approved

#4215 AP-3440: Update limitations page
  app/views/providers/limitations/_proceeding_type.html.erb
  config/locales/en/providers.yml
Labels: UAT, Approved

#4234 Remove redundant blazer db_url config
  config/application.rb
Labels: Approved

#4232 Fix: Update CFE service calls
  app/services/cfe/submission_manager.rb
  spec/services/cfe/submission_manager_spec.rb
Labels: Approved
