Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2022-11, with the labels that each got.

#4500 Send applicant employed status to CFE
  app/services/cfe/create_applicant_service.rb
  spec/services/cfe/create_applicant_service_spec.rb
Labels: Ready to merge

#4491 AP-3485: Add specific issue merits question
  app/controllers/providers/proceeding_merits_task/specific_issue_controller.rb
  app/forms/providers/proceeding_merits_task/specific_issue_form.rb
  app/models/proceeding.rb
  app/models/proceeding_merits_task/specific_issue.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/merits_loop.rb
  app/views/providers/proceeding_merits_task/specific_issue/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20221026095914_create_specific_issue.rb
  db/schema.rb
  spec/factories/legal_framework_merits_task_list.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/factories/proceedings.rb
  spec/forms/providers/proceeding_merits_task/specific_issue_form_spec.rb
  spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/specific_issue_controller_spec.rb
Labels: UAT

#4504 AP-3486: Add prohibited steps merits question
  app/controllers/providers/proceeding_merits_task/prohibited_steps_controller.rb
  app/forms/providers/proceeding_merits_task/prohibited_steps_form.rb
  app/models/proceeding.rb
  app/models/proceeding_merits_task/prohibited_steps.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/merits_loop.rb
  app/views/providers/proceeding_merits_task/prohibited_steps/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20221027065931_create_prohibited_steps.rb
  db/schema.rb
  spec/factories/legal_framework_merits_task_list.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/factories/proceedings.rb
  spec/factories/prohibited_steps.rb
  spec/forms/providers/proceeding_merits_task/prohibited_steps_form_spec.rb
  spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
  spec/requests/providers/proceeding_merits_task/prohibited_steps_controller_spec.rb
  spec/support/shared_examples/provider_auth_shared_examples.rb
Labels: Ready for review

#4499 AP-3531 better differentiate substantive from emergency on default LOS pages
  app/views/providers/proceeding_loop/emergency_defaults/show.html.erb
  app/views/providers/proceeding_loop/substantive_defaults/show.html.erb
  config/locales/en/providers.yml
  features/providers/proceeding-loop/does_not_use_delegated_functions.feature
  features/providers/proceeding-loop/uses_delegated_functions.feature
  spec/requests/providers/proceeding_loop/emergency_defaults_controller_spec.rb
Labels: UAT, Approved

#4522 AP-3198 fix form labels
  app/controllers/providers/means/outstanding_mortgages_controller.rb
  app/controllers/providers/outstanding_mortgages_controller.rb
  app/services/flow/flows/provider_property.rb
  app/views/privacy_policy/index.html.erb
  app/views/providers/applicant_bank_accounts/show.html.erb
  app/views/providers/means/outstanding_mortgages/show.html.erb
  app/views/providers/means/percentage_homes/show.html.erb
  app/views/providers/means/property_values/show.html.erb
  app/views/providers/proceeding_merits_task/attempts_to_settle/show.html.erb
  config/locales/en/privacy_policy.yml
  config/locales/en/providers.yml
  config/routes.rb
  spec/requests/providers/means/outstanding_mortgages_controller_spec.rb
  spec/requests/providers/means/property_value_spec.rb
  spec/requests/providers/means/shared_ownerships_spec.rb
Labels: Ready for review

#4523 AP-3493: Move LASPO question to merits task list
  app/controllers/providers/application_merits_task/in_scope_of_laspos_controller.rb
  app/controllers/providers/in_scope_of_laspos_controller.rb
  app/forms/legal_aid_applications/in_scope_of_laspo_form.rb
  app/forms/providers/application_merits_task/in_scope_of_laspo_form.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/merits_loop.rb
  app/views/providers/application_merits_task/in_scope_of_laspos/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/check_answers/_proceedings_details.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  features/providers/civil_application_journey.feature
  features/providers/merits_task_list.feature
  features/providers/mini-loop/multi_proceeding.feature
  features/providers/pathways_from_check_your_answers.feature
  features/providers/proceeding-loop/multi-proceeding.feature
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/models/legal_framework/merits_task_list_spec.rb
  spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
  spec/requests/providers/application_merits_task/in_scope_of_laspos_controller_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
Labels: Ready to merge

#4519 Simplify `LegalAidApplications::HasOtherProceedingsForm`
  app/forms/legal_aid_applications/has_other_proceedings_form.rb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  spec/requests/providers/has_other_proceedings_controller_spec.rb
Labels: UAT, Approved

#4528 Providers can categorise disregarded benefit transactions (again)
  app/controllers/providers/means/identify_types_of_incomes_controller.rb
  app/models/transaction_type.rb
  features/cassettes/Non-passported_applicant_journeys/Selects_and_categorises_bank_transactions_into_transaction_types.yml
  features/providers/non_passported_journey.feature
  features/support/steps_helper.rb
  spec/models/transaction_type_spec.rb
  spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
Labels: Approved, Ready to merge

#4513 Ap 3487 additional merits q3
  app/controllers/providers/application_merits_task/nature_of_urgencies_controller.rb
  app/forms/providers/application_merits_task/nature_of_urgency_form.rb
  app/models/application_merits_task/urgency.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/merits_loop.rb
  app/views/providers/application_merits_task/nature_of_urgencies/show.html.erb
  app/views/providers/check_merits_answers/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20221031111422_create_urgencies.rb
  db/schema.rb
  spec/factories/legal_framework_merits_task_list.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/forms/providers/application_merits_task/nature_of_urgency_form_spec.rb
  spec/requests/providers/application_merits_task/nature_of_urgencies_controller_spec.rb
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
Labels: Approved

#4518 [AP-3489] add "vary order" merits question 5
  app/controllers/providers/proceeding_merits_task/vary_order_controller.rb
  app/forms/providers/proceeding_merits_task/vary_order_form.rb
  app/models/proceeding.rb
  app/models/proceeding_merits_task/vary_order.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/merits_loop.rb
  app/services/legal_framework/merits_tasks_service.rb
  app/views/providers/proceeding_merits_task/vary_order/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20221101141154_create_vary_order.rb
  db/schema.rb
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/factories/legal_framework_merits_task_list.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/factories/vary_order.rb
  spec/forms/providers/proceeding_merits_task/vary_order_form_spec.rb
  spec/models/proceeding_merits_task/vary_order_spec.rb
  spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
  spec/requests/providers/proceeding_merits_task/vary_order_controller_spec.rb
Labels: Ready for review

#4554 Remove explicit builder arguments.
  app/views/providers/applicant_bank_accounts/show.html.erb
  app/views/providers/has_evidence_of_benefits/show.html.erb
  app/views/providers/proceeding_merits_task/attempts_to_settle/show.html.erb
  app/views/providers/proceeding_merits_task/linked_children/show.html.erb
  app/views/providers/proceeding_merits_task/specific_issue/show.html.erb
Labels: Ready for review

#4557 Fix: Remove TODO code block
  spec/services/legal_framework/merits_tasks_service_spec.rb
Labels: Ready for review

#4531 Add matter opposition question to merits task list
  app/controllers/providers/application_merits_task/matter_opposed_reasons_controller.rb
  app/forms/providers/application_merits_task/matter_opposed_reason_form.rb
  app/models/application_merits_task/matter_opposition.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/merits_loop.rb
  app/services/legal_framework/merits_tasks_service.rb
  app/views/providers/application_merits_task/matter_opposed_reasons/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20221102161808_create_matter_oppositions.rb
  db/migrate/20221102162032_add_matter_oppositions_index.rb
  db/schema.rb
  features/providers/merits_task_list.feature
  spec/factories/application_merits_task/matter_oppositions.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/forms/providers/application_merits_task/matter_opposed_reason_form_spec.rb
  spec/models/legal_framework/merits_task_list_spec.rb
  spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
  spec/requests/providers/application_merits_task/matter_opposed_reasons_controller_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
  spec/support/shared_examples/provider_auth_shared_examples.rb
Labels: UAT

#4558 Fix: Update overcommit rule for DB anonymisation
  .overcommit.yml
Labels: Ready for review

#4529 AP-3488 Opponent application merits task list question
  app/controllers/providers/proceeding_merits_task/opponents_application_controller.rb
  app/forms/providers/proceeding_merits_task/opponents_application_form.rb
  app/models/proceeding.rb
  app/models/proceeding_merits_task/opponents_application.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/merits_loop.rb
  app/views/providers/proceeding_merits_task/opponents_application/show.html.erb
  app/views/providers/proceeding_merits_task/prohibited_steps/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20221103164239_create_opponents_application.rb
  db/schema.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/factories/proceeding_merits_task/opponents_application.rb
  spec/forms/providers/proceeding_merits_task/opponents_application_form_spec.rb
  spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
  spec/requests/providers/proceeding_merits_task/opponents_application_controller_spec.rb
Labels: UAT, Approved

#4566 Fix flaky bank statement spec
  features/providers/check_your_answers.feature
Labels: Approved

#4577 AP-3609 add feature flag for MTR
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  db/migrate/20221110161139_add_mtr_flag_to_settings.rb
  db/schema.rb
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
Labels: UAT, Approved

#4544 ap-3524: display multiple scope limitations on limitations and
  app/helpers/proceeding_helper.rb
  app/views/providers/limitations/_proceeding_type.html.erb
  spec/helpers/proceeding_helper_spec.rb
Labels: Ready for review

#4576 Update Puma to v6.0
  Gemfile
  Gemfile.lock
Labels: UAT, Approved

#4555 [AP-3608] move national insurance number question
  app/controllers/providers/applicant_details_controller.rb
  app/controllers/providers/applicants_controller.rb
  app/controllers/providers/has_national_insurance_numbers_controller.rb
  app/controllers/providers/no_national_insurance_numbers_controller.rb
  app/forms/applicants/basic_details_form.rb
  app/forms/applicants/has_national_insurance_number_form.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/check_benefits/_applicant_details.html.erb
  app/views/providers/check_provider_answers/_standard.html.erb
  app/views/providers/has_national_insurance_numbers/show.html.erb
  app/views/providers/no_national_insurance_numbers/show.html.erb
  app/views/providers/start/index.html.erb
  app/views/shared/check_answers/_client_details.html.erb
  app/views/shared/forms/_applicant_form.html.erb
  config/locales/cy/shared.yml
  config/locales/en/activemodel.yml
  config/locales/en/generic.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/migrate/20221109161647_add_has_national_insurance_number_to_applicant.rb
  db/migrate/20221113212453_backfill_applicant_has_national_insurance_number.rb
  db/schema.rb
  features/accessibility/provider.feature
  features/cassettes/Checking_client_details_answers_backwards_and_forwards/I_am_able_to_return_and_amend_the_client_s_address.yml
  features/cassettes/No_national_insurance_number_for_applicant/I_can_see_that_the_applicant_receives_benefits.yml
  features/providers/back_button.feature
  features/providers/check_provider_answers.feature
  features/providers/civil_application_journey.feature
  features/providers/cost_override.feature
  features/providers/no_nino_flow.feature
  features/providers/pathways_from_check_your_answers.feature
  features/step_definitions/check_provider_answers_steps.rb
  features/step_definitions/civil_journey_steps.rb
  features/step_definitions/generic_steps.rb
  features/step_definitions/means_report_steps.rb
  spec/factories/applicants.rb
  spec/forms/applicants/basic_details_form_spec.rb
  spec/forms/applicants/has_national_insurance_number_form_spec.rb
  spec/requests/providers/applicant_details_spec.rb
  spec/requests/providers/applicants_spec.rb
  spec/requests/providers/check_benefits_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/concerns/draftable_spec.rb
  spec/requests/providers/has_national_insurance_numbers_controller_spec.rb
  spec/requests/providers/limitations_spec.rb
  spec/requests/providers/no_national_insurance_numbers_controller_spec.rb
Labels: Ready for review, UAT

#4593 Ignore soon to be deleted columns
  app/models/proceeding_merits_task/attempts_to_settle.rb
  app/models/proceeding_merits_task/chances_of_success.rb
Labels: Approved

#4589 Update schema.rb to reflect production
  db/schema.rb
Labels: Approved

#4595 Remove redundant proceeding type columns
  db/migrate/20221118094938_remove_application_proceeding_type_from_attempts_to_settles.rb
  db/migrate/20221118095617_remove_application_proceeding_type_from_chances_of_successes.rb
  db/schema.rb
Labels: Approved

#4568 Fix student finance irregular income bug
  app/controllers/providers/means/student_finances_controller.rb
  app/forms/student_finances/annual_amount_form.rb
  app/views/shared/review_application/_income_payments_and_assets.html.erb
  config/locales/cy/activemodel.yml
  config/locales/en/activemodel.yml
  db/migrate/20221117155146_destroy_redundant_irregular_incomes.rb
  features/providers/review_and_print.feature
  features/step_definitions/review_and_print_steps.rb
  spec/forms/student_finances/annual_amount_form_spec.rb
  spec/requests/providers/means/student_finance_spec.rb
  spec/requests/providers/means/student_finances_controller_spec.rb
Labels: UAT, Ready to merge

#4583 ap-3624: prevent duplicate scope limitations
  app/forms/proceedings/emergency_defaults_form.rb
  app/forms/proceedings/substantive_defaults_form.rb
  spec/cassettes/Proceedings_SubstantiveDefaultsForm/_save/when_the_submission_is_valid/and_the_user_accepts_the_defaults/when_the_proceeding_already_has_scope_limitations/deletes_the_existing_substantive_scope_limitations_and_creates_one_new_substantive_scope_limitation.yml
  spec/forms/proceedings/emergency_defaults_form_spec.rb
  spec/forms/proceedings/substantive_defaults_form_spec.rb
Labels: approved

#4605 Address Rubocop erblint failures in app/views/shared
  .erb-lint.yml
  app/views/shared/_applicant_declaration.html.erb
  app/views/shared/_application_ref.html.erb
  app/views/shared/_cash_transactions.html.erb
  app/views/shared/_employment_income_table.html.erb
  app/views/shared/_error.html.erb
  app/views/shared/_irregular_incomes_table.html.erb
  app/views/shared/_other_assets.html.erb
  app/views/shared/_property_results.html.erb
  app/views/shared/_provider_header_link.html.erb
  app/views/shared/_restrictions.html.erb
  app/views/shared/_savings_and_investments.html.erb
  app/views/shared/_signed_out_header_link.html.erb
  app/views/shared/_total_capital.html.erb
  app/views/shared/_worker_complete.html.erb
  app/views/shared/_worker_failed.html.erb
  app/views/shared/_worker_working.html.erb
  app/views/shared/assessment_results/_capital_and_income_contribution_required.html.erb
  app/views/shared/assessment_results/_ineligible.html.erb
  app/views/shared/assessment_results/_manual_check_required.html.erb
  app/views/shared/assessment_results/_no_cfe_result.html.erb
  app/views/shared/assessment_results/_partially_eligible_capital_income.html.erb
  app/views/shared/means/_student_finances.html.erb
  app/views/shared/means_report/_item.html.erb
  app/views/shared/page_templates/_basic_page_template.html.erb
  app/views/shared/page_templates/_default_page_template.html.erb
  app/views/shared/partials/_cookie_banner.html.erb
  app/views/shared/partials/_modal_dialogue.html.erb
  app/views/shared/partials/_notification_banner.html.erb
  app/views/shared/partials/_revealing_checkbox.html.erb
  app/views/shared/review_application/_income_payments_and_assets.html.erb
  app/views/shared/review_application/_income_payments_and_assets_for_bank_statement_upload.html.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
  app/views/shared/scope_limitations/_hearing_date.html.erb
  app/views/shared/scope_limitations/_limitation_note.html.erb
Labels: approved

#4610 Remove redundant ORM diagram
  docs/ApplicationProceedingTypesORM.png
Labels: ready for review

#4611 Use govuk_warning_text component
  app/views/providers/application_merits_task/statement_of_cases/show.html.erb
  app/views/providers/confirm_client_declarations/show.html.erb
  app/webpack/stylesheets/application.scss
  app/webpack/stylesheets/citizens/declarations.scss
  app/webpack/stylesheets/govuk-mods.scss
Labels: ready for review

#4600 Ap 3404 add new supporting evidence categories
  app/services/required_document_category_analyser.rb
  app/validators/document_category_validator.rb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  db/seeds/document_categories.csv
  spec/factories/legal_aid_applications.rb
  spec/factories/proceedings.rb
  spec/models/document_category_spec.rb
  spec/services/required_document_category_analyser_spec.rb
Labels: ready for review

#4617 Use `govuk_notification_banner` component
  app/views/providers/application_merits_task/statement_of_cases/show.html.erb
  app/views/providers/bank_statements/show.html.erb
  app/views/providers/check_provider_answers/_read_only.html.erb
  app/views/providers/cookies/show.html.erb
  app/views/providers/uploaded_evidence_collections/show.html.erb
  app/views/shared/partials/_notification_banner.html.erb
Labels: Ready to merge

#4622 Refactor age calculator spec
  app/services/age_calculator.rb
  spec/services/age_calculator_spec.rb
Labels: ready for review

#4520 Refactor routes
  config/routes.rb
Labels: approved

#4626 Remove IE conditional comments
  app/views/layouts/application.html.erb
Labels: approved

#4609 Ap 3497 multiple scope limitations ccms
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/requestors/case_add_requestor.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
Labels: UAT

#4637 AP-3593: Split opponent tidy up
  app/models/application_merits_task/opponent.rb
  db/migrate/20221122083958_remove_full_name_from_opponent.rb
  db/schema.rb
  lib/tasks/migrate_opponent_name.rake
Labels: ready for review

#4639 Fix: Opponent task errors while in progress
  app/controllers/providers/merits_task_lists_controller.rb
  app/services/legal_framework/opponent_task_update_service.rb
  spec/factories/legal_framework_merits_task_list.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/services/legal_framework/opponent_task_update_service_spec.rb
Labels: ready for review
