Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2022-12, with the labels that each got.

#4633 Ap 3659 remove domestic abuse proceeding limitation
  app/forms/legal_aid_applications/has_other_proceedings_form.rb
  app/models/legal_aid_application.rb
  app/services/legal_framework/lead_proceeding_assignment_service.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/services/legal_framework/lead_proceeding_assignment_service_spec.rb
Labels: UAT

#4664 Remove redundant dependabot ignore rule
  .github/dependabot.yml
Labels: approved

#4661 Address Rubocop erblint failures in `app/views/shared/forms`
  .erb-lint.yml
  app/views/shared/forms/_applicant_form.html.erb
  app/views/shared/forms/_cash_income_form.html.erb
  app/views/shared/forms/_cash_outgoings_form.html.erb
  app/views/shared/forms/_date_input_fields.html.erb
  app/views/shared/forms/_date_part_input_fields.html.erb
  app/views/shared/forms/_error_summary.html.erb
  app/views/shared/forms/_error_summary_hidden.html.erb
  app/views/shared/forms/_next_action_buttons.html.erb
  app/views/shared/forms/_offline_accounts_form.html.erb
  app/views/shared/forms/_radio_inputs.html.erb
  app/views/shared/forms/_text_fields.html.erb
  app/views/shared/forms/_types_of_income_form.html.erb
  app/views/shared/forms/_types_of_outgoings_form.html.erb
  app/views/shared/forms/proceedings_types/_legacy_proceeding_type_form.html.erb
  app/views/shared/forms/proceedings_types/_proceeding_type.html.erb
  app/views/shared/forms/received_benefit_confirmation/_form.html.erb
  app/views/shared/forms/revealing_checkbox/_attribute.html.erb
Labels: approved

#4652 Remove `enhanced_bank_upload` column from settings
  db/migrate/20221201085138_remove_enhanced_bank_upload_from_settings.rb
  db/schema.rb
Labels: Ready to merge

#4662 Address Rubocop erblint failures in `app/views/shared/check_answers`
  .erb-lint.yml
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_bank_statements.html.erb
  app/views/shared/check_answers/_bank_transaction_table.html.erb
  app/views/shared/check_answers/_capital_result.html.erb
  app/views/shared/check_answers/_client_details.html.erb
  app/views/shared/check_answers/_client_involvement_type_details.html.erb
  app/views/shared/check_answers/_deductions_details.html.erb
  app/views/shared/check_answers/_delegated_functions.html.erb
  app/views/shared/check_answers/_dependants.html.erb
  app/views/shared/check_answers/_emergency_costs.html.erb
  app/views/shared/check_answers/_emergency_limitations.html.erb
  app/views/shared/check_answers/_employed_income.html.erb
  app/views/shared/check_answers/_final_hearing.html.erb
  app/views/shared/check_answers/_full_employment_details.html.erb
  app/views/shared/check_answers/_housing_benefit.html.erb
  app/views/shared/check_answers/_income_cash_payments.html.erb
  app/views/shared/check_answers/_income_details.html.erb
  app/views/shared/check_answers/_income_result.html.erb
  app/views/shared/check_answers/_income_summary.html.erb
  app/views/shared/check_answers/_item.html.erb
  app/views/shared/check_answers/_level_of_service.html.erb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/check_answers/_no_link_cash_transaction_item.html.erb
  app/views/shared/check_answers/_no_link_item.html.erb
  app/views/shared/check_answers/_no_link_long_item.html.erb
  app/views/shared/check_answers/_no_link_transaction_type_item.html.erb
  app/views/shared/check_answers/_offline_savings_accounts.html.erb
  app/views/shared/check_answers/_one_link_section.html.erb
  app/views/shared/check_answers/_only_link_section.html.erb
  app/views/shared/check_answers/_outgoings_cash_payments.html.erb
  app/views/shared/check_answers/_outgoings_details.html.erb
  app/views/shared/check_answers/_proceeding_details_section.html.erb
  app/views/shared/check_answers/_proceedings_details.html.erb
  app/views/shared/check_answers/_property.html.erb
  app/views/shared/check_answers/_regular_transaction_item.html.erb
  app/views/shared/check_answers/_restrictions.html.erb
  app/views/shared/check_answers/_scope_limits.html.erb
  app/views/shared/check_answers/_student_finance.html.erb
  app/views/shared/check_answers/_substantive_costs.html.erb
  app/views/shared/check_answers/_substantive_limitations.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
Labels: approved

#4651 AP-3526: CYA update for full-loop
  app/controllers/providers/limitations_controller.rb
  app/controllers/providers/proceeding_loop/delegated_functions_controller.rb
  app/services/flow/flows/provider_proceeding_loop.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/proceeding_loop.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/limitations/_proceeding_type.html.erb
  app/views/shared/check_answers/_client_involvement_type_details.html.erb
  app/views/shared/check_answers/_delegated_function_details.erb
  app/views/shared/check_answers/_level_of_service.html.erb
  app/views/shared/check_answers/_proceeding_details.erb
  app/views/shared/check_answers/_proceedings_details.html.erb
  app/views/shared/check_answers/_scope_limits.html.erb
  features/cassettes/mini-loop_check-your-answers/When_the_application_has_multiple_proceedings_and_I_m_changing_delegated_functions.yml
  features/cassettes/mini-loop_check-your-answers/When_the_application_has_multiple_proceedings_and_I_m_using_an_old_delegated_functions_date.yml
  features/cassettes/mini-loop_check-your-answers/When_the_application_has_multiple_proceedings_and_I_m_using_delegated_functions.yml
  features/cassettes/proceeding-loop_check_provider_answers/When_I_want_to_change_something_for_an_application_that_has_multiple_proceedings.yml
  features/providers/civil_application_journey.feature
  features/providers/mini-loop/check_your_answers.feature
  features/providers/pathways_from_check_your_answers.feature
  features/providers/proceeding-loop/check_provider_answers.feature
  features/step_definitions/civil_journey_steps.rb
  spec/cassettes/EmergencyDefaultsController/POST_/providers/applications/_legal_aid_application_id/emergency_defaults/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_checking_answers/when_the_date_is_within_the_last_month/continues_through_the_sub_flow.yml
  spec/cassettes/SubstantiveDefaultsController/POST_/providers/applications/_legal_aid_application_id/substantive_defaults/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_checking_answers/when_the_date_is_within_the_last_month/continues_through_the_sub_flow.yml
  spec/cassettes/SubstantiveDefaultsController/POST_/providers/applications/_legal_aid_application_id/substantive_defaults/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_checking_answers/when_the_date_is_within_the_last_month/redirects_continuing_through_the_sub_flow.yml
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/proceeding_loop/confirm_delegated_functions_date_controller_spec.rb
  spec/requests/providers/proceeding_loop/delegated_functions_controller_spec.rb
  spec/requests/providers/proceeding_loop/emergency_defaults_controller_spec.rb
  spec/requests/providers/proceeding_loop/final_hearings_controller_spec.rb
  spec/requests/providers/proceeding_loop/substantive_defaults_controller_spec.rb
  spec/services/flow/proceeding_loop_spec.rb
Labels: Ready to merge

#4694 Remove unused styles
  app/views/shared/forms/_currency_input_wrapper.html.erb
  app/webpack/stylesheets/application.scss
  app/webpack/stylesheets/govuk-currency-input.scss
  app/webpack/stylesheets/govuk-percent-input.scss
  app/webpack/stylesheets/govuk-prefix-input.scss
  app/webpack/stylesheets/tickbox-divider.scss
Labels: ready for review

#4690 [AP-3662] Add stylesheet linting
  .circleci/config.yml
  .overcommit.yml
  app/webpack/stylesheets/admin.scss
  app/webpack/stylesheets/application.scss
  app/webpack/stylesheets/bank-selection.scss
  app/webpack/stylesheets/check-your-answers.scss
  app/webpack/stylesheets/citizens/spinner.scss
  app/webpack/stylesheets/dropzone.scss
  app/webpack/stylesheets/forms/revealing_checkboxes.scss
  app/webpack/stylesheets/govuk-currency-input.scss
  app/webpack/stylesheets/govuk-frontend.scss
  app/webpack/stylesheets/govuk-mods.scss
  app/webpack/stylesheets/govuk-percent-input.scss
  app/webpack/stylesheets/govuk-prefix-input.scss
  app/webpack/stylesheets/govuk-secondary-button.scss
  app/webpack/stylesheets/helpers.scss
  app/webpack/stylesheets/interruption-panel.scss
  app/webpack/stylesheets/language-switcher.scss
  app/webpack/stylesheets/layout.scss
  app/webpack/stylesheets/long-email-truncation.scss
  app/webpack/stylesheets/modal-dialogue.scss
  app/webpack/stylesheets/moj-banner.scss
  app/webpack/stylesheets/narrow-table-display.scss
  app/webpack/stylesheets/no-script.scss
  app/webpack/stylesheets/pagination.scss
  app/webpack/stylesheets/print-styles.scss
  app/webpack/stylesheets/providers/legal_aid_applications.scss
  app/webpack/stylesheets/providers/proceeding_types.scss
  app/webpack/stylesheets/submissions.scss
  app/webpack/stylesheets/table-category-column.scss
  app/webpack/stylesheets/table-sort.scss
  app/webpack/stylesheets/task-list.scss
  app/webpack/stylesheets/tickbox-divider.scss
  app/webpack/stylesheets/width-style-correction.scss
  package.json
  stylelint.config.js
  yarn.lock
Labels: approved

#4569 Remove unneeded forward step logic?
  app/services/flow/flows/provider_start.rb
  spec/requests/providers/applicant_details_spec.rb
Labels: approved

#4684 AP-3668: Update Client Undertaking question
  app/controllers/providers/application_merits_task/client_offered_undertakings_controller.rb
  app/forms/providers/application_merits_task/client_offered_undertakings_form.rb
  app/views/providers/application_merits_task/client_offered_undertakings/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  features/providers/mini-loop/merits_questions.feature
  spec/forms/providers/application_merits_task/client_offered_undertakings_form_spec.rb
  spec/requests/providers/application_merits_task/client_offered_undertakings_controller_spec.rb
Labels: UAT, approved

#4696 AP-3706: Update review and print heading for proceeding details
  app/views/shared/review_application/_questions_and_answers.html.erb
Labels: ready for review

#4683 [AP-3685] Modify applicant#age to apply non means tested logic
  .git-blame-ignore-revs
  app/models/applicant.rb
  features/providers/means_report.feature
  features/step_definitions/means_report_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/models/applicant_spec.rb
Labels: ready for review

#4695 AP-3083: Replace secure header gem
  Gemfile
  Gemfile.lock
  app/views/layouts/_google_tag_manager.html.erb
  app/views/layouts/application.html.erb
  app/views/providers/application_merits_task/statement_of_cases/show.html.erb
  app/views/providers/bank_statements/show.html.erb
  app/views/providers/gateway_evidences/show.html.erb
  app/views/providers/uploaded_evidence_collections/show.html.erb
  app/views/saml_idp/idp/saml_post.html.erb
  config/initializers/content_security_policy.rb
  config/initializers/secure_headers.rb
Labels: UAT

#4708 AP-3705: Fix missing substantive date
  app/controllers/providers/proceeding_loop/delegated_functions_controller.rb
  app/forms/base_form.rb
  app/forms/proceedings/delegated_functions_form.rb
  app/models/proceeding.rb
  features/cassettes/Extended_proceeding_loop/When_the_application_has_a_single_proceeding_and_I_m_going_to_use_delegated_functions.yml
  features/cassettes/Mini-loop_single_proceeding/When_the_application_has_a_single_proceeding_and_I_m_going_to_use_an_old_delegated_functions_date.yml
  features/cassettes/Mini-loop_single_proceeding/When_the_application_has_a_single_proceeding_and_I_m_going_to_use_delegated_functions.yml
  features/cassettes/mini-loop_multi_proceeding/When_the_application_has_multiple_proceedings_and_I_m_using_delegated_functions.yml
  features/providers/mini-loop/single_proceeding.feature
  spec/services/delegated_functions_date_service_spec.rb
Labels: ready for review

#4706 Remove loofah as direct dependency
  Gemfile
  Gemfile.lock
Labels: approved

#4707 Remove `regexp-examples` gem
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/models/legal_aid_application.rb
  app/services/reference_number.rb
  app/services/reference_number_creator.rb
  spec/models/legal_aid_application_spec.rb
  spec/services/reference_number_creator_spec.rb
  spec/services/reference_number_spec.rb
Labels: ready for review

#4724 Clean up factory associations
  spec/factories/cfe_results.rb
  spec/factories/cfe_results/empty/results.rb
  spec/factories/cfe_results/v3/results.rb
  spec/factories/cfe_results/v4/results.rb
  spec/factories/cfe_results/v5/results.rb
  spec/factories/cfe_submissions.rb
  spec/factories/legal_framework_submissions.rb
  spec/factories/scope_limitations.rb
  spec/factories/submissions.rb
Labels: ready for review
