Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2022-05, with the labels that each got.

#3738 AP-2894 Refactor UploadedEvidenceCollectionsController
  app/controllers/providers/uploaded_evidence_collections_controller.rb
  app/services/uploaded_evidence/base.rb
  app/services/uploaded_evidence/deletion_service.rb
  app/services/uploaded_evidence/draft_service.rb
  app/services/uploaded_evidence/list_service.rb
  app/services/uploaded_evidence/populate_upload_form_service.rb
  app/services/uploaded_evidence/save_and_continue_service.rb
  app/services/uploaded_evidence/uploader_service.rb
  app/views/providers/uploaded_evidence_collections/show.html.erb
  spec/cassettes/Providers_CheckProviderAnswersController/POST_/providers/applications/_legal_aid_application_id/check_provider_answers/reset/when_the_provider_is_authenticated/changes_the_stage_back_to_entering_applicant_details.yml
  spec/cassettes/Providers_CheckProviderAnswersController/POST_/providers/applications/_legal_aid_application_id/check_provider_answers/reset/when_the_provider_is_authenticated/redirects_back.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/the_applicant_s_address_used_manual_entry/redirects_to_the_manual_address_page_lookup_page.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/the_applicant_s_address_used_s_address_lookup_service/redirects_to_the_address_lookup_page.yml
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/services/uploaded_evidence/base_spec.rb
  spec/services/uploaded_evidence/deletion_service_spec.rb
  spec/services/uploaded_evidence/draft_service_spec.rb
  spec/services/uploaded_evidence/list_service_spec.rb
  spec/services/uploaded_evidence/populate_upload_form_service_spec.rb
  spec/services/uploaded_evidence/save_and_continue_service_spec.rb
Labels: UAT, Approved

#3744 Ap 2880 signature process
  app/controllers/providers/check_merits_answers_controller.rb
  app/controllers/providers/confirm_client_declarations_controller.rb
  app/controllers/providers/review_and_print_applications_controller.rb
  app/forms/legal_aid_applications/confirm_client_declaration_form.rb
  app/helpers/application_helper.rb
  app/services/flow/flows/provider_merits.rb
  app/views/providers/check_merits_answers/show.html.erb
  app/views/providers/confirm_client_declarations/show.html.erb
  app/views/providers/review_and_print_applications/show.html.erb
  app/views/providers/submitted_applications/show.html.erb
  app/views/shared/_employment_income_table.html.erb
  app/views/shared/_irregular_incomes_table.html.erb
  app/views/shared/_review_application.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/migrate/20220420073516_add_client_declaration_confirmed_at_to_legal_aid_application.rb
  db/schema.rb
  features/accessibility/provider.feature
  features/providers/check_ccms_autogrant.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/civil_application_journey.feature
  features/providers/merits_task_list.feature
  spec/forms/legal_aid_applications/confirm_client_declaration_form_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/confirm_client_declarations_controller_spec.rb
  spec/requests/providers/review_and_print_applications_controller_spec.rb
  spec/requests/providers/submitted_applications_spec.rb
Labels: UAT, Approved

#3740 Update ruby version to 3.1.2
  .circleci/config.yml
  .circleci/docker_build
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  docker/apply_base.dockerfile
  docker/apply_ci.dockerfile
Labels: Ready for review, Approved

#3783 Fix: Update Cronjob api version
  helm_deploy/apply-for-legal-aid/templates/.dashboard_template_cron.yaml.sample
  helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-metrics.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
Labels: Approved

#3801 ap-2968: update cloud-platform docker image
  .circleci/config.yml
Labels: Ready for review

#3797 Fix: Rate limiting feedback
  Gemfile
  Gemfile.lock
  app/mailers/feedback_mailer.rb
  config/application.rb
  config/initializers/rack_attack.rb
  spec/requests/feedbacks_spec.rb
Labels: Approved

#3798 Add team members as default dependabot code reviewers
  .github/dependabot.yml
Labels: Approved

#3806 Fix: Jest updates
  package.json
  yarn.lock
Labels: Approved

#3802 Rubocop fixes
  .rubocop_todo.yml
  spec/services/ccms/requestors/applicant_add_requestor_spec.rb
  spec/services/ccms/requestors/applicant_add_status_requestor_spec.rb
  spec/services/ccms/requestors/applicant_search_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_status_requestor_spec.rb
  spec/services/ccms/requestors/document_id_requestor_spec.rb
  spec/services/ccms/requestors/document_upload_requestor_spec.rb
  spec/services/ccms/requestors/reference_data_requestor_spec.rb
  spec/services/true_layer/api_client_spec.rb
  spec/services/true_layer/bank_data_import_service_spec.rb
  spec/services/true_layer/banks_retriever_spec.rb
  spec/services/true_layer/importers/import_account_balance_service_spec.rb
  spec/services/true_layer/importers/import_account_holders_service_spec.rb
  spec/services/true_layer/importers/import_accounts_service_spec.rb
  spec/services/true_layer/importers/import_provider_service_spec.rb
  spec/services/true_layer/importers/import_transactions_service_spec.rb
  spec/services/true_layer_error_decoder_spec.rb
  spec/services/use_ccms_arbiter_spec.rb
  spec/support/shared_context/ccms_soa_configuration_context.rb
  spec/support/shared_examples/cfe_failures_shared_examples.rb
  spec/support/shared_examples/legal_framework_failures_shared_examples.rb
  spec/validators/document_category_validator_spec.rb
  spec/workers/ccms/submission_process_worker_spec.rb
  spec/workers/hmrc/result_worker_spec.rb
  spec/workers/hmrc/submission_worker_spec.rb
  spec/workers/import_bank_data_worker_spec.rb
Labels: Approved

#3808 Fix: Rack Attack blocking
  config/initializers/rack_attack.rb
Labels: UAT, Approved

#3799 Bump rails 6.1.5 to 6.1.5.1
  Gemfile.lock
Labels: Approved

#3813 Fix: Add print button to Submitted Application page
  app/views/providers/submitted_applications/show.html.erb
  config/locales/en/providers.yml
Labels: Ready to merge

#3820 Rubocop fixes
  .rubocop_todo.yml
  spec/forms/applicants/email_form_spec.rb
  spec/forms/citizens/other_assets_form_spec.rb
  spec/forms/legal_aid_applications/dependant_form_spec.rb
  spec/forms/legal_aid_applications/percentage_home_form_spec.rb
  spec/forms/legal_aid_applications/restrictions_form_spec.rb
  spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb
  spec/forms/opponents/opponent_form_spec.rb
  spec/forms/savings_amounts/savings_amounts_form_spec.rb
Labels: Approved

#3815 Refactor tests
  app/services/use_ccms_arbiter.rb
  spec/services/use_ccms_arbiter_spec.rb
Labels: Approved

#3826 Fix: Update HMRC::CreateResponseService invocation
  app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
Labels: Ready to merge

#3831 Fix GOVUK Rubocop RSpec/ContextWording offences.
  .rubocop_todo.yml
  spec/factory_specs/legal_aid_application_factory_spec.rb
  spec/factory_specs/v4/cfe_result_factory_spec.rb
  spec/forms/outstanding_mortgage_form_spec.rb
  spec/forms/providers/application_merits_task/involved_child_form_spec.rb
Labels: Approved

#3844 Rubocop fixes
  .rubocop_todo.yml
  spec/lib/alert_manager_spec.rb
  spec/lib/authorized_ip_ranges_spec.rb
  spec/lib/id_p_settings_adapter_spec.rb
  spec/lib/omni_auth/strategies/moj_oauth2_spec.rb
  spec/lib/task_helpers/ccms_payload_yamlizer_spec.rb
  spec/mailers/feedback_mailer_spec.rb
  spec/mailers/submit_application_reminder_mailer_spec.rb
  spec/mailers/submit_citizen_financial_reminder_mailer_spec.rb
  spec/mailers/submit_provider_financial_reminder_mailer_spec.rb
  spec/models/aggregated_cash_income_spec.rb
  spec/models/aggregated_cash_outgoings_spec.rb
  spec/models/applicant_spec.rb
Labels: Approved

#3843 AP-3091 Extra employment info on application Digest
  app/models/application_digest.rb
  app/services/flow/flows/provider_capital.rb
  app/services/hmrc/status_analyzer.rb
  db/migrate/20220512125715_add_employed_field_to_digest.rb
  db/schema.rb
  features/step_definitions/civil_journey_steps.rb
  lib/tasks/digest.rake
  spec/factories/applicants.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/permissions.rb
  spec/forms/applicants/employed_form_spec.rb
  spec/models/application_digest_spec.rb
  spec/requests/providers/applicant_employed_spec.rb
  spec/requests/providers/client_completed_means_spec.rb
  spec/services/digest_extractor_spec.rb
  spec/services/hmrc/status_analyzer_spec.rb
Labels: Approved

#3846 Rubocop fixes
  .rubocop_todo.yml
  spec/models/application_digest_spec.rb
  spec/models/application_merits_task/involved_child_spec.rb
  spec/models/application_merits_task/opponent_spec.rb
  spec/models/attachment_spec.rb
  spec/models/bank_account_spec.rb
  spec/models/bank_transaction_spec.rb
  spec/models/cash_transaction_spec.rb
  spec/models/ccms/opponent_id_spec.rb
  spec/models/ccms/submission_spec.rb
  spec/models/cfe/remarked_transaction_collection_spec.rb
  spec/models/cfe/remarked_transaction_spec.rb
  spec/models/cfe/remarks_spec.rb
  spec/models/cfe/v1/result_spec.rb
  spec/models/cfe/v2/result_spec.rb
Labels: Approved

#3853 bugfix: update dependabot delete script
  .circleci/config.yml
  bin/delete_dependabot_deployment
Labels: Approved

#3854 Rubocop fixes
  .rubocop_todo.yml
  spec/models/cfe/v3/result_spec.rb
  spec/models/cfe/v4/result_spec.rb
  spec/models/concerns/cfe_submission_state_machine_spec.rb
  spec/models/concerns/translatable_model_attribute_spec.rb
  spec/models/dashboard/widget_data_providers/number_provider_firms_spec.rb
  spec/models/dashboard/widget_data_providers/percentage_declined_open_banking_spec.rb
  spec/models/dependant_spec.rb
Labels: Approved

#3863 Fix: Revert the ingress changes
  helm_deploy/apply-for-legal-aid/templates/ingress.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: Approved

#3703 AP-2640 Employed journey feature tests
  features/cassettes/check_multiple_employment/I_am_able_to_complete_an_application_for_an_employed_applicant_with_multiple_employers.yml
  features/cassettes/check_pending_employment/I_am_able_to_complete_an_application_for_an_employed_applicant_with_pending_HMRC_request.yml
  features/cassettes/check_single_employment/I_am_able_to_complete_an_application_for_an_employed_applicant_with_a_single_employer.yml
  features/providers/check_multiple_employment.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/step_definitions/employment_setup_steps.rb
  features/support/env.rb
  features/support/hooks.rb
  spec/factories/addresses.rb
  spec/factories/applicants.rb
Labels: WIP

#3860 Rubocop fixes
  .rubocop_todo.yml
  spec/models/firm_spec.rb
  spec/models/hmrc/response_spec.rb
  spec/models/host_env_spec.rb
  spec/models/irregular_income_spec.rb
  spec/models/legal_aid_application_spec.rb
Labels: Approved

#3871 Add environment mapping details
  README.md
  docs/environment_mappings.md
Labels: Approved

#3841 AP-2993 Cookies page
  app/controllers/providers/cookies_controller.rb
  app/forms/providers/cookies_form.rb
  app/helpers/google_tag_manager_helper.rb
  app/views/layouts/_footer.html.erb
  app/views/layouts/application.html.erb
  app/views/providers/application_merits_task/statement_of_cases/show.html.erb
  app/views/providers/cookies/show.html.erb
  app/views/providers/uploaded_evidence_collections/show.html.erb
  app/views/shared/partials/_delete_notification.html.erb
  app/views/shared/partials/_notification_banner.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/generic.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/migrate/20220510131202_update_provider_add_cookie_enabled.rb
  db/schema.rb
  features/providers/civil_application_journey.feature
  spec/requests/providers/cookies_controller_spec.rb
Labels: UAT, Approved

#3869 reload evidence collection before the list is populated
  app/controllers/providers/uploaded_evidence_collections_controller.rb
  features/providers/check_multiple_employment.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
Labels: Approved

#3864 Rubocop fixes
  .rubocop_todo.yml
  spec/models/legal_framework/serializable_merits_task_list_spec.rb
  spec/models/legal_framework/serializable_merits_task_spec.rb
  spec/models/other_assets_declaration_spec.rb
  spec/models/proceeding_merits_task/chances_of_success_spec.rb
  spec/models/proceeding_merits_task/proceeding_linked_child_spec.rb
  spec/models/proceeding_spec.rb
  spec/models/provider_spec.rb
  spec/models/savings_amount_spec.rb
  spec/models/scheduled_mailing_spec.rb
  spec/models/transaction_type_spec.rb
Labels: Approved

#3872 AP-2844: Update CFE routing in production
  helm_deploy/apply-for-legal-aid/values-production.yaml
Labels: Approved

#3859 AP-2363 Improve alerting around document conversion
  app/lib/sidekiq/exhausted_failure_message.rb
  app/workers/pdf_converter_worker.rb
  spec/workers/pdf_converter_worker_spec.rb
Labels: Approved

#3882 AP-2911 Update error messages
  config/locales/en/providers.yml
  spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
  spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
Labels: Approved

#3897 Rubocop fixes
  .rubocop_todo.yml
  spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/but_the_lookup_does_not_return_any_valid_results/renders_the_manual_address_selection_page.yml
  spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/performs_an_address_lookup_with_the_provided_postcode.yml
  spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/renders_the_address_selection_page.yml
  spec/requests/citizens/cash_outgoings_spec.rb
  spec/requests/citizens/check_answers_spec.rb
  spec/requests/citizens/consent_spec.rb
  spec/requests/citizens/gather_transactions_spec.rb
  spec/requests/citizens/identify_types_of_incomes_spec.rb
  spec/requests/citizens/identify_types_of_outgoings_spec.rb
  spec/requests/citizens/legal_aid_applications_spec.rb
  spec/requests/citizens/student_finance/annual_amounts_spec.rb
  spec/requests/citizens/student_finance_spec.rb
  spec/requests/errors_spec.rb
  spec/requests/feedbacks_spec.rb
  spec/requests/providers/address_lookups_spec.rb
  spec/requests/providers/address_selections_spec.rb
  spec/requests/providers/addresses_spec.rb
  spec/requests/providers/applicant_bank_accounts_spec.rb
Labels: Approved

#3881 [AP-3085] Use local github action to delete UAT release
  .github/actions/delete-uat-release/README.md
  .github/actions/delete-uat-release/action.yml
  .github/workflows/delete-uat-release.yml
Labels: Approved

#3896 AP-3130: Update ModSec handling for Statement of Case page
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: Ready to merge

#3912 Fix: Update backable cassettes
  spec/cassettes/Backable/back_path/when_we_go_back_once/has_a_link_to_the_previous_page.yml
  spec/cassettes/Backable/back_path/when_we_go_back_once/redirects_to_same_page_without_the_param.yml
  spec/cassettes/Backable/back_path/when_we_reload_the_current_page_several_times/has_a_back_link_to_the_previous_page.yml
Labels: Approved
