Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2022-04, with the labels that each got.

#3661 Tech-debt: Remove i18n action
  .github/workflows/i18n_checks.yml
Labels: Ready for review

#3663 Tech-debt: Update the code climate badges
  README.md
Labels: Approved

#3665 Fix GOVUK Rubocop Style/WordArray offences
  .rubocop_todo.yml
  app/controllers/feedback_controller.rb
  app/helpers/address_helper.rb
  app/models/attachment.rb
  app/models/document_category.rb
  db/seeds/test_provider_populator.rb
  spec/models/cfe/remarks_spec.rb
  spec/models/dashboard/widget_data_providers/applications_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/services/cfe/create_explicit_remarks_service_spec.rb
  spec/services/oauth_session_saver_spec.rb
  spec/services/reports/reports_types_creator_spec.rb
Labels: Approved

#3646 Refactor nested if statements for readability
  app/controllers/citizens/additional_accounts_controller.rb
Labels: Ready for review

#3670 AP-3024: Improve admin CFE display
  app/helpers/hash_format_helper.rb
  app/views/admin/legal_aid_applications/submissions/show.html.erb
  spec/helpers/hash_format_helper_spec.rb
Labels: UAT, Approved

#3625 ap-2940: caseworker referrals
  app/services/ccms/manual_review_determiner.rb
  config/locales/en/providers.yml
  spec/services/ccms/manual_review_determiner_spec.rb
Labels: Approved

#3683 Fix GOVUK Rubocop Style/Lambda Offences
  .rubocop_todo.yml
  app/models/bank_transaction.rb
  app/models/cash_transaction.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/citizen_capital.rb
  app/services/flow/flows/citizen_start.rb
  app/services/flow/flows/provider_capital.rb
  app/services/flow/flows/provider_dependants.rb
  app/services/flow/flows/provider_dwp_override.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/flows/provider_property.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/flows/provider_vehicle.rb
  config/initializers/sentry.rb
  config/initializers/sidekiq.rb
  features/support/env.rb
Labels: Ready for review

#3613 AP-2907 Print Employment-related remarks on Means Report
  app/services/hmrc/mock_data/four_weekly_multiple_employment.json
  app/services/hmrc/mock_data/monthly_employment_amount_variations.json
  app/services/hmrc/mock_data/nic_refund.json
  app/services/hmrc/mock_data/tax_refund.json
  app/services/hmrc/mock_data/weekly_multiple_employment.json
  app/services/hmrc/mock_data/weekly_single_employment.json
  app/services/hmrc/mock_interface_response_service.rb
  app/views/providers/employment_incomes/show.html.erb
  app/views/providers/means_reports/_caseworker_review.html.erb
  config/locales/en/providers.yml
  lib/tasks/employ.rake
  spec/factories/cfe_results/v4/mock_results.rb
  spec/factories/cfe_results/v4/results.rb
  spec/factories/employments.rb
  spec/factories/hmrc/responses.rb
  spec/factory_helpers/cfe_employment_remarks_adder.rb
  spec/factory_helpers/hmrc_response/use_case_one.rb
  spec/requests/providers/means_reports_spec.rb
Labels: Approved

#3664 AP-2955 Remove enable evidence upload flag
  app/controllers/admin/settings_controller.rb
  app/controllers/providers/check_merits_answers_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/services/flow/flows/provider_merits.rb
  app/views/admin/settings/show.html.erb
  app/views/providers/application_merits_task/statement_of_cases/_show_new.html.erb
  app/views/providers/application_merits_task/statement_of_cases/_show_old.html.erb
  app/views/providers/application_merits_task/statement_of_cases/show.html.erb
  app/views/providers/has_evidence_of_benefits/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/environments/test.rb
  config/locales/en/providers.yml
  db/migrate/20220331084008_remove_evidence_upload_flag.rb
  db/schema.rb
  features/providers/check_nonpassport_autogrant.feature
  features/providers/civil_application_journey.feature
  features/providers/evidence_upload.feature
  features/providers/merits_task_list.feature
  features/step_definitions/debug_steps.rb
  features/step_definitions/evidence_upload_steps.rb
  features/support/steps_helper.rb
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/has_evidence_of_benefits_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
Labels: UAT, Approved

#3688 Fix rubocop empty line after example
  .rubocop_todo.yml
  spec/forms/legal_aid_applications/emergency_cost_override_form_spec.rb
  spec/forms/outstanding_mortgage_form_spec.rb
  spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb
  spec/helpers/user_transactions_helper_spec.rb
  spec/jobs/bank_transactions_analyser_job_spec.rb
  spec/models/aggregated_cash_income_spec.rb
  spec/models/applicant_spec.rb
  spec/models/bank_account_spec.rb
  spec/models/cfe/v1/result_spec.rb
  spec/models/cfe/v4/result_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/legal_framework/serializable_merits_task_list_spec.rb
  spec/models/transaction_type_spec.rb
  spec/requests/feedbacks_spec.rb
  spec/requests/providers/invalid_logins_spec.rb
  spec/requests/providers/percentage_home_spec.rb
  spec/requests/providers/policy_disregards_controller_spec.rb
  spec/requests/providers/substantive_applications_spec.rb
  spec/services/admin/provider_details_service_spec.rb
  spec/services/ccms/requestors/applicant_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/cleanup_capitial_attributes_spec.rb
  spec/services/hmrc/create_responses_service_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: Approved

#3696 Add explicit check for zeitwork compliance
  spec/zeitwork_spec.rb
Labels: Approved

#3699 Fix GOVUK Rubocop RSpec/ExcessiveDocstringSpacing offences
  .rubocop_todo.yml
  spec/forms/legal_aid_applications/shared_ownership_form_spec.rb
  spec/models/application_merits_task/involved_child_spec.rb
  spec/models/bank_account_spec.rb
  spec/models/cfe/v2/result_spec.rb
  spec/models/cfe/v3/result_spec.rb
  spec/models/cfe/v4/result_spec.rb
  spec/models/firm_spec.rb
  spec/models/host_env_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/legal_framework/serializable_merits_task_spec.rb
  spec/models/transaction_type_spec.rb
  spec/requests/admin/roles_spec.rb
  spec/requests/providers/applicant_employed_spec.rb
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
  spec/requests/providers/capital_assessment_results_spec.rb
  spec/requests/providers/capital_income_assessment_results_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/legal_aid_applications_spec.rb
  spec/requests/providers/offline_accounts_spec.rb
  spec/requests/providers/savings_and_investments_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/ccms/submitters/add_applicant_service_spec.rb
  spec/services/ccms/submitters/add_case_service_spec.rb
  spec/services/ccms/submitters/check_applicant_status_service_spec.rb
  spec/services/ccms/submitters/check_case_status_service_spec.rb
  spec/validators/document_category_validator_spec.rb
Labels: Approved

#3704 Reduce tests per example
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/services/hmrc/parsed_response/persistor_spec.rb
Labels: Approved

#3705 Add jsugarman to provider seed
  db/seeds/test_provider_populator.rb
Labels: Approved

#3708 Add clamav to brewfile
  Brewfile
  README.md
Labels: Approved

#3698 AP-3053 Make dates in HMEC Mock payloads dynamic
  app/services/hmrc/mock_data/eligible_employment.json.erb
  app/services/hmrc/mock_data/employment_tax_credits.json.erb
  app/services/hmrc/mock_data/four_weekly_multiple_employment.json.erb
  app/services/hmrc/mock_data/monthly_employment_amount_variations.json.erb
  app/services/hmrc/mock_data/multiple_employments.json.erb
  app/services/hmrc/mock_data/nic_refund.json.erb
  app/services/hmrc/mock_data/pending_response.json.erb
  app/services/hmrc/mock_data/single_employment.json.erb
  app/services/hmrc/mock_data/tax_refund.json.erb
  app/services/hmrc/mock_data/unknown_response.json.erb
  app/services/hmrc/mock_data/weekly_multiple_employment.json.erb
  app/services/hmrc/mock_data/weekly_single_employment.json.erb
  app/services/hmrc/mock_interface_response_service.rb
  spec/services/hmrc/mock_interface_response_service_spec.rb
Labels: Approved

#3706 Fix GOVUK Rubocop Offences
  .rubocop_todo.yml
  db/seeds.rb
  lib/tasks/helpers/cy_helper.rb
  spec/rails_helper.rb
  spec/requests/v1/workers_spec.rb
  spec/services/banking/bank_transaction_balance_calculator_spec.rb
  spec/services/banking/bank_transactions_trimmer_spec.rb
  spec/services/dashboard_event_handler_spec.rb
Labels: Approved

#3682 Ap 3026 handle pending HMRC response
  app/controllers/providers/full_employment_details_controller.rb
  app/models/hmrc/response.rb
  app/models/legal_aid_application.rb
  spec/factories/hmrc/responses.rb
  spec/models/hmrc/response_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/full_employment_details_controller_spec.rb
Labels: UAT, Approved

#3721 Fix GOVUK Rubocop RSpec/ExampleWording Offences
  .rubocop_todo.yml
  spec/forms/applicants/basic_details_form_spec.rb
  spec/forms/applicants/email_form_spec.rb
  spec/forms/legal_aid_applications/own_home_form_spec.rb
  spec/forms/legal_aid_applications/shared_ownership_form_spec.rb
  spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb
  spec/forms/savings_amounts/offline_accounts_form_spec.rb
  spec/forms/savings_amounts/savings_amounts_form_spec.rb
  spec/helpers/providers_helper_spec.rb
  spec/models/proceeding_merits_task/proceeding_linked_child_spec.rb
  spec/policies/legal_aid_application_policy_spec.rb
  spec/requests/citizens/additional_accounts_spec.rb
  spec/requests/citizens/check_answers_spec.rb
  spec/requests/citizens/identify_types_of_incomes_spec.rb
  spec/requests/citizens/identify_types_of_outgoings_spec.rb
  spec/requests/citizens/means_test_results_spec.rb
  spec/requests/citizens/student_finance_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/identify_types_of_incomes_spec.rb
  spec/requests/providers/identify_types_of_outgoings_spec.rb
  spec/requests/providers/limitations_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/requests/providers/proceedings_types_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/provider_details_creator_spec.rb
  spec/support/shared_examples/provider_auth_shared_examples.rb
Labels: Approved

#3728 AP-2853: Remove legacy ingress values
  bin/uat_deploy
Labels: Approved

#3726 AP-2198: Update Circle CI UAT variable handling
  .circleci/config.yml
  bin/delete_uat_release
  bin/uat_deploy
  helm_deploy/apply-for-legal-aid/README.md
Labels: Approved

#3720 Tech-Debt: Address CodeQL issues
  app/models/host_env.rb
  features/support/env.rb
  spec/lib/omni_auth/hmrc_spec.rb
  spec/services/hmrc/interface/result_service_spec.rb
  spec/services/hmrc/interface/submission_service_spec.rb
Labels: Approved

#3732 Fix GOVUK Rubcop RSpec/EmptyLineAfterSubject Offences
  .rubocop_todo.yml
  spec/forms/legal_aid_applications/emergency_cost_override_form_spec.rb
  spec/forms/opponents/opponent_form_spec.rb
  spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb
  spec/helpers/providers_helper_spec.rb
  spec/jobs/reports_uploader_job_spec.rb
  spec/models/cfe/v2/result_spec.rb
  spec/models/cfe/v3/result_spec.rb
  spec/models/cfe/v4/result_spec.rb
  spec/models/dependant_spec.rb
  spec/models/hmrc/response_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/legal_framework/serializable_merits_task_spec.rb
  spec/models/savings_amount_spec.rb
  spec/policies/legal_aid_application_policy_spec.rb
  spec/presenters/bank_transaction_presenter_spec.rb
  spec/requests/admin/legal_aid_applications_controller_spec.rb
  spec/requests/admin/roles/permissions_spec.rb
  spec/requests/citizens/check_answers_spec.rb
  spec/requests/problem_spec.rb
  spec/requests/providers/application_confirmations_spec.rb
  spec/requests/providers/capital_assessment_results_spec.rb
  spec/requests/providers/capital_income_assessment_results_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/client_completed_means_spec.rb
  spec/requests/providers/confirm_offices_spec.rb
  spec/requests/providers/in_scope_of_laspos_controller_spec.rb
  spec/requests/providers/income_summary_spec.rb
  spec/requests/providers/legal_aid_applications_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/requests/providers/outgoings_summary_spec.rb
  spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb
  spec/requests/providers/received_benefit_confirmations_spec.rb
  spec/requests/providers/restrictions_spec.rb
  spec/requests/saml_sessions_spec.rb
  spec/services/admin/provider_details_service_spec.rb
  spec/services/ccms/attribute_configuration_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/enable_ccms_submission_spec.rb
  spec/services/hmrc/create_responses_service_spec.rb
  spec/services/hmrc/interface/result_service_spec.rb
  spec/services/legal_framework/proceeding_types/all_spec.rb
  spec/services/legal_framework/proceeding_types/proceeding_spec.rb
  spec/services/pdf_converter_spec.rb
  spec/services/populators/transaction_type_populator_spec.rb
Labels: Ready for review

#3707 [AP-3028] handle HMRC unexpected responses
  app/models/hmrc/response.rb
  app/services/hmrc/mock_data/unknown_response.json.erb
  app/services/hmrc/parsed_response/persistor.rb
  app/services/hmrc/parsed_response/validator.rb
  features/providers/employed_journey.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/hmrc/responses.rb
  spec/factories/legal_aid_applications.rb
  spec/models/hmrc/response_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/employed_incomes_spec.rb
  spec/services/hmrc/parsed_response/persistor_spec.rb
  spec/services/hmrc/parsed_response/validator_spec.rb
Labels: Approved

#3747 AP-2953 Increase memory allocation for admin report generation
  helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
Labels: Ready for review

#3757 Update: Bump google-apis-drive_v3 to 0.21.0
  Gemfile.lock
Labels: Ready for review

#3759 [AP-3064] Validate and alert for missing employments
  app/services/hmrc/parsed_response/validator.rb
  spec/services/hmrc/parsed_response/validator_spec.rb
Labels: Approved

#3745 AP-3042: Update employment_income error display
  app/views/providers/employment_incomes/show.html.erb
Labels: Ready to merge

#3749 Tech-Debt: Add slack notification on job completion
  .github/workflows/base-docker-image.yml
  .github/workflows/ci-docker-image.yml
Labels: Approved

#3748 AP-3059 Omit third bullet point for employed applicants
  app/views/providers/open_banking_consents/show.html.erb
  config/locales/en/providers.yml
  spec/requests/providers/open_banking_consents_spec.rb
Labels: UAT, Approved

#3769 AP-2924 disable previews in dropzone
  app/webpack/src/dropzone.js
Labels: UAT, Approved

#3780 Tech-debt: Update simple_command gem loading
  Gemfile
  Gemfile.lock
Labels: Approved

#3768 AP-3065 Refactor Admin Report creation to use temporary file
  app/jobs/reports_uploader_job.rb
  app/services/reports/mis/application_details_report.rb
  spec/jobs/reports_uploader_job_spec.rb
  spec/services/reports/mis/application_details_report_spec.rb
Labels: Approved

#3781 Fix: node-forge yarn security warnings
  package.json
  yarn.lock
Labels: Ready for review, Approved

#3770 AP-2922 add hmrc_benefit type and tests
  db/sample_data/bank_transactions.csv
  spec/services/banking/state_benefit_analyser_service_spec.rb
Labels: UAT, Approved
