Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2023-06, with the labels that each got.

#5336 Update: CFECivil headers
  app/services/cfe_civil/submission_builder.rb
Labels: ready for review

#5341 Update: CFE Comparison
  app/services/cfe/compare_results.rb
  spec/factories/legal_aid_applications.rb
  spec/services/cfe/compare_results_spec.rb
Labels: ready for review

#5345 Fix: Update MatchLabel with worker Suffix for sidekiq pods
  helm_deploy/apply-for-legal-aid/templates/deployment_worker.yaml
Labels: ready for review

#5351 CFE-Civil comparison: Update vehicle handling
  app/services/cfe/compare_submission.rb
  spec/fixtures/files/cfe_civil_comparison/v5/missing_vehicle.json
  spec/fixtures/files/cfe_civil_comparison/v6/missing_vehicle.json
  spec/services/cfe/compare_submission_spec.rb
Labels: ready for review

#5363 Fix: CCMS Queue errors
  app/controllers/admin/ccms_queues_controller.rb
Labels: ready for review

#5329 AP-4066 add client means caption
  app/helpers/page_template_helper.rb
  app/models/transaction_type.rb
  app/views/providers/about_the_financial_assessments/show.html.erb
  app/views/providers/applicant_employed/index.html.erb
  app/views/providers/bank_statements/show.html.erb
  app/views/providers/email_addresses/show.html.erb
  app/views/providers/income_summary/_income_type_item.html.erb
  app/views/providers/income_summary/index.html.erb
  app/views/providers/means/cash_incomes/show.html.erb
  app/views/providers/means/cash_outgoings/show.html.erb
  app/views/providers/means/employment_incomes/show.html.erb
  app/views/providers/means/full_employment_details/show.html.erb
  app/views/providers/means/identify_types_of_incomes/show.html.erb
  app/views/providers/means/identify_types_of_outgoings/show.html.erb
  app/views/providers/means/regular_outgoings/show.html.erb
  app/views/providers/means/student_finances/show.html.erb
  app/views/providers/means/unexpected_employment_incomes/show.html.erb
  app/views/providers/open_banking_consents/show.html.erb
  app/views/providers/open_banking_guidances/show.html.erb
  app/views/providers/outgoings_summary/_outgoing_type_item.html.erb
  app/views/providers/outgoings_summary/index.html.erb
  app/views/providers/transactions/show.html.erb
  app/views/shared/forms/_cash_income_form.html.erb
  app/views/shared/forms/_cash_outgoings_form.html.erb
  app/views/shared/forms/_types_of_income_form.html.erb
  app/views/shared/forms/_types_of_outgoings_form.html.erb
  app/views/shared/means/_student_finances.html.erb
  app/views/shared/page_templates/_default_page_template.html.erb
  app/views/shared/partials/_revealing_checkbox.html.erb
  config/locales/cy/shared.yml
  config/locales/en/generic.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/locales/en/transaction_types.yml
  features/accessibility/provider.feature
  features/providers/applicant_details.feature
  features/providers/bank_statement_upload/check_your_means_answers.feature
  features/providers/bank_statement_upload/happy_path_journey.feature
  features/providers/bank_statement_upload/state_benefit_loop.feature
  features/providers/change_email.feature
  features/providers/check_multiple_employment.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/employed_journey.feature
  features/providers/no_nino_flow.feature
  features/providers/non_passported_journey/waiting_for_applicant.feature
  features/providers/non_passported_journey/with_bank_transactions.feature
  features/providers/non_passported_journey/with_capital.feature
  features/providers/non_passported_journey/with_dependants.feature
  features/providers/non_passported_journey/with_means.feature
  features/providers/pathways_from_check_your_answers.feature
  features/providers/review_and_print.feature
  spec/requests/providers/means/cash_outgoings_controller_spec.rb
Labels: UAT

#5366 CFE: Remove the no_eligibility_assessments controller
  app/controllers/providers/no_eligibility_assessments_controller.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/no_eligibility_assessments/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  spec/requests/providers/no_eligibility_assessments_spec.rb
Labels: ready for review

#5365 AP-4069: Create partner's financial assessment intro page
  app/controllers/providers/partners/about_financial_means_controller.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/about_financial_means/show.html.erb
  app/views/providers/partners/about_financial_means/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/partner_means_assessment/means_check.feature
  features/step_definitions/partner_means_check.rb
  spec/requests/providers/partners/about_financial_means_controller_spec.rb
Labels: ready for review

#5374 Ap 4069/create partner financial assessment intro v2
  app/controllers/providers/partners/about_financial_means_controller.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/about_financial_means/show.html.erb
  app/views/providers/partners/about_financial_means/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/partner_means_assessment/means_check.feature
  features/step_definitions/partner_means_check.rb
  spec/requests/providers/partners/about_financial_means_controller_spec.rb
Labels: ready for review

#5376 CFE: Update Spreadsheet Comparison
  app/services/cfe/store_compare_result.rb
  spec/services/cfe/store_compare_result_spec.rb
Labels: ready for review

#5375 Ap 4067: Create partner employment status question page
  app/controllers/providers/partners/employed_controller.rb
  app/forms/applicants/employed_form.rb
  app/forms/base_employed_form.rb
  app/forms/partners/employed_form.rb
  app/services/flow/flows/provider_capital.rb
  app/services/flow/flows/provider_partner.rb
  app/views/providers/applicant_employed/index.html.erb
  app/views/providers/partners/employed/index.html.erb
  app/views/shared/_employment_status.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/generic.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/migrate/20230614094521_add_employment_to_partners.rb
  db/schema.rb
  features/providers/partner_means_assessment/means_check.feature
  features/step_definitions/partner_means_check.rb
  spec/forms/partners/employed_form_spec.rb
  spec/requests/providers/partners/about_financial_means_controller_spec.rb
  spec/requests/providers/partners/employed_controller_spec.rb
Labels: UAT

#5386 Doorkeeper test: Update scope request
  app/lib/omni_auth/hmrc.rb
Labels: ready for review

#4776 Fix: Make all features accessible
  .circleci/config.yml
  app/assets/stylesheets/helpers.scss
  app/helpers/task_list_helper.rb
  app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/layouts/admin.html.erb
  app/views/providers/application_merits_task/statement_of_cases/_uploaded_files.html.erb
  app/views/providers/bank_statements/_uploaded_files.html.erb
  app/views/providers/capital_introductions/show.html.erb
  app/views/providers/gateway_evidences/_uploaded_files.html.erb
  app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/providers/merits_task_lists/_task_list_item.html.erb
  app/views/providers/merits_task_lists/show.html.erb
  app/views/providers/partners/about_financial_means/show.html.erb
  app/views/providers/uploaded_evidence_collections/_uploaded_files.html.erb
  app/views/shared/check_answers/_proceeding_details_section.html.erb
  app/views/shared/forms/_list_items.html.erb
  app/views/shared/partials/_modal_dialogue.html.erb
  config/locales/en/providers.yml
  features/accessibility/citizen.feature
  features/providers/bank_statement_upload/happy_path_journey.feature
  features/providers/merits_task_list.feature
  features/step_definitions/civil_journey_steps.rb
  features/support/steps_helper.rb
  spec/helpers/task_list_helper_spec.rb
Labels: ready for review

#5397 AP-4149: CCMS page for partner means assessment
  app/assets/stylesheets/providers/legal_aid_applications.scss
  app/controllers/providers/partners/use_ccms_employment_controller.rb
  app/controllers/providers/use_ccms_employed_controller.rb
  app/controllers/providers/use_ccms_employment_controller.rb
  app/models/concerns/base_state_machine.rb
  app/services/flow/flows/provider_partner.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/partners/use_ccms_employment/index.html.erb
  app/views/providers/use_ccms/show.html.erb
  app/views/providers/use_ccms_employed/index.html.erb
  app/views/providers/use_ccms_employment/index.html.erb
  app/views/providers/use_ccms_under16s/show.html.erb
  app/views/shared/_use_ccms.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  spec/concerns/base_state_machine_spec.rb
  spec/concerns/passported_state_machine_spec.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/applicant_employed_spec.rb
  spec/requests/providers/partners/employed_controller_spec.rb
  spec/requests/providers/partners/use_ccms_employment_controller_spec.rb
  spec/requests/providers/use_ccms_employed_spec.rb
  spec/requests/providers/use_ccms_employment_controller_spec.rb
  spec/requests/providers/use_ccms_spec.rb
  spec/services/reports/mis/non_passported_applications_report_spec.rb
Labels: UAT, approved

#5406 Fix: Update CFE Comparison
  app/services/cfe/compare_submission.rb
  spec/fixtures/files/cfe_civil_comparison/v5/employment_mismatch.json
  spec/fixtures/files/cfe_civil_comparison/v6/employment_mismatch.json
  spec/services/cfe/compare_submission_spec.rb
Labels: ready for review

#5407 Update: remove specific accessibility checks
  features/accessibility/provider.feature
  features/cassettes/Provider_accessibility/I_complete_the_non-passported_means_assessment_and_it_is_accessible.yml
  features/cassettes/Provider_accessibility/I_complete_the_non-passported_merits_assessment_and_it_is_accessible.yml
  features/cassettes/Provider_accessibility/I_start_a_new_non-passported_application_and_enter_client_details.yml
  features/providers/applicant_details.feature
  features/providers/applicant_under_16_blocked.feature
  features/providers/bank_statement_upload/uploading_files.feature
  features/providers/check_multiple_employment.feature
  features/step_definitions/accessibility.rb
Labels: ready for review

#5416 Fix: Reduce 502 errors on pods
  helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-metrics.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
  helm_deploy/apply-for-legal-aid/templates/deployment_metrics.yaml
Labels: ready for review

#5423 Use govuk_back_link component
  app/helpers/application_helper.rb
Labels: approved, Ready to merge
