Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2023-03, with the labels that each got.

#5011 AP-3873: Split opponent model
  app/controllers/providers/application_merits_task/domestic_abuse_summaries_controller.rb
  app/controllers/providers/application_merits_task/opponents_mental_capacities_controller.rb
  app/forms/opponents/domestic_abuse_summary_form.rb
  app/forms/opponents/mental_capacity_form.rb
  app/forms/providers/application_merits_task/domestic_abuse_summary_form.rb
  app/models/application_merits_task/domestic_abuse_summary.rb
  app/models/application_merits_task/opponent.rb
  app/models/application_merits_task/parties_mental_capacity.rb
  app/models/legal_aid_application.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/reports/mis/application_detail_csv_line.rb
  app/views/providers/check_merits_answers/show.html.erb
  app/views/providers/merits_reports/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
  config/ccms/attribute_block_configs/base.yml
  config/locales/cy/activemodel.yml
  config/locales/cy/helpers.yml
  config/locales/en/activemodel.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  db/anonymise/rules.rb
  db/migrate/20230226113130_create_domestic_abuse_summary.rb
  db/migrate/20230226121859_create_parties_mental_capacity.rb
  db/schema.rb
  features/accessibility/provider.feature
  features/providers/back_button.feature
  features/providers/check_ccms_autogrant.feature
  features/providers/check_multiple_employment.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/merits_task_list.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/passported_journey.feature
  features/step_definitions/civil_journey_steps.rb
  features/step_definitions/review_and_print_steps.rb
  lib/tasks/migrate_opponents.rake
  spec/factories/domestic_abuse_summaries.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/opponents.rb
  spec/factories/parties_mental_capacities.rb
  spec/forms/opponents/domestic_abuse_summary_form_spec.rb
  spec/forms/opponents/mental_capacity_form_spec.rb
  spec/requests/providers/application_merits_task/domestic_abuse_summaries_controller_spec.rb
  spec/requests/providers/application_merits_task/opponents_mental_capacities_controller_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_means_tested_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/ccms/submitters/add_case_service_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
  spec/services/reports/mis/application_details_report_spec.rb
Labels: UAT, approved

#5050 AP-3873: Opponent clear up
  db/anonymise/rules.rb
  db/migrate/20230228132829_update_opponent_fields.rb
  db/schema.rb
  lib/tasks/migrate_opponents.rake
Labels: approved

#5054 Fix: Admin report generation
  app/services/reports/mis/application_detail_csv_line.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: ready for review

#5079 AP-3943: Fix for citizens locked out of applications
  app/controllers/citizens/legal_aid_applications_controller.rb
  spec/requests/citizens/legal_aid_applications_controller_spec.rb
Labels: approved

#5083 Bump Devise to v4.9.0
  Gemfile
  Gemfile.lock
Labels: UAT, Ready to merge

#5074 AP-3896: Remove bank statement upload restrictions
  app/models/legal_aid_application.rb
  app/models/provider.rb
  app/services/flow/flows/provider_start.rb
  app/views/shared/check_answers/_student_finance.html.erb
  db/migrate/20200708102815_create_permissions_table.rb
  db/seeds/permissions.rb
  features/providers/applicant_details.feature
  features/step_definitions/bank_statement_upload_steps.rb
  features/step_definitions/check_your_answers_steps.rb
  features/step_definitions/means_report_steps.rb
  features/step_definitions/review_and_print_steps.rb
  spec/factories/permissions.rb
  spec/factories/providers.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/provider_spec.rb
  spec/requests/providers/bank_statements_spec.rb
  spec/requests/providers/means/employed_incomes_spec.rb
  spec/requests/providers/means/full_employment_details_controller_spec.rb
  spec/requests/providers/means/student_finances_controller_spec.rb
  spec/requests/providers/no_eligibility_assessments_spec.rb
  spec/requests/providers/open_banking_consents_spec.rb
  spec/requests/providers/open_banking_guidances_controller_spec.rb
  spec/services/ccms/manual_review_determiner_spec.rb
  spec/services/cfe/submission_manager_spec.rb
Labels: approved

#5078 AP-3888: Remove section 8 permissions
  app/forms/legal_aid_applications/has_other_proceedings_form.rb
  app/models/proceeding.rb
  app/models/provider.rb
  app/services/legal_framework/proceeding_types/all.rb
  app/views/providers/proceedings_types/index.html.erb
  config/locales/en/providers.yml
  db/seeds/permissions.rb
  lib/tasks/full_section_8.rake
  spec/factories/permissions.rb
  spec/factories/providers.rb
  spec/models/provider_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/proceedings_types_spec.rb
  spec/services/legal_framework/proceeding_types/all_spec.rb
Labels: ready for review

#5098 Remove unused `UsedMultipleDelegatedFunctionsForm`
  .rubocop_todo.yml
  app/forms/legal_aid_applications/used_multiple_delegated_functions_form.rb
  spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb
Labels: approved

#5100 RuboCop tidy up
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/citizens/citizen_base_controller.rb
  app/helpers/accessible_navigation_helper.rb
  app/helpers/table_sort_helper.rb
  spec/models/dashboard/single_object/applicant_email_spec.rb
  spec/models/dashboard/single_object/feedback_spec.rb
  spec/models/dashboard/single_object/provider_data_spec.rb
  spec/models/document_category_spec.rb
  spec/models/proceeding_spec.rb
  spec/models/provider_spec.rb
  spec/requests/providers/transactions_spec.rb
Labels: ready for review

#5105 Fix: Error with bank uploads
  app/models/concerns/non_passported_state_machine.rb
Labels: ready for review

#5066 AP-3915: Add CCMS queue analysis to admin
  app/controllers/admin/ccms_queues_controller.rb
  app/models/ccms/submission.rb
  app/views/admin/ccms_queues/index.html.erb
  app/views/admin/ccms_queues/show.html.erb
  app/views/layouts/admin.html.erb
  config/locales/cy/layouts.yml
  config/locales/en/admin.yml
  config/locales/en/dates.yml
  config/locales/en/layouts.yml
  config/routes.rb
  spec/models/ccms/submission_spec.rb
  spec/requests/admin/ccms_queues_controller_spec.rb
Labels: ready for review, Discussion

#5106 Update: Allow the bin/div to read $PORT from .env
  Procfile.dev
Labels: ready for review, Discussion

#5107 AP-3800: Client has a partner question
  app/controllers/providers/partner/client_has_partners_controller.rb
  app/forms/providers/partners/client_has_partner_form.rb
  app/models/applicant.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_partner.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/provider_flow_service.rb
  app/views/providers/partner/client_has_partners/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/migrate/20230320094303_add_has_partner_to_applicant.rb
  db/schema.rb
  spec/forms/providers/partners/client_has_partner_form_spec.rb
  spec/models/applicant_spec.rb
  spec/requests/providers/has_national_insurance_numbers_controller_spec.rb
  spec/requests/providers/partner/client_has_partners_controller_spec.rb
Labels: Ready to merge

#5109 AP-3936: Buttons not aligned correctly on mobile
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/govuk-secondary-button.scss
  app/views/admin/settings/show.html.erb
  app/views/citizens/banks/index.html.erb
  app/views/providers/application_merits_task/statement_of_cases/show.html.erb
  app/views/providers/bank_statements/show.html.erb
  app/views/providers/cookies/show.html.erb
  app/views/providers/uploaded_evidence_collections/_upload_evidence.html.erb
  app/views/shared/forms/_next_action_buttons.html.erb
  app/views/shared/partials/_modal_dialogue.html.erb
Labels: UAT

#5125 Remove redundant module
  app/controllers/concerns/providers/pre_dwp_check_visible.rb
  app/controllers/providers/address_lookups_controller.rb
  app/controllers/providers/address_selections_controller.rb
  app/controllers/providers/addresses_controller.rb
  app/controllers/providers/applicant_details_controller.rb
  app/controllers/providers/check_benefits_controller.rb
  app/controllers/providers/check_provider_answers_controller.rb
  app/controllers/providers/has_national_insurance_numbers_controller.rb
  app/controllers/providers/limitations_controller.rb
  app/controllers/providers/partner/client_has_partners_controller.rb
  app/controllers/providers/proceeding_loop/client_involvement_type_controller.rb
  app/controllers/providers/proceeding_loop/delegated_functions_controller.rb
  app/controllers/providers/proceeding_loop/emergency_defaults_controller.rb
  app/controllers/providers/proceeding_loop/final_hearings_controller.rb
  app/controllers/providers/proceeding_loop/substantive_defaults_controller.rb
  app/controllers/providers/proceedings_types_controller.rb
  spec/requests/providers/address_lookups_spec.rb
  spec/requests/providers/address_selections_spec.rb
  spec/requests/providers/applicant_details_spec.rb
  spec/requests/providers/check_benefits_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/has_national_insurance_numbers_controller_spec.rb
  spec/requests/providers/limitations_spec.rb
  spec/requests/providers/proceedings_types_spec.rb
Labels: ready for review

#5110 AP-3801: Partner details
  app/controllers/providers/partners/client_has_partners_controller.rb
  app/controllers/providers/partners/details_controller.rb
  app/forms/partners/details_form.rb
  app/forms/providers/partners/client_has_partner_form.rb
  app/models/legal_aid_application.rb
  app/models/partner.rb
  app/services/flow/flows/provider_partner.rb
  app/views/providers/partners/client_has_partners/show.html.erb
  app/views/providers/partners/details/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20230321081156_create_partners.rb
  db/schema.rb
  spec/factories/partners.rb
  spec/forms/partners/details_form_spec.rb
  spec/requests/providers/partners/client_has_partners_controller_spec.rb
  spec/requests/providers/partners/details_controller_spec.rb
Labels: ready for review
