Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2023-05, with the labels that each got.

#5254 Update: CFECivil comparison
  app/services/cfe_civil/components/employments.rb
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/services/cfe_civil/components/employments_spec.rb
Labels: ready for review

#5255 Update: CFE Comparison
  app/services/cfe_civil/components/employments.rb
  spec/services/cfe_civil/components/employments_spec.rb
Labels: ready for review

#5244 AP-3951: Remove scheduled mails on change
  app/controllers/providers/about_the_financial_assessments_controller.rb
  spec/requests/providers/about_the_financial_assessments_controller_spec.rb
Labels: approved

#5261 Update: CFE Comparison
  app/services/cfe/compare_submission.rb
  app/services/cfe_civil/components/cash_transactions.rb
  spec/fixtures/files/cfe_civil_comparison/v5/mismatch_array.json
  spec/fixtures/files/cfe_civil_comparison/v5/result.json
  spec/fixtures/files/cfe_civil_comparison/v5/sequence_mismatch.json
  spec/fixtures/files/cfe_civil_comparison/v6/compare_result.json
  spec/fixtures/files/cfe_civil_comparison/v6/mismatch_array.json
  spec/fixtures/files/cfe_civil_comparison/v6/result.json
  spec/fixtures/files/cfe_civil_comparison/v6/sequence_mismatch.json
  spec/services/cfe/compare_results_spec.rb
  spec/services/cfe/compare_submission_spec.rb
  spec/services/cfe_civil/components/cash_transactions_spec.rb
Labels: ready for review

#5260 AP-3231: Uploading multiple files on the statement of case page with JS disabled
  app/views/providers/application_merits_task/statement_of_cases/show.html.erb
Labels: ready for review

#5272 Update CFECivil handling of outgoings
  app/services/cfe_civil/components/outgoings.rb
  spec/services/cfe_civil/components/outgoings_spec.rb
Labels: ready for review

#5275 Update: CFE-Civil irregular income submissions
  app/services/cfe_civil/components/irregular_incomes.rb
  spec/services/cfe_civil/components/irregular_incomes_spec.rb
Labels: ready for review

#5285 Update: CFE Comparison
  app/services/cfe/compare_submission.rb
Labels: ready for review

#5279 AP-3902: What you need to do next page (before financial means assessment)
  app/controllers/providers/about_financial_means_controller.rb
  app/services/flow/flows/provider_dwp_override.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/about_financial_means/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  features/accessibility/provider.feature
  features/providers/applicant_details.feature
  features/providers/change_email.feature
  features/providers/non_passported_journey/used_delegated_functions.feature
  features/providers/non_passported_journey/waiting_for_applicant.feature
  features/providers/passported_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  spec/requests/providers/about_financial_means_controller_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
  spec/requests/providers/has_evidence_of_benefits_spec.rb
  spec/requests/providers/received_benefit_confirmations_spec.rb
Labels: approved

#5292 AP-4088: Update client upload page
  app/views/providers/bank_statements/show.html.erb
  config/locales/en/providers.yml
  features/providers/bank_statement_upload/happy_path_journey.feature
  features/providers/bank_statement_upload/uploading_files.feature
Labels: ready for review

#5299 Update CFE comparison
  app/services/cfe/compare_submission.rb
Labels: approved

#5287 AP-3909: Update regular transactions ownership
  app/forms/providers/means/applicant_owner.rb
  app/forms/providers/means/housing_benefit_form.rb
  app/forms/providers/means/regular_income_form.rb
  app/forms/providers/means/regular_outgoings_form.rb
  app/forms/providers/means/regular_transaction_form.rb
  db/migrate/20230515130906_update_regular_transactions.rb
  db/schema.rb
  lib/tasks/migrate_regular_transaction_owners.rake
  spec/factories/legal_aid_applications.rb
  spec/forms/providers/means/housing_benefit_form_spec.rb
  spec/forms/providers/means/regular_income_form_spec.rb
  spec/forms/providers/means/regular_outgoings_form_spec.rb
  spec/forms/providers/means/regular_transaction_form_spec.rb
  spec/requests/providers/means/housing_benefits_controller_spec.rb
  spec/requests/providers/means/regular_incomes_controller_spec.rb
  spec/requests/providers/means/regular_outgoings_controller_spec.rb
Labels: Ready to merge

#5324 Fix: Allow a CCMS Submission when the flag is off
  app/models/concerns/base_state_machine.rb
Labels: ready for review

#5318 Update: CFE-Civil headers
  app/services/cfe_civil/submission_builder.rb
  spec/cassettes/CFECivil_SubmissionBuilder/_call/if_HostEnv_is_not_set/still_generates_the_expected_JSON_but_uses_missing_in_the_header.yml
  spec/services/cfe_civil/submission_builder_spec.rb
Labels: ready for review

#5327 [AP-3648] Use start button helper
  app/assets/stylesheets/govuk-mods.scss
  app/helpers/application_helper.rb
  app/views/citizens/legal_aid_applications/index.html.erb
  app/views/providers/legal_aid_applications/index.html.erb
  app/views/providers/start/index.html.erb
Labels: approved

#5326 Update CFE::CompareSubmission
  app/services/cfe/compare_submission.rb
  spec/fixtures/files/cfe_civil_comparison/v5/mismatch_array.json
  spec/fixtures/files/cfe_civil_comparison/v5/payment_sequence_mismatch_array.json
  spec/fixtures/files/cfe_civil_comparison/v6/mismatch_array.json
  spec/fixtures/files/cfe_civil_comparison/v6/payment_sequence_mismatch_array.json
  spec/services/cfe/compare_submission_spec.rb
Labels: approved
