Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2023-04, with the labels that each got.

#5141 Confirm prohibited steps is not for change of name
  app/controllers/providers/proceeding_merits_task/prohibited_steps_controller.rb
  app/forms/providers/proceeding_merits_task/prohibited_steps_form.rb
  app/views/providers/proceeding_merits_task/prohibited_steps/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  db/migrate/20230330155942_add_confirmed_not_change_of_name_to_prohibited_steps.rb
  db/schema.rb
  spec/forms/providers/proceeding_merits_task/prohibited_steps_form_spec.rb
  spec/requests/providers/proceeding_merits_task/prohibited_steps_controller_spec.rb
Labels: ready for review

#4949 Fix: Update circle build and push step
  .circleci/config.yml
Labels: ready for review

#5140 AP-3649: summary list check answer page
  app/helpers/check_answers_helper.rb
  app/views/citizens/check_answers/_bank_accounts.html.erb
  app/views/providers/means_reports/_dependants.html.erb
  app/views/providers/means_reports/_income_cash_payments.html.erb
  app/views/providers/means_reports/_outgoings_cash_payments.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_bank_statements.html.erb
  app/views/shared/check_answers/_client_details.html.erb
  app/views/shared/check_answers/_client_involvement_type_details.html.erb
  app/views/shared/check_answers/_delegated_function_details.html.erb
  app/views/shared/check_answers/_dependants.html.erb
  app/views/shared/check_answers/_emergency_costs.html.erb
  app/views/shared/check_answers/_final_hearing.html.erb
  app/views/shared/check_answers/_full_employment_details.html.erb
  app/views/shared/check_answers/_housing_benefit.html.erb
  app/views/shared/check_answers/_income_cash_payments.html.erb
  app/views/shared/check_answers/_income_summary.html.erb
  app/views/shared/check_answers/_level_of_service.html.erb
  app/views/shared/check_answers/_offline_savings_accounts.html.erb
  app/views/shared/check_answers/_one_change_link_long_answers_section.html.erb
  app/views/shared/check_answers/_one_link_section.html.erb
  app/views/shared/check_answers/_outgoings_cash_payments.html.erb
  app/views/shared/check_answers/_proceeding_details.html.erb
  app/views/shared/check_answers/_proceedings_details.html.erb
  app/views/shared/check_answers/_property.html.erb
  app/views/shared/check_answers/_student_finance.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  config/locales/en/shared.yml
Labels: approved

#5126 AP-3949: partners address
  app/controllers/concerns/address_handling.rb
  app/controllers/providers/address_selections_controller.rb
  app/controllers/providers/partners/address_lookups_controller.rb
  app/controllers/providers/partners/address_selections_controller.rb
  app/controllers/providers/partners/addresses_controller.rb
  app/controllers/providers/partners/details_controller.rb
  app/controllers/providers/partners/shared_addresses_controller.rb
  app/forms/addresses/address_form.rb
  app/forms/addresses/address_lookup_form.rb
  app/forms/addresses/address_selection_form.rb
  app/forms/addresses/partner_address_form.rb
  app/forms/addresses/partner_address_lookup_form.rb
  app/forms/addresses/partner_address_selection_form.rb
  app/forms/applicants/basic_details_form.rb
  app/forms/applicants/has_national_insurance_number_form.rb
  app/forms/base_address_form.rb
  app/forms/base_address_lookup_form.rb
  app/forms/base_address_selection_form.rb
  app/forms/base_form.rb
  app/forms/concerns/date_of_birth_handling.rb
  app/forms/concerns/national_insurance_handling.rb
  app/forms/partners/details_form.rb
  app/forms/partners/shared_address_form.rb
  app/services/flow/flows/provider_partner.rb
  app/views/providers/address_lookups/show.html.erb
  app/views/providers/address_selections/show.html.erb
  app/views/providers/addresses/show.html.erb
  app/views/providers/partners/address_lookups/show.html.erb
  app/views/providers/partners/address_selections/show.html.erb
  app/views/providers/partners/addresses/show.html.erb
  app/views/providers/partners/shared_addresses/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20230327134642_add_address_fields_to_partner.rb
  db/schema.rb
  features/cassettes/partner_means_assessment_with_a_different_address/I_am_able_to_add_a_partner_with_a_different_address_from_the_applicant.yml
  features/cassettes/partner_means_assessment_with_a_shared_address/I_am_able_to_add_a_partner_with_an_address_shared_with_the_applicant.yml
  features/cassettes/partner_means_assessment_with_an_unknown_address/I_am_able_to_add_a_partner_with_a_different_address_from_the_applicant.yml
  features/providers/partner_means_assessment/with_an_unknown_address.feature
  features/providers/partner_means_assessment/with_different_address.feature
  features/providers/partner_means_assessment/with_shared_address.feature
  features/step_definitions/civil_journey_steps.rb
  spec/cassettes/Providers_Partners_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/partner_address_selections/edit/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/but_the_lookup_does_not_return_any_valid_results/renders_the_manual_address_selection_page.yml
  spec/cassettes/Providers_Partners_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/partner_address_selections/edit/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/performs_an_address_lookup_with_the_provided_postcode.yml
  spec/cassettes/Providers_Partners_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/partner_address_selections/edit/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/renders_the_address_selection_page.yml
  spec/factories/partners.rb
  spec/forms/addresses/partner_address_form_spec.rb
  spec/forms/addresses/partner_address_lookup_form_spec.rb
  spec/forms/addresses/partner_address_selection_form_spec.rb
  spec/forms/partners/shared_address_form_spec.rb
  spec/requests/providers/partners/address_lookups_controller_spec.rb
  spec/requests/providers/partners/address_selections_controller_spec.rb
  spec/requests/providers/partners/addresses_controller_spec.rb
  spec/requests/providers/partners/details_controller_spec.rb
  spec/requests/providers/partners/shared_addresses_controller_spec.rb
Labels: UAT, approved

#5191 Update ruby to 3.2.2
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  docker/apply_base.dockerfile
  docker/apply_ci.dockerfile
Labels: ready for review

#5196 Fix: Faker safe_email deprecation warnings
  spec/factories/applicants.rb
  spec/factories/providers.rb
  spec/factories/scheduled_mailings.rb
  spec/forms/applicants/email_form_spec.rb
  spec/mailers/citizen_completed_means_mailer_spec.rb
  spec/mailers/citizen_confirmation_mailer_spec.rb
  spec/mailers/notify_mailer_spec.rb
  spec/mailers/submit_application_reminder_mailer_spec.rb
  spec/mailers/submit_citizen_financial_reminder_mailer_spec.rb
  spec/mailers/submit_provider_financial_reminder_mailer_spec.rb
  spec/models/scheduled_mailing_spec.rb
  spec/requests/providers/applicant_details_spec.rb
  spec/requests/providers/email_addresses_spec.rb
Labels: ready for review

#5166 AP-3990: Summary list non check answers pages
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/providers/has_other_dependants.scss
  app/views/citizens/accounts/index.html.erb
  app/views/providers/about_the_financial_assessments/show.html.erb
  app/views/providers/capital_income_assessment_results/_bank_statements.html.erb
  app/views/providers/has_other_proceedings/show.html.erb
  app/views/providers/limitations/_proceeding_type.html.erb
  app/views/providers/limitations/_proceeding_types.html.erb
  app/views/providers/limitations/_proceeding_types_with_df.html.erb
  app/views/providers/limitations/show.html.erb
  app/views/providers/means/has_other_dependants/show.html.erb
  app/views/shared/check_answers/_proceeding_details_section.html.erb
  app/views/shared/check_answers/_substantive_costs.html.erb
  app/views/shared/review_application/_income_payments_and_assets.html.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
  config/locales/en/providers.yml
  spec/requests/providers/limitations_spec.rb
Labels: approved

#5208 Fix: Speed up CircleCI integration test steps
  .circleci/config.yml
Labels: ready for review

#5217 Fix: Update dependabot time
  .github/dependabot.yml
Labels: ready for review

#5156 AP-3802: Implement check your answers for partner details
  app/controllers/concerns/providers/draftable.rb
  app/controllers/providers/check_provider_answers_controller.rb
  app/controllers/providers/partners/shared_addresses_controller.rb
  app/models/partner.rb
  app/services/flow/flows/provider_partner.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/check_provider_answers/index.html.erb
  app/views/providers/means_reports/show.html.erb
  app/views/providers/merits_reports/show.html.erb
  app/views/shared/check_answers/_client_details.html.erb
  app/views/shared/check_answers/_partner_details.html.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
  config/locales/en/shared.yml
  features/cassettes/partner_means_assessment_check_your_answers/I_am_able_to_add_a_partner_with_an_address_shared_with_the_applicant_and_then_change_it.yml
  features/providers/partner_means_assessment/check_your_answers.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/applicants.rb
  spec/models/partner_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/partners/shared_addresses_controller_spec.rb
Labels: Ready to merge

#5188 AP-3991: Use summary_list component on merits page
  app/views/shared/check_answers/_bank_statements.html.erb
  app/views/shared/check_answers/_children_involved.html.erb
  app/views/shared/check_answers/_gateway_evidence.html.erb
  app/views/shared/check_answers/_laspo.html.erb
  app/views/shared/check_answers/_latest_incident_details.html.erb
  app/views/shared/check_answers/_matter_opposition.html.erb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/check_answers/_merits_proceeding_section.html.erb
  app/views/shared/check_answers/_offline_savings_accounts.html.erb
  app/views/shared/check_answers/_one_link_section.html.erb
  app/views/shared/check_answers/_opponent_details.html.erb
  app/views/shared/check_answers/_property.html.erb
  app/views/shared/check_answers/_supporting_evidence.html.erb
  app/views/shared/check_answers/_undertaking.html.erb
  app/views/shared/check_answers/_urgency.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  config/locales/cy/shared.yml
  config/locales/en/shared.yml
  spec/requests/providers/check_merits_answers_spec.rb
Labels: approved

#5198 AP-3642 details component
  app/views/citizens/consents/show.html.erb
  app/views/providers/limitations/_proceeding_type.html.erb
  app/views/providers/open_banking_guidances/show.html.erb
  app/views/shared/forms/_types_of_income_form.html.erb
  app/views/shared/forms/_types_of_outgoings_form.html.erb
  config/locales/cy/shared.yml
  config/locales/en/shared.yml
Labels: UAT, approved

#5237 Update cfe comparison
  app/services/cfe/compare_results.rb
  app/services/cfe/compare_submission.rb
  app/services/cfe_civil/submission_builder.rb
  spec/services/cfe/compare_results_spec.rb
  spec/services/cfe/compare_submission_spec.rb
Labels: ready for review

#5238 Update SubmissionBuilder
  app/services/cfe/compare_results.rb
  app/services/cfe_civil/submission_builder.rb
Labels: ready for review

#5236 AP-4039: Fix non-js application delete
  app/controllers/providers/delete_controller.rb
  spec/requests/providers/delete_controller_spec.rb
Labels: UAT
