Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2023-02, with the labels that each got.

#4932 Remove unused/redundant partial
  app/views/shared/_cash_transactions.html.erb
  config/locales/cy/shared.yml
  config/locales/en/shared.yml
Labels: ready for review

#4935 Fix: Remove sidekiq-alive queue
  config/sidekiq.yml
  spec/services/metrics/sidekiq_queue_sizes_spec.rb
Labels: ready for review

#4936 AP-3331 vehicles answer not saved
  .erb-lint.yml
  app/views/providers/vehicles/remaining_payments/show.html.erb
  features/providers/check_your_answers.feature
  features/step_definitions/check_your_answers_steps.rb
Labels: UAT, approved

#4820 Add new check answers page for income assessment section
  app/controllers/providers/bank_statements_controller.rb
  app/controllers/providers/check_capital_answers_controller.rb
  app/controllers/providers/means/check_income_answers_controller.rb
  app/helpers/dependant_helper.rb
  app/models/concerns/non_means_tested_state_machine.rb
  app/models/concerns/non_passported_state_machine.rb
  app/models/concerns/passported_state_machine.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_capital.rb
  app/services/flow/flows/provider_dependants.rb
  app/services/flow/flows/provider_property.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/flows/provider_vehicle.rb
  app/views/providers/check_capital_answers/show.html.erb
  app/views/providers/means/check_income_answers/_income_assessment.html.erb
  app/views/providers/means/check_income_answers/show.html.erb
  app/views/shared/check_answers/_dependants.html.erb
  config/locales/en/enums.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  features/accessibility/provider.feature
  features/providers/bank_statement_upload/check_your_means_answers.feature
  features/providers/check_multiple_employment.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/check_your_answers.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/employed_journey.feature
  features/providers/non_passported_journey/with_capital.feature
  features/providers/non_passported_journey/with_dependants.feature
  features/providers/non_passported_journey/with_means.feature
  features/step_definitions/bank_statement_upload_steps.rb
  features/step_definitions/check_your_answers_steps.rb
  features/step_definitions/civil_journey_steps.rb
  spec/concerns/non_passported_state_machine_spec.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/check_capital_answers_controller_spec.rb
  spec/requests/providers/means/cash_incomes_controller_spec.rb
  spec/requests/providers/means/cash_outgoings_controller_spec.rb
  spec/requests/providers/means/check_income_answers_controller_spec.rb
  spec/requests/providers/means/dependants_controller_spec.rb
  spec/requests/providers/means/has_dependants_controller_spec.rb
  spec/requests/providers/means/has_other_dependants_controller_spec.rb
  spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
  spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
  spec/requests/providers/means/other_assets_controller_spec.rb
  spec/requests/providers/means/own_home_spec.rb
  spec/requests/providers/means/policy_disregards_controller_spec.rb
  spec/requests/providers/means/regular_incomes_controller_spec.rb
  spec/requests/providers/means/regular_outgoings_controller_spec.rb
  spec/requests/providers/means/restrictions_spec.rb
  spec/requests/providers/means/vehicles_spec.rb
  spec/requests/providers/vehicles/regular_uses_spec.rb
Labels: ready for review

#4940 Tech-debt: Update capybara config
  features/support/env.rb
Labels: ready for review

#4951 AP-3794: Update digest-exporter
  app/services/digest_exporter.rb
  spec/services/digest_exporter_spec.rb
Labels: ready for review

#4958 Revert "AP-3794: Update digest-exporter"
  app/services/digest_exporter.rb
  spec/services/digest_exporter_spec.rb
Labels: ready for review

#4960 AP-3794: Update DigestExporter... again
  app/services/digest_exporter.rb
  spec/services/digest_exporter_spec.rb
Labels: ready for review

#4950 ap-3640: implement gov.uk header component
  app/helpers/application_helper.rb
  app/views/layouts/_header.html.erb
  app/views/shared/_provider_header_link.html.erb
  spec/helpers/application_helper_spec.rb
Labels: UAT

#4974 Remove `data_migrate` gem
  .circleci/config.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  README.md
  db/anonymise/rules.rb
  db/data/20211020133241_add_proceeding_id_to_attempts_to_settles.rb
  db/data/20211022112450_add_proceeding_id_to_chances_of_successes.rb
  db/data/20211103105816_populate_extra_proceedings_fields.rb
  db/data/20211112125241_add_ccms_matter_code_to_proccedings.rb
  db/data/20220111135820_standardise_matter_types.rb
  db/data_schema.rb
  db/migrate/20230209145917_drop_data_migrations_table.rb
  db/schema.rb
  docker/setup_db
Labels: approved

#4967 Use `ActiveRecord::Encryption` to encrypt TrueLayer tokens
  app/models/applicant.rb
  config/application.rb
  db/migrate/20230208133125_add_encrypted_true_layer_token_to_applicants.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/models/applicant_spec.rb
Labels: approved, active-record-encryption

#4979 AP-3781: Update client truelayer notify email
  config/govuk_notify_templates.yml
Labels: UAT

#4980 AP-3794: Update digest exporter
  Gemfile
  Gemfile.lock
  app/services/digest_exporter.rb
  spec/services/digest_exporter_spec.rb
Labels: ready for review

#4966 ap-3472: add employment status to your application
  app/models/applicant.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/shared/check_answers/_client_details.html.erb
  config/locales/cy/activemodel.yml
  config/locales/cy/shared.yml
  config/locales/en/activemodel.yml
  config/locales/en/shared.yml
  features/providers/non_passported_journey/waiting_for_applicant.feature
  spec/models/applicant_spec.rb
Labels: ready for review, UAT

#4968 Migrate applicant SecureData true layer tokens
  app/models/applicant.rb
  lib/tasks/secure_data_migration.rake
  spec/models/applicant_spec.rb
Labels: UAT, active-record-encryption

#4999 Fix a tupo
  config/locales/en/providers.yml
Labels: ready for review

#4991 Ignore the `SecureData` true layer token
  .rubocop_todo.yml
  app/controllers/applicants/omniauth_callbacks_controller.rb
  app/models/applicant.rb
  app/models/bank_provider.rb
  app/services/true_layer/bank_data_import_service.rb
  app/services/true_layer/importers/import_provider_service.rb
  db/migrate/20230213141824_add_true_layer_provider_id_applicant_index_to_bank_providers.rb
  db/schema.rb
  lib/tasks/secure_data_migration.rake
  spec/factories/applicants.rb
  spec/factories/bank_providers.rb
  spec/models/applicant_spec.rb
  spec/services/true_layer/bank_data_import_service_spec.rb
  spec/services/true_layer/importers/import_account_balance_service_spec.rb
  spec/services/true_layer/importers/import_account_holders_service_spec.rb
  spec/services/true_layer/importers/import_accounts_service_spec.rb
  spec/services/true_layer/importers/import_provider_service_spec.rb
  spec/services/true_layer/importers/import_transactions_service_spec.rb
  spec/support/true_layer_helpers.rb
  spec/support/true_layer_mock_data.rb
  spec/workers/import_bank_data_worker_spec.rb
Labels: active-record-encryption

#5002 Remove redundant `BenefitType` model
  app/models/benefit_type.rb
  config/locales/cy/activerecord.yml
  config/locales/en/activerecord.yml
Labels: ready for review

#4975 Use `rails db:prepare` to prepare the database
  .circleci/config.yml
  docker/run
  docker/setup_db
Labels: approved, do not merge

#5001 Remove ignored true layer columns
  db/migrate/20230215160839_remove_true_layer_secure_data_id_from_applicants.rb
  db/migrate/20230215161023_remove_token_from_bank_providers.rb
  db/migrate/20230215161035_remove_token_expires_at_from_bank_providers.rb
  db/schema.rb
Labels: ready for review, active-record-encryption

#5003 Stop ignoring removed columns
  app/models/applicant.rb
  app/models/bank_provider.rb
Labels: ready for review, do not merge, active-record-encryption

#5010 Use `ActiveRecord::Encryption` for citizen URLs
  app/models/legal_aid_application.rb
  db/migrate/20230217105228_add_citizen_url_id_to_legal_aid_applications.rb
  db/migrate/20230217111318_add_citizen_url_expires_on_to_legal_aid_applications.rb
  db/schema.rb
  spec/models/legal_aid_application_spec.rb
Labels: ready for review, active-record-encryption

#5022 Remove `simulated_email_address` config
  config/application.rb
  config/environments/test.rb
  spec/services/citizen_email_service_spec.rb
  spec/services/provider_email_service_spec.rb
  spec/services/submit_application_reminder_service_spec.rb
  spec/services/submit_citizen_reminder_service_spec.rb
  spec/services/submit_provider_reminder_service_spec.rb
Labels: Ready to merge

#5031 Introduce encrypted Citizen access tokens
  app/models/citizen/access_token.rb
  app/models/legal_aid_application.rb
  db/anonymise/rules.rb
  db/migrate/20230221174503_create_citizen_access_tokens.rb
  db/schema.rb
  lib/tasks/migrate_citizen_urls.rake
  spec/factories/citizen/access_tokens.rb
  spec/models/citizen/access_token_spec.rb
  spec/models/legal_aid_application_spec.rb
Labels: approved, active-record-encryption

#5032 Remove citizen URL columns
  db/migrate/20230223154933_remove_citizen_url_from_legal_aid_applications.rb
  db/schema.rb
Labels: approved, active-record-encryption

#5034 Retrieve applications by Citizen access token
  .rubocop_todo.yml
  app/controllers/citizens/resend_link_requests_controller.rb
  app/controllers/providers/about_the_financial_assessments_controller.rb
  app/models/legal_aid_application.rb
  app/services/citizen_email_service.rb
  app/services/secure_application_finder.rb
  app/services/submit_citizen_reminder_service.rb
  features/step_definitions/citizens_steps.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/applicants/omniauth_callbacks_spec.rb
  spec/requests/citizens/accounts_spec.rb
  spec/requests/citizens/additional_accounts_spec.rb
  spec/requests/citizens/bank_spec.rb
  spec/requests/citizens/check_answers_spec.rb
  spec/requests/citizens/consents_controller_spec.rb
  spec/requests/citizens/contact_providers_controller_spec.rb
  spec/requests/citizens/gather_transactions_spec.rb
  spec/requests/citizens/legal_aid_applications_controller_spec.rb
  spec/requests/citizens/legal_aid_applications_spec.rb
  spec/requests/citizens/means_test_results_controller_spec.rb
  spec/requests/citizens/means_test_results_spec.rb
  spec/requests/citizens/resend_link_requests_controller_spec.rb
  spec/requests/citizens/resend_link_requests_spec.rb
  spec/requests/providers/means/property_value_spec.rb
  spec/services/citizen_email_service_spec.rb
  spec/services/secure_application_finder_spec.rb
  spec/services/submit_citizen_reminder_service_spec.rb
  spec/support/citizen_helpers.rb
Labels: approved, do not merge, active-record-encryption

#4973 [AP-3778] Under 18 content changes
  app/assets/stylesheets/helpers.scss
  app/assets/stylesheets/print-styles.scss
  app/models/applicant.rb
  app/models/legal_aid_application.rb
  app/views/providers/confirm_client_declarations/show.html.erb
  app/views/providers/declarations/show.html.erb
  app/views/providers/end_of_applications/show.html.erb
  app/views/providers/open_banking_guidances/show.html.erb
  app/views/providers/review_and_print_applications/show.html.erb
  app/views/shared/_applicant_declaration.html.erb
  app/views/shared/_printable_over_18_declaration.html.erb
  app/views/shared/_printable_under_18_declaration.html.erb
  app/views/shared/forms/_list_with_items.html.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
  config/locales/cy/shared.yml
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/non_means_tested_journey/certification_test.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/review_and_print.feature
  features/step_definitions/civil_journey_steps.rb
  spec/forms/legal_aid_applications/confirm_client_declaration_form_spec.rb
  spec/models/applicant_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/confirm_client_declarations_controller_spec.rb
  spec/requests/providers/review_and_print_applications_controller_spec.rb
  spec/requests/providers/submitted_applications_spec.rb
Labels: UAT, approved

#5036 Stop ignoring Citizen URL columns
  app/models/legal_aid_application.rb
Labels: Ready to merge, active-record-encryption

#5035 Remove `SecureData`
  .rubocop_todo.yml
  Gemfile
  app/models/secure_data.rb
  config/application.rb
  db/anonymise/rules.rb
  db/migrate/20230224112243_drop_secure_data.rb
  db/schema.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  lib/tasks/migrate_citizen_urls.rake
  spec/factories/secure_data.rb
  spec/models/applicant_spec.rb
  spec/models/secure_data_spec.rb
Labels: active-record-encryption

#5042 Remove unused method
  app/models/applicant.rb
  spec/models/applicant_spec.rb
  spec/requests/applicants/omniauth_callbacks_spec.rb
Labels: approved

#5044 Add Partner means assessment feature flag
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  db/migrate/20230228112837_add_partner_means_assessment_to_settings.rb
  db/schema.rb
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
Labels: approved
