Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2023-11, with the labels that each got.

#5930 Fix: Partner review application page
  app/views/shared/check_answers/_partner_details.html.erb
Labels: approved

#5921 Update Rails 7 gem and node
  Gemfile.lock
  app/forms/legal_aid_applications/has_evidence_of_benefit_form.rb
  app/lib/omni_auth/omni_auth_true_layer.rb
  app/models/bank_holiday.rb
  app/models/bank_transaction.rb
  app/models/provider.rb
  app/models/scheduled_mailing.rb
  app/models/true_layer_bank.rb
  app/services/legal_framework/merits_tasks_service.rb
  config/application.rb
  config/environments/test.rb
  config/initializers/devise.rb
  config/locales/en/transaction_types.yml
  package.json
  spec/forms/legal_aid_applications/has_evidence_of_benefit_form_spec.rb
  spec/requests/admin_users/sessions_controller_spec.rb
  spec/requests/providers/check_capital_answers_controller_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
  spec/requests/providers/means/employment_incomes_controller_spec.rb
  spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
  spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
  spec/requests/providers/outgoings_summary_controller_spec.rb
  spec/requests/providers/partners/employment_incomes_controller_spec.rb
  spec/requests/providers/submitted_applications_controller_spec.rb
  yarn.lock
Labels: UAT, approved

#5941 build(deps): bump govuk-frontend from 4.6.0 to 4.7.0
  package.json
  yarn.lock
Labels: approved

#5929 AP-4583: Extend upload evidence for partner
  app/models/partner.rb
  app/services/required_document_category_analyser.rb
  app/services/uploaded_evidence/base.rb
  app/validators/document_category_validator.rb
  ccms_integration/example_payloads/NonMeansTested.xml
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  db/schema.rb
  db/seeds/document_categories.csv
  features/providers/applicant_details.feature
  features/providers/applicant_under_16_blocked.feature
  features/providers/check_multiple_employment.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/check_pending_employment.feature
  features/providers/check_provider_answers.feature
  features/providers/check_single_employment.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/cost_override.feature
  features/providers/no_nino_flow.feature
  features/providers/non_means_tested_journey/under_18_application_journey.feature
  features/providers/non_means_tested_journey/with_delegated_functions.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/non_passported_journey/with_capital.feature
  features/providers/non_passported_journey/with_dependants.feature
  features/providers/non_passported_journey/with_means.feature
  features/providers/partner_means_assessment/upload_partner_employment_evidence.feature
  features/providers/pathways_from_check_your_answers.feature
  features/providers/regressions/scope_limitations.feature
  features/step_definitions/evidence_upload_steps.rb
  features/step_definitions/partner_employment_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/models/document_category_spec.rb
  spec/requests/providers/proceeding_loop/client_involvement_type_controller_spec.rb
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/services/required_document_category_analyser_spec.rb
  spec/services/uploaded_evidence/save_and_continue_service_spec.rb
Labels: approved, Ready to merge, ruby

#5926 AP-4567: Add non-passported to list of reasons on means report
  app/models/legal_aid_application.rb
  app/services/ccms/manual_review_determiner.rb
  config/locales/en/providers.yml
  features/providers/means_report.feature
  spec/services/ccms/manual_review_determiner_spec.rb
Labels: approved

#5925 Ap-4566: means report bank account changes
  app/views/shared/check_answers/_assets.html.erb
  config/locales/en/shared.yml
  features/providers/means_report.feature
  features/step_definitions/generic_steps.rb
  features/step_definitions/means_report_steps.rb
Labels: approved

#5959 Rubocop: Address let! usage in tests
  .rubocop_todo.yml
  spec/forms/applicants/employed_form_spec.rb
  spec/jobs/email_monitor_job_spec.rb
  spec/jobs/scheduled_mailings_delivery_job_spec.rb
  spec/presenters/applicant_account_presenter_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_benefits_attrs_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/reports/merits_report_creator_spec.rb
  spec/workers/bank_holiday_update_worker_spec.rb
  spec/workers/true_layer_banks_update_worker_spec.rb
Labels: ready for review

#5949 AP-3887: Add Partner CCMS values
  app/services/ccms/attribute_value_generator.rb
  config/ccms/attribute_block_configs/base.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: UAT, approved

#5932 AP-4575: Add copy case page flows
  Gemfile
  Gemfile.lock
  app/controllers/providers/copy_case/confirmations_controller.rb
  app/controllers/providers/copy_case/invitations_controller.rb
  app/controllers/providers/copy_case/searches_controller.rb
  app/forms/copy_case/confirmation_form.rb
  app/forms/copy_case/invitation_form.rb
  app/forms/copy_case/search_form.rb
  app/services/copy_case/cloner_service.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/copy_case/confirmations/show.html.erb
  app/views/providers/copy_case/invitations/show.html.erb
  app/views/providers/copy_case/searches/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/migrate/20231020085303_add_copy_case_to_legal_aid_application.rb
  db/schema.rb
  features/cassettes/Copy_a_case_s_applicable_details/I_choose_not_to_copy_another_case_s_details.yml
  features/cassettes/Copy_a_case_s_applicable_details/I_choose_to_copy_another_case_s_details.yml
  features/providers/copy_case.feature
  features/step_definitions/copy_case.rb
  spec/forms/copy_case/confirmation_form_spec.rb
  spec/forms/copy_case/invitation_form_spec.rb
  spec/forms/copy_case/search_form_spec.rb
  spec/requests/providers/address_selections_controller_spec.rb
  spec/requests/providers/addresses_controller_spec.rb
  spec/requests/providers/copy_case/confirmations_controller_spec.rb
  spec/requests/providers/copy_case/invitations_controller_spec.rb
  spec/requests/providers/copy_case/searches_controller_spec.rb
  spec/services/copy_case/cloner_service_spec.rb
Labels: UAT, approved

#6000 Chore: Amend babel dependabot group
  .github/dependabot.yml
Labels: ready for review

#6003 Fix: CFE vehicle submission
  app/services/cfe_civil/components/vehicles.rb
Labels: approved

#6009 AP-4575[ext]: handle clearup of copy case data for negative and reverse flows
  app/forms/copy_case/confirmation_form.rb
  app/forms/copy_case/invitation_form.rb
  spec/forms/copy_case/confirmation_form_spec.rb
  spec/forms/copy_case/invitation_form_spec.rb
Labels: ready for review

#6018 Fix: partner minor tweaks
  app/models/partner.rb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_partner_details.html.erb
Labels: approved

#6020 AP-4633: Remove word status
  config/locales/en/providers.yml
  features/providers/check_single_employment.feature
  features/providers/partner_means_assessment/upload_partner_employment_evidence.feature
Labels: ready for review, ruby

#5982 Ap 4503 correction to ineligible result
  app/helpers/ineligible_reasons_helper.rb
  app/models/cfe/v6/result.rb
  app/views/shared/assessment_results/_ineligible.html.erb
  config/locales/en/shared.yml
  spec/factories/cfe_results/v6/mock_results.rb
  spec/factories/cfe_results/v6/results.rb
  spec/helpers/ineligible_reasons_helper_spec.rb
  spec/models/cfe/v6/result_spec.rb
  spec/requests/providers/capital_assessment_results_controller_spec.rb
  spec/requests/providers/capital_income_assessment_results_controller_spec.rb
Labels: UAT, approved

#6017 AP-4575 [EXT]: Display copy case search ref if exists
  app/controllers/providers/copy_case/searches_controller.rb
  app/forms/copy_case/invitation_form.rb
  app/views/providers/copy_case/searches/show.html.erb
  spec/forms/copy_case/invitation_form_spec.rb
  spec/requests/providers/copy_case/searches_controller_spec.rb
Labels: approved

#6028 AP-4629: Update policy-disregards error handling
  app/views/providers/means/policy_disregards/show.html.erb
Labels: UAT

#6037 AP-4632: Update partner details on review page
  app/views/shared/check_answers/_partner_details.html.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
Labels: UAT

#6043 Rubocop: Address save_bang exclusions
  .rubocop_todo.yml
  app/controllers/concerns/providers/draftable.rb
  app/forms/base_form.rb
  app/forms/legal_aid_applications/dependant_form.rb
  app/forms/proceedings/emergency_defaults_form.rb
  app/forms/proceedings/emergency_level_of_service_form.rb
  app/forms/proceedings/scope_limitations_form.rb
  app/forms/proceedings/substantive_defaults_form.rb
  app/forms/proceedings/substantive_level_of_service_form.rb
  app/forms/providers/application_merits_task/client_denial_of_allegation_form.rb
  app/forms/providers/application_merits_task/client_offered_undertakings_form.rb
  app/forms/providers/application_merits_task/nature_of_urgency_form.rb
  app/forms/providers/proceeding_merits_task/linked_children_form.rb
  app/forms/providers/regular_transaction_form.rb
  app/forms/providers/uploaded_evidence_collection_form.rb
  app/forms/statement_of_cases/statement_of_case_form.rb
  app/forms/vehicles/details_form.rb
Labels: ready for review

#6050 Fix: Update delete deployment script
  bin/delete_dependabot_deployment
Labels: ready for review

#6051 delete any PVC named after the release
  bin/delete_dependabot_deployment
Labels: approved

#6063 Docs: update pull request template
  README.md
  docs/pull_request_template.md
Labels: approved

#5968 AP-4597:Update required evidence text,add line break,and add accessib…
  app/views/providers/uploaded_evidence_collections/_upload_evidence.html.erb
  app/views/providers/uploaded_evidence_collections/_uploaded_files.html.erb
  app/views/providers/uploaded_evidence_collections/show.html.erb
  config/locales/en/providers.yml
  features/providers/check_single_employment.feature
  features/providers/partner_means_assessment/upload_partner_employment_evidence.feature
Labels: Ready to merge, ruby, bug
