Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2023-07, with the labels that each got.

#5408 AP-4222: Fix scope limitation/next proceeding handling
  app/models/proceeding.rb
  app/services/flow/proceeding_loop.rb
  app/services/query/incomplete_proceedings.rb
  features/cassettes/Scope_limitations_not_being_set/When_a_provider_creates_an_application_with_multiple_proceedings_and_uses_the_back_button_scope_limitations_should_not_be_removed.yml
  features/providers/regressions/scope_limitations.feature
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/services/flow/proceeding_loop_spec.rb
  spec/services/query/incomplete_proceedings_spec.rb
Labels: UAT, approved

#5438 Fix: Update DB export
  scripts/db_export.sh
Labels: ready for review

#5432 AP-3805 Update HMRC Responses to have owner
  app/models/applicant.rb
  app/models/hmrc/response.rb
  app/models/partner.rb
  app/services/hmrc/create_responses_service.rb
  db/migrate/20230628085216_add_owner_to_hmrc_responses.rb
  db/schema.rb
  lib/tasks/migrate_hmrc_responses.rake
  spec/factory_specs/hmrc_response/use_case_one_helper_spec.rb
  spec/models/hmrc/response_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/means/full_employment_details_controller_spec.rb
  spec/services/cfe/create_employments_service_spec.rb
  spec/services/hmrc/create_responses_service_spec.rb
  spec/services/hmrc/interface/result_service_spec.rb
  spec/services/hmrc/interface/submission_service_spec.rb
  spec/services/hmrc/mock_interface_response_service_spec.rb
  spec/services/hmrc/parsed_response/persistor_spec.rb
  spec/services/hmrc/parsed_response/validator_spec.rb
  spec/workers/hmrc/result_worker_spec.rb
  spec/workers/hmrc/submission_worker_spec.rb
Labels: UAT, approved

#5444 AP-4214: Update partner description
  app/views/providers/partners/client_has_partners/show.html.erb
  config/locales/en/providers.yml
Labels: approved

#5443 AP-3805 Part 2 add owner to employments
  app/models/applicant.rb
  app/models/employment.rb
  app/models/partner.rb
  app/services/hmrc/parsed_response/persistor.rb
  db/migrate/20230703102937_add_owner_to_employment.rb
  db/schema.rb
  features/step_definitions/bank_statement_upload_steps.rb
  features/step_definitions/check_your_answers_steps.rb
  features/step_definitions/civil_journey_steps.rb
  lib/tasks/migrate_employments.rake
  spec/factories/legal_aid_applications.rb
  spec/models/hmrc/response_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/means/employed_incomes_spec.rb
  spec/requests/providers/means/full_employment_details_controller_spec.rb
  spec/requests/providers/means/unexpected_employed_incomes_spec.rb
  spec/services/cfe/create_employments_service_spec.rb
  spec/services/cfe_civil/components/employments_spec.rb
  spec/services/hmrc/parsed_response/persistor_spec.rb
  spec/services/hmrc/status_analyzer_spec.rb
Labels: approved

#5456 AP-4266: Remove partner address
  app/controllers/concerns/providers/draftable.rb
  app/controllers/providers/partners/address_lookups_controller.rb
  app/controllers/providers/partners/address_selections_controller.rb
  app/controllers/providers/partners/addresses_controller.rb
  app/controllers/providers/partners/shared_addresses_controller.rb
  app/forms/addresses/partner_address_form.rb
  app/forms/addresses/partner_address_lookup_form.rb
  app/forms/addresses/partner_address_selection_form.rb
  app/forms/partners/shared_address_form.rb
  app/models/partner.rb
  app/services/flow/flows/provider_partner.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/means_reports/show.html.erb
  app/views/providers/merits_reports/show.html.erb
  app/views/providers/partners/address_lookups/show.html.erb
  app/views/providers/partners/address_selections/show.html.erb
  app/views/providers/partners/addresses/show.html.erb
  app/views/providers/partners/shared_addresses/show.html.erb
  app/views/shared/check_answers/_partner_details.html.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20230706095142_remove_address_fields_from_partner.rb
  db/schema.rb
  features/providers/partner_means_assessment/check_your_answers.feature
  features/providers/partner_means_assessment/with_an_unknown_address.feature
  features/providers/partner_means_assessment/with_different_address.feature
  features/providers/partner_means_assessment/with_shared_address.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/partners.rb
  spec/forms/addresses/partner_address_form_spec.rb
  spec/forms/addresses/partner_address_lookup_form_spec.rb
  spec/forms/addresses/partner_address_selection_form_spec.rb
  spec/forms/partners/shared_address_form_spec.rb
  spec/models/partner_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/partners/address_lookups_controller_spec.rb
  spec/requests/providers/partners/address_selections_controller_spec.rb
  spec/requests/providers/partners/addresses_controller_spec.rb
  spec/requests/providers/partners/details_controller_spec.rb
  spec/requests/providers/partners/shared_addresses_controller_spec.rb
Labels: UAT, approved

#5458 Fix: Add missing close dl tag
  app/views/providers/means_reports/_income_cash_payments.html.erb
Labels: approved

#5468 Fix: Remove duplicated locale blocks
  app/views/providers/means/other_assets/_second_home_conditional_checkbox.html.erb
  config/locales/en/providers.yml
  spec/requests/providers/means/other_assets_controller_spec.rb
Labels: ready for review

#5418 Remove db backup cronjobs
  README.md
  bin/cleanup_manual_snapshots
  bin/create_manual_snapshot
  helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
  helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml
Labels: approved

#5467 AP-4103: Update types of income page text
  config/locales/en/providers.yml
  features/providers/check_multiple_employment.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/employed_journey.feature
  features/providers/non_passported_journey/with_bank_transactions.feature
  features/providers/non_passported_journey/with_capital.feature
  features/providers/non_passported_journey/with_dependants.feature
  features/providers/non_passported_journey/with_means.feature
  features/providers/partner_means_assessment/means_check.feature
  spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
Labels: approved

#5477 Fix: Update CFE::BaseResult ownership
  app/models/cfe/submission.rb
Labels: approved

#5469 AP-4037: Add contrary interest question
  app/controllers/providers/partners/client_has_partners_controller.rb
  app/controllers/providers/partners/contrary_interests_controller.rb
  app/forms/partners/client_has_partner_form.rb
  app/forms/partners/contrary_interests_form.rb
  app/forms/providers/partners/client_has_partner_form.rb
  app/services/flow/flows/provider_partner.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/partners/contrary_interests/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/migrate/20230711081546_add_partner_has_contrary_interest_to_applicants.rb
  db/schema.rb
  spec/forms/partners/client_has_partner_form_spec.rb
  spec/forms/partners/contrary_interests_form_spec.rb
  spec/requests/providers/partners/client_has_partners_controller_spec.rb
  spec/requests/providers/partners/contrary_interests_controller_spec.rb
Labels: approved

#5459 AP-3805: HRMC request for partner
  app/models/partner.rb
  app/services/hmrc/create_responses_service.rb
  app/services/hmrc/interface/submission_service.rb
  app/services/hmrc/mock_interface_response_service.rb
  app/services/hmrc/parsed_response/persistor.rb
  app/services/hmrc/parsed_response/validator.rb
  app/views/admin/legal_aid_applications/submissions/show.html.erb
  features/step_definitions/partner_means_check.rb
  spec/services/cfe_civil/components/employments_spec.rb
  spec/services/hmrc/create_responses_service_spec.rb
  spec/services/hmrc/interface/submission_service_spec.rb
  spec/services/hmrc/mock_interface_response_service_spec.rb
  spec/services/hmrc/parsed_response/validator_spec.rb
Labels: UAT

#5472 ap-4294: Remove ecr cleanup scripts and associated circleci config
  .circleci/config.yml
  bin/clean_up_ecr
  bin/delete_ecr_images
Labels: approved

#5478 ap-4290: add serviceAccountName to deployment
  config/storage.yml
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/deployment_metrics.yaml
  helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
  helm_deploy/apply-for-legal-aid/templates/deployment_worker.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: UAT, approved

#5484 AP-4084: Update client financial assessment page
  app/controllers/providers/client_completed_means_controller.rb
  config/locales/en/providers.yml
  spec/requests/providers/client_completed_means_spec.rb
Labels: UAT, approved

#5486 Add opponent organisations feature flag
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  db/migrate/20230713083234_add_opponent_organisations_setting_feature_flag.rb
  db/schema.rb
  spec/models/setting_spec.rb
  spec/requests/admin/settings_spec.rb
Labels: approved

#5498 AP-4033 make child error messages and headings consistent
  app/controllers/providers/application_merits_task/remove_involved_child_controller.rb
  app/controllers/providers/application_merits_task/remove_opponent_controller.rb
  app/controllers/providers/means/remove_dependants_controller.rb
  app/models/concerns/binary_choice_form.rb
  app/views/providers/application_merits_task/remove_involved_child/show.html.erb
  app/views/providers/application_merits_task/remove_opponent/show.html.erb
  app/views/providers/capital_introductions/show.html.erb
  config/locales/en/providers.yml
  features/providers/merits_task_list.feature
  features/providers/non_passported_journey/with_dependants.feature
  spec/requests/providers/application_merits_task/remove_involved_child_spec.rb
  spec/requests/providers/means/remove_dependant_controller_spec.rb
Labels: UAT, approved

#5528 Fix: Flickering test
  spec/requests/providers/means/remove_dependant_controller_spec.rb
Labels: ready for review

#5518 AP-4302: Add page for opponent type question
  app/controllers/providers/application_merits_task/opponent_types_controller.rb
  app/services/flow/flows/provider_merits.rb
  app/views/providers/application_merits_task/opponent_types/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/merits_task_list.feature
  spec/requests/providers/application_merits_task/has_other_opponents_controller_spec.rb
  spec/requests/providers/application_merits_task/opponent_types_controller_spec.rb
Labels: ready for review

#5519 AP-4284: Migrate to using an opposable individual
  app/controllers/providers/application_merits_task/opponent_individuals_controller.rb
  app/forms/opponents/individual_form.rb
  app/forms/opponents/name_form.rb
  app/models/application_merits_task/individual.rb
  app/models/application_merits_task/opponent.rb
  app/services/flow/flows/provider_merits.rb
  app/views/providers/application_merits_task/has_other_opponents/show.html.erb
  app/views/providers/application_merits_task/opponent_individuals/_form.html.erb
  app/views/providers/application_merits_task/opponent_individuals/new.html.erb
  app/views/providers/application_merits_task/opponent_individuals/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  lib/tasks/migrate_opponents_to_individuals.rake
  scripts/restore_anonymised_db.sh
  spec/factories/opponents.rb
  spec/forms/opponents/individual_form_spec.rb
  spec/forms/opponents/name_form_spec.rb
  spec/models/application_merits_task/individual_spec.rb
  spec/models/application_merits_task/opponent_spec.rb
  spec/requests/providers/application_merits_task/domestic_abuse_summaries_controller_spec.rb
  spec/requests/providers/application_merits_task/has_other_opponents_controller_spec.rb
  spec/requests/providers/application_merits_task/opponent_individuals_controller_spec.rb
  spec/requests/providers/application_merits_task/opponent_types_controller_spec.rb
  spec/requests/providers/application_merits_task/remove_opponent_controller_spec.rb
Labels: ready for review

#4733 Fix: Update web deploy with shell sleep
  helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
Labels: UAT, approved
