Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2023-09, with the labels that each got.

#5694 Fix: GatewayEvidence count in admin report
  app/services/reports/mis/application_detail_csv_line.rb
Labels: approved

#5696 AP-3212:Set user cookie duration for 1 year
  app/controllers/v1/providers_controller.rb
  app/helpers/cookie_banner_helper.rb
  app/views/layouts/_header.html.erb
  db/migrate/20230821163930_add_cookie_timestamp_to_provider.rb
  db/schema.rb
  features/providers/cookies.feature
  features/step_definitions/cookie_steps.rb
  spec/helpers/cookie_banner_helper_spec.rb
  spec/requests/providers/legal_aid_applications_spec.rb
  spec/requests/v1/providers_spec.rb
Labels: approved

#5697 AP-4425: Fix CashTransaction handling client/partner separation
  app/forms/providers/regular_transaction_form.rb
  features/providers/partner_means_assessment/end_to_end_income_assessment.feature
  features/support/steps_helper.rb
  spec/forms/providers/means/housing_benefit_form_spec.rb
Labels: approved

#5698 Rubocop: services/CCMS fixes
  .rubocop_todo.yml
  spec/services/ccms/attribute_configuration_spec.rb
  spec/services/ccms/manual_review_determiner_spec.rb
  spec/services/ccms/parsers/applicant_add_response_parser_spec.rb
  spec/services/ccms/requestors/applicant_add_requestor_spec.rb
  spec/services/ccms/requestors/applicant_add_status_requestor_spec.rb
  spec/services/ccms/requestors/applicant_search_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_status_requestor_spec.rb
  spec/services/ccms/requestors/document_id_requestor_spec.rb
  spec/services/ccms/requestors/document_upload_requestor_spec.rb
  spec/services/ccms/requestors/reference_data_requestor_spec.rb
  spec/services/ccms/restart_submissions_spec.rb
  spec/services/ccms/submitters/add_applicant_service_spec.rb
  spec/services/ccms/submitters/add_case_service_spec.rb
  spec/services/ccms/submitters/check_applicant_status_service_spec.rb
  spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
  spec/services/ccms/submitters/obtain_case_reference_service_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
  spec/services/ccms/submitters/upload_documents_service_spec.rb
Labels: ready for review

#5692 AP-4126: Update dependants pages
  app/views/providers/means/dependants/_form.html.erb
  app/views/providers/means/dependants/show.html.erb
  app/views/providers/means/has_dependants/show.html.erb
  app/views/providers/means/has_other_dependants/show.html.erb
  config/locales/en/providers.yml
  features/providers/partner_means_assessment/end_to_end_income_assessment.feature
  spec/requests/providers/means/dependants_controller_spec.rb
  spec/requests/providers/means/has_dependants_controller_spec.rb
Labels: approved

#5722 AP-4449 fix states for partner employment page
  app/controllers/providers/partners/employed_controller.rb
  app/models/concerns/base_state_machine.rb
  app/models/concerns/non_passported_state_machine.rb
  spec/requests/providers/partners/employed_controller_spec.rb
Labels: UAT, approved

#5726 Update: Remove kubectl from Dockerfile
  docker/apply_base.dockerfile
Labels: ready for review

#5728 AP-4441: Fix the overnight purge job
  db/migrate/20230911120457_update_legal_framework_merits_task_list_foreign_key.rb
  db/migrate/20230912082919_validate_legal_framework_merits_task_list_fk.rb
  db/schema.rb
Labels: approved, Ready to merge

#5709 AP-4107 partner housing benefit
  app/controllers/providers/means/housing_benefits_controller.rb
  app/services/flow/flows/provider_income.rb
  app/services/flow/flows/provider_partner.rb
  app/views/providers/means/housing_benefits/show.html.erb
  config/locales/en/generic.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/bank_statement_upload/check_your_means_answers.feature
  features/providers/bank_statement_upload/happy_path_journey.feature
  features/providers/partner_means_assessment/end_to_end_income_assessment.feature
  spec/requests/providers/means/cash_outgoings_controller_spec.rb
  spec/requests/providers/means/housing_benefits_controller_spec.rb
  spec/requests/providers/means/regular_outgoings_controller_spec.rb
  spec/requests/providers/outgoings_summary_controller_spec.rb
  spec/requests/providers/partners/cash_outgoings_controller_spec.rb
Labels: UAT, approved

#5734 AP-4445: Update student financial partial
  app/views/shared/_student_finances.html.erb
Labels: approved

#5737 Rubocop: Address RSpec/OverwritingSetup infractions
  .rubocop_todo.yml
  spec/models/legal_aid_application_spec.rb
  spec/requests/feedbacks_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
  spec/services/required_document_category_analyser_spec.rb
  spec/services/true_layer/importers/import_accounts_service_spec.rb
Labels: approved

#5736 Rubocop: More RSpec/NamedSubject improvements
  .rubocop_todo.yml
  spec/requests/admin/feedback_controller_spec.rb
  spec/requests/admin/legal_aid_applications/submissions_controller_spec.rb
  spec/requests/admin/legal_aid_applications_controller_spec.rb
  spec/requests/admin/reports_controller_spec.rb
  spec/requests/admin/roles/permissions_controller_spec.rb
  spec/requests/admin/roles_controller_spec.rb
  spec/requests/admin/settings_controller_spec.rb
  spec/requests/admin/submitted_applications_reports_controller_spec.rb
  spec/requests/admin_users/omniauth_callbacks_spec.rb
  spec/requests/applicants/omniauth_callbacks_spec.rb
  spec/requests/auth_spec.rb
  spec/requests/citizens/accounts_spec.rb
  spec/requests/citizens/check_answers_spec.rb
  spec/requests/citizens/gather_transactions_spec.rb
  spec/requests/errors_controller_spec.rb
  spec/requests/feedbacks_spec.rb
  spec/requests/problem_controller_spec.rb
Labels: approved

#5735 AP-4446: Clarify dependant errors
  config/locales/en/activemodel.yml
Labels: approved

#5743 Rubocop: Remove RSpec/ExpectInHook exclusions
  .rubocop_todo.yml
  spec/models/application_merits_task/involved_child_spec.rb
  spec/models/dashboard/widget_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/citizens/gather_transactions_spec.rb
  spec/services/bank_holiday_retriever_service_spec.rb
  spec/services/provider_after_login_service_spec.rb
  spec/services/reports/mis/application_details_report_spec.rb
  spec/services/true_layer/api_client_mock_spec.rb
Labels: approved

#5730 AP-4128 partner capital introductions page
  app/controllers/providers/capital_introductions_controller.rb
  app/services/flow/flows/provider_income.rb
  app/views/providers/capital_introductions/show.html.erb
  app/views/shared/check_answers/_income_cash_payments.html.erb
  app/views/shared/check_answers/_outgoings_cash_payments.html.erb
  config/locales/en/providers.yml
  features/providers/check_multiple_employment.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey/with_capital.feature
  features/providers/non_passported_journey/with_dependants.feature
  features/providers/non_passported_journey/with_means.feature
  features/providers/partner_means_assessment/end_to_end_income_assessment.feature
  spec/requests/providers/capital_introductions_controller_spec.rb
  spec/requests/providers/means/check_income_answers_controller_spec.rb
Labels: UAT, approved

#5738 AP-3810 partner own home
  app/views/providers/capital_introductions/show.html.erb
  app/views/providers/means/own_homes/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/generic.yml
  config/locales/en/providers.yml
  features/providers/partner_means_assessment/end_to_end_income_assessment.feature
  spec/requests/providers/means/own_home_spec.rb
Labels: UAT, approved

#5744 AP-4442: Ensure dependant pages show save as draft button
  app/controllers/providers/means/has_dependants_controller.rb
  app/controllers/providers/means/has_other_dependants_controller.rb
  app/forms/legal_aid_applications/has_dependants_form.rb
  app/views/providers/means/has_dependants/show.html.erb
  app/views/providers/means/has_other_dependants/show.html.erb
Labels: approved

#5755 Ap 4379/use details helper
  app/views/admin/legal_aid_applications/submissions/show.html.erb
  app/views/providers/transactions/show.html.erb
Labels: approved, Ready to merge, ruby

#5752 AP-4137 partner vehicles question
  app/views/providers/means/vehicles/show.html.erb
  config/locales/en/providers.yml
  features/providers/partner_means_assessment/end_to_end_income_assessment.feature
  features/step_definitions/civil_journey_steps.rb
  spec/requests/providers/means/vehicles_controller_spec.rb
Labels: UAT, approved

#5783 Rubocop: address RSpec/NamedSubject exclusions
  .rubocop_todo.yml
  spec/requests/providers/address_lookups_controller_spec.rb
  spec/requests/providers/address_selections_controller_spec.rb
  spec/requests/providers/addresses_spec.rb
  spec/requests/providers/applicant_bank_accounts_controller_spec.rb
  spec/requests/providers/applicant_details_controller_spec.rb
  spec/requests/providers/application_confirmations_spec.rb
  spec/requests/providers/application_dependable_spec.rb
  spec/requests/providers/application_merits_task/date_client_told_incidents_spec.rb
  spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
  spec/requests/providers/application_merits_task/involved_children_spec.rb
  spec/requests/providers/application_merits_task/remove_involved_child_spec.rb
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
  spec/requests/providers/bank_transactions_controller_spec.rb
Labels: ready for review

#5785 Rubocop: Address more NamedSubject exclusions
  .rubocop_todo.yml
  spec/requests/providers/capital_assessment_results_controller_spec.rb
  spec/requests/providers/capital_income_assessment_results_controller_spec.rb
  spec/requests/providers/check_benefits_controller_spec.rb
  spec/requests/providers/check_client_details_controller_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
  spec/requests/providers/check_provider_answers_controller_spec.rb
  spec/requests/providers/client_completed_means_controller_spec.rb
  spec/requests/providers/concerns/providers/draftable_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_controller_spec.rb
  spec/requests/providers/confirm_offices_spec.rb
  spec/requests/providers/delegated_confirmation_controller_spec.rb
  spec/requests/providers/email_addresses_spec.rb
  spec/requests/providers/end_of_applications_controller_spec.rb
  spec/requests/providers/has_evidence_of_benefits_controller_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/income_summary_controller_spec.rb
  spec/requests/providers/legal_aid_applications_spec.rb
  spec/requests/providers/limitations_controller_spec.rb
Labels: ready for review

#5786 AP-3813: Update bank account guidance
  config/locales/en/providers.yml
Labels: UAT

#5791 Rubocop: Address the next batch of NamedSubject exclusions
  .rubocop_todo.yml
  spec/requests/providers/means/dependants_controller_spec.rb
  spec/requests/providers/means/other_assets_controller_spec.rb
  spec/requests/providers/means/policy_disregards_controller_spec.rb
  spec/requests/providers/means/remove_dependants_controller_spec.rb
  spec/requests/providers/means/restrictions_spec.rb
  spec/requests/providers/means/savings_and_investments_spec.rb
  spec/requests/providers/means/vehicles_controller_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/requests/providers/offline_accounts_spec.rb
  spec/requests/providers/outgoings_summary_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
  spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
  spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb
  spec/requests/providers/proceedings_types_controller_spec.rb
  spec/requests/providers/providers_controller_spec.rb
  spec/requests/providers/received_benefit_confirmations_controller_spec.rb
Labels: approved

#5792 Ap 3655 use link helpers part 1
  app/helpers/admin_helper.rb
  app/helpers/flow_helper.rb
  app/helpers/language_switcher_helper.rb
  app/helpers/providers_helper.rb
  app/views/accessibility_statement/index.html.erb
  app/views/admin/ccms_queues/show.html.erb
  app/views/admin/firms/index.html.erb
  app/views/admin/legal_aid_applications/submissions/show.html.erb
  app/views/admin/reports/index.html.erb
  app/views/admin/user_dashboard/index.html.erb
  app/views/citizens/accounts/index.html.erb
  app/views/citizens/check_answers/_bank_accounts.html.erb
  app/views/citizens/gather_transactions/display_error.html.erb
  app/views/citizens/means_test_results/show.html.erb
  app/views/citizens/resend_link_requests/show.html.erb
  app/views/feedback/show.html.erb
  app/views/problem/index.html.erb
Labels: ready for review, ruby

#5760 AP-4400: CCMS inject new and existing opponent organisations
  app/models/application_merits_task/individual.rb
  app/models/application_merits_task/involved_child.rb
  app/models/application_merits_task/opponent.rb
  app/models/application_merits_task/organisation.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/payload_generators/other_party_attribute_generator.rb
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/legal_framework/add_opponent_organisation_service.rb
  app/views/providers/application_merits_task/has_other_opponents/show.html.erb
  config/ccms/attribute_block_configs/base.yml
  db/migrate/20230918142519_add_exists_in_ccms_to_opponents.rb
  db/schema.rb
  spec/models/application_merits_task/individual_spec.rb
  spec/models/application_merits_task/involved_child_spec.rb
  spec/models/application_merits_task/opponent_spec.rb
  spec/models/application_merits_task/organisation_spec.rb
  spec/services/ccms/payload_generators/other_party_attribute_generator_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_means_tested_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/legal_framework/add_opponent_organisation_service_spec.rb
  spec/support/have_xml.rb
  spec/support/xml_attribute_block_matcher.rb
Labels: UAT, approved

#5768 AP-4138: Update partner vehicle questions
  app/controllers/providers/check_capital_answers_controller.rb
  app/controllers/providers/means/vehicle_details_controller.rb
  app/forms/vehicles/details_form.rb
  app/views/providers/means/vehicle_details/show.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  db/migrate/20230918144429_add_owner_to_vehicles.rb
  db/schema.rb
  features/providers/partner_means_assessment/end_to_end_capital_assessment.feature
  features/step_definitions/partner_means_check.rb
  lib/tasks/add_vehicle_ownership.rake
  spec/factories/vehicles.rb
  spec/forms/vehicles/details_form_spec.rb
  spec/requests/providers/check_capital_answers_controller_spec.rb
  spec/requests/providers/means/vehicle_details_controller_spec.rb
Labels: approved

#5782 AP-4455: Full text search headlines for organisation search
  app/assets/stylesheets/providers/search_results.scss
  app/javascript/src/modules/organisations.js
  app/javascript/src/modules/organisations.spec.js
  features/cassettes/lfa_organisations_all.yml
  features/providers/search_opponent_organisations.feature
  features/step_definitions/merits_task_steps.rb
  jest-setup.js
  jest.config.js
  package.json
  spec/cassettes/lfa_organisations_all.yml
  spec/requests/providers/application_merits_task/opponent_existing_organisations_controller_spec.rb
  yarn.lock
Labels: ready for review

#5762 AP-4139: Allow adding another vehicle
  app/controllers/providers/check_capital_answers_controller.rb
  app/controllers/providers/means/add_other_vehicles_controller.rb
  app/controllers/providers/means/remove_vehicles_controller.rb
  app/controllers/providers/means/vehicle_details_controller.rb
  app/controllers/providers/means/vehicles_controller.rb
  app/models/legal_aid_application.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/cfe_civil/components/vehicles.rb
  app/services/flow/flows/provider_capital.rb
  app/services/reports/mis/application_detail_csv_line.rb
  app/views/providers/means/add_other_vehicles/show.html.erb
  app/views/providers/means/remove_vehicles/show.html.erb
  app/views/providers/means/vehicle_details/_form.html.erb
  app/views/providers/means/vehicle_details/new.html.erb
  app/views/providers/means/vehicle_details/show.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  config/ccms/attribute_block_configs/base.yml
  config/ccms/attribute_block_configs/non_passported.yml
  config/ccms/means_entity_configs/non_passported.yml
  config/ccms/means_entity_configs/passported.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  features/providers/check_your_answers.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/means_report.feature
  features/providers/non_passported_journey/with_capital.feature
  features/providers/vehicle.feature
  features/step_definitions/civil_journey_steps.rb
  features/step_definitions/means_report_steps.rb
  spec/data/ccms/case_add_request.xml
  spec/data/ccms/df_case_add_request.xml
  spec/data/ccms/non_default_client_involvement_type.xml
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/check_capital_answers_controller_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
  spec/requests/providers/means/add_other_vehicles_controller_spec.rb
  spec/requests/providers/means/remove_vehicles_controller_spec.rb
  spec/requests/providers/means/vehicle_details_controller_spec.rb
  spec/requests/providers/means/vehicles_controller_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/cfe_civil/submission_builder_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: UAT

#5800 Rubocop: Address remaining request RSpec/NamedSubject exclusions
  .rubocop_todo.yml
  spec/requests/providers/select_offices_spec.rb
  spec/requests/providers/start_spec.rb
  spec/requests/providers/submitted_applications_controller_spec.rb
  spec/requests/providers/substantive_applications_controller_spec.rb
  spec/requests/providers/transactions_controller_spec.rb
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/requests/providers/use_ccms_controller_spec.rb
  spec/requests/saml_sessions_spec.rb
  spec/requests/v1/legal_aid_applications_spec.rb
  spec/requests/v1/statement_of_cases_spec.rb
  spec/requests/v1/uploaded_evidence_collections_spec.rb
  spec/requests/v1/workers_spec.rb
Labels: ready for review

#5802 Fix: vehicle_detail error handling
  app/views/providers/means/vehicle_details/_form.html.erb
Labels: approved

#5769 AP-4133 partner property details
  app/views/providers/means/property_details/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/back_button.feature
  features/providers/check_your_answers.feature
  features/providers/means_report.feature
  features/providers/non_passported_journey/with_capital.feature
  features/providers/partner_means_assessment/end_to_end_income_assessment.feature
  features/providers/passported_journey.feature
  spec/requests/providers/means/property_details_controller_spec.rb
Labels: approved

#5805 Fix: @individual parameter missing from partial
  app/views/providers/means_reports/_with_bank_statement_uploads.html.erb
  app/views/providers/means_reports/_with_cfe_result_details.html.erb
Labels: ready for review
