Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2023-12, with the labels that each got.

#6048 AP-4628: Partner manual review determiner
  app/models/legal_aid_application.rb
  app/services/ccms/manual_review_determiner.rb
  config/locales/en/providers.yml
  features/providers/means_report.feature
  spec/services/ccms/manual_review_determiner_spec.rb
Labels: approved

#6075 Rubocop: Remove verified doubles violations
  .rubocop_todo.yml
  app/services/ccms/attribute_value_generator.rb
  spec/lib/slack_alerter_spec.rb
  spec/services/ccms/attribute_value_generator_spec.rb
  spec/services/govuk_emails/delivery_man_spec.rb
  spec/services/malware_scanner_spec.rb
  spec/support/shared_context/ccms_soa_configuration_context.rb
Labels: ready for review

#6041 AP-4617: Use puffing-billy to stub feature test javascript API calls
  Gemfile
  Gemfile.lock
  README.md
  docs/puffing_billy_recording.md
  features/providers/applicant_details.feature
  features/providers/search_opponent_organisations.feature
  features/step_definitions/civil_journey_steps.rb
  features/step_definitions/merits_task_steps.rb
  features/support/env.rb
  features/support/puffing_billy.rb
  features/support/puffing_billy_helper.rb
  features/support/vcr.rb
Labels: ready for review

#6071 AP-4664: Update CFE Review Reason values
  app/models/cfe/remarks.rb
  config/locales/en/providers.yml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/models/cfe/remarks_spec.rb
Labels: UAT, approved

#6081 Rubocop: Address StubbedMocks issues
  .rubocop_todo.yml
  spec/jobs/citizen_complete_means_job_spec.rb
  spec/jobs/dashboard/updater_job_spec.rb
  spec/jobs/scheduled_mailings_delivery_job_spec.rb
  spec/lib/omni_auth/strategies/moj_oauth2_spec.rb
  spec/lib/slack_alerter_spec.rb
  spec/models/dashboard/single_object/applicant_email_spec.rb
  spec/models/dashboard/single_object/feedback_spec.rb
  spec/models/dashboard/single_object/provider_data_spec.rb
  spec/models/dashboard/widget_spec.rb
  spec/models/provider_spec.rb
  spec/requests/saml_sessions_spec.rb
  spec/services/ccms/attribute_value_generator_spec.rb
  spec/services/digest_exporter_spec.rb
  spec/services/govuk_emails/delivery_man_spec.rb
  spec/services/metrics/send_metrics_spec.rb
Labels: ready for review, approved

#6083 Ap 4630 partner/cash income
  app/controllers/providers/partners/cash_incomes_controller.rb
  app/controllers/providers/partners/cash_outgoings_controller.rb
  app/views/providers/means/cash_incomes/show.html.erb
  app/views/providers/means/cash_outgoings/show.html.erb
  app/views/providers/partners/cash_incomes/show.html.erb
  app/views/providers/partners/cash_outgoings/show.html.erb
  app/views/shared/means/_cash_income.html.erb
  app/views/shared/means/_cash_outgoing.html.erb
  db/migrate/20231205092447_add_no_cash_income_to_partners.rb
  db/migrate/20231205180352_add_no_cash_outgoings_to_partners.rb
  db/schema.rb
  spec/requests/providers/partners/cash_incomes_controller_spec.rb
  spec/requests/providers/partners/cash_outgoings_controller_spec.rb
Labels: approved, Ready to merge, ruby, bug

#6139 Fix some rspec any-instance rubocop warnings
  .rubocop_todo.yml
  spec/jobs/bank_transactions_analyser_job_spec.rb
  spec/requests/admin/settings_controller_spec.rb
  spec/requests/applicants/omniauth_callbacks_spec.rb
  spec/requests/providers/application_merits_task/statement_of_case_spec.rb
  spec/requests/providers/means/other_assets_controller_spec.rb
  spec/requests/v1/statement_of_cases_spec.rb
  spec/requests/v1/uploaded_evidence_collections_spec.rb
  spec/services/reports/mis/application_details_report_spec.rb
Labels: approved

#6144 AP-4434: Change h3 to h2
  app/views/providers/open_banking_guidances/show.html.erb
Labels: approved

#6116 AP-4703: Use task list component, update feature tests
  app/assets/stylesheets/task-list.scss
  app/helpers/task_list_helper.rb
  app/services/flow/merits_loop.rb
  app/services/legal_framework/merits_tasks_service.rb
  app/views/providers/income_summary/index.html.erb
  app/views/providers/merits_task_lists/_task_list_item.html.erb
  app/views/providers/merits_task_lists/_task_list_section.html.erb
  app/views/providers/merits_task_lists/show.html.erb
  config/locales/en/providers.yml
  features/providers/check_ccms_autogrant.feature
  features/providers/merits_task_list.feature
  features/providers/merits_task_list_opponent.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/non_passported_journey/with_means.feature
  features/providers/passported_journey.feature
  features/providers/search_opponent_organisations.feature
  features/providers/statement_of_case_upload.feature
  spec/helpers/task_list_helper_spec.rb
Labels: ready for review

#6107 AP-4604: Validation so "none" and another checkbox cannot both be selected
  app/forms/applicants/employed_form.rb
  app/forms/base_employed_form.rb
  app/forms/partners/employed_form.rb
  app/forms/partners/offline_accounts_form.rb
  app/forms/providers/other_assets_form.rb
  app/forms/providers/policy_disregards_form.rb
  app/forms/savings_amounts/offline_accounts_form.rb
  app/forms/savings_amounts/savings_amounts_form.rb
  config/locales/en/activemodel.yml
  spec/forms/applicants/employed_form_spec.rb
  spec/forms/partners/employed_form_spec.rb
  spec/forms/partners/offline_accounts_form_spec.rb
  spec/forms/providers/other_assets_form_spec.rb
  spec/forms/savings_amounts/offline_accounts_form_spec.rb
  spec/forms/savings_amounts/savings_amounts_form_spec.rb
  spec/requests/providers/means/policy_disregards_controller_spec.rb
Labels: ready for review

#6062 AP-3811 partner means assessment
  app/models/cfe/v4/result.rb
  app/models/cfe/v6/result.rb
  app/views/providers/capital_assessment_results/_result_details.html.erb
  app/views/providers/capital_income_assessment_results/_bank_statements.html.erb
  app/views/providers/capital_income_assessment_results/_deductions.html.erb
  app/views/providers/capital_income_assessment_results/_disposable_income.html.erb
  app/views/providers/capital_income_assessment_results/_employment_income.html.erb
  app/views/providers/capital_income_assessment_results/_other_income.html.erb
  app/views/providers/capital_income_assessment_results/_outgoings.html.erb
  app/views/providers/capital_income_assessment_results/_result_details.html.erb
  app/views/shared/_property_results.html.erb
  app/views/shared/_savings_and_investments.html.erb
  app/views/shared/_total_capital.html.erb
  app/views/shared/_vehicle_results.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  spec/factories/cfe_results/v6/mock_results.rb
  spec/factories/cfe_results/v6/results.rb
  spec/models/cfe/v6/result_spec.rb
  spec/models/cfe/v6/with_partner_result_spec.rb
  spec/requests/providers/capital_assessment_results_controller_spec.rb
  spec/requests/providers/capital_income_assessment_results_controller_spec.rb
Labels: approved
