Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2023-10, with the labels that each got.

#5812 Fix: css table styling
  app/assets/stylesheets/application.scss
Labels: approved

#5819 Axe core updates
  .github/dependabot.yml
Labels: ready for review

#5832 AP-4468: Update feature step susceptible to false positives
  features/providers/check_your_answers.feature
  features/providers/passported_journey.feature
  features/step_definitions/check_your_answers_steps.rb
  features/step_definitions/civil_journey_steps.rb
Labels: approved

#5829 AP-4506: Add linked_applications feature flag
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  db/migrate/20231004080150_add_linked_applications_setting_feature_flag.rb
  db/schema.rb
  spec/models/setting_spec.rb
  spec/requests/admin/settings_controller_spec.rb
Labels: approved

#5824 Rubocop: Address RSpec/NamedSubjects in services
  .rubocop_todo.yml
  spec/services/admin/provider_details_service_spec.rb
  spec/services/bank_holiday_retriever_service_spec.rb
  spec/services/banking/bank_transaction_balance_calculator_spec.rb
  spec/services/banking/bank_transactions_trimmer_spec.rb
  spec/services/banking/state_benefit_analyser_service_spec.rb
  spec/services/dashboard_event_handler_spec.rb
  spec/services/delegated_functions_date_service_spec.rb
  spec/services/flow/base_flow_service_spec.rb
  spec/services/flow/key_point_spec.rb
  spec/services/govuk_emails/delivery_man_spec.rb
  spec/services/job_queue_spec.rb
  spec/services/legal_framework/add_proceeding_service_spec.rb
  spec/services/legal_framework/lead_proceeding_assignment_service_spec.rb
  spec/services/malware_scanner_spec.rb
  spec/services/metrics/send_metrics_spec.rb
  spec/services/metrics/sidekiq_queue_sizes_spec.rb
  spec/services/mock_benefit_check_service_spec.rb
Labels: ready for review

#5838 Rubocop: Final removal of NamedSubject exclusions
  .rubocop_todo.yml
  spec/services/page_history_service_spec.rb
  spec/services/pdf_converter_spec.rb
  spec/services/populators/transaction_type_populator_spec.rb
  spec/services/provider_after_login_service_spec.rb
  spec/services/provider_details_retriever_spec.rb
  spec/services/provider_email_service_spec.rb
  spec/services/reports/bank_transactions/bank_transaction_report_creator_spec.rb
  spec/services/reports/merits_report_creator_spec.rb
  spec/services/reports/mis/non_passported_application_csv_line_spec.rb
  spec/services/reports/reports_creator_spec.rb
  spec/services/required_document_category_analyser_spec.rb
  spec/services/submit_application_reminder_service_spec.rb
  spec/services/submit_provider_reminder_service_spec.rb
  spec/services/substantive_application_deadline_calculator_spec.rb
  spec/services/true_layer/api_client_mock_spec.rb
  spec/services/true_layer/banks_retriever_spec.rb
  spec/services/true_layer/importers/import_account_balance_service_spec.rb
  spec/services/true_layer/importers/import_account_holders_service_spec.rb
  spec/services/true_layer/importers/import_accounts_service_spec.rb
  spec/services/true_layer_error_decoder_spec.rb
Labels: ready for review, approved

#5830 AP-4499: Add redis scanner utility class
  .simplecov
  lib/utilities/redis_scanner.rb
Labels: approved

#5807 AP-4143 partner asset questions
  app/controllers/providers/means/other_assets_controller.rb
  app/forms/providers/other_assets_form.rb
  app/views/providers/means/check_income_answers/_applicant_income_assessment.html.erb
  app/views/providers/means/check_income_answers/_partner_income_assessment.html.erb
  app/views/providers/means/other_assets/_second_home_conditional_checkbox.html.erb
  app/views/providers/means/other_assets/show.html.erb
  app/views/providers/means/policy_disregards/show.html.erb
  app/views/providers/means/restrictions/show.html.erb
  app/views/providers/means/savings_and_investments/show.html.erb
  app/views/providers/means_reports/_with_bank_statement_uploads.html.erb
  app/views/providers/means_reports/_with_cfe_result_details.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_employed_income.html.erb
  app/views/shared/review_application/_income_payments_and_assets_for_bank_statement_upload.html.erb
  config/locales/cy/shared.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/back_button.feature
  features/providers/check_ccms_autogrant.feature
  features/providers/check_multiple_employment.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/check_your_answers.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/means_report.feature
  features/providers/non_passported_journey/with_capital.feature
  features/providers/non_passported_journey/with_dependants.feature
  features/providers/non_passported_journey/with_means.feature
  features/providers/partner_means_assessment/end_to_end_capital_assessment.feature
  features/providers/partner_means_assessment/end_to_end_income_assessment.feature
  features/providers/passported_journey.feature
  spec/forms/providers/other_assets_form_spec.rb
  spec/requests/providers/means/other_assets_controller_spec.rb
  spec/requests/providers/means/policy_disregards_controller_spec.rb
Labels: UAT, approved

#5826 AP-4448: Replace link_to_accessible with govuk_link_to component
  app/helpers/accessible_navigation_helper.rb
  app/views/shared/_error.html.erb
  app/views/shared/_use_ccms.html.erb
  app/views/shared/check_answers/_employed_income.html.erb
  app/views/shared/check_answers/_housing_benefit.html.erb
  app/views/shared/check_answers/_item.html.erb
  app/views/shared/check_answers/_offline_savings_accounts.html.erb
  app/views/shared/check_answers/_one_link_section.html.erb
  app/views/shared/check_answers/_only_link_section.html.erb
  app/views/shared/check_answers/_proceeding_details.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  app/views/shared/forms/_error_summary.html.erb
  app/views/shared/forms/proceedings_types/_proceeding_type.html.erb
  spec/helpers/accessible_navigation_helper_spec.rb
Labels: ready for review, ruby

#5831 AP-4018: Update declarations
  app/views/providers/confirm_client_declarations/show.html.erb
  app/views/providers/end_of_applications/show.html.erb
  app/views/providers/review_and_print_applications/show.html.erb
  app/views/shared/_partner_declaration.html.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
Labels: UAT, approved

#5847 Rubocop: address RSpec/RepeatedDescription exclusions
  .rubocop_todo.yml
  spec/forms/legal_aid_applications/substantive_application_form_spec.rb
  spec/models/cfe/v2/result_spec.rb
  spec/models/cfe/v3/result_spec.rb
  spec/models/dependant_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
  spec/services/ccms/submitters/upload_documents_service_spec.rb
Labels: ready for review

#5854 Rubocop: address RSpec/RepeatedExample* exclusions
  .rubocop_todo.yml
  spec/factory_specs/v4/cfe_result_factory_spec.rb
  spec/helpers/providers_helper_spec.rb
  spec/models/cfe/v4/result_spec.rb
  spec/requests/citizens/additional_accounts_spec.rb
  spec/requests/citizens/gather_transactions_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/means/savings_and_investments_spec.rb
  spec/requests/providers/offline_accounts_spec.rb
  spec/services/ccms/parsers/applicant_add_status_response_parser_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Labels: ready for review

#5844 AP-4142: Add joint bank accounts page
  app/forms/partners/offline_accounts_form.rb
  app/forms/savings_amounts/offline_accounts_form.rb
  app/models/concerns/capital.rb
  app/models/savings_amount.rb
  app/views/providers/offline_accounts/show.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/forms/_offline_accounts_form.html.erb
  app/views/shared/forms/revealing_checkbox/_attribute.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  db/migrate/20231006091714_add_joint_accounts_to_savings_amounts.rb
  db/schema.rb
  features/providers/partner_means_assessment/end_to_end_capital_assessment.feature
  features/step_definitions/bank_statement_upload_steps.rb
  features/support/steps_helper.rb
  spec/forms/savings_amounts/offline_accounts_form_spec.rb
Labels: UAT, approved

#5833 AP-4452: Remove organisation feature flag
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/helpers/task_list_helper.rb
  app/models/setting.rb
  app/services/flow/flows/provider_merits.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  db/migrate/20231004144844_remove_opponent_organisations_flag_from_settings.rb
  db/schema.rb
  features/providers/check_ccms_autogrant.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/merits_task_list.feature
  features/providers/merits_task_list_opponent.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/passported_journey.feature
  features/providers/search_opponent_organisations.feature
  spec/helpers/task_list_helper_spec.rb
  spec/models/setting_spec.rb
  spec/requests/admin/settings_controller_spec.rb
  spec/requests/providers/application_merits_task/domestic_abuse_summaries_controller_spec.rb
  spec/requests/providers/application_merits_task/has_other_opponents_controller_spec.rb
  spec/requests/providers/application_merits_task/remove_opponent_controller_spec.rb
Labels: approved

#5855 Rubocop: address Rails/SaveBang exclusions
  .rubocop_todo.yml
  app/controllers/admin/legal_aid_applications_controller.rb
  app/controllers/citizens/additional_accounts_controller.rb
  app/controllers/providers/applicant_bank_accounts_controller.rb
  app/controllers/providers/application_merits_task/statement_of_cases_controller.rb
  app/controllers/providers/received_benefit_confirmations_controller.rb
  app/controllers/v1/statement_of_cases_controller.rb
  app/controllers/v1/uploaded_evidence_collections_controller.rb
  app/forms/base_bank_statement_form.rb
  app/forms/providers/uploaded_evidence_collection_form.rb
  app/forms/statement_of_cases/statement_of_case_form.rb
  app/jobs/reports_uploader_job.rb
  app/services/admin/provider_details_service.rb
  app/services/banking/bank_transaction_balance_calculator.rb
  app/services/digest_extractor.rb
  app/services/hmrc/create_responses_service.rb
  app/services/populators/transaction_type_populator.rb
  app/workers/hmrc/result_worker.rb
  app/workers/hmrc/submission_worker.rb
  db/seeds/admin_users.rb
  db/seeds/permissions.rb
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/transaction_types.rb
  spec/forms/applicants/basic_details_form_spec.rb
  spec/forms/applicants/email_form_spec.rb
  spec/forms/applicants/employed_form_spec.rb
  spec/forms/incidents/told_on_form_spec.rb
  spec/forms/legal_aid_applications/own_home_form_spec.rb
  spec/forms/legal_aid_applications/restrictions_form_spec.rb
  spec/forms/savings_amounts/savings_amounts_form_spec.rb
  spec/requests/providers/bank_transactions_controller_spec.rb
  spec/requests/providers/capital_assessment_results_controller_spec.rb
  spec/requests/providers/capital_income_assessment_results_controller_spec.rb
  spec/services/govuk_emails/monitor_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: UAT

#5857 Rubocop: address some RSpec/ExpectActual exclusions
  .rubocop_todo.yml
  app/helpers/capital_helper.rb
  app/helpers/check_benefits_helper.rb
  app/helpers/layouts_helper.rb
  app/views/providers/check_benefits/_check_benefits_result.html.erb
  app/views/providers/check_benefits/index.html.erb
  app/views/shared/check_answers/_assets.html.erb
Labels: approved

#5710 AP-4314: Update Puppeteer
  .circleci/config.yml
  .github/dependabot.yml
  docker/apply_base.dockerfile
  package.json
  yarn.lock
Labels: Ready to merge

#5875 Ap 4502 update vehicle in admin report
  app/services/reports/mis/application_detail_csv_line.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: approved, Ready to merge, ruby

#5825 AP-4499: Remove redis namespacing
  .simplecov
  app/jobs/test_mail_job.rb
  config/application.rb
  config/initializers/sidekiq.rb
  helm_deploy/apply-for-legal-aid/Chart.lock
  helm_deploy/apply-for-legal-aid/Chart.yaml
  helm_deploy/apply-for-legal-aid/charts/redis-16.13.2.tgz
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
  helm_deploy/apply-for-legal-aid/templates/deployment_drainer.yaml
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: approved

#5872 ap-4509: add linked_applications table, model and associations
  app/models/legal_aid_application.rb
  app/models/linked_application.rb
  config/locales/en/activerecord.yml
  db/anonymise/rules.rb
  db/migrate/20231009145448_create_linked_applications.rb
  db/schema.rb
  spec/factories/linked_applications.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/linked_application_spec.rb
Labels: approved

#5892 AP-4556: Remove namespaced sidekiq drainer worker
  Gemfile
  Gemfile.lock
  config/initializers/sidekiq.rb
  helm_deploy/apply-for-legal-aid/templates/deployment_drainer.yaml
Labels: On Hold

#5864 AP-3809: Means assessment capital check your answers page
  app/helpers/capital_helper.rb
  app/helpers/policy_disregards_helper.rb
  app/models/concerns/non_passported_state_machine.rb
  app/models/savings_amount.rb
  app/services/flow/flows/provider_capital.rb
  app/views/providers/check_capital_answers/show.html.erb
  app/views/providers/check_passported_answers/show.html.erb
  app/views/providers/means_reports/_with_bank_statement_uploads.html.erb
  app/views/providers/means_reports/_with_cfe_result_details.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_property.html.erb
  app/views/shared/check_answers/_restrictions.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  app/views/shared/review_application/_income_payments_and_assets.html.erb
  app/views/shared/review_application/_income_payments_and_assets_for_bank_statement_upload.html.erb
  config/locales/cy/shared.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/bank_statement_upload/check_your_means_answers.feature
  features/providers/check_your_answers.feature
  features/providers/means_report.feature
  features/providers/review_and_print.feature
  features/step_definitions/means_report_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/savings_amounts.rb
  spec/requests/providers/check_capital_answers_controller_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
Labels: approved

#5842 AP-4326 partner employment info
  app/controllers/providers/means/employment_incomes_controller.rb
  app/controllers/providers/means/unexpected_employment_incomes_controller.rb
  app/controllers/providers/partners/employment_incomes_controller.rb
  app/controllers/providers/partners/unexpected_employment_incomes_controller.rb
  app/forms/applicants/employment_income_form.rb
  app/forms/applicants/unexpected_employment_income_form.rb
  app/forms/base_employment_income_form.rb
  app/forms/legal_aid_applications/employment_income_form.rb
  app/forms/partners/employment_income_form.rb
  app/forms/partners/unexpected_employment_income_form.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_partner.rb
  app/services/reports/mis/application_detail_csv_line.rb
  app/views/providers/means/check_income_answers/_partner_income_assessment.html.erb
  app/views/providers/means_reports/_with_bank_statement_uploads.html.erb
  app/views/providers/means_reports/_with_cfe_result_details.html.erb
  app/views/shared/_employment_income_table.html.erb
  app/views/shared/check_answers/_employed_income.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/shared.yml
  db/migrate/20231005160623_add_extra_employment_information_to_applicant.rb
  db/migrate/20231005161440_add_extra_employment_information_to_partner.rb
  db/schema.rb
  features/providers/bank_statement_upload/happy_path_journey.feature
  features/providers/bank_statement_upload/state_benefit_loop.feature
  features/providers/check_single_employment.feature
  features/providers/employed_journey.feature
  features/step_definitions/bank_statement_upload_steps.rb
  features/step_definitions/check_your_answers_steps.rb
  features/step_definitions/means_report_steps.rb
  features/step_definitions/review_and_print_steps.rb
  lib/tasks/migrate_extra_employment_information.rake
  spec/factories/applicants.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/partners.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/capital_assessment_results_controller_spec.rb
  spec/requests/providers/capital_income_assessment_results_controller_spec.rb
  spec/requests/providers/means/employment_incomes_controller_spec.rb
  spec/requests/providers/means/full_employment_details_controller_spec.rb
  spec/requests/providers/means/unexpected_employment_incomes_controller_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/requests/providers/partners/employment_incomes_controller_spec.rb
  spec/requests/providers/partners/unexpected_employment_incomes_controller_spec.rb
  spec/requests/providers/submitted_applications_controller_spec.rb
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/services/ccms/manual_review_determiner_spec.rb
  spec/services/manual_review_detailer_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
  spec/services/required_document_category_analyser_spec.rb
  spec/services/results_panel_selector_spec.rb
Labels: ready for review

#5894 AP-4427: Add alert and area-live=assertive for screen readers and reformat sign in page
  app/controllers/saml_idp_controller.rb
  app/views/saml_idp/idp/new.html.erb
Labels: UAT, approved, ruby

#5871 AP-4359: Add cfe_civil partner submission
  app/services/cfe_civil/component_list.rb
  app/services/cfe_civil/components/base_data_block.rb
  app/services/cfe_civil/components/capitals.rb
  app/services/cfe_civil/components/cash_transactions.rb
  app/services/cfe_civil/components/employments.rb
  app/services/cfe_civil/components/irregular_incomes.rb
  app/services/cfe_civil/components/partner.rb
  app/services/cfe_civil/components/regular_transactions.rb
  app/services/cfe_civil/components/vehicles.rb
  spec/factories/employments.rb
  spec/factories/regular_transactions.rb
  spec/services/cfe_civil/component_list_spec.rb
  spec/services/cfe_civil/components/capitals_spec.rb
  spec/services/cfe_civil/components/cash_transactions_spec.rb
  spec/services/cfe_civil/components/employments_spec.rb
  spec/services/cfe_civil/components/irregular_incomes_spec.rb
  spec/services/cfe_civil/components/partner_spec.rb
  spec/services/cfe_civil/components/regular_transactions_spec.rb
  spec/services/cfe_civil/components/vehicles_spec.rb
Labels: ready for review

#5914 Fix: Partner definition update
  config/locales/en/providers.yml
Labels: ready for review

#5906 AP-4328 Add contrary interest question to check your answers
  app/controllers/providers/partners/contrary_interests_controller.rb
  app/models/partner.rb
  app/services/flow/flows/provider_partner.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/shared/check_answers/_partner_details.html.erb
  config/locales/en/shared.yml
  spec/requests/providers/partners/contrary_interests_controller_spec.rb
Labels: UAT, approved

#5915 AP-4586: Update PrometheusExporter
  Gemfile
  Gemfile.lock
  helm_deploy/apply-for-legal-aid/templates/deployment_metrics.yaml
Labels: ready for review

#5920 AP-4170: Correct validation for dwp override
  app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_controller_spec.rb
Labels: approved
