Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2023-01, with the labels that each got.

#4712 Ap 3704 update scope limitation pages
  app/forms/proceedings/scope_limitations_form.rb
  app/views/providers/proceeding_loop/emergency_scope_limitations/show.html.erb
  app/views/providers/proceeding_loop/substantive_scope_limitations/show.html.erb
  app/views/shared/scope_limitations/_hearing_date.html.erb
  app/views/shared/scope_limitations/_limitation_note.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  spec/cassettes/EmergencyScopeLimitationsController/POST_/providers/applications/_legal_aid_application_id/emergency_scope_limitations/_proceeding_id/when_the_provider_is_authenticated/when_the_form_is_invalid/when_a_mandatory_hearing_date_is_missing/shows_an_error.yml
  spec/cassettes/EmergencyScopeLimitationsController/POST_/providers/applications/_legal_aid_application_id/emergency_scope_limitations/_proceeding_id/when_the_provider_is_authenticated/when_the_form_is_invalid/when_no_scope_limitation_is_selected/shows_an_error.yml
  spec/cassettes/SubstantiveScopeLimitationsController/POST_/providers/applications/_legal_aid_application_id/substantive_scope_limitations/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_the_form_is_invalid/when_a_mandatory_limitation_note_is_missing/shows_an_error.yml
  spec/cassettes/SubstantiveScopeLimitationsController/POST_/providers/applications/_legal_aid_application_id/substantive_scope_limitations/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_the_form_is_invalid/when_no_scope_limitation_is_selected/shows_an_error_if_no_scope_limitation_is_selected.yml
  spec/factories/proceedings.rb
  spec/requests/providers/proceeding_loop/emergency_scope_limitations_controller_spec.rb
  spec/requests/providers/proceeding_loop/substantive_scope_limitations_controller_spec.rb
Labels: UAT

#4754 Fix: Update the github action versions
  .github/workflows/anonymise_check.yml
  .github/workflows/base-docker-image.yml
  .github/workflows/ci-docker-image.yml
  .github/workflows/codeql-analysis.yml
Labels: approved

#4759 Fix: Flaky features
  spec/factories/other_assets_declarations.rb
  spec/factories/providers.rb
Labels: approved

#4734 AP-3722: Update the support evidence bullet point list
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
Labels: UAT, approved

#4752 AP-3721: Remove No response textarea from Nature of Urgency question
  app/controllers/providers/application_merits_task/nature_of_urgencies_controller.rb
  app/forms/providers/application_merits_task/nature_of_urgency_form.rb
  app/views/providers/application_merits_task/nature_of_urgencies/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/forms/providers/application_merits_task/nature_of_urgency_form_spec.rb
  spec/requests/providers/application_merits_task/nature_of_urgencies_controller_spec.rb
Labels: approved

#4738 AP-3723: Update mental capacity question wording
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/accessibility/provider.feature
  features/providers/check_ccms_autogrant.feature
  features/providers/check_multiple_employment.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/civil_application_journey.feature
  features/providers/merits_task_list.feature
  features/providers/mini-loop/merits_questions.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  spec/requests/providers/application_merits_task/opponents_mental_capacities_controller_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
Labels: UAT, approved

#4740 AP-3720: Matter opposed question
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/merits_task_list.feature
  spec/requests/providers/application_merits_task/matter_opposed_reasons_controller_spec.rb
Labels: UAT, approved

#4753 AP-3724: Update OpponentApplication question
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
Labels: approved

#4773 Fix: Revert the UAT framework URL for UAT
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: approved

#4772 Ap 3682 reorganise np features
  features/cassettes/non_passported_journey_with_bank_transactions/Selects_and_categorises_bank_transactions_into_transaction_types.yml
  features/providers/non_passported_journey.feature
  features/providers/non_passported_journey/used_delegated_functions.feature
  features/providers/non_passported_journey/waiting_for_applicant.feature
  features/providers/non_passported_journey/with_bank_transactions.feature
  features/providers/non_passported_journey/with_capital.feature
  features/providers/non_passported_journey/with_dependants.feature
Labels: approved

#4778 Remove Stephen from provider seeds and saml
  config/initializers/mock_saml.rb
  db/seeds/test_provider_populator.rb
Labels: ready for review

#4700 Generate PDF reports from HTML using `grover` gem
  .circleci/config.yml
  .gitignore
  .rubocop_todo.yml
  .ruby-version
  Brewfile
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/providers/means_reports_controller.rb
  app/controllers/providers/merits_reports_controller.rb
  app/helpers/pdf_helper.rb
  app/services/reports/base_report_creator.rb
  app/views/layouts/_govuk_base64_fonts.html.erb
  app/views/layouts/pdf.html.erb
  app/views/providers/means_reports/_with_cfe_result_details.html.erb
  config/initializers/grover.rb
  config/initializers/wicked_pdf.rb
  docker/apply_base.dockerfile
  docker/apply_ci.dockerfile
  package.json
  puppeteer.config.cjs
  spec/requests/providers/means_reports_controller_spec.rb
  spec/requests/providers/means_reports_spec.rb
  spec/requests/providers/merits_reports_controller_spec.rb
  spec/requests/providers/merits_reports_spec.rb
  yarn.lock
Labels: Ready to merge

#4718 AP-3623: Cost of living updates
  app/forms/providers/means/regular_income_form.rb
  app/views/providers/means/other_assets/show.html.erb
  app/views/providers/means/regular_incomes/_cost_of_living_and_disregarded_benefits.html.erb
  app/views/providers/means/regular_incomes/_disregarded_benefits.html.erb
  app/views/providers/means/regular_incomes/show.html.erb
  app/views/providers/means/restrictions/show.html.erb
  app/views/providers/transactions/_disregarded_list.html.erb
  app/views/providers/transactions/show.html.erb
  app/views/shared/means/_cost_of_living_details.html.erb
  app/views/shared/means/_cost_of_living_section.html.erb
  app/views/shared/means/_disregarded_benefits_section.erb
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/locales/en/transaction_types.yml
  features/accessibility/provider.feature
  features/providers/back_button.feature
  features/providers/bank_statement_upload/happy_path_journey.feature
  features/providers/check_ccms_autogrant.feature
  features/providers/check_multiple_employment.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/check_your_answers.feature
  features/providers/civil_application_journey.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/means_report.feature
  features/providers/non_passported_journey/with_capital.feature
Labels: UAT, do not merge

#4797 AP-3200: Update delete button labelling
  app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
  config/locales/en/providers.yml
  features/providers/deleting_applications.feature
  features/step_definitions/generic_steps.rb
  spec/requests/providers/legal_aid_applications_spec.rb
Labels: Ready to merge

#4777 [AP-3199] Add label to select component on evidence upload page
  app/views/providers/uploaded_evidence_collections/_uploaded_files.html.erb
  config/locales/en/providers.yml
Labels: approved

#4774 [AP-3646] Use govuk pagination component
  .overcommit.yml
  app/views/admin/feedback/_feedbacks.erb
  app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/admin/submitted_applications_reports/_submitted_applications.html.erb
  app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/shared/partials/_pagination.html.erb
  app/webpack/stylesheets/pagination.scss
  spec/requests/admin/feedback_spec.rb
  spec/requests/admin/legal_aid_applications_controller_spec.rb
  spec/requests/admin/submitted_applications_reports_spec.rb
  spec/requests/providers/legal_aid_applications_spec.rb
Labels: approved

#4812 AP-3711: Update Means and Merits report
  app/views/providers/means_reports/show.html.erb
  app/views/providers/merits_reports/show.html.erb
  app/views/shared/check_answers/_client_details.html.erb
  config/locales/cy/shared.yml
  config/locales/en/shared.yml
Labels: ready for review

#4650 Add a base_state_machine spec
  app/models/concerns/base_state_machine.rb
  spec/concerns/base_state_machine_spec.rb
  spec/factories/base_state_machines.rb
  spec/factories/legal_aid_applications.rb
Labels: ready for review

#4819 Address rubocop todos
  .rubocop.yml
  .rubocop_todo.yml
  lib/tasks/db.rake
  spec/factories/application_merits_task/involved_children.rb
  spec/factories/attempts_to_settles.rb
  spec/factories/ccms_submission_documents.rb
  spec/factories/ccms_submission_histories.rb
  spec/factories/ccms_submissions.rb
  spec/factories/cfe_results.rb
  spec/factories/cfe_results/v3/results.rb
  spec/factories/cfe_results/v4/results.rb
  spec/factories/cfe_submissions.rb
  spec/factories/hmrc/responses.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/legal_framework_merits_task_list.rb
  spec/factories/legal_framework_serializable_merits_task.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/factories/legal_framework_submissions.rb
  spec/factories/proceeding_merits_task/proceeding_linked_children.rb
  spec/factories/submission_documents.rb
  spec/factories/submissions.rb
  spec/requests/providers/capital_assessment_results_spec.rb
  spec/requests/providers/capital_income_assessment_results_spec.rb
  spec/requests/saml_idp_spec.rb
  spec/requests/status_spec.rb
  spec/requests/v1/bank_statements_spec.rb
  spec/requests/v1/statement_of_cases_spec.rb
  spec/requests/v1/uploaded_evidence_collections_spec.rb
  spec/services/true_layer/bank_data_import_service_spec.rb
  spec/services/true_layer/importers/import_account_balance_service_spec.rb
  spec/services/true_layer/importers/import_account_holders_service_spec.rb
  spec/services/true_layer/importers/import_accounts_service_spec.rb
  spec/services/true_layer/importers/import_provider_service_spec.rb
  spec/services/true_layer/importers/import_transactions_service_spec.rb
Labels: ready for review

#4813 Ap 3710 means report non means tested
  app/views/providers/means_reports/show.html.erb
  features/providers/means_report.feature
Labels: UAT

#4818 ap-3746 update proceeding types hint text
  app/views/providers/proceedings_types/index.html.erb
  config/locales/en/providers.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/when_the_provider_doesn_t_have_full_section_8_permissions/prompts_users_that_they_must_enter_a_domestic_abuse_proceeding.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/when_the_provider_has_full_section_8_permissions/doesn_t_prompt_users_that_they_must_enter_a_domestic_abuse_proceeding.yml
  spec/requests/providers/proceedings_types_spec.rb
Labels: UAT

#4831 Bump test executor postgres version 10.18 to 11.16
  .circleci/config.yml
Labels: approved

#4786 AP-3331 save vehicles remaining payments answer
  app/forms/vehicle_form/remaining_payment_form.rb
  app/views/providers/vehicles/remaining_payments/show.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  features/providers/check_your_answers.feature
  features/step_definitions/check_your_answers_steps.rb
  spec/requests/providers/vehicles/remaining_payments_spec.rb
Labels: UAT, approved

#4873 Fix flaky test
  app/models/concerns/translatable_model_attribute.rb
  app/views/feedback/new.html.erb
  spec/models/concerns/translatable_model_attribute_spec.rb
Labels: ready for review

#4853 AP-3235: Update HMRC response alerting
  app/models/hmrc/response.rb
  spec/workers/hmrc/result_worker_spec.rb
  spec/workers/hmrc/submission_worker_spec.rb
Labels: ready for review, approved

#4876 Remove redundant styles
  app/webpack/stylesheets/application.scss
  app/webpack/stylesheets/forms/revealing_checkboxes.scss
  app/webpack/stylesheets/govuk-currency-input.scss
  app/webpack/stylesheets/govuk-percent-input.scss
  app/webpack/stylesheets/govuk-prefix-input.scss
  app/webpack/stylesheets/tickbox-divider.scss
Labels: ready for review

#4821 Means test review declaration content changes
  app/controllers/providers/confirm_client_declarations_controller.rb
  app/forms/legal_aid_applications/confirm_client_declaration_form.rb
  app/views/providers/confirm_client_declarations/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  features/accessibility/provider.feature
  features/providers/check_ccms_autogrant.feature
  features/providers/check_multiple_employment.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/merits_task_list.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/passported_journey.feature
  spec/forms/legal_aid_applications/confirm_client_declaration_form_spec.rb
  spec/requests/providers/confirm_client_declarations_controller_spec.rb
Labels: Ready to merge

#4874 Remove `TranslatableModelAttribute` concern
  app/mailers/feedback_mailer.rb
  app/models/concerns/translatable_model_attribute.rb
  app/models/feedback.rb
  app/models/legal_aid_application.rb
  app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/feedback/new.html.erb
  app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
  config/locales/cy/enums.yml
  config/locales/en/enums.yml
  lib/tasks/helpers/cy_helper.rb
  spec/models/concerns/translatable_model_attribute_spec.rb
  spec/models/legal_aid_application_spec.rb
Labels: ready for review, Discussion

#4872 ap-3224: Do not display CCMS reference if this doesn't yet exist
  app/views/shared/review_application/_questions_and_answers.html.erb
Labels: ready for review

#4894 Use Snyk to scan docker image daily
  .github/workflows/docker-image-scan.yml
Labels: ready for review

#4892 Add hint text when a new substantive cost limit is requested
  config/locales/en/helpers.yml
Labels: Ready to merge

#4905 Ignore Puppeteer dependabot updates
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: approved

#4893 Update Ruby to v3.2.0
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  app/forms/proceedings/client_involvement_type_form.rb
  docker/apply_base.dockerfile
  docker/apply_ci.dockerfile
Labels: ready for review

#4909 Update DWP results page
  app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
  app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
  config/locales/en/providers.yml
  features/accessibility/provider.feature
  features/providers/applicant_details.feature
  features/providers/change_email.feature
  features/providers/non_means_tested_journey/under_18_application_with_means_test_review_phase_one_disabled.feature
  features/providers/non_passported_journey/used_delegated_functions.feature
  features/providers/non_passported_journey/waiting_for_applicant.feature
  features/providers/passported_journey.feature
  features/providers/pathways_from_check_your_answers.feature
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
Labels: ready for review

#4914 Use reusable snyk workflow to scan docker images
  .github/workflows/docker-image-scan.yml
Labels: ready for review

#4924 Rubocop rspec todos
  .rubocop_todo.yml
  spec/forms/applicants/basic_details_form_spec.rb
  spec/forms/applicants/email_form_spec.rb
  spec/forms/legal_aid_applications/shared_ownership_form_spec.rb
  spec/forms/outstanding_mortgage_form_spec.rb
  spec/helpers/check_answer_url_helper_spec.rb
  spec/lib/omni_auth/hmrc_spec.rb
  spec/models/aggregated_cash_income_spec.rb
  spec/models/aggregated_cash_outgoings_spec.rb
  spec/models/dashboard/single_object/applicant_email_spec.rb
  spec/models/dashboard/single_object/feedback_spec.rb
  spec/models/dashboard/single_object/provider_data_spec.rb
  spec/requests/admin_users/omniauth_callbacks_spec.rb
  spec/requests/applicants/omniauth_callbacks_spec.rb
  spec/requests/backable_spec.rb
  spec/requests/citizens/bank_spec.rb
  spec/requests/citizens/check_answers_spec.rb
  spec/requests/errors_spec.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/means/own_home_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/flow/base_flow_service_spec.rb
  spec/services/page_history_service_spec.rb
Labels: ready for review

#4923 AP-3442: Monitor banking path usage
  app/models/application_digest.rb
  app/models/legal_aid_application.rb
  app/services/digest_exporter.rb
  app/services/reports/mis/application_detail_csv_line.rb
  db/migrate/20230131084513_add_banking_paths_to_application_digest.rb
  db/schema.rb
  spec/services/digest_exporter_spec.rb
Labels: ready for review
