Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2023-08, with the labels that each got.

#5563 Rubocop: reduce RSpec/ContextWording infractions
  .rubocop_todo.yml
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
  spec/requests/providers/check_provider_answers_spec.rb
  spec/requests/providers/client_completed_means_spec.rb
  spec/requests/providers/concerns/draftable_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
  spec/requests/providers/confirm_offices_spec.rb
  spec/requests/providers/email_addresses_spec.rb
  spec/requests/providers/end_of_applications_spec.rb
  spec/requests/providers/gateway_evidence_spec.rb
  spec/requests/providers/has_evidence_of_benefits_spec.rb
  spec/requests/providers/has_other_proceedings_controller_spec.rb
  spec/requests/providers/income_summary_spec.rb
  spec/requests/providers/invalid_logins_spec.rb
  spec/requests/providers/legal_aid_applications_spec.rb
  spec/requests/providers/means/dependants_controller_spec.rb
  spec/requests/providers/means/has_dependants_controller_spec.rb
  spec/requests/providers/means/remove_dependant_controller_spec.rb
  spec/requests/providers/means/restrictions_spec.rb
  spec/requests/providers/means/savings_and_investments_spec.rb
  spec/requests/providers/means/shared_ownerships_spec.rb
  spec/requests/providers/means/vehicles_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/requests/providers/received_benefit_confirmations_spec.rb
  spec/requests/providers/select_offices_spec.rb
  spec/requests/providers/transactions_spec.rb
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/requests/providers/vehicles/ages_spec.rb
  spec/requests/providers/vehicles/estimated_values_spec.rb
  spec/requests/providers/vehicles/regular_uses_spec.rb
Labels: approved

#5538 AP-4132 combine property pages
  app/controllers/providers/means/outstanding_mortgages_controller.rb
  app/controllers/providers/means/own_homes_controller.rb
  app/controllers/providers/means/percentage_homes_controller.rb
  app/controllers/providers/means/property_details_controller.rb
  app/controllers/providers/means/property_values_controller.rb
  app/controllers/providers/means/shared_ownerships_controller.rb
  app/forms/legal_aid_applications/outstanding_mortgage_form.rb
  app/forms/legal_aid_applications/own_home_form.rb
  app/forms/legal_aid_applications/percentage_home_form.rb
  app/forms/legal_aid_applications/property_details_form.rb
  app/forms/legal_aid_applications/property_value_form.rb
  app/forms/legal_aid_applications/shared_ownership_form.rb
  app/helpers/check_answer_url_helper.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_property.rb
  app/views/providers/means/outstanding_mortgages/show.html.erb
  app/views/providers/means/percentage_homes/show.html.erb
  app/views/providers/means/property_details/show.html.erb
  app/views/providers/means/property_values/show.html.erb
  app/views/providers/means/shared_ownerships/show.html.erb
  app/views/shared/check_answers/_property.html.erb
  config/locales/cy/activemodel.yml
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  features/providers/check_your_answers.feature
  features/providers/means_report.feature
  features/providers/non_passported_journey/with_capital.feature
  features/providers/passported_journey.feature
  features/step_definitions/means_report_steps.rb
  lib/tasks/migrate_property_pages.rake
  spec/factories/legal_aid_applications.rb
  spec/forms/legal_aid_applications/own_home_form_spec.rb
  spec/forms/legal_aid_applications/percentage_home_form_spec.rb
  spec/forms/legal_aid_applications/shared_ownership_form_spec.rb
  spec/forms/outstanding_mortgage_form_spec.rb
  spec/helpers/check_answer_url_helper_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
  spec/requests/providers/means/outstanding_mortgages_controller_spec.rb
  spec/requests/providers/means/own_home_spec.rb
  spec/requests/providers/means/percentage_home_spec.rb
  spec/requests/providers/means/property_details_controller_spec.rb
  spec/requests/providers/means/property_value_spec.rb
  spec/requests/providers/means/savings_and_investments_spec.rb
  spec/requests/providers/means/shared_ownerships_spec.rb
  spec/requests/providers/offline_accounts_spec.rb
Labels: approved, Question

#5565 Rubocop: update and remove RSpec/FilePath exclusions
  .rubocop_todo.yml
  spec/forms/legal_aid_applications/has_evidence_of_benefit_form_spec.rb
  spec/forms/legal_aid_applications/outstanding_mortgage_form_spec.rb
  spec/requests/admin/feedback_controller_spec.rb
  spec/requests/admin/firms_controller_spec.rb
  spec/requests/admin/providers_controller_spec.rb
  spec/requests/admin/reports_controller_spec.rb
  spec/requests/admin/roles/permissions_controller_spec.rb
  spec/requests/admin/roles_controller_spec.rb
  spec/requests/admin/settings_controller_spec.rb
  spec/requests/admin/submitted_applications_reports_controller_spec.rb
  spec/requests/citizens/banks_controller_spec.rb
  spec/requests/errors_controller_spec.rb
  spec/requests/problem_controller_spec.rb
  spec/requests/providers/address_lookups_controller_spec.rb
  spec/requests/providers/address_selections_controller_spec.rb
  spec/requests/providers/applicant_bank_accounts_controller_spec.rb
  spec/requests/providers/applicant_details_controller_spec.rb
  spec/requests/providers/applicant_employed_controller_spec.rb
  spec/requests/providers/applicants_controller_spec.rb
  spec/requests/providers/bank_transactions_controller_spec.rb
  spec/requests/providers/capital_assessment_results_controller_spec.rb
  spec/requests/providers/capital_income_assessment_results_controller_spec.rb
  spec/requests/providers/capital_introductions_controller_spec.rb
  spec/requests/providers/check_benefits_controller_spec.rb
  spec/requests/providers/check_client_details_controller_spec.rb
  spec/requests/providers/check_provider_answers_controller_spec.rb
  spec/requests/providers/client_completed_means_controller_spec.rb
  spec/requests/providers/concerns/providers/draftable_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_controller_spec.rb
  spec/requests/providers/declarations_controller_spec.rb
  spec/requests/providers/delegated_confirmation_controller_spec.rb
  spec/requests/providers/end_of_applications_controller_spec.rb
  spec/requests/providers/gateway_evidences_controller_spec.rb
  spec/requests/providers/has_evidence_of_benefits_controller_spec.rb
  spec/requests/providers/income_summary_controller_spec.rb
  spec/requests/providers/limitations_controller_spec.rb
  spec/requests/providers/means/property_values_controller_spec.rb
  spec/requests/providers/means/remove_dependants_controller_spec.rb
  spec/requests/providers/means/vehicles_controller_spec.rb
  spec/requests/providers/outgoings_summary_controller_spec.rb
  spec/requests/providers/proceedings_types_controller_spec.rb
  spec/requests/providers/providers_controller_spec.rb
  spec/requests/providers/received_benefit_confirmations_controller_spec.rb
  spec/requests/providers/submitted_applications_controller_spec.rb
  spec/requests/providers/substantive_applications_controller_spec.rb
  spec/requests/providers/transactions_controller_spec.rb
  spec/requests/providers/use_ccms_controller_spec.rb
  spec/requests/providers/vehicles/ages_controller_spec.rb
  spec/requests/providers/vehicles/estimated_values_controller_spec.rb
  spec/requests/providers/vehicles/regular_uses_controller_spec.rb
  spec/requests/providers/vehicles/remaining_payments_controller_spec.rb
  spec/requests/saml_idp_controller_spec.rb
  spec/requests/status_controller_spec.rb
  spec/services/cleanup_capital_attributes_spec.rb
  spec/services/mock_benefit_check_service_spec.rb
Labels: ready for review

#5574 Tech-debt: add additional IP ranges for admin access via global protect
  config/ipaddrs.crypt.yml
Labels: ready for review

#5553 ap-4301: add opponent organisations
  app/controllers/providers/application_merits_task/opponent_organisations_controller.rb
  app/controllers/providers/application_merits_task/opponent_types_controller.rb
  app/forms/opponents/organisation_form.rb
  app/helpers/opponent_url_helper.rb
  app/helpers/task_list_helper.rb
  app/models/application_merits_task/individual.rb
  app/models/application_merits_task/opponent.rb
  app/models/application_merits_task/organisation.rb
  app/services/flow/flows/provider_merits.rb
  app/services/legal_framework/organisation_types/all.rb
  app/views/providers/application_merits_task/has_other_opponents/show.html.erb
  app/views/providers/application_merits_task/opponent_organisations/_form.html.erb
  app/views/providers/application_merits_task/opponent_organisations/new.html.erb
  app/views/providers/application_merits_task/opponent_organisations/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  features/cassettes/Merits_task_list/With_an_organisation_opponent.yml
  features/providers/merits_task_list.feature
  features/step_definitions/civil_journey_steps.rb
  spec/cassettes/LegalFramework_OrganisationTypes_All/_call/makes_one_external_call.yml
  spec/cassettes/LegalFramework_OrganisationTypes_All/_call/returns_the_expected_number_of_results.yml
  spec/cassettes/Opponents_OrganisationForm/_save/with_existing_opposable_object/does_not_add_an_organisation.yml
  spec/cassettes/Opponents_OrganisationForm/_save/with_existing_opposable_object/updates_the_existing_organisation.yml
  spec/cassettes/Opponents_OrganisationForm/_save/with_no_existing_opposable_object/creates_a_new_organisation.yml
  spec/cassettes/Opponents_OrganisationForm/_save/with_no_existing_opposable_object/creates_and_associates_a_new_opponent_with_the_organisation.yml
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentOrganisationsController/new_GET_/providers/applications/_legal_aid_application_id/opponent_organisations/new/when_authenticated/displays_the_form_to_add_new_opponent_organisations.yml
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentOrganisationsController/new_GET_/providers/applications/_legal_aid_application_id/opponent_organisations/new/when_authenticated/returns_success.yml
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentOrganisationsController/show_GET_/providers/applications/_legal_aid_application_id/opponent_organisations/_opponent_id/when_authenticated/displays_opponent_s_details.yml
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentOrganisationsController/show_GET_/providers/applications/_legal_aid_application_id/opponent_organisations/_opponent_id/when_authenticated/returns_success.yml
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentOrganisationsController/update_PATCH_/providers/applications/_legal_aid_application_id/opponent_organisations/_opponent_id/amends_the_opponent_opposable_individual_with_the_values_entered.yml
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentOrganisationsController/update_PATCH_/providers/applications/_legal_aid_application_id/opponent_organisations/_opponent_id/amends_the_opponent_opposable_organisation_with_the_values_entered.yml
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentOrganisationsController/update_PATCH_/providers/applications/_legal_aid_application_id/opponent_organisations/_opponent_id/redirects_to_the_has_another_opponent_question.yml
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentOrganisationsController/update_PATCH_/providers/applications/_legal_aid_application_id/opponent_organisations/_opponent_id/sets_the_task_to_complete.yml
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentOrganisationsController/update_PATCH_/providers/applications/_legal_aid_application_id/opponent_organisations/_opponent_id/when_incomplete/contains_error_message.yml
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentOrganisationsController/update_PATCH_/providers/applications/_legal_aid_application_id/opponent_organisations/_opponent_id/when_incomplete/does_not_set_the_task_to_complete.yml
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentOrganisationsController/update_PATCH_/providers/applications/_legal_aid_application_id/opponent_organisations/_opponent_id/when_incomplete/renders_show.yml
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentOrganisationsController/update_PATCH_/providers/applications/_legal_aid_application_id/opponent_organisations/_opponent_id/when_save_as_draft_selected/does_not_set_the_task_to_complete.yml
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentOrganisationsController/update_PATCH_/providers/applications/_legal_aid_application_id/opponent_organisations/_opponent_id/when_save_as_draft_selected/redirects_to_provider_draft_endpoint.yml
  spec/forms/opponents/organisation_form_spec.rb
  spec/helpers/opponent_url_helper_spec.rb
  spec/helpers/task_list_helper_spec.rb
  spec/models/application_merits_task/individual_spec.rb
  spec/models/application_merits_task/organisation_spec.rb
  spec/requests/providers/application_merits_task/has_other_opponents_controller_spec.rb
  spec/requests/providers/application_merits_task/opponent_organisations_controller_spec.rb
  spec/requests/providers/application_merits_task/opponent_types_controller_spec.rb
  spec/services/legal_framework/organisation_types/all_spec.rb
Labels: Ready to merge

#5579 AP-3416: Update UAT Postgres handling
  helm_deploy/apply-for-legal-aid/Chart.lock
  helm_deploy/apply-for-legal-aid/Chart.yaml
  helm_deploy/apply-for-legal-aid/charts/postgresql-10.2.8.tgz
  helm_deploy/apply-for-legal-aid/charts/postgresql-11.9.13.tgz
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: ready for review

#5580 Update: Update DB restoration
  lib/tasks/db.rake
  scripts/db_export.sh
  scripts/restore_anonymised_db.sh
Labels: ready for review

#5583 AP-4105: Tidy up
  app/forms/student_finances/annual_amount_form.rb
  app/models/irregular_income.rb
  app/models/legal_aid_application.rb
  app/services/reports/mis/application_detail_csv_line.rb
  config/locales/cy/activemodel.yml
  config/locales/en/activemodel.yml
  db/anonymise/rules.rb
  db/migrate/20230807135356_drop_irregular_incomes.rb
  db/schema.rb
  lib/tasks/migrate_student_finance.rake
  spec/factories/irregular_incomes.rb
  spec/forms/student_finances/annual_amount_form_spec.rb
  spec/models/irregular_income_spec.rb
Labels: approved

#5589 Rubocop: Address RSpec/ContextWording exclusions in CCMS tests
  .rubocop_todo.yml
  spec/services/ccms/attribute_configuration_spec.rb
  spec/services/ccms/attribute_value_generator_spec.rb
  spec/services/ccms/manual_review_determiner_spec.rb
  spec/services/ccms/parsers/applicant_add_response_parser_spec.rb
  spec/services/ccms/parsers/applicant_search_response_parser_spec.rb
  spec/services/ccms/parsers/case_add_response_parser_spec.rb
  spec/services/ccms/parsers/case_add_status_response_parser_spec.rb
  spec/services/ccms/parsers/document_id_response_parser_spec.rb
  spec/services/ccms/parsers/reference_data_response_parser_spec.rb
  spec/services/ccms/payload_generators/entity_attributes_generator_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_benefits_attrs_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
  spec/services/ccms/submitters/add_applicant_service_spec.rb
  spec/services/ccms/submitters/add_case_service_spec.rb
  spec/services/ccms/submitters/check_applicant_status_service_spec.rb
  spec/services/ccms/submitters/check_case_status_service_spec.rb
  spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
  spec/services/ccms/submitters/obtain_case_reference_service_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
  spec/services/ccms/submitters/upload_documents_service_spec.rb
Labels: ready for review

#5591 [AP-3650] Apply GOVUK Table component to citizen views
  app/views/citizens/accounts/index.html.erb
Labels: approved

#5590 [AP-3650] Apply GOVUK Table component to admin views
  app/views/admin/ccms_queues/index.html.erb
  app/views/admin/feedback/_feedbacks.erb
  app/views/admin/firms/index.html.erb
  app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/admin/providers/index.html.erb
  app/views/admin/reports/index.html.erb
  app/views/admin/submitted_applications_reports/_submitted_applications.html.erb
  config/locales/en/admin.yml
Labels: approved

#5597 Rubocop: reduce RSpec/ContextWording exclusions
  .rubocop_todo.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
Labels: ready for review

#5582 AP-2509: Improve error handling when case_ccms_reference is ERROR
  app/services/ccms/parsers/reference_data_response_parser.rb
  spec/data/ccms/reference_data_response_error.xml
  spec/services/ccms/parsers/reference_data_response_parser_spec.rb
Labels: Ready to merge

#5588 ap-4304: amend opponent_details cya
  app/helpers/opponent_helper.rb
  app/views/providers/application_merits_task/has_other_opponents/show.html.erb
  app/views/shared/check_answers/_opponent_details.html.erb
  spec/helpers/opponent_helper_spec.rb
Labels: approved

#4775 Refactor CaseAddRequestor factory logic
  app/models/ccms/submission.rb
  app/models/concerns/non_means_tested_state_machine.rb
  app/models/concerns/non_passported_state_machine.rb
  app/models/concerns/passported_state_machine.rb
  app/models/legal_aid_application.rb
  app/services/ccms/case_add_requestor_factory.rb
  app/services/ccms/submitters/add_case_service.rb
  spec/models/ccms/submission_spec.rb
  spec/services/ccms/case_add_requestor_factory_spec.rb
  spec/services/ccms/submitters/add_case_service_spec.rb
Labels: approved

#5607 AP-4374: Update proceeding flow
  app/services/flow/flows/provider_start.rb
  features/cassettes/Using_the_back_button_on_proceedings_should_not_lock_a_user_out/When_a_provider_is_adding_proceedings_and_uses_the_back_button_they_should_route_to_the_list_of_proceedings_first.yml
  features/providers/regressions/back_button_on_proceedings.feature
Labels: approved

#5609 Rubocop: reduce RSpec/ContextWording exclusions
  .rubocop_todo.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
Labels: approved

#5617 AP-4350: Ignore unneeded opponent model attributes
  app/models/application_merits_task/opponent.rb
  spec/models/application_merits_task/opponent_spec.rb
Labels: approved

#5608 AP-4373: Add internally routed LFA url
  app/views/providers/proceedings_types/index.html.erb
  config/application.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: approved

#5622 AP-4350: Drop first_name, last_name from opponents
  db/migrate/20230815072458_remove_first_name_last_name_from_opponents.rb
  db/schema.rb
Labels: approved

#5626 Add caption class suffix to match corresponding heading class
  app/views/providers/open_banking_guidances/show.html.erb
  app/views/providers/proceeding_loop/client_involvement_type/show.html.erb
  app/views/providers/proceeding_loop/confirm_delegated_functions_date/show.html.erb
  app/views/providers/proceeding_loop/delegated_functions/show.html.erb
  app/views/providers/proceeding_loop/emergency_defaults/show.html.erb
  app/views/providers/proceeding_loop/emergency_level_of_service/show.html.erb
  app/views/providers/proceeding_loop/emergency_scope_limitations/show.html.erb
  app/views/providers/proceeding_loop/final_hearings/show.html.erb
  app/views/providers/proceeding_loop/substantive_defaults/show.html.erb
  app/views/providers/proceeding_loop/substantive_level_of_service/show.html.erb
  app/views/providers/proceeding_loop/substantive_scope_limitations/show.html.erb
  app/views/shared/state_benefits/_add_other_state_benefits.html.erb
Labels: approved

#5623 AP-3654: Use button helpers v2
  app/assets/stylesheets/providers/legal_aid_applications.scss
  app/controllers/providers/application_merits_task/statement_of_cases_controller.rb
  app/helpers/accessible_navigation_helper.rb
  app/javascript/src/admin-delete.js
  app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/admin/legal_aid_applications/index.html.erb
  app/views/admin/roles/_form.html.erb
  app/views/admin_users/sessions/new.html.erb
  app/views/providers/application_merits_task/statement_of_cases/_uploaded_files.html.erb
  app/views/providers/application_merits_task/statement_of_cases/show.html.erb
  app/views/providers/bank_transactions/_list_selected.html.erb
  app/views/providers/delete/show.html.erb
  app/views/providers/gateway_evidences/_uploaded_files.html.erb
  app/views/providers/uploaded_evidence_collections/_uploaded_files.html.erb
  app/views/shared/_signed_out_header_link.html.erb
  app/views/shared/_uploaded_files.html.erb
  app/views/shared/forms/proceedings_types/_legacy_proceeding_type_form.html.erb
  spec/helpers/accessible_navigation_helper_spec.rb
Labels: approved

#5616 AP-4140: Merge vehicle questions into single page
  app/controllers/providers/means/vehicle_details_controller.rb
  app/controllers/providers/vehicles/ages_controller.rb
  app/controllers/providers/vehicles/estimated_values_controller.rb
  app/controllers/providers/vehicles/regular_uses_controller.rb
  app/controllers/providers/vehicles/remaining_payments_controller.rb
  app/forms/vehicle_form/age_form.rb
  app/forms/vehicle_form/estimated_value_form.rb
  app/forms/vehicle_form/remaining_payment_form.rb
  app/forms/vehicle_form/used_regularly_form.rb
  app/forms/vehicles/details_form.rb
  app/services/flow/flows/provider_vehicle.rb
  app/views/providers/means/vehicle_details/show.html.erb
  app/views/providers/vehicles/ages/show.html.erb
  app/views/providers/vehicles/estimated_values/show.html.erb
  app/views/providers/vehicles/regular_uses/show.html.erb
  app/views/providers/vehicles/remaining_payments/show.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/check_your_answers.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey/with_capital.feature
  features/providers/vehicle.feature
  features/support/steps_helper.rb
  lib/tasks/migrate_vehicle_provider_steps.rake
  spec/forms/vehicles/details_form_spec.rb
  spec/requests/providers/means/vehicle_details_controller_spec.rb
  spec/requests/providers/means/vehicles_controller_spec.rb
  spec/requests/providers/vehicles/ages_controller_spec.rb
  spec/requests/providers/vehicles/estimated_values_controller_spec.rb
  spec/requests/providers/vehicles/regular_uses_controller_spec.rb
  spec/requests/providers/vehicles/remaining_payments_controller_spec.rb
Labels: ready for review

#5641 Friday: Rubocop todo
  .rubocop_todo.yml
  spec/models/aggregated_cash_income_spec.rb
  spec/models/aggregated_cash_outgoings_spec.rb
  spec/models/cash_transaction_spec.rb
  spec/requests/admin_users/sessions_controller_spec.rb
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/services/benefit_check_service_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/submitters/check_case_status_service_spec.rb
  spec/services/reports/reports_types_creator_spec.rb
Labels: approved

#5645 AP-4285: Set cash transaction ownership
  app/controllers/providers/means/cash_incomes_controller.rb
  app/controllers/providers/means/cash_outgoings_controller.rb
  app/models/base_aggregated_cash_transaction.rb
  app/models/cash_transaction.rb
  db/migrate/20230821070336_add_owner_to_cash_transaction.rb
  db/schema.rb
  lib/tasks/migrate_cash_transaction_ownership.rake
  spec/factories/legal_aid_applications.rb
  spec/forms/providers/means/regular_income_form_spec.rb
  spec/forms/providers/means/regular_outgoings_form_spec.rb
  spec/models/aggregated_cash_income_spec.rb
  spec/models/aggregated_cash_outgoings_spec.rb
  spec/models/cash_transaction_spec.rb
  spec/models/legal_aid_application_transaction_type_spec.rb
  spec/requests/providers/means/cash_incomes_controller_spec.rb
  spec/requests/providers/means/cash_outgoings_controller_spec.rb
  spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
  spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
  spec/services/cfe_civil/components/cash_transactions_spec.rb
Labels: approved

#5646 Fix: Remove FFI from Circle CI lint executor
  .circleci/config.yml
Labels: ready for review

#5657 Fix: Update flaky RemoveInvolvedChildController test
  spec/requests/providers/application_merits_task/remove_involved_child_spec.rb
Labels: ready for review

#5648 AP-4285: Update cash transaction handling
  app/controllers/providers/means/cash_incomes_controller.rb
  app/controllers/providers/means/cash_outgoings_controller.rb
  app/models/base_aggregated_cash_transaction.rb
  db/migrate/20230822111710_change_cash_transaction_index.rb
  db/schema.rb
  spec/models/aggregated_cash_income_spec.rb
  spec/models/aggregated_cash_outgoings_spec.rb
Labels: UAT, approved

#5592 [AP-4375] Apply GOVUK Table component to provider views
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/narrow-table-display.scss
  app/assets/stylesheets/table-category-column.scss
  app/assets/stylesheets/tables.scss
  app/helpers/gov_uk_form_helper.rb
  app/helpers/table_sort_helper.rb
  app/helpers/transaction_type_helper.rb
  app/views/providers/application_merits_task/has_other_involved_children/show.html.erb
  app/views/providers/application_merits_task/has_other_opponents/show.html.erb
  app/views/providers/bank_transactions/_list_selected.html.erb
  app/views/providers/capital_income_assessment_results/_deductions.html.erb
  app/views/providers/capital_income_assessment_results/_disposable_income.html.erb
  app/views/providers/capital_income_assessment_results/_employment_income.html.erb
  app/views/providers/capital_income_assessment_results/_other_income.html.erb
  app/views/providers/capital_income_assessment_results/_outgoings.html.erb
  app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/providers/providers/show.html.erb
  app/views/providers/transactions/show.html.erb
  app/views/providers/uploaded_evidence_collections/_uploaded_files.html.erb
  app/views/shared/_employment_income_table.html.erb
  app/views/shared/_other_assets.html.erb
  app/views/shared/_property_results.html.erb
  app/views/shared/_restrictions.html.erb
  app/views/shared/_results_detail_row.html.erb
  app/views/shared/_results_total_bold_row.html.erb
  app/views/shared/_results_total_row.html.erb
  app/views/shared/_savings_and_investments.html.erb
  app/views/shared/_student_finances_table.html.erb
  app/views/shared/_total_capital.html.erb
  app/views/shared/_uploaded_files.html.erb
  app/views/shared/_vehicle_results.html.erb
  app/views/shared/check_answers/_bank_transaction_table.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/step_definitions/review_and_print_steps.rb
  spec/requests/providers/capital_income_assessment_results_controller_spec.rb
Labels: ready for review

#5668 Test: Group Jest dependencies together in dependabot
  .github/dependabot.yml
Labels: ready for review

#5649 AP-4392: Fix routing issue on client regular_outgoings and cash_outgoings pages
  app/services/flow/flows/provider_income.rb
  spec/requests/providers/means/cash_outgoings_controller_spec.rb
  spec/requests/providers/means/regular_outgoings_controller_spec.rb
Labels: Ready to merge

#5676 Rubocop: address todos
  .rubocop_todo.yml
  spec/forms/applicants/email_form_spec.rb
  spec/forms/applicants/employed_form_spec.rb
  spec/forms/concerns/date_field_builder_spec.rb
  spec/forms/incidents/told_on_form_spec.rb
  spec/forms/legal_aid_applications/dependant_form_spec.rb
  spec/forms/legal_aid_applications/has_evidence_of_benefit_form_spec.rb
  spec/forms/legal_aid_applications/own_home_form_spec.rb
  spec/forms/legal_aid_applications/restrictions_form_spec.rb
  spec/forms/legal_aid_applications/substantive_application_form_spec.rb
  spec/forms/providers/application_merits_task/involved_child_form_spec.rb
  spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb
  spec/forms/savings_amounts/offline_accounts_form_spec.rb
  spec/forms/savings_amounts/savings_amounts_form_spec.rb
  spec/models/applicant_spec.rb
  spec/services/flow/base_flow_service_spec.rb
  spec/services/manual_review_detailer_spec.rb
Labels: ready for review

#5671 Update: Dependabot group names
  .github/dependabot.yml
Labels: ready for review

#5681 Refactor: Client cash income checkbox
  app/views/providers/means/cash_incomes/show.html.erb
  config/locales/en/providers.yml
  features/providers/bank_statement_upload/check_your_means_answers.feature
  features/providers/bank_statement_upload/happy_path_journey.feature
  features/providers/check_multiple_employment.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/non_passported_journey/with_bank_transactions.feature
  features/providers/partner_means_assessment/end_to_end_income_assessment.feature
  features/providers/partner_means_assessment/means_check.feature
Labels: ready for review

#5682 Fix: Ensure truelayer transactions set ownership too
  app/controllers/providers/means/identify_types_of_incomes_controller.rb
  app/controllers/providers/means/identify_types_of_outgoings_controller.rb
  spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
  spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
Labels: ready for review

#5684 Rubocop: Address more named subject infractions
  .rubocop_todo.yml
  spec/helpers/hash_format_helper_spec.rb
  spec/helpers/providers_helper_spec.rb
  spec/helpers/user_transactions_helper_spec.rb
  spec/jobs/bank_transactions_analyser_job_spec.rb
  spec/jobs/citizen_complete_means_job_spec.rb
  spec/jobs/dashboard/applicant_email_job_spec.rb
  spec/jobs/dashboard/feedback_item_job_spec.rb
  spec/jobs/dashboard/provider_data_job_spec.rb
  spec/jobs/post_submission_processing_job_spec.rb
  spec/jobs/scheduled_mailings_delivery_job_spec.rb
  spec/lib/authorized_ip_ranges_spec.rb
  spec/lib/omni_auth/strategies/true_layer_spec.rb
  spec/lib/prometheus_collectors/sidekiq_queue_collector_spec.rb
  spec/policies/legal_aid_application_policy_spec.rb
  spec/presenters/applicant_account_presenter_spec.rb
  spec/validators/document_category_validator_spec.rb
  spec/workers/bank_holiday_update_worker_spec.rb
  spec/workers/ccms/submission_process_worker_spec.rb
  spec/workers/hmrc/result_worker_spec.rb
  spec/workers/hmrc/submission_worker_spec.rb
  spec/workers/true_layer_banks_update_worker_spec.rb
Labels: ready for review

#5691 Fix: Partner routing after income summary
  app/services/flow/flows/provider_income.rb
  spec/requests/providers/income_summary_controller_spec.rb
Labels: ready for review
