Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2024-09, with the labels that each got.

#7108 AP-5257: Add matter type and category of law to added proceedings page
  app/views/providers/has_other_proceedings/show.html.erb
Labels: UAT

#7074 AP-5220: Remove 'client has home address?' question from CYA
  app/forms/addresses/care_of_form.rb
  app/forms/addresses/choice_form.rb
  app/forms/home_address/status_form.rb
  app/services/flow/steps/addresses/correspondence_address_care_ofs_step.rb
  app/services/flow/steps/addresses/correspondence_address_manuals_step.rb
  app/views/shared/check_answers/_client_details.html.erb
  features/cassettes/Checking_client_details_answers_backwards_and_forwards/I_am_able_to_change_from_A_UK_office_address_to_Another_UK_residential_address_.yml
  features/cassettes/Checking_client_details_answers_backwards_and_forwards/I_am_able_to_change_from_A_UK_office_address_to_My_client_s_UK_home_address_.yml
  features/cassettes/Checking_client_details_answers_backwards_and_forwards/I_am_able_to_change_from_Another_UK_residential_address_to_My_client_s_UK_home_address_.yml
  features/cassettes/Checking_client_details_answers_backwards_and_forwards/I_am_able_to_change_from_My_client_s_UK_home_address_to_A_UK_office_address_.yml
  features/cassettes/Checking_client_details_answers_backwards_and_forwards/I_am_able_to_change_from_My_client_s_UK_home_address_to_Another_UK_residential_address_.yml
  features/providers/check_provider_answers.feature
  features/step_definitions/check_provider_answers_steps.rb
  spec/forms/addresses/care_of_form_spec.rb
  spec/forms/addresses/choice_form_spec.rb
  spec/forms/home_address/status_form_spec.rb
  spec/requests/providers/home_address/statuses_controller_spec.rb
  spec/services/flow/steps/addresses/correspondence_address_manuals_step_spec.rb
Labels: approved

#7107 Ap 5230 link cannot be removed
  app/controllers/providers/check_provider_answers_controller.rb
  app/views/providers/check_provider_answers/_standard.html.erb
  app/views/shared/check_answers/_linking_and_copying.html.erb
  spec/requests/providers/check_provider_answers_controller_spec.rb
Labels: ready for review

#7125 AP-4216: Update pages to display proceedings as in designs
  app/models/cfe/empty/empty_result.rb
  app/services/query/incomplete_proceedings.rb
  app/views/providers/has_other_proceedings/show.html.erb
  app/views/providers/proceedings_types/index.html.erb
  config/initializers/inflections.rb
  features/support/puffing_billy_helper.rb
  spec/factories/cfe_results/empty/mock_results.rb
  spec/factories/proceedings.rb
  spec/services/legal_framework/proceeding_types/all_spec.rb
Labels: do not merge

#7106 AP-5231: SCA emergency references
  app/services/flow/proceeding_loop.rb
  app/services/query/incomplete_proceedings.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/providers/limitations/_proceeding_type.html.erb
  app/views/shared/check_answers/_proceeding_details.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  spec/services/flow/proceeding_loop_spec.rb
  spec/services/query/incomplete_proceedings_spec.rb
Labels: UAT

#7159 AP-5297: Fix proceeding search requests for SCA
  app/services/legal_framework/proceeding_types/all.rb
Labels: ready for review

#7174 AP-5176: Add Temp data store for contract responses
  app/controllers/providers/confirm_offices_controller.rb
  app/controllers/providers/select_offices_controller.rb
  app/models/temp_contract_data.rb
  app/services/pda/current_contracts.rb
  app/services/pda/provider_details_retriever.rb
  app/workers/provider_contract_details_worker.rb
  config/environments/test.rb
  db/anonymise/rules.rb
  db/migrate/20240913145848_create_temp_contract_data.rb
  db/schema.rb
  db/seeds/test_provider_populator.rb
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/models/temp_contract_data_spec.rb
  spec/requests/providers/confirm_offices_spec.rb
  spec/requests/providers/select_offices_spec.rb
  spec/services/pda/current_contracts_spec.rb
  spec/services/pda/provider_details_retriever_spec.rb
  spec/workers/provider_contract_details_worker_spec.rb
Labels: UAT

#7197 AP-5176: Update the PDA values for staging and production
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: ready for review

#7188 Changes coming out of setup experience
  Brewfile
  README.md
  spec/services/pda/compare_provider_details_spec.rb
  spec/services/pda/provider_details_creator_spec.rb
  spec/services/provider_details_creator_spec.rb
Labels: ready for review

#7189 Bump ruby 3.3.4 to 3.3.5
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  docker/apply_base.dockerfile
  docker/apply_ci.dockerfile
  features/step_definitions/civil_journey_steps.rb
Labels: ready for review

#7207 Chore: Add `?debug` handler to merits report
  app/controllers/providers/merits_reports_controller.rb
  spec/requests/providers/merits_reports_controller_spec.rb
Labels: ready for review

#7183 AP-4454: Fix for DWP Override means report review reason
  app/services/ccms/manual_review_determiner.rb
  spec/services/ccms/manual_review_determiner_spec.rb
Labels: UAT

#7204 AP-5262: applied before question
  app/controllers/providers/previous_references_controller.rb
  app/forms/applicants/previous_reference_form.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/steps/provider_start/applicant_details_step.rb
  app/services/flow/steps/provider_start/applicants_step.rb
  app/services/flow/steps/provider_start/previous_references_step.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/merits_reports/show.html.erb
  app/views/providers/previous_references/show.html.erb
  app/views/shared/check_answers/_client_details.html.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/migrate/20240905104607_add_previous_reference_to_applicant.rb
  db/schema.rb
  features/providers/applicant_details.feature
  features/providers/applicant_under_16_blocked.feature
  features/providers/cost_override.feature
  features/providers/linked_applications/back_button.feature
  features/providers/no_nino_flow.feature
  features/providers/non_means_tested_journey/under_18_application_journey.feature
  features/providers/non_means_tested_journey/with_delegated_functions.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/regressions/back_button_on_proceedings.feature
  features/providers/regressions/scope_limitations.feature
  features/providers/search_proceedings.feature
  spec/forms/applicants/previous_reference_form_spec.rb
  spec/requests/providers/concerns/providers/draftable_spec.rb
  spec/requests/providers/previous_references_controller_spec.rb
  spec/services/flow/steps/provider_start/applicant_details_step_spec.rb
  spec/services/flow/steps/provider_start/applicants_step_spec.rb
  spec/services/flow/steps/provider_start/previous_references_step_spec.rb
Labels: approved, Ready to merge

#7213 Chore: Update docker/login-action
  .github/workflows/base-docker-image.yml
  .github/workflows/ci-docker-image.yml
Labels: ready for review

#7208 Chore: puppeteer update
  docker/apply_base.dockerfile
  package.json
  yarn.lock
Labels: approved

#7209 AP-5307: Add firm offices to new PDA result
  app/services/pda/compare_provider_details.rb
  app/services/pda/provider_details_creator.rb
  app/services/pda/provider_details_retriever.rb
  helm_deploy/apply-for-legal-aid/templates/NOTES.txt
  spec/cassettes/PDA_ProviderDetailsRetriever/_call/with_a_non_existent_user/returns_an_error.yml
  spec/cassettes/PDA_ProviderDetailsRetriever/_call/with_an_existing_user/returns_provider_details.yml
  spec/services/pda/compare_provider_details_spec.rb
  spec/services/pda/provider_details_creator_spec.rb
  spec/services/pda/provider_details_request_stubs.rb
  spec/services/pda/provider_details_retriever_spec.rb
Labels: ready for review, approved

#7214 AP-5313: create MTR A feature flag
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  db/migrate/20240923104047_add_means_test_review_a_to_settings.rb
  db/schema.rb
  spec/models/setting_spec.rb
  spec/requests/admin/settings_controller_spec.rb
Labels: ready for review

#7205 AP-5169 Add separate representation required to merits report
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/check_answers/_separate_representation.html.erb
  config/locales/en/shared.yml
Labels: UAT, approved

#7215 AP-5315: Fix SCA proceeding search bug
  app/javascript/src/modules/proceedings.js
Labels: ready for review

#7212 Ap 5272 add linked cases application digest
  app/models/application_digest.rb
  app/models/legal_aid_application.rb
  app/services/reports/mis/application_detail_csv_line.rb
  db/migrate/20240918073446_add_fields_to_application_digest.rb
  db/schema.rb
  spec/models/application_digest_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: ready for review
