Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2024-11, with the labels that each got.

#7340 AP-5416: Fix truelayer client with partner means CYA and flow
  app/controllers/providers/income_summary_controller.rb
  app/controllers/providers/means/check_income_answers_controller.rb
  app/controllers/providers/outgoings_summary_controller.rb
  app/helpers/transaction_type_helper.rb
  app/models/legal_aid_application.rb
  app/models/legal_aid_application_transaction_type.rb
  app/services/flow/steps/partner/regular_outgoings_step.rb
  app/services/flow/steps/provider_income/cash_incomes_step.rb
  app/services/flow/steps/provider_income/cash_outgoings_step.rb
  app/services/flow/steps/provider_income/outgoings_summary_step.rb
  app/views/providers/income_summary/index.html.erb
  app/views/providers/outgoings_summary/index.html.erb
  app/views/shared/check_answers/_payments_summary.html.erb
  features/cassettes/non_passported_journey_with_bank_transactions/Selects_and_categorises_bank_transactions_into_transaction_types.yml
  features/providers/non_passported_journey/with_bank_transactions.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/helpers/transaction_type_helper_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/legal_aid_application_transaction_type_spec.rb
  spec/requests/providers/income_summary_controller_spec.rb
  spec/requests/providers/means/check_income_answers_controller_spec.rb
  spec/requests/providers/outgoings_summary_controller_spec.rb
  spec/services/flow/steps/partner/regular_outgoings_step_spec.rb
  spec/services/flow/steps/provider_income/cash_incomes_step_spec.rb
  spec/services/flow/steps/provider_income/cash_outgoings_step_spec.rb
  spec/services/flow/steps/provider_income/outgoings_summary_step_spec.rb
Labels: ready for review, bug

#7395 AP-5396: Update SCA merits report
  app/components/reports/merits/delegated_functions_component.rb
  app/views/providers/merits_reports/show.html.erb
  app/views/shared/check_answers/_merits_proceeding_section.html.erb
  app/views/shared/check_answers/_separate_representation.html.erb
Labels: ready for review

#7351 AP-5347 Mandatory disregards page
  app/controllers/providers/means/capital_disregards/mandatory_controller.rb
  app/forms/providers/means/capital_disregards/mandatory_form.rb
  app/forms/providers/policy_disregards_form.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_capital_disregards.rb
  app/services/flow/steps/provider_capital/other_assets_step.rb
  app/services/flow/steps/provider_capital_disregards/mandatory_step.rb
  app/views/providers/means/capital_disregards/mandatory/show.html.erb
  app/views/providers/means/policy_disregards/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  db/migrate/20241030094958_add_uniqueness_index_to_capital_disregards.rb
  db/schema.rb
  features/providers/mtr_accelerated/capital_disregards.feature
  spec/forms/providers/means/capital_disregards/mandatory_form_spec.rb
  spec/requests/providers/means/capital_disregards/mandatory_controller_spec.rb
  spec/requests/providers/means/other_assets_controller_spec.rb
Labels: approved

#7396 AP-5453: CYA truelayer transaction bug
  app/controllers/providers/means/identify_types_of_incomes_controller.rb
  app/controllers/providers/means/identify_types_of_outgoings_controller.rb
  app/models/legal_aid_application.rb
  app/models/legal_aid_application_transaction_type.rb
  app/services/flow/steps/provider_income/identify_types_of_income_step.rb
  app/services/flow/steps/provider_income/identify_types_of_outgoings_step.rb
  app/views/providers/means/identify_types_of_incomes/show.html.erb
  app/views/providers/means/identify_types_of_outgoings/show.html.erb
  features/providers/regressions/client_truelayer_partner_bank_statements_check_means_answer.feature
  features/step_definitions/civil_journey_steps.rb
  features/step_definitions/regression_steps.rb
  spec/models/legal_aid_application_transaction_type_spec.rb
  spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
  spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
  spec/services/flow/steps/provider_income/identify_types_of_income_step_spec.rb
  spec/services/flow/steps/provider_income/identify_types_of_outgoings_step_spec.rb
Labels: UAT

#7399 AP-5398: Update date_field_builder to handle spaces
  app/forms/concerns/date_field_builder.rb
  spec/forms/applicants/basic_details_form_spec.rb
Labels: UAT

#7397 AP-5418: Update save as draft handling in the means pages
  app/controllers/providers/means/receives_state_benefits_controller.rb
  app/controllers/providers/means/student_finances_controller.rb
  app/controllers/providers/partners/receives_state_benefits_controller.rb
  app/controllers/providers/partners/student_finances_controller.rb
  app/forms/providers/means/receives_state_benefits_form.rb
  app/forms/providers/partners/receives_state_benefits_form.rb
  app/forms/student_finances/base_student_finance_form.rb
  app/services/flow/steps/partner/receives_state_benefits_step.rb
  app/services/flow/steps/provider_means_state_benefits/receives_state_benefits_step.rb
  app/views/shared/state_benefits/_new_benefit_form.erb
  spec/requests/providers/means/receives_state_benefits_controller_spec.rb
  spec/requests/providers/means/student_finances_controller_spec.rb
  spec/requests/providers/partners/receives_state_benefits_controller_spec.rb
  spec/requests/providers/partners/student_finances_controller_spec.rb
  spec/services/flow/steps/partner/receives_state_benefits_step_spec.rb
  spec/services/flow/steps/provider_means_state_benefits/receives_state_benefits_step_spec.rb
Labels: UAT

#7401 AP-5397: Update handling of CIT for SCA Secure Accommodation Orders
  app/models/legal_aid_application.rb
  app/views/providers/proceeding_loop/client_involvement_type/show.html.erb
  config/locales/en/providers.yml
  features/cassettes/Adding_an_SCA_Secure_Accommodation_Order_proceeding_sets_all_client_involvement_types_to_Child/When_a_provider_is_adding_proceedings_and_only_adds_a.yml
  features/providers/special_children_act/secure_accomodation_order_cit.feature
Labels: UAT

#7409 AP-5474: Add start date for MTR-A feature flag
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  app/views/shared/means/_cost_of_living_and_disregarded_benefits.html.erb
  config/application.rb
  config/locales/en/admin.yml
  features/providers/mtr_accelerated/capital_disregards.feature
  features/providers/mtr_accelerated/disregard_list.feature
  features/providers/mtr_accelerated/main_dwelling.feature
  features/step_definitions/debug_steps.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/models/setting_spec.rb
Labels: Ready to merge

#7414 AP-5473: Replace display_emergency_certificate? calls
  app/models/legal_aid_application.rb
  app/views/providers/limitations/_proceeding_type.html.erb
  app/views/providers/limitations/show.html.erb
  spec/models/legal_aid_application_spec.rb
Labels: ready for review

#7416 AP-5393: Update SCA client declaration page
  app/views/providers/confirm_client_declarations/show.html.erb
  features/providers/special_children_act/client_declaration.feature
  features/step_definitions/civil_journey_steps.rb
Labels: ready for review

#7428 AP-5412: Amend MTRA disregard list
  app/views/shared/means/_cost_of_living_and_disregarded_benefits.html.erb
  config/locales/en/helpers.yml
  config/locales/en/shared.yml
  db/schema.rb
  features/providers/mtr_accelerated/disregard_list.feature
Labels: ready for review

#7420 Chore: Update UAT digest Rake task exclusion
  lib/tasks/digest.rake
  spec/lib/tasks/digest_spec.rb
Labels: ready for review

#7422 AP-5442: Implement SCA firm permissions
  app/models/provider.rb
  app/services/legal_framework/proceeding_types/all.rb
  app/views/providers/has_national_insurance_numbers/show.html.erb
  db/seeds/permissions.rb
  features/cassettes/Adding_an_SCA_Secure_Accommodation_Order_proceeding_sets_all_client_involvement_types_to_Child/When_a_provider_is_adding_proceedings_and_only_adds_a_Secure_Accommodation_Order.yml
  features/providers/special_children_act/secure_accomodation_order_cit.feature
  features/step_definitions/debug_steps.rb
  spec/factories/firms.rb
  spec/factories/permissions.rb
  spec/models/provider_spec.rb
  spec/services/legal_framework/proceeding_types/all_spec.rb
Labels: ready for review

#7431 Fix: nullify student_finance_amount when no
  app/controllers/providers/means/student_finances_controller.rb
  app/controllers/providers/partners/student_finances_controller.rb
  app/forms/student_finances/base_student_finance_form.rb
  app/views/providers/means/vehicle_details/_form.html.erb
  app/views/shared/_student_finances.html.erb
  spec/forms/applicants/student_finance_form_spec.rb
  spec/forms/partners/student_finance_form_spec.rb
  spec/requests/providers/means/student_finances_controller_spec.rb
  spec/requests/providers/partners/student_finances_controller_spec.rb
Labels: ready for review, bug

#7430 AP-5465 Replace old secrets references
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
Labels: ready for review

#7438 Chore: Update PDA endpoints
  app/services/pda/current_contracts.rb
  app/services/pda/provider_details_retriever.rb
  spec/cassettes/PDA_ProviderDetailsRetriever/_call/with_a_non_existent_user/returns_an_error.yml
  spec/cassettes/PDA_ProviderDetailsRetriever/_call/with_an_existing_user/returns_provider_details.yml
  spec/services/pda/current_contracts_spec.rb
  spec/services/pda/provider_details_request_stubs.rb
  spec/services/pda/provider_details_retriever_spec.rb
Labels: ready for review

#7439 Chore: Remove Settings home_address column
  db/migrate/20241115143002_remove_home_address_from_settings.rb
  db/schema.rb
  features/providers/check_provider_answers.feature
  features/providers/linked_applications/back_button.feature
Labels: ready for review

#7370 AP-5143: Remove geckoboard updates
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/admin/user_dashboard_controller.rb
  app/jobs/dashboard/applicant_email_job.rb
  app/jobs/dashboard/feedback_item_job.rb
  app/jobs/dashboard/provider_data_job.rb
  app/jobs/dashboard/suspendable_job.rb
  app/jobs/dashboard/updater_job.rb
  app/lib/alert_manager.rb
  app/models/ccms/submission.rb
  app/models/dashboard/single_object/applicant_email.rb
  app/models/dashboard/single_object/feedback.rb
  app/models/dashboard/single_object/provider_data.rb
  app/models/dashboard/widget.rb
  app/models/dashboard/widget_data_providers/applications.rb
  app/models/dashboard/widget_data_providers/number_provider_firms.rb
  app/models/dashboard/widget_data_providers/pending_ccms_submissions.rb
  app/models/dashboard/widget_data_providers/percentage_declined_open_banking.rb
  app/models/feedback.rb
  app/models/firm.rb
  app/models/legal_aid_application.rb
  app/models/provider.rb
  app/services/citizen_email_service.rb
  app/services/dashboard_event_handler.rb
  config/application.rb
  config/initializers/active_support_notification_events.rb
  config/initializers/dashboard.rb
  config/initializers/sidekiq.rb
  helm_deploy/apply-for-legal-aid/templates/.dashboard_template_cron.yaml.sample
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
  lib/tasks/jobs/dashboard_updater.rake
  spec/jobs/dashboard/applicant_email_job_spec.rb
  spec/jobs/dashboard/feedback_item_job_spec.rb
  spec/jobs/dashboard/provider_data_job_spec.rb
  spec/jobs/dashboard/updater_job_spec.rb
  spec/lib/alert_manager_spec.rb
  spec/models/dashboard/single_object/applicant_email_spec.rb
  spec/models/dashboard/single_object/feedback_spec.rb
  spec/models/dashboard/single_object/provider_data_spec.rb
  spec/models/dashboard/widget_data_providers/applications_spec.rb
  spec/models/dashboard/widget_data_providers/number_provider_firms_spec.rb
  spec/models/dashboard/widget_data_providers/pending_ccms_submissions_spec.rb
  spec/models/dashboard/widget_data_providers/percentage_declined_open_banking_spec.rb
  spec/models/dashboard/widget_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/confirm_client_declarations_controller_spec.rb
  spec/services/citizen_email_service_spec.rb
  spec/services/dashboard_event_handler_spec.rb
Labels: approved, Ready to merge

#7445 Chore: Restore the admin user dashboard controller
  app/controllers/admin/user_dashboard_controller.rb
Labels: approved

#7441 AP-5515: Update the SCA Interrupt pages
  config/locales/en/providers.yml
  spec/requests/providers/proceedings_sca/interrupts_controller_spec.rb
Labels: UAT

#7440 AP-2910: Save attachment categorisation on select
  app/controllers/v1/attachments_controller.rb
  app/controllers/v1/uploaded_evidence_collections_controller.rb
  app/javascript/application.js
  app/javascript/src/dropzone.js
  app/javascript/src/file-upload-categorisation.js
  app/views/providers/uploaded_evidence_collections/_uploaded_files.html.erb
  config/routes.rb
  features/providers/check_multiple_employment.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/evidence_upload.feature
  features/providers/partner_means_assessment/upload_partner_employment_evidence.feature
  features/step_definitions/evidence_upload_steps.rb
  spec/requests/v1/attachments_spec.rb
Labels: UAT, approved, bug

#7452 Remove encryption from values files
  .gitattributes
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: approved

#7460 Chore: split rubocop from dependabot
  .github/dependabot.yml
Labels: ready for review

#7463 Chore: split rubocop from bulk dependabot
  .github/dependabot.yml
Labels: ready for review

#7467 Chore: Update URI gem
  Gemfile
  Gemfile.lock
  app/services/faraday/soap_call.rb
Labels: ready for review

#7458 AP-5368 cash income and outgoings bug
  app/controllers/providers/means/cash_incomes_controller.rb
  app/controllers/providers/means/cash_outgoings_controller.rb
  app/views/shared/means/_cash_income.html.erb
  app/views/shared/means/_cash_outgoing.html.erb
Labels: ready for review

#7453 AP-5177: Switch to new PDA after login
  .rubocop_todo.yml
  app/models/provider.rb
  app/services/provider_after_login_service.rb
  app/services/provider_details_retriever.rb
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/models/provider_spec.rb
  spec/requests/saml_sessions_controller_spec.rb
  spec/services/provider_after_login_service_spec.rb
Labels: Ready to merge

#7454 AP-5524: Replace error handling with exceptions_app
  app/controllers/application_controller.rb
  app/controllers/errors_controller.rb
  app/forms/applicants/basic_details_form.rb
  app/views/errors/show.html.erb
  app/views/errors/show/_internal_server_error.html.erb
  config/application.rb
  config/environments/development.rb
  config/locales/cy/errors.yml
  config/locales/en/errors.yml
  config/routes.rb
  public/favicon.ico
  spec/requests/citizens/legal_aid_applications_controller_spec.rb
  spec/requests/errors_controller_spec.rb
  spec/requests/providers/bank_transactions_controller_spec.rb
  spec/support/request_error_helpers.rb
Labels: UAT, approved

#7473 AP-5368 cash income and outgoings bug
  app/controllers/providers/means/cash_incomes_controller.rb
  app/controllers/providers/means/cash_outgoings_controller.rb
  app/views/shared/means/_cash_income.html.erb
  app/views/shared/means/_cash_outgoing.html.erb
Labels: UAT, approved

#7432 AP-5288: SCA CCMS payload updates
  app/models/application_digest.rb
  app/models/concerns/non_means_tested_state_machine.rb
  app/models/concerns/special_children_act_state_machine.rb
  app/models/legal_aid_application.rb
  app/services/ccms/attribute_configuration.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/ccms/requestors/special_children_act_case_add_requestor.rb
  app/services/flow/steps/provider_start/check_provider_answers_step.rb
  app/services/reports/mis/application_detail_csv_line.rb
  config/ccms/attribute_block_configs/special_children_act.yml
  spec/concerns/non_means_tested_state_machine_spec.rb
  spec/concerns/special_children_act_state_machine_spec.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/non_means_tested_state_machines.rb
  spec/factories/proceedings.rb
  spec/requests/providers/proceeding_merits_task/check_who_client_is_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/does_client_have_parental_responsibilities_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/is_client_biological_parent_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/is_client_child_subject_controller_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/special_children_act_case_add_requestor_spec.rb
  spec/services/flow/steps/provider_start/check_provider_answers_step_spec.rb
  spec/support/xml_extractor.rb
Labels: Ready to merge

#7464 AP-5490 add inset text to CYA pages
  app/views/providers/check_capital_answers/show.html.erb
  app/views/providers/check_merits_answers/show.html.erb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/means/check_income_answers/show.html.erb
  config/locales/en/generic.yml
  features/providers/check_provider_answers.feature
Labels: UAT, approved

#7477 AP-4435 fix form grouping accessibility error
  app/views/shared/forms/_applicant_form.html.erb
  config/locales/en/shared.yml
Labels: ready for review

#7488 fix: remove debug block
  app/views/providers/proceeding_loop/substantive_defaults/show.html.erb
Labels: approved

#7487 AP-5377: Update instructions for development and UAT LFA usage
  .env.sample
Labels: approved
