Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2024-03, with the labels that each got.

#6420 Fix: Update leap-date check
  features/step_definitions/applicant_detail_steps.rb
  spec/forms/proceedings/delegated_functions_form_spec.rb
Labels: ready for review

#6425 Fix: Update the dashboard update cronjob
  helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
Labels: ready for review

#6440 AP-4801: Add non-UK home address page
  app/controllers/providers/home_address/non_uk_home_addresses_controller.rb
  app/forms/addresses/non_uk_home_address_form.rb
  app/services/flow/flows/provider_start.rb
  app/services/legal_framework/non_uk_home_addresses/all.rb
  app/views/providers/home_address/non_uk_home_addresses/show.html.erb
  app/views/shared/_address_lookup.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/migrate/20240306122233_add_country_to_address_model.rb
  db/schema.rb
  spec/cassettes/Providers_HomeAddress_NonUkHomeAddressesController/GET_/providers/applications/_legal_aid_application_id/home_address/non_uk_home_address/edit/when_the_provider_is_authenticated/returns_success.yml
  spec/cassettes/Providers_HomeAddress_NonUkHomeAddressesController/PATCH_/providers/applications/_legal_aid_application_id/home_address/non_uk_home_address/when_the_provider_is_authenticated/with_an_invalid_address/renders_the_form_again_if_validation_fails.yml
  spec/cassettes/country_names_all.yml
  spec/forms/addresses/non_uk_home_address_form_spec.rb
  spec/requests/providers/home_address/non_uk_home_addresses_controller_spec.rb
  spec/services/legal_framework/non_uk_home_addresses/all_spec.rb
Labels: approved, Ready to merge, ruby

#6471 Fix: Update the postgres image used in circle
  .circleci/config.yml
Labels: ready for review

#6464 AP-4906: Update default country handling for addresses
  app/controllers/providers/address_lookups_controller.rb
  app/controllers/providers/address_selections_controller.rb
  app/controllers/providers/addresses_controller.rb
  app/controllers/providers/home_address/addresses_controller.rb
  app/controllers/providers/home_address/home_address_lookups_controller.rb
  app/controllers/providers/home_address/home_address_selections_controller.rb
  spec/requests/providers/address_lookups_controller_spec.rb
  spec/requests/providers/address_selections_controller_spec.rb
  spec/requests/providers/addresses_controller_spec.rb
  spec/requests/providers/home_address/addresses_controller_spec.rb
  spec/requests/providers/home_address/home_address_lookups_controller_spec.rb
  spec/requests/providers/home_address/home_address_selections_controller_spec.rb
Labels: ready for review

#6475 AP-4728: Update CCMS address handling
  app/helpers/address_helper.rb
  app/models/address.rb
  app/models/applicant.rb
  app/services/ccms/requestors/applicant_add_requestor.rb
  spec/factories/addresses.rb
  spec/factories/legal_aid_applications.rb
  spec/models/applicant_spec.rb
  spec/services/ccms/requestors/applicant_add_requestor_spec.rb
Labels: ready for review

#6496 AP-4898: Update home address warning text
  app/views/shared/_address_lookup.html.erb
  config/locales/en/shared.yml
Labels: approved
