Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2024-04, with the labels that each got.

#6506 ap-4913: build a new home address if changing between overseas and uk home address
  app/controllers/providers/home_address/addresses_controller.rb
  app/controllers/providers/home_address/home_address_lookups_controller.rb
  app/controllers/providers/home_address/non_uk_home_addresses_controller.rb
  spec/cassettes/Providers_HomeAddress_NonUkHomeAddressesController/GET_/providers/applications/_legal_aid_application_id/home_address/non_uk_home_address/edit/when_the_provider_is_authenticated/when_the_applicant_has_an_existing_overseas_home_address/displays_the_home_address.yml
  spec/cassettes/Providers_HomeAddress_NonUkHomeAddressesController/GET_/providers/applications/_legal_aid_application_id/home_address/non_uk_home_address/edit/when_the_provider_is_authenticated/when_the_applicant_has_an_existing_uk_home_address/does_not_display_the_home_address.yml
  spec/requests/providers/home_address/addresses_controller_spec.rb
  spec/requests/providers/home_address/home_address_lookups_controller_spec.rb
  spec/requests/providers/home_address/non_uk_home_addresses_controller_spec.rb
Labels: ready for review

#6523 Fix: Remove govuk-typography-responsive deprecation warning
  app/assets/stylesheets/language-switcher.scss
Labels: ready for review

#6532 AP-4919: Remove linked case proof of concept work
  app/controllers/providers/copy_case/confirmations_controller.rb
  app/controllers/providers/copy_case/invitations_controller.rb
  app/controllers/providers/copy_case/searches_controller.rb
  app/controllers/providers/link_case/confirmations_controller.rb
  app/controllers/providers/link_case/invitations_controller.rb
  app/controllers/providers/link_case/searches_controller.rb
  app/forms/base_form.rb
  app/forms/copy_case/confirmation_form.rb
  app/forms/copy_case/invitation_form.rb
  app/forms/copy_case/search_form.rb
  app/forms/link_case/confirmation_form.rb
  app/forms/link_case/invitation_form.rb
  app/forms/link_case/search_form.rb
  app/services/flow/flows/provider_start.rb
  app/views/providers/copy_case/confirmations/show.html.erb
  app/views/providers/copy_case/invitations/show.html.erb
  app/views/providers/copy_case/searches/show.html.erb
  app/views/providers/link_case/confirmations/show.html.erb
  app/views/providers/link_case/invitations/show.html.erb
  app/views/providers/link_case/searches/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  features/providers/copy_case.feature
  features/providers/link_case.feature
  spec/forms/copy_case/confirmation_form_spec.rb
  spec/forms/copy_case/invitation_form_spec.rb
  spec/forms/copy_case/search_form_spec.rb
  spec/forms/link_case/confirmation_form_spec.rb
  spec/forms/link_case/invitation_form_spec.rb
  spec/forms/link_case/search_form_spec.rb
  spec/requests/providers/address_selections_controller_spec.rb
  spec/requests/providers/addresses_controller_spec.rb
  spec/requests/providers/copy_case/confirmations_controller_spec.rb
  spec/requests/providers/copy_case/invitations_controller_spec.rb
  spec/requests/providers/copy_case/searches_controller_spec.rb
  spec/requests/providers/home_address/addresses_controller_spec.rb
  spec/requests/providers/home_address/home_address_selections_controller_spec.rb
  spec/requests/providers/home_address/non_uk_home_addresses_controller_spec.rb
  spec/requests/providers/link_case/confirmations_controller_spec.rb
  spec/requests/providers/link_case/invitations_controller_spec.rb
  spec/requests/providers/link_case/searches_controller_spec.rb
Labels: ready for review

#6543 Fix: Resolve flickering address test
  spec/requests/providers/home_address/addresses_controller_spec.rb
Labels: ready for review

#6546 AP-4933: Replace out-of-date text with voided
  config/locales/en/enums.yml
  config/locales/en/providers.yml
  config/routes.rb
  spec/helpers/providers_helper_spec.rb
Labels: ready for review

#6108 Incident: Disable maintenance mode
  helm_deploy/apply-for-legal-aid/values-production.yaml
Labels: On Hold

#6582 Chore: Update devise warning
  config/initializers/devise.rb
Labels: ready for review

#6584 AP-4826: Add LAA reference link question
  app/controllers/providers/link_application/find_link_applications_controller.rb
  app/forms/providers/link_application/find_link_application_form.rb
  app/services/flow/flows/provider_start.rb
  app/views/layouts/application.html.erb
  app/views/providers/link_application/find_link_applications/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  spec/forms/providers/link_application/find_link_application_form_spec.rb
  spec/requests/providers/link_application/find_link_applications_controller_spec.rb
  spec/requests/providers/link_application/make_links_controller_spec.rb
Labels: approved, Ready to merge

#6569 ap-4827: add link applications confirm link page
  app/controllers/providers/link_application/confirm_links_controller.rb
  app/forms/providers/link_application/confirm_link_form.rb
  app/helpers/linked_applications_helper.rb
  app/models/linked_application.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/steps/linked_applications/confirm_link_step.rb
  app/services/flow/steps/step.rb
  app/views/providers/link_application/confirm_links/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  spec/forms/providers/link_application/confirm_link_form_spec.rb
  spec/helpers/linked_applications_helper_spec.rb
  spec/models/linked_application_spec.rb
  spec/requests/providers/link_application/confirm_links_controller_spec.rb
  spec/requests/providers/link_application/find_link_applications_controller_spec.rb
  spec/services/flow/steps/linked_applications/confirm_link_step_spec.rb
Labels: UAT

#6585 ap-4951: attempt to fix unknow-levels-of-service error
  app/forms/proceedings/emergency_defaults_form.rb
  app/forms/proceedings/emergency_level_of_service_form.rb
  app/forms/proceedings/substantive_level_of_service_form.rb
  spec/cassettes/Proceedings_EmergencyLevelOfServiceForm/_save_as_draft/when_the_submission_is_valid/and_the_user_selects_Family_Help_Higher_/updates_the_emergency_level_of_service_value.yml
  spec/cassettes/Proceedings_EmergencyLevelOfServiceForm/_save_as_draft/when_the_submission_is_valid/and_the_user_selects_Full_Representation/updates_the_accepted_emergency_defaults_value.yml
  spec/cassettes/Proceedings_EmergencyLevelOfServiceForm/_save_as_draft/when_the_user_doesn_t_answer_the_question/is_valid.yml
  spec/cassettes/Proceedings_SubstantiveLevelOfServiceForm/_save_as_draft/when_the_submission_is_valid/and_the_user_selects_Family_Help_Higher_/updates_the_substantive_level_of_service_value.yml
  spec/cassettes/Proceedings_SubstantiveLevelOfServiceForm/_save_as_draft/when_the_submission_is_valid/and_the_user_selects_Full_Representation/updates_the_accepted_substantive_defaults_value.yml
  spec/cassettes/Proceedings_SubstantiveLevelOfServiceForm/_save_as_draft/when_the_user_doesn_t_answer_the_question/is_valid.yml
  spec/forms/proceedings/emergency_defaults_form_spec.rb
  spec/forms/proceedings/emergency_level_of_service_form_spec.rb
  spec/forms/proceedings/substantive_level_of_service_form_spec.rb
Labels: ready for review

#6575 AP-4828: Add copy case question
  app/controllers/providers/link_application/copies_controller.rb
  app/forms/providers/link_application/copy_form.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/steps/linked_applications/confirm_link_step.rb
  app/services/flow/steps/linked_applications/copy_step.rb
  app/views/providers/link_application/copies/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  spec/forms/providers/link_application/copy_form_spec.rb
  spec/requests/providers/link_application/copies_controller_spec.rb
  spec/services/flow/steps/linked_applications/confirm_link_step_spec.rb
  spec/services/flow/steps/linked_applications/copy_step_spec.rb
Labels: ready for review

#6597 AP-4952: Bug - move any step with no path into new step pattern
  app/services/flow/flows/provider_capital.rb
  app/services/flow/flows/provider_means_state_benefits.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/flows/provider_partner.rb
  app/services/flow/steps/addresses/correspondence_address_manuals_step.rb
  app/services/flow/steps/addresses/home_address_manuals_step.rb
  app/services/flow/steps/partner/remove_state_benefits_step.rb
  app/services/flow/steps/provider_capital/remove_vehicles_step.rb
  app/services/flow/steps/provider_means/remove_state_benefits_step.rb
  app/services/flow/steps/provider_merits/opponent_new_organisation_step.rb
  app/services/flow/steps/provider_merits/remove_involved_child_step.rb
  app/services/flow/steps/provider_merits/remove_opponent_step.rb
  spec/cassettes/Providers_ApplicationMeritsTask_OpponentNewOrganisationsController/update_PATCH_/providers/applications/_legal_aid_application_id/opponent_new_organisation/_opponent_id/redirects_along_the_flow.yml
  spec/requests/providers/application_merits_task/opponent_new_organisations_controller_spec.rb
  spec/requests/providers/application_merits_task/remove_involved_child_spec.rb
  spec/requests/providers/application_merits_task/remove_opponent_controller_spec.rb
  spec/requests/providers/home_address/manuals_controller_spec.rb
  spec/requests/providers/means/remove_state_benefits_controller_spec.rb
  spec/requests/providers/means/remove_vehicles_controller_spec.rb
  spec/requests/providers/partners/remove_state_benefits_controller_spec.rb
  spec/services/flow/steps/addresses/correspondence_address_manuals_step_spec.rb
  spec/services/flow/steps/addresses/home_address_manuals_step_spec.rb
  spec/services/flow/steps/partner/remove_state_benefits_step_spec.rb
  spec/services/flow/steps/provider_capital/remove_vehicles_step_spec.rb
  spec/services/flow/steps/provider_means/remove_state_benefits_step_spec.rb
  spec/services/flow/steps/provider_merits/opponent_new_organisation_step_spec.rb
  spec/services/flow/steps/provider_merits/remove_involved_child_step_spec.rb
  spec/services/flow/steps/provider_merits/remove_opponent_step_spec.rb
Labels: UAT

#6609 CHORE: Update super_diff gem
  Gemfile.lock
Labels: ready for review

#6610 ap-4830: refactor routing after linking
  app/controllers/providers/link_application/confirm_links_controller.rb
  app/services/flow/steps/linked_applications/confirm_link_step.rb
  config/locales/en/providers.yml
  spec/requests/providers/link_application/confirm_links_controller_spec.rb
  spec/services/flow/steps/linked_applications/confirm_link_step_spec.rb
Labels: UAT
