Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2024-10, with the labels that each got.

#7235 AP-5180: Client address tracking data
  app/models/application_digest.rb
  app/services/reports/mis/application_detail_csv_line.rb
  db/migrate/20240930074635_add_address_to_digest.rb
  db/schema.rb
  spec/models/application_digest_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: approved

#7247 AP-5329: Add previous_reference to admin report
  app/services/reports/mis/application_detail_csv_line.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: UAT

#7032 Chore: Update Rails to 7.2.1
  Gemfile.lock
  app/helpers/flow_helper.rb
  app/views/providers/application_merits_task/opponent_existing_organisations/index.html.erb
  app/views/providers/proceedings_types/index.html.erb
  app/views/providers/uploaded_evidence_collections/show.html.erb
  app/views/shared/_uploaded_files.html.erb
  features/providers/mock_saml.feature
  features/step_definitions/mock_saml_steps.rb
  features/support/env.rb
Labels: approved

#7264 AP-5365: Fix vehicle not found error
  app/controllers/application_controller.rb
  app/controllers/concerns/providers/application_dependable.rb
  app/services/flow/steps/provider_capital/vehicle_details_step.rb
  spec/services/flow/steps/provider_capital/vehicle_details_step_spec.rb
Labels: ready for review, URGENT

#7256 Chore: Update gemfile-lock with new darwin osx version
  Gemfile.lock
Labels: approved

#7267 AP-5326: Add Public Law Family feature flag to proceeding search
  app/services/legal_framework/proceeding_types/all.rb
  spec/services/legal_framework/proceeding_types/all_spec.rb
Labels: approved, Ready to merge

#7269 Stop updating student_loan `archived_at` date
  app/services/populators/transaction_type_populator.rb
Labels: approved

#7245 AP-4707: Prevent none plus other checkbox selection when JS not enabled
  app/controllers/providers/means/identify_types_of_incomes_controller.rb
  app/controllers/providers/means/identify_types_of_outgoings_controller.rb
  app/forms/providers/regular_transaction_form.rb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  spec/forms/providers/means/regular_income_form_spec.rb
  spec/forms/providers/means/regular_outgoings_form_spec.rb
  spec/forms/providers/partners/regular_income_form_spec.rb
  spec/forms/providers/partners/regular_outgoings_form_spec.rb
  spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
  spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
Labels: ready for review, UAT

#7268 AP-3985: Clear employment if citizen does not complete truelayer
  app/controllers/citizens/consents_controller.rb
  app/views/shared/check_answers/_full_employment_details.html.erb
Labels: approved

#7284 FIX: fix truelayer category display
  app/views/providers/transactions/show.html.erb
  features/providers/non_passported_journey/with_bank_transactions.feature
  features/step_definitions/generic_steps.rb
Labels: approved, bug

#7287 ap-5158: part 3 migrate postgres and redis secrets
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: approved

#7277 AP-5269: Update delete application handling
  app/controllers/providers/delete_controller.rb
  app/javascript/application.js
  app/javascript/src/modal-dialogue.js
  app/views/providers/delete/show.html.erb
  app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
  app/views/shared/partials/_modal_dialogue.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/deleting_applications.feature
  features/step_definitions/civil_journey_steps.rb
Labels: UAT

#7291 ap-5158: part 5 migrate ccms soa secrets to external secret
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: approved

#7276 AP-5370: Allow applications for under 16s
  app/controllers/providers/use_ccms_under16s_controller.rb
  app/models/applicant.rb
  app/models/concerns/base_state_machine.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/steps/provider_start/check_provider_answers_step.rb
  app/services/flow/steps/provider_start/use_ccms_under16s_step.rb
  app/views/providers/use_ccms_under16s/show.html.erb
  config/locales/en/providers.yml
  features/providers/applicant_under_16_blocked.feature
  spec/concerns/base_state_machine_spec.rb
  spec/models/applicant_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/check_provider_answers_controller_spec.rb
  spec/services/flow/steps/provider_start/check_provider_answers_step_spec.rb
  spec/services/flow/steps/provider_start/use_ccms_under16s_step_spec.rb
Labels: do not merge

#7289 AP-5336: Remove automatic categorisation of benefits
  app/jobs/bank_transactions_analyser_job.rb
  app/models/bank_account.rb
  app/services/banking/state_benefit_analyser_service.rb
  spec/factories/bank_transactions.rb
  spec/factories/legal_aid_applications.rb
  spec/jobs/bank_transactions_analyser_job_spec.rb
  spec/models/bank_account_spec.rb
  spec/models/bank_transaction_spec.rb
  spec/presenters/bank_transaction_presenter_spec.rb
  spec/requests/providers/transactions_controller_spec.rb
  spec/services/banking/state_benefit_analyser_service_spec.rb
  spec/services/cfe_civil/components/state_benefits_spec.rb
Labels: UAT, approved, do not merge

#7308 AP-5343: MTR accelerated measures - Main dwelling updates
  app/views/providers/means/own_homes/show.html.erb
  app/views/providers/means/property_details/show.html.erb
  app/views/shared/check_answers/_property.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/mtr_accelerated/main_dwelling.feature
  spec/requests/providers/means/own_home_controller_spec.rb
Labels: UAT, approved

#7335 Disable digest export on UAT
  .simplecov
  lib/tasks/digest.rake
  spec/lib/tasks/digest_spec.rb
Labels: ready for review

#7336 ap-5158: migrate additional google sheet secrets to external secret
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: approved

#7337 ap-5080: Do not alert apply team if citizen_start_email is undeliverable
  app/services/govuk_emails/monitor.rb
  spec/services/govuk_emails/monitor_spec.rb
Labels: ready for review

#7292 AP-5335: Remove ability to add disregarded benefits
  app/controllers/providers/means/housing_benefits_controller.rb
  app/helpers/means_report_helper.rb
  app/models/legal_aid_application.rb
  app/services/cfe_civil/component_list.rb
  app/services/flow/steps/partner/cash_outgoings_step.rb
  app/services/flow/steps/provider_income/cash_outgoings_step.rb
  app/services/flow/steps/provider_income/outgoings_summary_step.rb
  app/services/populators/transaction_type_populator.rb
  app/views/providers/capital_income_assessment_results/_deductions.html.erb
  app/views/providers/means/check_income_answers/show.html.erb
  app/views/shared/check_answers/_outgoings_details.html.erb
  app/views/shared/means_report/_item.html.erb
  app/views/shared/review_application/_income_payments_and_assets.html.erb
  app/views/shared/review_application/_income_payments_and_assets_for_bank_statement_upload.html.erb
  config/locales/cy/shared.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/check_multiple_employment.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/check_your_answers.feature
  features/providers/means_report.feature
  features/providers/non_passported_journey/with_bank_transactions.feature
  features/providers/non_passported_journey/with_means.feature
  features/providers/partner_means_assessment/means_report.feature
  features/providers/review_and_print.feature
  features/step_definitions/check_your_answers_steps.rb
  features/step_definitions/civil_journey_steps.rb
  spec/helpers/means_report_helper_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/models/transaction_type_spec.rb
  spec/services/cfe_civil/component_list_spec.rb
  spec/services/flow/steps/partner/cash_outgoings_step_spec.rb
  spec/services/flow/steps/provider_income/cash_outgoings_step_spec.rb
  spec/services/flow/steps/provider_income/outgoings_summary_step_spec.rb
  spec/services/populators/transaction_type_populator_spec.rb
Labels: UAT, approved

#7327 AP-5412: Amend benefit and income quesion content
  app/controllers/providers/partners/add_other_state_benefits_controller.rb
  app/models/concerns/binary_choice_form.rb
  app/views/providers/transactions/show.html.erb
  app/views/shared/means/_regular_income.html.erb
  app/views/shared/state_benefits/_add_other_state_benefits.html.erb
  app/views/shared/state_benefits/_new_benefit_form.erb
  config/locales/cy/transaction_types.yml
  config/locales/en/activemodel.yml
  config/locales/en/helpers.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/locales/en/transaction_types.yml
  features/providers/bank_statement_upload/happy_path_journey.feature
  features/providers/bank_statement_upload/state_benefit_loop.feature
  features/providers/check_your_answers.feature
  features/providers/means_report.feature
  features/providers/non_passported_journey/with_bank_transactions.feature
  features/providers/non_passported_journey/with_means.feature
  features/providers/partner_means_assessment/end_to_end_income_assessment.feature
  features/providers/partner_means_assessment/means_report.feature
  features/providers/partner_means_assessment/state_benefits.feature
  features/providers/review_and_print.feature
  spec/requests/providers/means/add_other_state_benefits_controller_spec.rb
  spec/requests/providers/means/state_benefits_controller_spec.rb
  spec/requests/providers/partners/add_other_state_benefits_controller_spec.rb
  spec/requests/providers/partners/state_benefits_controller_spec.rb
Labels: UAT, approved

#7331 AP-5404: Improve document naming
  app/services/ccms/requestors/document_id_requestor.rb
  app/services/ccms/requestors/document_upload_requestor.rb
  db/migrate/20241018081039_update_document_categories.rb
  db/schema.rb
  db/seeds/document_categories.csv
  spec/services/ccms/requestors/document_id_requestor_spec.rb
  spec/services/ccms/requestors/document_upload_requestor_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
Labels: approved

#7341 AP-5344: Amend list of disregarded benefits
  app/views/shared/means/_cost_of_living_and_disregarded_benefits.html.erb
  config/locales/en/shared.yml
  features/providers/mtr_accelerated/disregard_list.feature
  features/step_definitions/bank_statement_upload_steps.rb
  features/step_definitions/civil_journey_steps.rb
Labels: UAT, approved

#7368 AP-5392: SCA update check merits answers
  app/helpers/task_list_helper.rb
  app/views/shared/check_answers/_merits_proceeding_section.html.erb
  features/providers/check_merits_answers.feature
  features/step_definitions/civil_journey_steps.rb
  spec/factories/legal_framework_merits_task_list.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
Labels: approved

#7347 AP-5426 Create capital disregards DB table and add namespace
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20241022133251_create_capital_disregards.rb
  db/schema.rb
Labels: approved

#7379 AP-5394: Update SCA review and print
  app/models/concerns/delegated_functions.rb
  app/views/shared/check_answers/_client_details.html.erb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/check_answers/_proceeding_details_section.html.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
  features/providers/review_and_print.feature
  features/step_definitions/review_and_print_steps.rb
Labels: UAT

#7387 AP-5395: Update SCA means_tested display on Means Report
  app/helpers/client_helper.rb
  app/views/shared/check_answers/_client_details.html.erb
  config/locales/en/generic.yml
  spec/helpers/client_helper_spec.rb
Labels: UAT

#7391 AP-5450: Working discretionary disregards form
  app/controllers/providers/means/capital_disregards/discretionary_controller.rb
  app/forms/providers/means/capital_disregards/discretionary_form.rb
  app/views/providers/means/capital_disregards/discretionary/show.html.erb
  config/locales/en/activemodel.yml
  features/providers/mtr_accelerated/discretionary_capital_disregards.feature
  spec/factories/applicants.rb
  spec/forms/providers/means/capital_disregards/discretionary_form_spec.rb
  spec/requests/providers/means/capital_disregards/discretionary_controller_spec.rb
Labels: ready for review
