Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2024-07, with the labels that each got.

#6874 ap-4681: refactor end of provider_start flow
  app/services/flow/flows/provider_start.rb
  app/services/flow/steps/provider_start/about_the_financial_assessments_step.rb
  app/services/flow/steps/provider_start/application_confirmations_step.rb
  app/services/flow/steps/provider_start/check_benefits_step.rb
  app/services/flow/steps/provider_start/check_provider_answers_step.rb
  app/services/flow/steps/provider_start/delegated_confirmation_step.rb
  app/services/flow/steps/provider_start/no_national_insurance_numbers_step.rb
  app/services/flow/steps/provider_start/substantive_applications_step.rb
  app/services/flow/steps/provider_start/use_ccms_employment_step.rb
  app/services/flow/steps/provider_start/use_ccms_step.rb
  app/services/flow/steps/provider_start/use_ccms_under16s_step.rb
  spec/requests/providers/no_national_insurance_numbers_controller_spec.rb
  spec/requests/providers/substantive_applications_controller_spec.rb
  spec/services/flow/steps/provider_start/about_the_financial_assessments_step_spec.rb
  spec/services/flow/steps/provider_start/application_confirmations_step_spec.rb
  spec/services/flow/steps/provider_start/check_benefits_step_spec.rb
  spec/services/flow/steps/provider_start/check_provider_answers_step_spec.rb
  spec/services/flow/steps/provider_start/delegated_confirmation_step_spec.rb
  spec/services/flow/steps/provider_start/no_national_insurance_numbers_step_spec.rb
  spec/services/flow/steps/provider_start/substantive_applications_step_spec.rb
  spec/services/flow/steps/provider_start/use_ccms_employment_step_spec.rb
  spec/services/flow/steps/provider_start/use_ccms_step_spec.rb
  spec/services/flow/steps/provider_start/use_ccms_under16s_step_spec.rb
Labels: approved

#6892 Chore: Update strong_migration target_version
  config/initializers/strong_migrations.rb
Labels: ready for review

#6880 AP-4677: Flow refactoring - provider_merits - summary steps
  app/services/flow/flows/provider_merits.rb
  app/services/flow/steps/provider_merits/check_merits_answers_step.rb
  app/services/flow/steps/provider_merits/confirm_client_declarations_step.rb
  app/services/flow/steps/provider_merits/end_of_applications_step.rb
  app/services/flow/steps/provider_merits/merits_reports_step.rb
  app/services/flow/steps/provider_merits/merits_task_lists_step.rb
  app/services/flow/steps/provider_merits/review_and_print_applications_step.rb
  app/services/flow/steps/provider_merits/submitted_applications_step.rb
  app/services/flow/steps/provider_merits/uploaded_evidence_collections_step.rb
  spec/requests/providers/check_merits_answers_spec.rb
  spec/requests/providers/confirm_client_declarations_controller_spec.rb
  spec/requests/providers/end_of_applications_controller_spec.rb
  spec/requests/providers/merits_task_lists_controller_spec.rb
  spec/requests/providers/review_and_print_applications_controller_spec.rb
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/services/flow/steps/provider_merits/check_merits_answers_step_spec.rb
  spec/services/flow/steps/provider_merits/confirm_client_declarations_step_spec.rb
  spec/services/flow/steps/provider_merits/end_of_applications_step_spec.rb
  spec/services/flow/steps/provider_merits/merits_reports_step_spec.rb
  spec/services/flow/steps/provider_merits/merits_task_lists_step_spec.rb
  spec/services/flow/steps/provider_merits/review_and_print_applications_step_spec.rb
  spec/services/flow/steps/provider_merits/submitted_applications_step_spec.rb
  spec/services/flow/steps/provider_merits/uploaded_evidence_collections_step_spec.rb
Labels: approved

#6879 AP-5107: Update case link handling
  app/controllers/providers/link_application/copies_controller.rb
  app/forms/providers/link_application/copy_form.rb
  app/forms/providers/link_application/find_link_application_form.rb
  app/helpers/linked_applications_helper.rb
  app/models/legal_aid_application.rb
  app/models/linked_application.rb
  app/views/providers/link_application/confirm_links/show.html.erb
  app/views/providers/link_application/copies/show.html.erb
  app/views/shared/check_answers/_linking_and_copying.html.erb
  db/migrate/20240627104142_add_target_application_to_linked_applications.rb
  db/schema.rb
  features/step_definitions/linked_cases_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/forms/providers/link_application/copy_form_spec.rb
  spec/forms/providers/link_application/find_link_application_form_spec.rb
  spec/helpers/linked_applications_helper_spec.rb
  spec/models/linked_application_spec.rb
  spec/requests/providers/link_application/confirm_links_controller_spec.rb
  spec/requests/providers/link_application/copies_controller_spec.rb
Labels: ready for review

#6893 AP-5095: Add partner data to reports
  app/controllers/admin/reports_controller.rb
  app/models/application_digest.rb
  app/services/reports/mis/application_detail_csv_line.rb
  app/views/admin/reports/index.html.erb
  db/migrate/20240702132532_add_new_fields_to_application_digest.rb
  db/schema.rb
  spec/models/application_digest_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: ready for review

#6904 Chore: Update MeritsTaskService
  app/services/legal_framework/merits_tasks_service.rb
Labels: ready for review

#6891 ap-4752: Remove the do you want to use the default level of service or scope for the substantive application? question
  app/forms/proceedings/substantive_defaults_form.rb
  app/models/proceeding.rb
  app/services/flow/steps/provider_proceeding_loop/substantive_defaults_step.rb
  app/views/providers/proceeding_loop/substantive_defaults/show.html.erb
  spec/cassettes/Proceedings_SubstantiveDefaultsForm/_save/with_a_Special_Childrens_Act_proceeding/sets_the_default_values.yml
  spec/cassettes/Proceedings_SubstantiveDefaultsForm/_save/with_a_Special_Childrens_Act_proceeding/without_calling_the_subject/creates_a_scope_limitation_object.yml
  spec/forms/proceedings/substantive_defaults_form_spec.rb
  spec/requests/providers/proceeding_loop/substantive_defaults_controller_spec.rb
  spec/services/flow/steps/provider_proceeding_loop/substantive_defaults_step_spec.rb
Labels: UAT

#6905 ap-5140: Fix error when provider has added SCA proceeding and uses de…
  app/controllers/providers/limitations_controller.rb
  spec/requests/providers/limitations_controller_spec.rb
Labels: ready for review

#6912 AP-4680: Refactor flow steps
  app/services/flow/flows/provider_dwp_override.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/steps/provider_dwp_override/check_client_details_step.rb
  app/services/flow/steps/provider_dwp_override/confirm_dwp_non_passported_applications_step.rb
  app/services/flow/steps/provider_dwp_override/has_evidence_of_benefits_step.rb
  app/services/flow/steps/provider_dwp_override/received_benefit_confirmations_step.rb
  app/services/flow/steps/provider_merits/client_denial_of_allegations_step.rb
  app/services/flow/steps/provider_merits/client_offered_undertakings_step.rb
  app/services/flow/steps/provider_merits/opponents_application_step.rb
  app/services/flow/steps/provider_start/about_financial_means_step.rb
  app/services/flow/steps/provider_start/applicant_employed_step.rb
  app/services/flow/steps/provider_start/has_national_insurance_numbers_step.rb
  spec/requests/providers/about_financial_means_controller_spec.rb
  spec/requests/providers/application_merits_task/client_denial_of_allegations_controller_spec.rb
  spec/requests/providers/application_merits_task/client_offered_undertakings_controller_spec.rb
  spec/requests/providers/check_client_details_controller_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_controller_spec.rb
  spec/requests/providers/has_evidence_of_benefits_controller_spec.rb
  spec/requests/providers/has_national_insurance_numbers_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/opponents_application_controller_spec.rb
  spec/requests/providers/received_benefit_confirmations_controller_spec.rb
  spec/services/flow/steps/provider_dwp_override/check_client_details_step_spec.rb
  spec/services/flow/steps/provider_dwp_override/confirm_dwp_non_passported_applications_step_spec.rb
  spec/services/flow/steps/provider_dwp_override/has_evidence_of_benefits_step_spec.rb
  spec/services/flow/steps/provider_dwp_override/received_benefit_confirmations_step_spec.rb
  spec/services/flow/steps/provider_merits/client_denial_of_allegations_step_spec.rb
  spec/services/flow/steps/provider_merits/client_offered_undertakings_step_spec.rb
  spec/services/flow/steps/provider_merits/opponents_application_step_spec.rb
  spec/services/flow/steps/provider_start/about_financial_means_step_spec.rb
  spec/services/flow/steps/provider_start/applicant_employed_step_spec.rb
  spec/services/flow/steps/provider_start/has_national_insurance_numbers_step_spec.rb
Labels: ready for review

#6911 ap-5111: Delete any existing SubmissionDocuments before creating new …
  app/services/ccms/submitters/obtain_document_id_service.rb
  spec/factories/submission_documents.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
Labels: ready for review

#6909 AP-4643: Add sca client relationship task
  app/controllers/providers/proceeding_merits_task/is_client_biological_parent_controller.rb
  app/forms/providers/proceeding_merits_task/biological_parent_form.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/merits_loop.rb
  app/services/flow/steps/provider_merits/biological_parent_step.rb
  app/views/providers/proceeding_merits_task/is_client_biological_parent/show.html.erb
  config/locales/en/providers.yml
  config/routes.rb
  db/migrate/20240704134837_add_relationship_to_child_to_proceedings.rb
  db/schema.rb
  spec/factories/legal_framework_merits_task_list.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/forms/providers/proceeding_merits_task/biological_parent_form_spec.rb
  spec/requests/providers/proceeding_merits_task/is_client_biological_parent_controller_spec.rb
  spec/services/flow/steps/provider_merits/biological_parent_step_spec.rb
Labels: UAT

#6920 AP-4688: Flow refactor partner employment steps
  app/services/flow/flows/provider_partner.rb
  app/services/flow/steps/partner/employed_step.rb
  app/services/flow/steps/partner/employment_incomes_step.rb
  app/services/flow/steps/partner/full_employment_details_step.rb
  app/services/flow/steps/partner/unexpected_employment_income_step.rb
  app/services/flow/steps/partner/use_ccms_employment_step.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/partners/employed_controller_spec.rb
  spec/requests/providers/partners/employment_incomes_controller_spec.rb
  spec/requests/providers/partners/full_employment_details_controller_spec.rb
  spec/requests/providers/partners/unexpected_employment_incomes_controller_spec.rb
  spec/services/flow/steps/partner/employed_step_spec.rb
  spec/services/flow/steps/partner/employment_incomes_step_spec.rb
  spec/services/flow/steps/partner/full_employment_details_step_spec.rb
  spec/services/flow/steps/partner/unexpected_employment_income_step_spec.rb
  spec/services/flow/steps/partner/use_ccms_employment_step_spec.rb
Labels: approved

#6924 AP-4641: Add sca evidence upload
  app/services/required_document_category_analyser.rb
  app/validators/document_category_validator.rb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  db/seeds/document_categories.csv
  spec/models/document_category_spec.rb
  spec/services/required_document_category_analyser_spec.rb
Labels: UAT

#6913 AP-4672: Flow refactor provider_capital outgoings steps
  app/services/flow/flows/provider_income.rb
  app/services/flow/steps/provider_income/cash_outgoings_step.rb
  app/services/flow/steps/provider_income/check_income_answers_step.rb
  app/services/flow/steps/provider_income/housing_benefits_step.rb
  app/services/flow/steps/provider_income/identify_types_of_outgoings_step.rb
  app/services/flow/steps/provider_income/outgoing_transactions_step.rb
  app/services/flow/steps/provider_income/outgoings_summary_step.rb
  app/services/flow/steps/provider_income/regular_outgoings_step.rb
  spec/requests/providers/means/cash_outgoings_controller_spec.rb
  spec/requests/providers/means/check_income_answers_controller_spec.rb
  spec/requests/providers/means/housing_benefits_controller_spec.rb
  spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
  spec/requests/providers/means/regular_outgoings_controller_spec.rb
  spec/requests/providers/outgoings_summary_controller_spec.rb
  spec/services/flow/steps/provider_income/cash_outgoings_step_spec.rb
  spec/services/flow/steps/provider_income/check_income_answers_step_spec.rb
  spec/services/flow/steps/provider_income/housing_benefits_step_spec.rb
  spec/services/flow/steps/provider_income/identify_types_of_outgoings_step_spec.rb
  spec/services/flow/steps/provider_income/outgoing_transactions_step_spec.rb
  spec/services/flow/steps/provider_income/outgoings_summary_step_spec.rb
  spec/services/flow/steps/provider_income/regular_outgoings_step_spec.rb
Labels: approved, Ready to merge

#6962 Fix benefit checker error handling
  app/services/benefit_check_service.rb
  spec/services/benefit_check_service_spec.rb
Labels: approved

#6955 AP-5136: Store dwp partner override on applicant too
  app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
  app/models/application_digest.rb
  app/services/reports/mis/application_detail_csv_line.rb
  db/migrate/20240722082922_add_shared_benefit_column_to_applicant.rb
  db/schema.rb
  spec/models/application_digest_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_controller_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: ready for review
