Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2024-01, with the labels that each got.

#6164 AP-4716: Update applicant search response parser
  app/lib/message_logger.rb
  app/services/ccms/parsers/applicant_search_response_parser.rb
  app/services/ccms/parsers/base_response_parser.rb
  app/services/ccms/submitters/base_submission_service.rb
  app/services/ccms/submitters/obtain_applicant_reference_service.rb
  spec/data/ccms/applicant_search_response_multiple_number_not_matched.xml
  spec/data/ccms/applicant_search_response_multiple_results.xml
  spec/data/ccms/applicant_search_response_number_not_held.xml
  spec/data/ccms/applicant_search_response_number_not_matched.xml
  spec/data/ccms/applicant_search_response_one_result.xml
  spec/services/ccms/parsers/applicant_search_response_parser_spec.rb
Labels: UAT

#6173 Chore: check page title in feature test
  features/providers/bank_statement_upload/state_benefit_loop.feature
Labels: approved

#6010 AP-4610: Update partner means report
  app/helpers/means_report_helper.rb
  app/models/cfe/v6/result.rb
  app/views/providers/means_reports/_with_cfe_result_details.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_benefits_breakdown.html.erb
  app/views/shared/check_answers/_employed_income.html.erb
  app/views/shared/check_answers/_income_result.html.erb
  app/views/shared/check_answers/_property.html.erb
  app/views/shared/means_report/_item.html.erb
  app/views/shared/review_application/_income_payments_and_assets_for_bank_statement_upload.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/bank_statement_upload/check_your_means_answers.feature
  features/providers/check_your_answers.feature
  features/providers/means_report.feature
  features/providers/partner_means_assessment/bank_statement_upload/check_your_means_answers.feature
  features/providers/partner_means_assessment/means_report.feature
  features/step_definitions/means_report_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/means_reports_controller_spec.rb
  spec/services/reports/means_report_creator_spec.rb
Labels: UAT

#6145 AP-4706: remove task list classes
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/sort-transactions.scss
  app/views/providers/income_summary/_add_other_income.html.erb
  app/views/providers/income_summary/index.html.erb
  app/views/providers/outgoings_summary/_add_other_outgoings.html.erb
  app/views/providers/outgoings_summary/_outgoing_type_item.html.erb
  app/views/providers/outgoings_summary/index.html.erb
  app/views/shared/_transaction_type_item.html.erb
  app/views/shared/_transactions_summary.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  spec/requests/providers/income_summary_controller_spec.rb
  spec/requests/providers/outgoings_summary_controller_spec.rb
  spec/requests/providers/transactions_controller_spec.rb
Labels: ready for review

#6196 Chore: Re-enable staging environment
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: ready for review

#6187 AP-4694: SAML login sequence change
  app/controllers/saml_sessions_controller.rb
  app/views/providers/start/index.html.erb
  features/providers/cookies.feature
  features/providers/mock_saml.feature
  features/providers/non_means_tested_journey/under_18_application_journey.feature
  features/providers/non_means_tested_journey/with_delegated_functions.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/search_applications.feature
  features/providers/search_proceedings.feature
  features/step_definitions/civil_journey_steps.rb
  features/step_definitions/cookie_steps.rb
  spec/requests/saml_sessions_spec.rb
Labels: ready for review

#6214 Chore: Update modsec ip deny list
  helm_deploy/apply-for-legal-aid/values-production.yaml
Labels: ready for review

#6229 Chore: Remove Rails Secret deprecation warning
  config/initializers/devise.rb
Labels: ready for review

#6238 AP-4327: Partner means fixes
  app/models/cfe/v6/result.rb
  app/services/flow/flows/provider_income.rb
  config/locales/en/shared.yml
  spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
Labels: ready for review

#6239 Fix: remove duplicate DocumentIdRequestor call
  app/services/ccms/submitters/obtain_document_id_service.rb
Labels: ready for review

#6230 ap-4732: some rubocop fixes
  .rubocop_todo.yml
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/services/ccms/submitters/upload_documents_service_spec.rb
  spec/services/reports/merits_report_creator_spec.rb
Labels: approved

#6237 AP-4465: Order banks alphabetically on view
  app/controllers/citizens/banks_controller.rb
  app/views/citizens/banks/index.html.erb
Labels: ready for review

#6256 AP-3151: Update clamav to latest version
  helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
Labels: approved

#6262 Chore: add *bundling-rails dependabot group
  .github/dependabot.yml
Labels: ready for review

#6253 AP-4735: Update hint text on address lookup page
  app/views/providers/address_lookups/show.html.erb
  config/locales/en/providers.yml
Labels: approved

#6273 AP-4758: Enable HMRC service environment toggling
  app/controllers/admin/settings_controller.rb
  app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  app/views/providers/means/full_employment_details/show.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/locales/en/admin.yml
  config/locales/en/shared.yml
  db/migrate/20240124161717_add_collect_hmrc_data_to_settings.rb
  db/schema.rb
  features/providers/check_multiple_employment.feature
  features/providers/check_pending_employment.feature
  features/providers/employed_journey.feature
  features/providers/partner_means_assessment/means_check.feature
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/models/setting_spec.rb
  spec/requests/admin/settings_controller_spec.rb
  spec/requests/providers/confirm_dwp_non_passported_applications_controller_spec.rb
  spec/requests/providers/means/full_employment_details_controller_spec.rb
Labels: approved

#6274 AP-4759: Update partner means
  app/models/cfe/submission.rb
  app/services/cfe_civil/component_list.rb
  app/views/providers/means/check_income_answers/_applicant_income_assessment.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_income_details.html.erb
  spec/services/cfe_civil/component_list_spec.rb
Labels: ready for review

#6285 AP-4695: Update start page content
  app/views/providers/start/index.html.erb
  config/locales/cy/generic.yml
  config/locales/en/generic.yml
  config/locales/en/providers.yml
  features/providers/applicant_under_16_blocked.feature
  features/providers/cookies.feature
  features/providers/non_means_tested_journey/under_18_application_journey.feature
  features/providers/non_means_tested_journey/with_delegated_functions.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/search_applications.feature
  features/providers/search_proceedings.feature
  features/step_definitions/civil_journey_steps.rb
  features/step_definitions/cookie_steps.rb
Labels: approved

#6291 Chore: Update github action versions
  .github/workflows/anonymise_check.yml
  .github/workflows/base-docker-image.yml
  .github/workflows/ci-docker-image.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/delete-uat-release.yml
Labels: ready for review
