Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2024-05, with the labels that each got.

#6611 ap-4678: flow refactoring proceeding loop
  app/services/flow/flows/provider_proceeding_loop.rb
  app/services/flow/steps/provider_proceeding_loop/client_involvement_type_step.rb
  app/services/flow/steps/provider_proceeding_loop/confirm_delegated_functions_date_step.rb
  app/services/flow/steps/provider_proceeding_loop/delegated_functions_step.rb
  app/services/flow/steps/provider_proceeding_loop/emergency_defaults_step.rb
  app/services/flow/steps/provider_proceeding_loop/emergency_level_of_service_step.rb
  app/services/flow/steps/provider_proceeding_loop/emergency_scope_limitations_step.rb
  app/services/flow/steps/provider_proceeding_loop/final_hearings_step.rb
  app/services/flow/steps/provider_proceeding_loop/substantive_defaults_step.rb
  app/services/flow/steps/provider_proceeding_loop/substantive_level_of_service_step.rb
  app/services/flow/steps/provider_proceeding_loop/substantive_scope_limitations_step.rb
  spec/cassettes/EmergencyLevelOfServiceController/POST_/providers/applications/_legal_aid_application_id/emergency_level_of_service/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/redirects_to_emergency_scope_limitation_page.yml
  spec/cassettes/EmergencyLevelOfServiceController/POST_/providers/applications/_legal_aid_application_id/emergency_level_of_service/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/redirects_to_the_next_page.yml
  spec/requests/providers/proceeding_loop/client_involvement_type_controller_spec.rb
  spec/requests/providers/proceeding_loop/emergency_level_of_service_controller_spec.rb
  spec/requests/providers/proceeding_loop/emergency_scope_limitations_controller_spec.rb
  spec/requests/providers/proceeding_loop/substantive_scope_limitations_controller_spec.rb
  spec/services/flow/steps/provider_proceeding_loop/client_involvement_type_step_spec.rb
  spec/services/flow/steps/provider_proceeding_loop/confirm_delegated_functions_date_step_spec.rb
  spec/services/flow/steps/provider_proceeding_loop/delegated_functions_step_spec.rb
  spec/services/flow/steps/provider_proceeding_loop/emergency_defaults_step_spec.rb
  spec/services/flow/steps/provider_proceeding_loop/emergency_level_of_service_step_spec.rb
  spec/services/flow/steps/provider_proceeding_loop/emergency_scope_limitations_step_spec.rb
  spec/services/flow/steps/provider_proceeding_loop/final_hearings_step_spec.rb
  spec/services/flow/steps/provider_proceeding_loop/substantive_defaults_step_spec.rb
  spec/services/flow/steps/provider_proceeding_loop/substantive_level_of_service_step_spec.rb
  spec/services/flow/steps/provider_proceeding_loop/substantive_scope_limitations_step_spec.rb
Labels: UAT

#6627 Fix: Flickering test
  spec/requests/citizens/check_answers_spec.rb
Labels: ready for review

#6630 AP-4919: Update start page with linking type available
  app/views/providers/start/index.html.erb
  config/locales/en/providers.yml
Labels: approved, Ready to merge

#6628 ap-4941: add linked applications to ccms payload
  app/services/ccms/requestors/case_add_requestor.rb
  spec/data/ccms/case_add_request.xml
  spec/data/ccms/case_add_request_with_surname_at_birth.xml
  spec/data/ccms/df_case_add_request.xml
  spec/data/ccms/non_default_client_involvement_type.xml
  spec/services/ccms/requestors/case_add_requestor_spec.rb
Labels: ready for review

#6620 AP-4601: Update CYA page with link and copy sections
  app/controllers/providers/check_provider_answers_controller.rb
  app/forms/providers/link_application/copy_form.rb
  app/forms/providers/link_application/make_link_form.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/steps/linked_applications/confirm_link_step.rb
  app/services/flow/steps/linked_applications/copy_step.rb
  app/services/flow/steps/linked_applications/make_link_step.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/check_provider_answers/_standard.html.erb
  app/views/shared/check_answers/_proceeding_details.html.erb
  config/locales/en/providers.yml
  features/cassettes/Checking_answers_for_linked_and_copied_cases/If_I_change_the_copied_from_Yes_to_No.yml
  features/cassettes/Checking_answers_for_linked_and_copied_cases/If_I_change_the_linked_from_Family_to_No.yml
  features/providers/linked_applications/check_your_answers_link_and_copy.feature
  features/providers/linked_applications/check_your_answers_link_only.feature
  features/providers/linked_applications/check_your_answers_not_linked.feature
  features/step_definitions/linked_cases_steps.rb
  spec/forms/providers/link_application/copy_form_spec.rb
  spec/forms/providers/link_application/make_link_form_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/link_application/make_links_controller_spec.rb
  spec/services/flow/steps/linked_applications/confirm_link_step_spec.rb
  spec/services/flow/steps/linked_applications/copy_step_spec.rb
  spec/services/flow/steps/linked_applications/make_link_step_spec.rb
Labels: Ready to merge

#6642 Ap 4991 update linked applications helper for discarded applications
  app/helpers/linked_applications_helper.rb
  app/views/providers/link_application/confirm_links/show.html.erb
  spec/helpers/linked_applications_helper_spec.rb
Labels: UAT

#6661 Fix: Flickery linked Application proceeding test
  spec/models/legal_aid_application_spec.rb
Labels: ready for review

#6669 Chore: Add csv gem to remove deprecation warning
  Gemfile
  Gemfile.lock
Labels: ready for review

#6612 AP-4577: Add merits to cloner service
  Gemfile
  Gemfile.lock
  app/services/copy_case/cloner_service.rb
  spec/factories/legal_aid_applications.rb
  spec/factories/specific_issue.rb
  spec/factories/urgency.rb
  spec/services/copy_case/cloner_service_spec.rb
Labels: approved

#6660 Ap 4666 citizen start flow refactor
  app/services/flow/flows/citizen_start.rb
  app/services/flow/steps/citizen_start/accounts_step.rb
  app/services/flow/steps/citizen_start/additional_accounts_step.rb
  app/services/flow/steps/citizen_start/banks_step.rb
  app/services/flow/steps/citizen_start/consents_step.rb
  app/services/flow/steps/citizen_start/contact_provider_step.rb
  app/services/flow/steps/citizen_start/gather_transactions_step.rb
  app/services/flow/steps/citizen_start/legal_aid_applications_step.rb
  app/services/flow/steps/citizen_start/true_layer_step.rb
  spec/requests/citizens/banks_controller_spec.rb
  spec/requests/citizens/consents_controller_spec.rb
  spec/services/flow/steps/citizen_start/accounts_step_spec.rb
  spec/services/flow/steps/citizen_start/additional_accounts_step_spec.rb
  spec/services/flow/steps/citizen_start/banks_step_spec.rb
  spec/services/flow/steps/citizen_start/consents_step_spec.rb
  spec/services/flow/steps/citizen_start/contact_provider_step_spec.rb
  spec/services/flow/steps/citizen_start/gather_transactions_step_spec.rb
  spec/services/flow/steps/citizen_start/legal_aid_applications_step_spec.rb
  spec/services/flow/steps/citizen_start/true_layer_step_spec.rb
Labels: approved

#6655 AP-4992: Update linking case back button handling
  app/controllers/providers/link_application/confirm_links_controller.rb
  app/forms/providers/link_application/confirm_link_form.rb
  app/forms/providers/link_application/make_link_form.rb
  app/services/flow/flows/provider_start.rb
  app/services/flow/steps/linked_applications/confirm_link_step.rb
  app/services/flow/steps/linked_applications/find_link_step.rb
  app/services/flow/steps/linked_applications/make_link_step.rb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/providers/link_application/confirm_links/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  db/migrate/20240510114941_add_confirm_link_to_linked_application.rb
  db/schema.rb
  features/cassettes/Linking_cases_back_button_use/Complete_flow_reversion_with_back_button.yml
  features/providers/linked_applications/back_button.feature
  features/step_definitions/linked_cases_steps.rb
  spec/forms/providers/link_application/confirm_link_form_spec.rb
  spec/forms/providers/link_application/make_link_form_spec.rb
  spec/requests/providers/link_application/confirm_links_controller_spec.rb
  spec/requests/providers/link_application/find_link_applications_controller_spec.rb
  spec/requests/providers/link_application/make_links_controller_spec.rb
  spec/services/flow/steps/linked_applications/confirm_link_step_spec.rb
  spec/services/flow/steps/linked_applications/find_link_step_spec.rb
  spec/services/flow/steps/linked_applications/make_link_step_spec.rb
Labels: Ready to merge

#6662 AP-4665: Flow refactoring - citizen_end flow
  app/services/flow/flows/citizen_end.rb
  app/services/flow/steps/citizen_end/check_answers_step.rb
  app/services/flow/steps/citizen_end/means_test_results_step.rb
  spec/services/flow/steps/citizen_end/check_answers_step_spec.rb
  spec/services/flow/steps/citizen_end/means_test_results_step_spec.rb
Labels: ready for review

#6671 AP-5005: Implement cloner service
  app/controllers/providers/check_provider_answers_controller.rb
  db/migrate/20240514091845_rename_link_case_to_case_cloned_on_legal_aid_application.rb
  db/schema.rb
  features/step_definitions/linked_cases_steps.rb
  spec/requests/providers/check_provider_answers_controller_spec.rb
Labels: ready for review

#6663 AP-4670-flow-refactoring-provider-dependants
  app/services/flow/flows/provider_dependants.rb
  app/services/flow/steps/provider_dependants/dependants_step.rb
  app/services/flow/steps/provider_dependants/has_dependants_step.rb
  app/services/flow/steps/provider_dependants/has_other_dependants_step.rb
  app/services/flow/steps/provider_dependants/remove_dependants_step.rb
  spec/requests/providers/means/dependants_controller_spec.rb
  spec/requests/providers/means/has_dependants_controller_spec.rb
  spec/requests/providers/means/has_other_dependants_controller_spec.rb
  spec/requests/providers/means/remove_dependants_controller_spec.rb
  spec/services/flow/steps/provider_dependants/dependants_step_spec.rb
  spec/services/flow/steps/provider_dependants/has_dependants_step_spec.rb
  spec/services/flow/steps/provider_dependants/has_other_dependants_step_spec.rb
  spec/services/flow/steps/provider_dependants/remove_dependants_step_spec.rb
Labels: Ready to merge

#6692 AP-5028: Add SCA feature flag
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  db/migrate/20240517110634_add_sca_to_settings.rb
  db/schema.rb
  spec/models/setting_spec.rb
  spec/requests/admin/settings_controller_spec.rb
Labels: approved

#6683 ap-5023: add merits task list to cloner service
  app/helpers/task_list_helper.rb
  app/services/copy_case/cloner_service.rb
  spec/helpers/task_list_helper_spec.rb
  spec/services/copy_case/cloner_service_spec.rb
Labels: approved

#6717 AP-4673: refactor receives_state_benefits_step
  app/services/flow/flows/provider_means_state_benefits.rb
  app/services/flow/steps/provider_means_state_benefits/add_other_state_benefits_step.rb
  app/services/flow/steps/provider_means_state_benefits/receives_state_benefits_step.rb
  app/services/flow/steps/provider_means_state_benefits/state_benefits_step.rb
  spec/requests/providers/means/add_other_state_benefits_controller_spec.rb
  spec/requests/providers/means/receives_state_benefits_controller_spec.rb
  spec/requests/providers/means/state_benefits_controller_spec.rb
  spec/services/flow/steps/provider_means_state_benefits/add_other_state_benefits_step_spec.rb
  spec/services/flow/steps/provider_means_state_benefits/receives_state_benefits_step_spec.rb
  spec/services/flow/steps/provider_means_state_benefits/state_benefits_step_spec.rb
Labels: approved

#6718 Ap 4683 flow refactor proceedings and limitations
  app/services/flow/flows/provider_start.rb
  app/services/flow/steps/provider_start/has_other_proceedings_step.rb
  app/services/flow/steps/provider_start/limitations_step.rb
  app/services/flow/steps/provider_start/proceedings_types_step.rb
  spec/requests/providers/limitations_controller_spec.rb
  spec/requests/providers/proceedings_types_controller_spec.rb
  spec/services/flow/steps/provider_start/has_other_proceedings_step_spec.rb
  spec/services/flow/steps/provider_start/limitations_step_spec.rb
  spec/services/flow/steps/provider_start/proceedings_types_step_spec.rb
Labels: Ready to merge

#6722 AP-5047: Updating ProceedingTypes all service
  app/javascript/src/modules/proceedings.js
  app/services/legal_framework/proceeding_types/all.rb
  spec/services/legal_framework/proceeding_types/all_spec.rb
Labels: ready for review

#6730 AP-4625: Update client_involvement_types_all
  app/services/legal_framework/client_involvement_types/all.rb
  features/providers/applicant_details.feature
  features/providers/applicant_under_16_blocked.feature
  features/providers/check_provider_answers.feature
  features/providers/cost_override.feature
  features/providers/linked_applications/check_your_answers_link_and_copy.feature
  features/providers/no_nino_flow.feature
  features/providers/non_means_tested_journey/under_18_application_journey.feature
  features/providers/non_means_tested_journey/with_delegated_functions.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/pathways_from_check_your_answers.feature
  features/providers/regressions/scope_limitations.feature
  spec/cassettes/LegalFramework_ClientInvolvementTypes_All/_call/returns_the_expected_number_of_results.yml
  spec/cassettes/lfa_client_involvement_types_all.yml
  spec/services/legal_framework/client_involvement_types/all_spec.rb
Labels: ready for review

#6723 AP-4676: Flow refactoring of provider_merits
  app/services/flow/flows/provider_merits.rb
  app/services/flow/steps/provider_merits/attempts_to_settle_step.rb
  app/services/flow/steps/provider_merits/chances_of_success_step.rb
  app/services/flow/steps/provider_merits/linked_children_step.rb
  app/services/flow/steps/provider_merits/prohibited_steps_step.rb
  app/services/flow/steps/provider_merits/specific_issue_step.rb
  app/services/flow/steps/provider_merits/success_prospects_step.rb
  app/services/flow/steps/provider_merits/vary_order_step.rb
  spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
  spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
  spec/requests/providers/proceeding_merits_task/prohibited_steps_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/specific_issue_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb
  spec/services/flow/steps/provider_merits/attempts_to_settle_step_spec.rb
  spec/services/flow/steps/provider_merits/chances_of_success_step_spec.rb
  spec/services/flow/steps/provider_merits/linked_children_step_spec.rb
  spec/services/flow/steps/provider_merits/prohibited_steps_step_spec.rb
  spec/services/flow/steps/provider_merits/specific_issue_step_spec.rb
  spec/services/flow/steps/provider_merits/success_prospects_step_spec.rb
  spec/services/flow/steps/provider_merits/vary_order_step_spec.rb
Labels: approved

#6729 AP-4675: Flow refactoring - provider_merits
  app/services/flow/flows/provider_merits.rb
  app/services/flow/steps/provider_merits/has_other_involved_children_step.rb
  app/services/flow/steps/provider_merits/in_scope_of_laspos_step.rb
  app/services/flow/steps/provider_merits/involved_children_step.rb
  app/services/flow/steps/provider_merits/matter_opposed_reasons_step.rb
  app/services/flow/steps/provider_merits/nature_of_urgencies_step.rb
  app/services/flow/steps/provider_merits/start_involved_children_task_step.rb
  spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
  spec/requests/providers/application_merits_task/involved_children_spec.rb
  spec/requests/providers/application_merits_task/matter_opposed_reasons_controller_spec.rb
  spec/services/flow/steps/provider_merits/has_other_involved_children_step_spec.rb
  spec/services/flow/steps/provider_merits/in_scope_of_laspos_step_spec.rb
  spec/services/flow/steps/provider_merits/involved_children_step_spec.rb
  spec/services/flow/steps/provider_merits/matter_opposed_reasons_step_spec.rb
  spec/services/flow/steps/provider_merits/nature_of_urgencies_step_spec.rb
  spec/services/flow/steps/provider_merits/start_involved_children_task_step_spec.rb
Labels: approved

#6745 Chore: Update docker scan action
  .github/workflows/docker-image-scan.yml
Labels: ready for review
