Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2024-02, with the labels that each got.

#6295 AP-4431: Add association between change button and context
  app/views/providers/about_the_financial_assessments/show.html.erb
  app/views/providers/check_provider_answers/_shared.html.erb
  app/views/shared/check_answers/_client_details.html.erb
  app/views/shared/check_answers/_proceeding_details.html.erb
  config/locales/en/shared.yml
Labels: UAT, approved

#6325 Fix: Flickering SAML tests
  spec/requests/saml_sessions_spec.rb
Labels: ready for review

#6324 AP-4782: Add surname at birth to ccms payloads
  app/models/applicant.rb
  app/services/ccms/requestors/applicant_add_requestor.rb
  app/services/ccms/requestors/applicant_search_requestor.rb
  app/services/ccms/requestors/case_add_requestor.rb
  config/ccms/attribute_block_configs/base.yml
  spec/data/ccms/case_add_request_with_surname_at_birth.xml
  spec/models/applicant_spec.rb
  spec/services/ccms/requestors/applicant_add_requestor_spec.rb
  spec/services/ccms/requestors/applicant_search_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/support/file_helpers.rb
Labels: ready for review

#6350 Fix: update DotEnv
  Gemfile
  Gemfile.lock
Labels: ready for review

#6340 AP-4767: Use faraday for CCMS soap calls
  app/services/ccms/requestors/applicant_add_status_requestor.rb
  app/services/ccms/requestors/base_requestor.rb
  app/services/ccms/requestors/case_add_status_requestor.rb
  app/services/ccms/requestors/document_id_requestor.rb
  app/services/ccms/requestors/document_upload_requestor.rb
  app/services/ccms/requestors/reference_data_requestor.rb
  app/services/ccms/submitters/base_submission_service.rb
  spec/services/ccms/requestors/applicant_add_status_requestor_spec.rb
  spec/services/ccms/requestors/case_add_status_requestor_spec.rb
  spec/services/ccms/requestors/document_id_requestor_spec.rb
  spec/services/ccms/requestors/document_upload_requestor_spec.rb
  spec/services/ccms/requestors/reference_data_requestor_spec.rb
  spec/services/ccms/submitters/add_applicant_service_spec.rb
  spec/services/ccms/submitters/add_case_service_spec.rb
  spec/services/ccms/submitters/check_applicant_status_service_spec.rb
  spec/services/ccms/submitters/check_case_status_service_spec.rb
  spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
  spec/services/ccms/submitters/obtain_case_reference_service_spec.rb
  spec/services/ccms/submitters/obtain_document_id_service_spec.rb
  spec/services/ccms/submitters/upload_documents_service_spec.rb
Labels: Ready to merge

#6337 AP-4789: Update client correspondence address
  app/forms/base_address_form.rb
  app/views/providers/addresses/show.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/routes.rb
  spec/forms/addresses/address_form_spec.rb
Labels: ready for review

#6344 AP-4771: replace benefit checker savon calls
  app/services/benefit_check_service.rb
  app/services/faraday/soap_call.rb
  spec/cassettes/benefit_check_service/service_error.yml
  spec/services/benefit_check_service_spec.rb
Labels: ready for review

#6357 AP-4772: Remove savon gem
  Gemfile
  Gemfile.lock
  app/controllers/concerns/flowable.rb
  spec/cassettes/benefit_check_service/savon_successful_call.yml
  spec/cassettes/benefit_check_service/successful_call.yml
  spec/services/benefit_check_service_spec.rb
  spec/services/faraday/soap_call_spec.rb
Labels: ready for review

#6366 Fix: K8s deploy alerts
  helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-metrics.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
  helm_deploy/apply-for-legal-aid/templates/deployment_metrics.yaml
  helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
  helm_deploy/apply-for-legal-aid/templates/deployment_worker.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: ready for review

#6358 AP-4788: Add home address feature flag
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/views/admin/settings/show.html.erb
  config/locales/en/admin.yml
  db/migrate/20240214160228_add_home_address_to_settings.rb
  db/schema.rb
  spec/models/setting_spec.rb
  spec/requests/admin/settings_controller_spec.rb
Labels: approved

#6377 AP-4821: Fix client relationship ccms values
  app/models/dependant.rb
  spec/models/dependant_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
Labels: ready for review

#6398 fix: amend typo in address test
  spec/forms/addresses/address_form_spec.rb
Labels: ready for review

#6378 AP-4800: Postcode finder search results for correspondence
  app/controllers/concerns/address_handling.rb
  app/controllers/providers/address_selections_controller.rb
  app/forms/addresses/address_form.rb
  app/forms/base_address_form.rb
  app/views/providers/address_selections/show.html.erb
  app/views/shared/address_selection/_confirm_address.html.erb
  app/views/shared/address_selection/_no_address.html.erb
  app/views/shared/address_selection/_select_address.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  features/cassettes/Applicant_details/Completes_the_application_using_address_lookup_with_building_number_name.yml
  features/cassettes/Using_the_back_button_on_proceedings_should_not_lock_a_user_out/When_a_provider_is_adding_proceedings_and_uses_the_back_button_they_should_route_to_the_list_of_proceedings_first.yml
  features/providers/applicant_details.feature
  features/providers/applicant_under_16_blocked.feature
  features/providers/check_provider_answers.feature
  features/providers/copy_case.feature
  features/providers/cost_override.feature
  features/providers/link_case.feature
  features/providers/no_nino_flow.feature
  features/providers/non_means_tested_journey/under_18_application_journey.feature
  features/providers/non_means_tested_journey/with_delegated_functions.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/regressions/back_button_on_proceedings.feature
  features/providers/regressions/scope_limitations.feature
  features/providers/search_proceedings.feature
  features/step_definitions/civil_journey_steps.rb
  spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selection/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/and_a_building_number_has_been_added/so_only_one_address_is_remaining_after_filtering/renders_address_confirmation_page.yml
  spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selection/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/and_a_building_number_has_been_added/so_several_addresses_are_remaining_after_filtering/correctly_filters_the_addresses.yml
  spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selection/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/and_a_building_number_has_been_added/so_several_addresses_are_remaining_after_filtering/renders_address_selection_page.yml
  spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selection/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/but_the_lookup_does_not_return_any_valid_results/renders_the_address_selection_page.yml
  spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selection/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/performs_an_address_lookup_with_the_provided_postcode.yml
  spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selection/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/renders_the_address_selection_page.yml
  spec/factories/addresses.rb
  spec/forms/addresses/address_selection_form_spec.rb
  spec/requests/providers/address_selections_controller_spec.rb
Labels: ready for review

#6404 AP-4777: refactor list from translation path
  app/helpers/application_helper.rb
  app/views/privacy_policy/index.html.erb
  app/views/providers/capital_introductions/show.html.erb
  app/views/providers/client_completed_means/show.html.erb
  app/views/providers/confirm_client_declarations/show.html.erb
  app/views/providers/means/restrictions/show.html.erb
  app/views/providers/open_banking_guidances/show.html.erb
  app/views/shared/_transactions_summary.html.erb
  config/locales/cy/privacy_policy.yml
  config/locales/en/privacy_policy.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
Labels: approved

#6413 Fix: reduce Staging sentry alerts
  helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
  helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
  helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
Labels: ready for review, Discussion

#6416 AP-4834: Update content on client benefits page
  app/views/shared/means/_cost_of_living_and_disregarded_benefits.html.erb
  app/views/shared/means/_cost_of_living_details.html.erb
  app/views/shared/means/_cost_of_living_section.html.erb
  app/views/shared/means/_disregarded_benefits_section.html.erb
  config/locales/en/shared.yml
  features/providers/bank_statement_upload/happy_path_journey.feature
Labels: approved
