Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2024-08, with the labels that each got.

#6998 AP-5195: PDF generation bug fix
  config/initializers/grover.rb
Labels: ready for review

#6999 Chore: Merge dependabots
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: ready for review

#6971 AP-5154: Revisit SCA parental relationship CYA
  app/controllers/concerns/providers/draftable.rb
  app/controllers/providers/proceeding_merits_task/check_who_client_is_controller.rb
  app/controllers/providers/proceeding_merits_task/does_client_have_parental_responsibilities_controller.rb
  app/controllers/providers/proceeding_merits_task/is_client_biological_parent_controller.rb
  app/controllers/providers/proceeding_merits_task/is_client_child_subject_controller.rb
  app/models/concerns/base_state_machine.rb
  app/models/concerns/non_means_tested_state_machine.rb
  app/models/legal_aid_application.rb
  app/services/flow/steps/provider_merits/biological_parent_step.rb
  app/services/flow/steps/provider_merits/child_subject_step.rb
  app/services/flow/steps/provider_merits/parental_responsibilities_step.rb
  spec/concerns/non_means_tested_state_machine_spec.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/proceeding_merits_task/check_who_client_is_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/does_client_have_parental_responsibilities_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/is_client_biological_parent_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/is_client_child_subject_controller_spec.rb
  spec/services/flow/steps/provider_merits/biological_parent_step_spec.rb
  spec/services/flow/steps/provider_merits/child_subject_step_spec.rb
  spec/services/flow/steps/provider_merits/parental_responsibilities_step_spec.rb
Labels: ready for review

#7044 Chore: Prepare for Rails 7.2
  app/models/applicant.rb
  app/models/bank_transaction.rb
  app/models/dependant.rb
  app/models/feedback.rb
  app/models/final_hearing.rb
  app/models/legal_aid_application.rb
  app/models/proceeding_merits_task/chances_of_success.rb
  app/models/scope_limitation.rb
Labels: ready for review

#7055 Fix: State enums
  config/locales/en/enums.yml
Labels: ready for review

#7067 Chore: Update VCR to 6.3.1
  Gemfile
  Gemfile.lock
Labels: ready for review

#7073 AP-5233: Add proceeding inset text
  app/views/providers/has_other_proceedings/show.html.erb
  config/locales/en/providers.yml
Labels: UAT

#7059 AP-5235: SCA proceeding filter
  app/controllers/providers/proceedings_types_controller.rb
  app/services/legal_framework/proceeding_types/all.rb
  features/cassettes/Applicant_details/Allows_return_to_and_proceed_from_Delegated_Function_date_view.yml
  features/cassettes/Applicant_details/Completes_the_application_using_address_lookup.yml
  features/cassettes/Applicant_details/Completes_the_application_using_address_lookup_with_building_number_name.yml
  features/cassettes/Applicant_details/Completes_the_application_using_address_lookup_with_multiple_proceedings.yml
  features/cassettes/Applicant_details/Completes_the_application_using_manual_address.yml
  features/cassettes/Applicant_details/I_can_see_that_the_applicant_does_not_receive_benefits.yml
  features/cassettes/Applicant_details/I_can_see_that_the_applicant_receives_benefits.yml
  features/cassettes/Applicant_under_16_blocked/I_am_instructed_to_use_CCMS_when_applicant_was_under_16_on_earliest_delegated_function_date.yml
  features/cassettes/Checking_answers_for_linked_and_copied_cases/If_I_change_the_copied_from_Yes_to_No.yml
  features/cassettes/Checking_answers_for_linked_and_copied_cases/If_I_change_the_linked_from_Family_to_No.yml
  features/cassettes/Checking_client_details_answers_backwards_and_forwards/I_want_to_change_the_proceeding_type_from_the_check_your_answers_page.yml
  features/cassettes/Choosing_full_representation_level_of_service_in_proceeding_loop/When_the_provider_changes_the_level_of_service_to_full_representation_from_the_default.yml
  features/cassettes/Copy_a_case_s_applicable_details/I_choose_not_to_copy_another_case_s_details.yml
  features/cassettes/Create_application/Allows_return_to_and_proceed_from_Delegated_Function_date_view.yml
  features/cassettes/Create_application/Completes_the_application_using_address_lookup.yml
  features/cassettes/Create_application/Completes_the_application_using_address_lookup_with_multiple_proceedings.yml
  features/cassettes/Create_application/Completes_the_application_using_manual_address.yml
  features/cassettes/Create_application/I_am_instructed_to_use_CCMS_on_the_passported_journey_with_an_applicant_does_not_receive_benefits.yml
  features/cassettes/Create_application/I_can_see_that_the_applicant_does_not_receive_benefits.yml
  features/cassettes/Create_application/I_can_see_that_the_applicant_receives_benefits.yml
  features/cassettes/Emergency_cost_override/Provider_is_prompted_to_override_emergency_cost_limitation.yml
  features/cassettes/Linking_cases_back_button_use/Complete_flow_reversion_with_back_button.yml
  features/cassettes/Linking_one_application_to_another_application/I_choose_not_to_link_another_case_s_details.yml
  features/cassettes/No_national_insurance_number_for_applicant/I_can_see_that_the_applicant_receives_benefits.yml
  features/cassettes/Non-means-tested_applicant_journey_with_use_of_delegation_functions/Completes_a_minimal_application_for_applicant_that_was_under_18_at_time_of_earliest_delegated_function.yml
  features/cassettes/Non-means-tested_applicant_journey_without_use_of_delegation_functions/Completes_an_application_for_applicant_that_is_under_18.yml
  features/cassettes/Pathways_from_check_your_answers/I_go_back_and_change_the_proceedings_on_an_application_with_multiple_proceedings.yml
  features/cassettes/Scope_limitations_not_being_set/When_a_provider_creates_an_application_with_multiple_proceedings_and_uses_the_back_button_scope_limitations_should_not_be_removed.yml
  features/cassettes/Search_proceedings/I_am_able_to_clear_proceeding_on_the_proceeding_page.yml
  features/cassettes/Search_proceedings/No_results_returned_is_seen_on_screen_when_invalid_proceeding_search_entered.yml
  features/cassettes/Under_18_applicant_journey/Completes_a_minimal_application_for_applicant_that_is_under_18.yml
  features/cassettes/Using_the_back_button_on_proceedings_should_not_lock_a_user_out/When_a_provider_is_adding_proceedings_and_uses_the_back_button_they_should_route_to_the_list_of_proceedings_first.yml
  features/cassettes/partner_means_assessment_with_a_different_address/I_am_able_to_add_a_partner_with_a_different_address_from_the_applicant.yml
  features/cassettes/partner_means_assessment_with_a_shared_address/I_am_able_to_add_a_partner_with_an_address_shared_with_the_applicant.yml
  features/cassettes/partner_means_assessment_with_an_unknown_address/I_am_able_to_add_a_partner_with_a_different_address_from_the_applicant.yml
  spec/cassettes/Backable/back_path/has_a_back_link_to_the_previous_page.yml
  spec/cassettes/Backable/back_path/when_we_go_back_once/has_a_link_to_the_previous_page.yml
  spec/cassettes/Backable/back_path/when_we_go_back_once/redirects_to_same_page_without_the_param.yml
  spec/cassettes/Backable/back_path/when_we_reload_the_current_page_several_times/has_a_back_link_to_the_previous_page.yml
  spec/cassettes/Providers_ApplicationDependable/GET_an_action/when_the_provider_is_authenticated/records_the_current_controller_name.yml
  spec/cassettes/Providers_ApplicationDependable/GET_an_action/when_the_provider_is_authenticated/returns_http_success.yml
  spec/cassettes/Providers_CheckProviderAnswersController/POST_/providers/applications/_legal_aid_application_id/check_provider_answers/reset/when_the_provider_is_authenticated/changes_the_stage_back_to_entering_applicant_details.yml
  spec/cassettes/Providers_CheckProviderAnswersController/POST_/providers/applications/_legal_aid_application_id/check_provider_answers/reset/when_the_provider_is_authenticated/redirects_back.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/displays_errors.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/renders_index.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/calls_the_add_proceeding_service.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/redirects_to_next_step.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/when_LegalFramework_ProceedingTypesService_call_returns_false/displays_errors.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/when_LegalFramework_ProceedingTypesService_call_returns_false/renders_index.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/when_the_applicant_s_address_used_address_lookup_service/redirects_to_the_address_lookup_page.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/when_the_applicant_s_address_used_manual_entry/redirects_to_the_manual_address_page_lookup_page.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/displays_no_errors.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/does_not_displays_the_proceeding_types.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/returns_http_success.yml
  spec/cassettes/SubstantiveDefaultsController/POST_/providers/applications/_legal_aid_application_id/substantive_defaults/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_the_application_is_a_Special_Childrens_Act_application/redirects_to_next_page.yml
  spec/requests/providers/proceedings_types_controller_spec.rb
  spec/services/legal_framework/proceeding_types/all_spec.rb
Labels: UAT

#7083 AP-5149: Update SCA proceeding questions to remove core
  app/views/providers/proceedings_sca/heard_as_alternatives/show.html.erb
  app/views/providers/proceedings_sca/heard_togethers/show.html.erb
  config/locales/en/providers.yml
  spec/requests/providers/proceedings_sca/heard_as_alternatives_controller_spec.rb
  spec/requests/providers/proceedings_sca/heard_togethers_controller_spec.rb
Labels: ready for review

#7072 Ap 5119 provider details api integration
  app/services/pda/compare_provider_details.rb
  app/services/pda/provider_details_creator.rb
  app/services/pda/provider_details_retriever.rb
  app/services/provider_details_creator.rb
  app/workers/compare_provider_details_worker.rb
  config/application.rb
  config/environments/test.rb
  config/initializers/inflections.rb
  features/support/vcr.rb
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/secret.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/cassettes/PDA_ProviderDetailsRetriever/_call/with_a_non_existent_user/returns_an_error.yml
  spec/cassettes/PDA_ProviderDetailsRetriever/_call/with_an_existing_user/returns_provider_details.yml
  spec/services/pda/compare_provider_details_spec.rb
  spec/services/pda/provider_details_creator_spec.rb
  spec/services/pda/provider_details_retriever_spec.rb
  spec/spec_helper.rb
  spec/workers/compare_provider_details_worker_spec.rb
Labels: ready for review, do not merge

#6956 Ap 5142 zero cost limits associated applications
  app/controllers/providers/limitations_controller.rb
  app/models/legal_aid_application.rb
  app/services/copy_case/cloner_service.rb
  app/views/providers/limitations/_cost_limits.html.erb
  app/views/providers/limitations/show.html.erb
  app/views/providers/proceedings_sca/supervision_orders/show.html.erb
  config/locales/en/providers.yml
  features/providers/linked_applications/check_your_answers_link_and_copy.feature
  spec/models/legal_aid_application_spec.rb
  spec/services/copy_case/cloner_service_spec.rb
Labels: ready for review

#7119 Chore: Update Rails to 7.1.4
  Gemfile.lock
  package.json
  spec/models/legal_aid_application_spec.rb
  yarn.lock
Labels: ready for review

#7120 AP-5273: SCA level of service fix
  app/forms/proceedings/substantive_defaults_form.rb
  app/views/shared/check_answers/_proceeding_details.html.erb
  config/locales/en/shared.yml
  spec/factories/proceedings.rb
  spec/forms/proceedings/substantive_defaults_form_spec.rb
Labels: UAT
