Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2025-06, with the labels that each got.

#7829 Fix: Inline styles for PDF generation
  app/controllers/concerns/grover_optionable.rb
  app/controllers/providers/means_reports_controller.rb
  app/controllers/providers/merits_reports_controller.rb
  app/services/reports/base_report_creator.rb
  spec/requests/providers/means_reports_controller_spec.rb
  spec/requests/providers/merits_reports_controller_spec.rb
Labels: approved

#7822 AP-6027: Change clamav image and move to its own deployment/service
  .env.sample
  app/services/malware_scanner.rb
  config/application.rb
  config/clamd.local.conf
  helm_deploy/apply-for-legal-aid/templates/_envs.tpl
  helm_deploy/apply-for-legal-aid/templates/configmap-clamav.yaml
  helm_deploy/apply-for-legal-aid/templates/deployment_clamav.yaml
  helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
  helm_deploy/apply-for-legal-aid/templates/pvc-clamav.yaml
  helm_deploy/apply-for-legal-aid/templates/service-clamav.yaml
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
Labels: approved

#7840 Documentation: For Clamav implementation
  README.md
  docs/clamav.md
Labels: ready for review

#7847 Chore: switch on whitelist for staging and production
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
Labels: ready for review

#7856 Fix: Flickering feature
  features/providers/proceeding_loop.feature
Labels: approved

#7831 AP-5519: Ensure consistent currency validation
  app/forms/providers/regular_transaction_form.rb
  app/helpers/transaction_type_helper.rb
  app/models/base_aggregated_cash_transaction.rb
  app/views/shared/check_answers/_benefits_income.html.erb
  app/views/shared/check_answers/_housing_benefit.html.erb
  features/providers/bank_statement_upload/check_your_means_answers.feature
  features/providers/check_your_answers.feature
  features/providers/partner_means_assessment/bank_statement_upload/check_your_means_answers.feature
  features/providers/regressions/client_truelayer_partner_bank_statements_check_means_answer.feature
  spec/helpers/transaction_type_helper_spec.rb
Labels: UAT, approved

#7846 AP-6060: updates to feedback
  app/controllers/feedback_controller.rb
  app/views/feedback/thanks.html.erb
  app/views/layouts/application.html.erb
  config/locales/cy/feedback.yml
  config/locales/en/feedback.yml
  features/citizens/citizens.feature
  features/providers/provider_feedback.feature
  features/step_definitions/generic_steps.rb
Labels: approved

#7830 AP-5958: Update service header
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/primary_navigation.scss
  app/helpers/application_helper.rb
  app/views/layouts/_header.html.erb
  app/views/layouts/_header_logo.html.erb
  app/views/layouts/_primary_navigation.html.erb
  app/views/layouts/application.html.erb
  spec/helpers/application_helper_spec.rb
  spec/requests/citizens/gather_transactions_spec.rb
Labels: approved
