Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2025-04, with the labels that each got.

#7699 AP-5775: Changing merits answers that require evidence - not handled
  app/controllers/concerns/providers/delete_attachments.rb
  app/controllers/providers/application_merits_task/court_order_copies_controller.rb
  app/controllers/providers/proceeding_merits_task/child_care_assessments_controller.rb
  app/views/providers/application_merits_task/court_order_copies/show.html.erb
  app/views/providers/proceeding_merits_task/child_care_assessments/show.html.erb
  config/locales/en/generic.yml
  spec/factories/attachments.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/application_merits_task/court_order_copies_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/child_care_assessments_controller_spec.rb
Labels: Ready to merge

#7728 AP-5881: update benefit check error handling
  app/controllers/errors_controller.rb
  app/controllers/providers/check_benefits_controller.rb
  app/views/errors/show/_benefit_checker_down.html.erb
  config/locales/cy/errors.yml
  config/locales/en/errors.yml
  spec/requests/errors_controller_spec.rb
  spec/requests/providers/check_benefits_controller_spec.rb
Labels: UAT, approved

#7722 AP-5914: Update MOJ Frontend npm package
  .github/dependabot.yml
  app/assets/stylesheets/_imports.scss
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/check-your-answers.scss
  app/assets/stylesheets/dropzone.scss
  app/assets/stylesheets/helpers.scss
  app/assets/stylesheets/language-switcher.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/pagination.scss
  app/assets/stylesheets/providers/legal_aid_applications.scss
  app/assets/stylesheets/providers/search_results.scss
  app/assets/stylesheets/sort-transactions.scss
  app/assets/stylesheets/table-sort.scss
  app/assets/stylesheets/tables.scss
  app/javascript/application.js
  package.json
  yarn.lock
Labels: ready for review, Discussion

#7741 AP-5627: Update UAT postgres bitnami
  helm_deploy/apply-for-legal-aid/Chart.lock
  helm_deploy/apply-for-legal-aid/Chart.yaml
  helm_deploy/apply-for-legal-aid/charts/postgresql-11.9.13.tgz
  helm_deploy/apply-for-legal-aid/charts/postgresql-16.6.3.tgz
Labels: approved

#7705 AP-5776 Fix bypassing evidence validation bug
  app/controllers/providers/application_merits_task/court_order_copies_controller.rb
  app/forms/providers/application_merits_task/plf_court_order_form.rb
  app/services/flow/steps/provider_merits/child_care_assessment_result_step.rb
  app/services/flow/steps/provider_merits/court_order_copies_step.rb
  features/providers/check_merits_answers.feature
  features/providers/public_law_family/merits_child_care_assessment_question_flow.feature
  features/support/steps_helper.rb
  spec/forms/providers/application_merits_task/plf_court_order_form_spec.rb
  spec/requests/providers/application_merits_task/court_order_copies_controller_spec.rb
  spec/services/flow/steps/provider_merits/child_care_assessment_result_step_spec.rb
  spec/services/flow/steps/provider_merits/court_order_copies_step_spec.rb
Labels: UAT, approved

#7754 AP-5646: Update two year digit handling
  app/forms/concerns/date_field_builder.rb
  spec/forms/partners/details_form_spec.rb
  spec/forms/proceedings/final_hearing_form_spec.rb
Labels: UAT

#7755 AP-5955: Fix employment status form
  app/forms/base_employed_form.rb
  app/views/shared/_employment_status.html.erb
  features/providers/applicant_details.feature
  features/providers/employment_status.feature
  features/step_definitions/civil_journey_steps.rb
  features/step_definitions/generic_steps.rb
  spec/forms/applicants/employed_form_spec.rb
  spec/forms/partners/employed_form_spec.rb
Labels: UAT, approved

#7743 AP-5430 Refactor income CYA page
  app/helpers/payments_summary_partial_url_helper.rb
  app/views/providers/means/check_income_answers/_applicant_income_assessment.html.erb
  app/views/providers/means/check_income_answers/_partner_income_assessment.html.erb
  app/views/providers/means/check_income_answers/show.html.erb
  app/views/shared/check_answers/_bank_statements.html.erb
  app/views/shared/check_answers/_benefits_income.html.erb
  app/views/shared/check_answers/_cash_payments.html.erb
  app/views/shared/check_answers/_employed_income.html.erb
  app/views/shared/check_answers/_full_employment_details.html.erb
  app/views/shared/check_answers/_housing_benefit.html.erb
  app/views/shared/check_answers/_payments_summary.html.erb
  app/views/shared/check_answers/_student_finance.html.erb
  app/views/shared/review_application/_partner_income.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/partner_means_assessment/review_and_print.feature
  spec/helpers/payments_summary_partial_url_helper_spec.rb
Labels: approved

#7757 Tidy: Refactor assessment results controllers
  app/controllers/providers/capital_assessment_results_controller.rb
  app/controllers/providers/capital_income_assessment_results_controller.rb
  app/controllers/providers/means_assessment_results_controller.rb
  spec/helpers/liquid_capital_items_helper_spec.rb
  spec/requests/providers/capital_assessment_results_controller_spec.rb
  spec/requests/providers/capital_income_assessment_results_controller_spec.rb
Labels: ready for review
