Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2025-05, with the labels that each got.

#7756 Chore: Update MOJ frontend package
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: ready for review

#7777 AP-5324: Remove public_law_family feature flag
  app/controllers/admin/settings_controller.rb
  app/forms/settings/setting_form.rb
  app/models/setting.rb
  app/services/legal_framework/proceeding_types/all.rb
  app/views/admin/settings/show.html.erb
  app/views/providers/start/index.html.erb
  config/locales/en/admin.yml
  config/locales/en/providers.yml
  features/cassettes/Loop_through_proceeding_questions/No_preselected_emergency_or_substantive_levels_of_service.yml
  features/cassettes/Loop_through_proceeding_questions/When_provider_accepts_default_levels_of_service.yml
  features/cassettes/Loop_through_proceeding_questions/When_provider_does_not_accept_default_levels_of_service.yml
  features/cassettes/Scope_limitations_not_being_set/When_a_provider_creates_an_application_with_multiple_proceedings_and_uses_the_back_button_scope_limitations_should_not_be_removed.yml
  features/providers/cost_override.feature
  features/providers/proceeding_loop.feature
  features/providers/regressions/back_button_on_proceedings.feature
  features/providers/special_children_act/secure_accomodation_order_cit.feature
  features/providers/start_page.feature
  features/step_definitions/civil_journey_steps.rb
  spec/models/setting_spec.rb
  spec/requests/admin/settings_controller_spec.rb
  spec/requests/providers/start_spec.rb
  spec/services/legal_framework/proceeding_types/all_spec.rb
Labels: UAT, approved

#7765 AP-5942: Amend caseworker review reasons content
  app/views/providers/means_reports/_caseworker_review.html.erb
  config/locales/en/providers.yml
  features/providers/means_report.feature
  features/providers/partner_means_assessment/means_report.feature
  features/step_definitions/means_report_steps.rb
  spec/factories/attachments.rb
  spec/factories/cfe_results/v6/mock_results.rb
  spec/factories/cfe_results/v6/results.rb
  spec/factories/legal_aid_applications.rb
Labels: approved

#7783 Fix: Broken feature test
  features/providers/regressions/scope_limitations.feature
Labels: ready for review

#7787 Chore: Bump ruby 3.4.2 to 3.4.3
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  app/views/layouts/application.html.erb
  config/environments/test.rb
  docker/apply_base.dockerfile
  docker/apply_ci.dockerfile
  features/step_definitions/civil_journey_steps.rb
  features/support/env.rb
Labels: ready for review

#7789 AP-5974: Remove FAM_PROSP_X attributes from NP CCMS payload
  app/services/ccms/attribute_value_generator.rb
  config/ccms/attribute_block_configs/non_passported.yml
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_chances_of_success_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/support/xml_attribute_block_matcher.rb
Labels: ready for review, UAT

#7782 AP-5970: Move nino question
  app/services/flow/steps/linked_applications/copy_step.rb
  app/services/flow/steps/provider_start/applicant_details_step.rb
  app/services/flow/steps/provider_start/applicants_step.rb
  app/services/flow/steps/provider_start/has_national_insurance_numbers_step.rb
  app/services/flow/steps/provider_start/limitations_step.rb
  app/views/shared/check_answers/_client_details.html.erb
  features/providers/applicant_details.feature
  features/providers/cost_override.feature
  features/providers/linked_applications/back_button.feature
  features/providers/no_nino_flow.feature
  features/providers/non_means_tested_journey/under_18_application_journey.feature
  features/providers/non_means_tested_journey/with_delegated_functions.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/proceeding_loop.feature
  features/providers/regressions/back_button_on_proceedings.feature
  features/providers/regressions/scope_limitations.feature
  features/providers/search_proceedings.feature
  features/providers/special_children_act/secure_accomodation_order_cit.feature
  lib/tasks/update_provider_step_to_nino_page.rake
  spec/requests/providers/concerns/providers/draftable_spec.rb
  spec/services/flow/steps/linked_applications/copy_step_spec.rb
  spec/services/flow/steps/provider_start/applicant_details_step_spec.rb
  spec/services/flow/steps/provider_start/applicants_step_spec.rb
  spec/services/flow/steps/provider_start/has_national_insurance_numbers_step_spec.rb
  spec/services/flow/steps/provider_start/limitations_step_spec.rb
Labels: approved, Ready to merge

#7814 Fix: fix flaky tests
  features/cassettes/Scope_limitations_not_being_set/When_a_provider_creates_an_application_with_multiple_proceedings_and_uses_the_back_button_scope_limitations_should_not_be_removed.yml
  features/providers/regressions/scope_limitations.feature
  spec/helpers/transaction_type_helper_spec.rb
Labels: ready for review
