Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2025-02, with the labels that each got.

#7597 AP-5379: Update chances of success handling
  app/controllers/providers/proceeding_merits_task/chances_of_success_controller.rb
  app/controllers/providers/proceeding_merits_task/success_prospects_controller.rb
  app/forms/chances_of_successes/success_likely_form.rb
  app/forms/chances_of_successes/success_prospect_form.rb
  app/forms/providers/proceeding_merits_task/chances_of_success_form.rb
  app/models/proceeding_merits_task/chances_of_success.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/steps/provider_merits/chances_of_success_step.rb
  app/services/flow/steps/provider_merits/success_prospects_step.rb
  app/services/migration_helpers/state_changer.rb
  app/views/providers/proceeding_merits_task/chances_of_success/index.html.erb
  app/views/providers/proceeding_merits_task/chances_of_success/show.html.erb
  app/views/providers/proceeding_merits_task/success_prospects/show.html.erb
  app/views/shared/check_answers/merits/_merits_proceeding_section.html.erb
  config/locales/cy/activemodel.yml
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  features/providers/back_button.feature
  features/providers/check_ccms_autogrant.feature
  features/providers/check_multiple_employment.feature
  features/providers/check_nonpassport_autogrant.feature
  features/providers/check_pending_employment.feature
  features/providers/check_single_employment.feature
  features/providers/merits_task_list.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/passported_journey.feature
  features/providers/public_law_family/merits_child_care_assessment_question_flow.feature
  spec/forms/providers/proceeding_merits_task/chances_of_success_form_spec.rb
  spec/models/proceeding_merits_task/chances_of_success_spec.rb
  spec/requests/providers/check_merits_answers_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/chances_of_success_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb
  spec/requests/providers/proceeding_merits_task/vary_order_controller_spec.rb
  spec/services/flow/steps/provider_merits/chances_of_success_step_spec.rb
  spec/services/flow/steps/provider_merits/success_prospects_step_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
  spec/support/change_link_matcher.rb
Labels: approved

#7601 AP-5621: Remove fixed width of means report print style
  app/assets/stylesheets/print-styles.scss
Labels: approved

#7607 AP-5725: Update state change for linked cases
  app/controllers/providers/address_selections_base_controller.rb
  app/controllers/providers/correspondence_address/choices_controller.rb
  spec/requests/providers/correspondence_address/choices_controller_spec.rb
Labels: ready for review

#7598 AP-4415: PLF update evidence upload page
  .rubocop_todo.yml
  app/controllers/providers/uploaded_evidence_collections_controller.rb
  app/helpers/uploaded_evidence_helper.rb
  app/models/legal_aid_application.rb
  app/models/uploaded_evidence_collection.rb
  app/services/document_category_analyser.rb
  app/services/required_document_category_analyser.rb
  app/services/uploaded_evidence/base.rb
  app/services/uploaded_evidence/uploader_service.rb
  app/validators/document_category_validator.rb
  app/views/providers/uploaded_evidence_collections/_upload_evidence.html.erb
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  db/migrate/20250203164133_rename_required_document_categories_to_allowed_document_categories.rb
  db/schema.rb
  db/seeds/document_categories.csv
  features/providers/public_law_family/merits_child_care_assessment_question_flow.feature
  spec/helpers/uploaded_evidence_helper_spec.rb
  spec/models/document_category_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/uploaded_evidence_collection_spec.rb
  spec/services/ccms/requestors/document_id_requestor_spec.rb
  spec/services/ccms/requestors/document_upload_requestor_spec.rb
  spec/services/document_category_analyser_spec.rb
  spec/services/required_document_category_analyser_spec.rb
  spec/services/uploaded_evidence/list_service_spec.rb
  spec/services/uploaded_evidence/populate_upload_form_service_spec.rb
  spec/support/shared_examples/ccms_document_upload_request_generator_shared_examples.rb
Labels: approved, out of hours deploy required

#7615 AP-5742: Add avoid breaks css to merits report
  app/assets/stylesheets/print-styles.scss
  app/views/providers/merits_reports/_applied_previously.html.erb
  app/views/providers/merits_reports/_delegated_functions.html.erb
  app/views/providers/merits_reports/_proceeding_details.html.erb
  app/views/providers/merits_reports/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  config/locales/en/providers.yml
Labels: UAT, approved

#7614 AP-5428: CYA update for means report
  .erb_lint.yml
  .rubocop.yml
  app/views/providers/means_reports/_benefits_breakdown.html.erb
  app/views/providers/means_reports/_capital_result.html.erb
  app/views/providers/means_reports/_caseworker_review.html.erb
  app/views/providers/means_reports/_income_details.html.erb
  app/views/providers/means_reports/_income_result.html.erb
  app/views/providers/means_reports/_outgoings_and_deductions_details.html.erb
  app/views/providers/means_reports/_receives_benefits.html.erb
  app/views/providers/means_reports/_uploaded_bank_statements.html.erb
  app/views/providers/means_reports/_with_cfe_result_details.html.erb
  app/views/shared/check_answers/_benefits_breakdown.html.erb
  app/views/shared/check_answers/_capital_result.html.erb
  app/views/shared/check_answers/_client_details.html.erb
  app/views/shared/check_answers/_income_result.html.erb
  app/views/shared/means_report/_income_details.html.erb
  app/views/shared/means_report/_outgoings_and_deductions_details.html.erb
  config/locales/cy/shared.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/means_report.feature
  features/step_definitions/check_provider_answers_steps.rb
  features/step_definitions/means_report_steps.rb
Labels: UAT, approved

#7625 Fix: spec date timebomb
  spec/services/secure_application_finder_spec.rb
Labels: ready for review

#7624 AP-5585: Update LAA logo
  app/assets/images/crest.svg
  app/assets/images/laa_logo.svg
  app/assets/stylesheets/print-styles.scss
  app/views/layouts/application.html.erb
Labels: ready for review

#7579 AP-5583: CYA update - check capital answers - visual changes
  app/forms/vehicles/details_form.rb
  app/helpers/capital_helper.rb
  app/views/providers/check_capital_answers/show.html.erb
  app/views/providers/check_passported_answers/show.html.erb
  app/views/providers/means_reports/_capital_disregards.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_capital_disregard_details.html.erb
  app/views/shared/check_answers/_capital_disregards.html.erb
  app/views/shared/check_answers/_offline_savings_accounts.html.erb
  app/views/shared/check_answers/_one_link_section.html.erb
  app/views/shared/check_answers/_property.html.erb
  app/views/shared/check_answers/_restrictions.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  app/views/shared/review_application/_income_payments_and_assets.html.erb
  config/locales/cy/shared.yml
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/check_capital_answers.feature
  features/providers/check_your_answers.feature
  features/providers/complete_and_check_means_answers.feature
  features/providers/means_report.feature
  features/providers/merits_report.feature
  features/providers/mtr_accelerated/main_dwelling.feature
  features/providers/non_passported_journey/with_capital.feature
  features/providers/partner_means_assessment/means_report.feature
  features/providers/partner_means_assessment/review_and_print.feature
  features/providers/review_and_print.feature
  features/step_definitions/check_your_answers_steps.rb
  features/step_definitions/civil_journey_steps.rb
  features/step_definitions/generic_steps.rb
  features/step_definitions/means_report_steps.rb
  spec/helpers/capital_helper_spec.rb
  spec/requests/providers/check_capital_answers_controller_spec.rb
  spec/requests/providers/check_passported_answers_spec.rb
Labels: approved, Ready to merge

#7638 AP-5086: Error message boxes - full page width
  app/views/shared/page_templates/_basic_page_template.html.erb
  app/views/shared/page_templates/_default_page_template.html.erb
Labels: ready for review

#7634 AP-5796: Fix mismatched HTML tag
  app/views/providers/check_capital_answers/show.html.erb
  app/views/providers/check_passported_answers/show.html.erb
  app/views/providers/means/check_income_answers/show.html.erb
  features/providers/check_capital_answers.feature
Labels: ready for review

#7606 AP-5639: Add routing to ECCT for PLF Second Appeal cases
  app/models/application_digest.rb
  app/models/legal_aid_application.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/ccms/requestors/case_add_requestor.rb
  app/services/reports/mis/application_detail_csv_line.rb
  config/ccms/attribute_block_configs/base.yml
  config/ccms/attribute_block_configs/non_passported.yml
  db/migrate/20250217105318_add_ecct_routed_to_application_digest.rb
  db/schema.rb
  spec/factories/proceedings.rb
  spec/models/legal_aid_application_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
Labels: Ready to merge

#7648 Fix: correct width of child_care_assessment CYA section
  app/views/shared/check_answers/_child_care_assessment.html.erb
Labels: approved
