Repository ministryofjustice/laa-apply-for-legal-aid, pull requests merged in 2025-03, with the labels that each got.

#7647 AP-5812: Amend content for court_application_or_order evidence
  config/locales/en/activemodel.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
Labels: UAT, approved

#7651 AP-5792: Fix evidence category naming after delete
  app/controllers/providers/uploaded_evidence_collections_controller.rb
  app/services/uploaded_evidence/base.rb
  app/services/uploaded_evidence/deletion_service.rb
  app/services/uploaded_evidence/uploader_service.rb
  app/views/providers/uploaded_evidence_collections/_uploaded_files.html.erb
  spec/services/uploaded_evidence/base_spec.rb
  spec/services/uploaded_evidence/deletion_service_spec.rb
  spec/services/uploaded_evidence/list_service_spec.rb
  spec/services/uploaded_evidence/populate_upload_form_service_spec.rb
  spec/services/uploaded_evidence/shared_examples_for_uploaded_evidence.rb
Labels: UAT, approved

#7654 AP-5792: Fix failing shared expectation
  spec/services/uploaded_evidence/shared_examples_for_uploaded_evidence.rb
Labels: ready for review

#7643 AP-5580: Move parental responsibility merits question to application level
  app/controllers/providers/application_merits_task/client_check_parental_answers_controller.rb
  app/controllers/providers/application_merits_task/client_has_parental_responsibilities_controller.rb
  app/controllers/providers/application_merits_task/client_is_biological_parent_controller.rb
  app/controllers/providers/application_merits_task/client_is_child_subject_controller.rb
  app/forms/providers/application_merits_task/biological_parent_form.rb
  app/forms/providers/application_merits_task/child_subject_form.rb
  app/forms/providers/application_merits_task/parental_responsibilities_form.rb
  app/helpers/task_list_helper.rb
  app/models/legal_aid_application.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/merits_loop.rb
  app/services/flow/steps/provider_application_merits/child_is_subject_step.rb
  app/services/flow/steps/provider_application_merits/client_check_parental_answers_step.rb
  app/services/flow/steps/provider_application_merits/is_biological_parent_step.rb
  app/services/flow/steps/provider_application_merits/parental_responsibilities_step.rb
  app/views/providers/application_merits_task/client_check_parental_answers/show.html.erb
  app/views/providers/application_merits_task/client_has_parental_responsibilities/show.html.erb
  app/views/providers/application_merits_task/client_is_biological_parent/show.html.erb
  app/views/providers/application_merits_task/client_is_child_subject/show.html.erb
  app/views/shared/check_answers/_merits.html.erb
  app/views/shared/check_answers/_relationship_to_children.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/migrate/20250213135157_add_relationship_to_children_to_applicant.rb
  db/schema.rb
  lib/tasks/fixes/ap_5580.rake
  spec/factories/legal_framework_merits_task_list.rb
  spec/factories/legal_framework_serialized_merits_task_list.rb
  spec/forms/providers/application_merits_task/biological_parent_form_spec.rb
  spec/forms/providers/application_merits_task/child_subject_form_spec.rb
  spec/forms/providers/application_merits_task/parental_responsibilities_form_spec.rb
  spec/helpers/task_list_helper_spec.rb
  spec/lib/tasks/fixes/ap_5580_spec.rb
  spec/models/application_digest_spec.rb
  spec/models/legal_aid_application_spec.rb
  spec/requests/providers/application_merits_task/client_check_parental_answers_controller_spec.rb
  spec/requests/providers/application_merits_task/client_has_parental_responsibilities_controller_spec.rb
  spec/requests/providers/application_merits_task/client_is_biological_parent_controller_spec.rb
  spec/requests/providers/application_merits_task/client_is_child_subject_controller_spec.rb
  spec/services/ccms/requestors/special_children_act_case_add_requestor_spec.rb
  spec/services/flow/steps/provider_application_merits/child_is_subject_step_spec.rb
  spec/services/flow/steps/provider_application_merits/client_check_parental_answers_step_spec.rb
  spec/services/flow/steps/provider_application_merits/is_biological_parent_step_spec.rb
  spec/services/flow/steps/provider_application_merits/parental_responsibilities_step_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: approved

#7653 AP-5791(ext): New interrupt card pattern
  app/helpers/moj_components_helper.rb
  app/views/citizens/contact_providers/show.html.erb
  app/views/providers/change_of_names_interrupts/_actions.html.erb
  app/views/providers/change_of_names_interrupts/show.html.erb
  app/views/providers/check_benefits/_actions.html.erb
  app/views/providers/check_benefits/show.html.erb
  app/views/providers/confirm_non_means_tested_applications/_actions.html.erb
  app/views/providers/confirm_non_means_tested_applications/show.html.erb
  app/views/providers/interrupt/blocks/_actions.html.erb
  app/views/providers/interrupt/blocks/show.html.erb
  app/views/providers/no_national_insurance_numbers/_actions.html.erb
  app/views/providers/no_national_insurance_numbers/show.html.erb
  app/views/providers/proceedings_sca/interrupts/_actions.html.erb
  app/views/providers/proceedings_sca/interrupts/show.html.erb
  app/views/shared/_use_ccms.html.erb
  app/views/shared/_use_ccms_actions.html.erb
  app/views/shared/assessment_results/_capital_and_income_contribution_required.html.erb
  app/views/shared/assessment_results/_capital_contribution_required.html.erb
  app/views/shared/assessment_results/_eligible.html.erb
  app/views/shared/assessment_results/_income_contribution_required.html.erb
  app/views/shared/assessment_results/_ineligible.html.erb
  app/views/shared/assessment_results/_manual_check_required.html.erb
  app/views/shared/assessment_results/_no_cfe_result.html.erb
  app/views/shared/assessment_results/_partially_eligible_capital.html.erb
  app/views/shared/assessment_results/_partially_eligible_capital_income.html.erb
  app/views/shared/assessment_results/_partially_eligible_income.html.erb
  app/views/shared/moj_components_templates/_interruption_card_template.html.erb
  config/locales/en/providers.yml
  spec/helpers/moj_components_helper_spec.rb
  spec/requests/providers/interrupt/blocks_controller_spec.rb
  spec/requests/providers/proceedings_sca/interrupts_controller_spec.rb
Labels: UAT, approved

#7630 AP-5771: Amend feedback form
  app/controllers/feedback_controller.rb
  app/models/feedback.rb
  app/views/contacts/show.html.erb
  app/views/feedback/_form.html.erb
  app/views/feedback/new.cy.html.erb
  app/views/feedback/new.en.html.erb
  app/views/feedback/new.html.erb
  app/views/feedback/thanks.html.erb
  config/locales/cy/contacts.yml
  config/locales/cy/enums.yml
  config/locales/cy/feedback.yml
  config/locales/en/activerecord.yml
  config/locales/en/contacts.yml
  config/locales/en/enums.yml
  config/locales/en/feedback.yml
  config/locales/en/helpers.yml
  config/routes.rb
  db/anonymise/rules.rb
  db/migrate/20250217150948_add_questions_to_feedback.rb
  db/schema.rb
  features/citizens/citizens_welsh.feature
  features/providers/provider_feedback.feature
  features/step_definitions/generic_steps.rb
  features/support/hooks.rb
  spec/factories/feedbacks.rb
  spec/requests/contact_spec.rb
  spec/requests/errors_controller_spec.rb
  spec/requests/feedbacks_spec.rb
Labels: approved

#7629 AP-5753: Add print-no-break sections on means reports print page
  app/assets/stylesheets/print-styles.scss
  app/views/providers/means_reports/_benefits_breakdown.html.erb
  app/views/providers/means_reports/_capital_result.html.erb
  app/views/providers/means_reports/_caseworker_review.html.erb
  app/views/providers/means_reports/_income_details.html.erb
  app/views/providers/means_reports/_income_result.html.erb
  app/views/providers/means_reports/_outgoings_and_deductions_details.html.erb
  app/views/providers/means_reports/_proceeding_eligibility.html.erb
  app/views/providers/means_reports/_receives_benefits.html.erb
  app/views/providers/means_reports/_uploaded_bank_statements.html.erb
  app/views/providers/means_reports/_with_cfe_result_details.html.erb
  app/views/providers/means_reports/show.html.erb
  app/views/shared/_savings_and_investments.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_property.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
Labels: approved, Ready to merge

#7656 AP-5816: Update service name to add civil
  README.md
  config/locales/en/activerecord.yml
  config/locales/en/layouts.yml
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/back_button.feature
  features/providers/cookies.feature
  features/providers/start_page.feature
  features/step_definitions/cookie_steps.rb
  spec/requests/providers/legal_aid_applications_spec.rb
Labels: approved, Ready to merge

#7664 AP-5816: Fix test failures
  app/views/feedback/new.cy.html.erb
  app/views/feedback/new.en.html.erb
  features/citizens/citizens_welsh.feature
  features/providers/provider_feedback.feature
  spec/requests/feedbacks_spec.rb
Labels: approved

#7636 AP-5429: CYA update - review and print and submitted applications pages
  app/controllers/concerns/providers/transaction_type_settable.rb
  app/controllers/providers/means/check_income_answers_controller.rb
  app/controllers/providers/review_and_print_applications_controller.rb
  app/controllers/providers/submitted_applications_controller.rb
  app/views/providers/means/check_income_answers/_applicant_income_assessment.html.erb
  app/views/providers/means/check_income_answers/_partner_income_assessment.html.erb
  app/views/providers/means/check_income_answers/show.html.erb
  app/views/providers/means_reports/_capital_disregards.html.erb
  app/views/providers/review_and_print_applications/show.html.erb
  app/views/providers/submitted_applications/show.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_capital_disregard_details.html.erb
  app/views/shared/check_answers/_capital_disregards.html.erb
  app/views/shared/check_answers/_dependants.html.erb
  app/views/shared/check_answers/_housing_benefit.html.erb
  app/views/shared/check_answers/_offline_savings_accounts.html.erb
  app/views/shared/check_answers/_proceeding_details.html.erb
  app/views/shared/check_answers/_proceeding_details_section.html.erb
  app/views/shared/check_answers/_property.html.erb
  app/views/shared/check_answers/_restrictions.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  app/views/shared/review_application/_questions_and_answers.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  features/providers/bank_statement_upload/check_your_means_answers.feature
  features/providers/non_means_tested_journey/without_delegated_functions.feature
  features/providers/non_passported_journey/with_bank_transactions.feature
  features/providers/partner_means_assessment/bank_statement_upload/check_your_means_answers.feature
  features/providers/partner_means_assessment/review_and_print.feature
  features/providers/passported_journey.feature
  features/providers/review_and_print.feature
  features/step_definitions/review_and_print_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/requests/providers/submitted_applications_controller_spec.rb
Labels: approved

#7663 AP-5818: Update check_answers to use summary cards
  app/views/citizens/check_answers/_bank_accounts.html.erb
  app/views/citizens/check_answers/index.html.erb
  config/locales/cy/citizens.yml
  config/locales/en/citizens.yml
Labels: approved

#7644 AP-5580 part 2: remove proceeding parental responsibility questions
  app/controllers/providers/proceeding_merits_task/check_who_client_is_controller.rb
  app/controllers/providers/proceeding_merits_task/does_client_have_parental_responsibilities_controller.rb
  app/controllers/providers/proceeding_merits_task/is_client_biological_parent_controller.rb
  app/controllers/providers/proceeding_merits_task/is_client_child_subject_controller.rb
  app/forms/providers/proceeding_merits_task/biological_parent_form.rb
  app/forms/providers/proceeding_merits_task/child_subject_form.rb
  app/forms/providers/proceeding_merits_task/parental_responsibilities_form.rb
  app/helpers/task_list_helper.rb
  app/services/ccms/attribute_value_generator.rb
  app/services/document_category_analyser.rb
  app/services/flow/flows/provider_merits.rb
  app/services/flow/merits_loop.rb
  app/services/flow/steps/provider_merits/biological_parent_step.rb
  app/services/flow/steps/provider_merits/check_who_client_is_step.rb
  app/services/flow/steps/provider_merits/child_subject_step.rb
  app/services/flow/steps/provider_merits/parental_responsibilities_step.rb
  app/views/providers/merits_task_lists/show.html.erb
  app/views/providers/proceeding_merits_task/check_who_client_is/show.html.erb
  app/views/providers/proceeding_merits_task/does_client_have_parental_responsibilities/show.html.erb
  app/views/providers/proceeding_merits_task/is_client_biological_parent/show.html.erb
  app/views/providers/proceeding_merits_task/is_client_child_subject/show.html.erb
  app/views/shared/check_answers/_relationship_to_child.html.erb
  app/views/shared/check_answers/merits/_merits_proceeding_section.html.erb
  config/locales/en/providers.yml
  config/locales/en/shared.yml
  config/routes.rb
  db/migrate/20250305080311_remove_proceedings_child_relationship.rb
  db/schema.rb
  features/step_definitions/civil_journey_steps.rb
  lib/tasks/fixes/ap_5580.rake
  spec/forms/providers/proceeding_merits_task/biological_parent_form_spec.rb
  spec/forms/providers/proceeding_merits_task/child_subject_form_spec.rb
  spec/forms/providers/proceeding_merits_task/parental_responsibilities_form_spec.rb
  spec/helpers/task_list_helper_spec.rb
  spec/lib/tasks/fixes/ap_5580_spec.rb
  spec/requests/providers/proceeding_merits_task/check_who_client_is_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/does_client_have_parental_responsibilities_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/is_client_biological_parent_controller_spec.rb
  spec/requests/providers/proceeding_merits_task/is_client_child_subject_controller_spec.rb
  spec/services/document_category_analyser_spec.rb
  spec/services/flow/steps/provider_merits/biological_parent_step_spec.rb
  spec/services/flow/steps/provider_merits/check_who_client_is_step_spec.rb
  spec/services/flow/steps/provider_merits/child_subject_step_spec.rb
  spec/services/flow/steps/provider_merits/parental_responsibilities_step_spec.rb
Labels: UAT, approved

#7667 AP-5837: make review reasons more clear on means report
  app/assets/stylesheets/print-styles.scss
  app/views/providers/means_reports/_with_cfe_result_details.html.erb
  app/views/providers/means_reports/show.html.erb
  config/initializers/grover.rb
  config/locales/en/providers.yml
Labels: UAT, approved

#7670 AP-5842: Update capital logic on review pages
  app/views/shared/review_application/_questions_and_answers.html.erb
  features/providers/review_and_print.feature
Labels: UAT

#7672 AP-5072: Change error message for accessibility
  config/locales/en/activemodel.yml
Labels: approved, Ready to merge

#7650 FIX: remove webdack gem
  Gemfile
  Gemfile.lock
  db/migrate/20180807211758_create_legal_aid_applications.rb
  db/migrate/20180820112730_create_applicant.rb
  db/migrate/20180829144026_create_proceeding_types.rb
  db/migrate/20180829150801_create_legal_aid_application_proceeding_types.rb
  db/migrate/20181011143410_create_addresses.rb
  db/migrate/20181018165405_id_to_uuid_fk.rb
  db/migrate/20181018165537_uuid_migration.rb
Labels: approved, Discussion

#7676 AP-5789: Prevent phantom vehicle submissions
  app/models/vehicle.rb
  app/services/flow/steps/provider_capital/own_homes_step.rb
  app/views/providers/means/add_other_vehicles/show.html.erb
  config/locales/en/providers.yml
  features/step_definitions/employment_setup_steps.rb
  spec/factories/legal_aid_applications.rb
  spec/models/vehicle_spec.rb
  spec/requests/providers/means/add_other_vehicles_controller_spec.rb
  spec/services/flow/steps/provider_capital/own_homes_step_spec.rb
Labels: UAT

#7660 AP-5432: Refactor check capital answers
  app/views/providers/means_reports/_capital_disregards.html.erb
  app/views/providers/means_reports/_capital_result.html.erb
  app/views/providers/means_reports/_caseworker_review.html.erb
  app/views/providers/means_reports/_income_details.html.erb
  app/views/providers/means_reports/_income_result.html.erb
  app/views/providers/means_reports/_outgoings_and_deductions_details.html.erb
  app/views/providers/means_reports/_proceeding_eligibility.html.erb
  app/views/providers/means_reports/_receives_benefits.html.erb
  app/views/providers/means_reports/_uploaded_bank_statements.html.erb
  app/views/shared/check_answers/_assets.html.erb
  app/views/shared/check_answers/_bank_statements.html.erb
  app/views/shared/check_answers/_capital_disregard_details.html.erb
  app/views/shared/check_answers/_capital_disregards.html.erb
  app/views/shared/check_answers/_client_bank_accounts.html.erb
  app/views/shared/check_answers/_client_online_bank_accounts.html.erb
  app/views/shared/check_answers/_joint_bank_accounts.html.erb
  app/views/shared/check_answers/_offline_savings_accounts.html.erb
  app/views/shared/check_answers/_one_link_section.html.erb
  app/views/shared/check_answers/_other_assets.html.erb
  app/views/shared/check_answers/_partner_bank_accounts.html.erb
  app/views/shared/check_answers/_property.html.erb
  app/views/shared/check_answers/_restrictions.html.erb
  app/views/shared/check_answers/_savings_and_investments.html.erb
  app/views/shared/check_answers/_total_in_online_bank_accounts.html.erb
  app/views/shared/check_answers/_vehicles.html.erb
  app/views/shared/check_answers/merits/_separate_representation.html.erb
  app/views/shared/check_answers/merits/_statement_of_case.html.erb
  config/locales/cy/shared.yml
  config/locales/en/shared.yml
  features/providers/partner_means_assessment/means_report.feature
  spec/requests/providers/check_capital_answers_controller_spec.rb
Labels: UAT, approved

#7692 Fix: Sass css compilation deprecation warnings
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/providers/search_results.scss
  package.json
Labels: Discussion

#7689 AP-5809: Amend HMRC duration check from 4 months to 93 days
  app/services/hmrc/interface/submission_service.rb
  config/application.rb
  helm_deploy/apply-for-legal-aid/values-production.yaml
  helm_deploy/apply-for-legal-aid/values-staging.yaml
  helm_deploy/apply-for-legal-aid/values-uat.yaml
  spec/services/hmrc/interface/submission_service_spec.rb
Labels: approved

#7697 AP-5728: Update proceeding type filter
  app/controllers/providers/proceedings_types_controller.rb
  app/services/legal_framework/proceeding_types/all.rb
  features/cassettes/Adding_an_SCA_Secure_Accommodation_Order_proceeding_sets_all_client_involvement_types_to_Child/When_a_provider_is_adding_proceedings_and_only_adds_a_Secure_Accommodation_Order.yml
  features/cassettes/Applicant_details/Allows_return_to_and_proceed_from_Delegated_Function_date_view.yml
  features/cassettes/Applicant_details/Completes_the_application_using_address_lookup.yml
  features/cassettes/Applicant_details/Completes_the_application_using_address_lookup_with_building_number_name.yml
  features/cassettes/Applicant_details/Completes_the_application_using_address_lookup_with_multiple_proceedings.yml
  features/cassettes/Applicant_details/Completes_the_application_using_manual_address.yml
  features/cassettes/Applicant_details/I_can_see_that_the_applicant_does_not_receive_benefits.yml
  features/cassettes/Applicant_details/I_can_see_that_the_applicant_receives_benefits.yml
  features/cassettes/Checking_answers_for_linked_and_copied_cases/If_I_change_the_copied_from_Yes_to_No.yml
  features/cassettes/Checking_answers_for_linked_and_copied_cases/If_I_change_the_linked_from_Family_to_No.yml
  features/cassettes/Checking_client_details_answers_backwards_and_forwards/I_want_to_change_the_proceeding_type_from_the_check_your_answers_page.yml
  features/cassettes/Emergency_cost_override/Provider_is_prompted_to_override_emergency_cost_limitation.yml
  features/cassettes/Linking_cases_back_button_use/Complete_flow_reversion_with_back_button.yml
  features/cassettes/Loop_through_proceeding_questions/No_preselected_emergency_or_substantive_levels_of_service.yml
  features/cassettes/Loop_through_proceeding_questions/When_provider_accepts_default_levels_of_service.yml
  features/cassettes/Loop_through_proceeding_questions/When_provider_does_not_accept_default_levels_of_service.yml
  features/cassettes/No_national_insurance_number_for_applicant/I_can_see_that_the_applicant_receives_benefits.yml
  features/cassettes/Non-means-tested_applicant_journey_with_use_of_delegation_functions/Completes_a_minimal_application_for_applicant_that_was_under_18_at_time_of_earliest_delegated_function.yml
  features/cassettes/Non-means-tested_applicant_journey_without_use_of_delegation_functions/Completes_an_application_for_applicant_that_is_under_18.yml
  features/cassettes/Pathways_from_check_your_answers/I_go_back_and_change_the_proceedings_on_an_application_with_multiple_proceedings.yml
  features/cassettes/Scope_limitations_not_being_set/When_a_provider_creates_an_application_with_multiple_proceedings_and_uses_the_back_button_scope_limitations_should_not_be_removed.yml
  features/cassettes/Search_proceedings/I_am_able_to_clear_proceeding_on_the_proceeding_page.yml
  features/cassettes/Search_proceedings/No_results_returned_is_seen_on_screen_when_invalid_proceeding_search_entered.yml
  features/cassettes/Under_18_applicant_journey/Completes_a_minimal_application_for_applicant_that_is_under_18.yml
  features/cassettes/Using_the_back_button_on_proceedings_should_not_lock_a_user_out/When_a_provider_is_adding_proceedings_and_uses_the_back_button_they_should_route_to_the_list_of_proceedings_first.yml
  spec/cassettes/Backable/back_path/has_a_back_link_to_the_previous_page.yml
  spec/cassettes/Backable/back_path/when_we_go_back_once/has_a_link_to_the_previous_page.yml
  spec/cassettes/Backable/back_path/when_we_go_back_once/redirects_to_same_page_without_the_param.yml
  spec/cassettes/Backable/back_path/when_we_reload_the_current_page_several_times/has_a_back_link_to_the_previous_page.yml
  spec/cassettes/Providers_ApplicationDependable/GET_an_action/when_the_provider_is_authenticated/records_the_current_controller_name.yml
  spec/cassettes/Providers_ApplicationDependable/GET_an_action/when_the_provider_is_authenticated/returns_http_success.yml
  spec/cassettes/Providers_CheckProviderAnswersController/POST_/providers/applications/_legal_aid_application_id/check_provider_answers/reset/when_the_provider_is_authenticated/changes_the_stage_back_to_entering_applicant_details.yml
  spec/cassettes/Providers_CheckProviderAnswersController/POST_/providers/applications/_legal_aid_application_id/check_provider_answers/reset/when_the_provider_is_authenticated/redirects_back.yml
  spec/cassettes/Providers_HasOtherProceedingsController/DELETE_/providers/_application_id/has_other_proceedings/when_a_proceeding_is_removed/and_it_s_the_lead_proceeding/sets_a_new_lead_proceeding_when_the_original_one_is_deleted.yml
  spec/cassettes/Providers_HasOtherProceedingsController/DELETE_/providers/_application_id/has_other_proceedings/when_a_proceeding_is_removed/displays_the_singular_number_of_proceedings_remaining.yml
  spec/cassettes/Providers_HasOtherProceedingsController/DELETE_/providers/_application_id/has_other_proceedings/when_a_proceeding_is_removed/leaves_the_correct_number_of_remaining_proceedings.yml
  spec/cassettes/Providers_HasOtherProceedingsController/DELETE_/providers/_application_id/has_other_proceedings/when_a_proceeding_is_removed/removes_one_proceeding.yml
  spec/cassettes/Providers_HasOtherProceedingsController/DELETE_/providers/_application_id/has_other_proceedings/when_all_proceedings_are_removed/redirects_to_the_proceedings_type_page_if_all_proceeding_types_removed.yml
  spec/cassettes/Providers_HasOtherProceedingsController/GET_/providers/_application_id/has_other_proceedings/shows_the_current_number_of_proceedings.yml
  spec/cassettes/Providers_HasOtherProceedingsController/GET_/providers/_application_id/has_other_proceedings/shows_the_page.yml
  spec/cassettes/Providers_HasOtherProceedingsController/GET_/providers/_application_id/has_other_proceedings/when_all_available_proceedings_have_been_added/renders_the_limited_page.yml
  spec/cassettes/Providers_HasOtherProceedingsController/PATCH_/providers/_application_id/has_other_proceedings/when_the_provider_chose_nothing/stays_on_the_page_if_there_is_a_validation_error.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/displays_errors.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/renders_index.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/calls_the_add_proceeding_service.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/redirects_to_next_step.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/when_LegalFramework_ProceedingTypesService_call_returns_false/displays_errors.yml
  spec/cassettes/Providers_ProceedingsTypesController/create_POST_/providers/applications/_legal_aid_application_id/proceedings_types/with_proceedings/when_LegalFramework_ProceedingTypesService_call_returns_false/renders_index.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/when_the_applicant_s_address_used_address_lookup_service/redirects_to_the_address_lookup_page.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/when_the_applicant_s_address_used_manual_entry/redirects_to_the_manual_address_page_lookup_page.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/displays_no_errors.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/does_not_displays_the_proceeding_types.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/returns_http_success.yml
  spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/when_there_are_no_available_proceedings_to_show/redirects_to_the_has_other_proceedings_page.yml
  spec/factories/proceedings.rb
  spec/requests/providers/proceedings_types_controller_spec.rb
  spec/services/legal_framework/proceeding_types/all_spec.rb
Labels: approved

#7708 Update: Landing page list for PLF
  app/views/providers/start/index.html.erb
  config/locales/en/providers.yml
  spec/requests/providers/start_spec.rb
Labels: ready for review

#7701 AP-5733: Change feedback report to created_at ascending
  app/controllers/admin/reports_controller.rb
Labels: approved, Ready to merge

#7703 AP-5698: Update Chance of Success handling
  app/services/legal_framework/merits_tasks_retriever_service.rb
  spec/services/legal_framework/merits_tasks_retriever_service_spec.rb
Labels: approved, do not merge, Remove commit before merge

#7710 Chore: Remove unused partials
  app/views/shared/check_answers/_item.html.erb
  app/views/shared/check_answers/_no_link_item.html.erb
Labels: ready for review

#7709 Chore: make merits report summary card column widths one-third/two-thirds
  app/views/providers/merits_reports/_applied_previously.html.erb
  app/views/providers/merits_reports/_delegated_functions.html.erb
  app/views/providers/merits_reports/_proceeding_details.html.erb
  app/views/shared/check_answers/_emergency_costs.html.erb
  app/views/shared/check_answers/_substantive_costs.html.erb
  app/views/shared/check_answers/merits/_separate_representation.html.erb
Labels: ready for review

#7716 AP-5432: Fix incorrect closing h tag
  app/views/shared/check_answers/_assets.html.erb
Labels: approved

#7714 AP-5787: Feedback form - summary errors do not link to field errors
  app/views/feedback/new.cy.html.erb
  app/views/feedback/new.en.html.erb
  app/views/feedback/new.html.erb
  config/locales/cy/feedback.yml
  config/locales/en/feedback.yml
Labels: approved, Ready to merge

#7712 Update: Vehicle model and factory bot handling
  app/models/vehicle.rb
  app/services/cfe_civil/components/vehicles.rb
  app/services/reports/mis/application_detail_csv_line.rb
  spec/factories/vehicles.rb
  spec/models/vehicle_spec.rb
  spec/services/ccms/requestors/case_add_requestor_spec.rb
  spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
  spec/services/ccms/requestors/special_children_act_case_add_requestor_spec.rb
  spec/services/cfe_civil/components/partner_spec.rb
  spec/services/cfe_civil/components/vehicles_spec.rb
  spec/services/cfe_civil/submission_builder_spec.rb
  spec/services/reports/mis/application_detail_csv_line_spec.rb
Labels: UAT, approved

#7720 Chore: Vehicle tidyup
  app/models/vehicle.rb
  db/migrate/20250325114131_remove_purchased_on_from_vehicle.rb
  db/schema.rb
Labels: ready for review
